// preview/dsr-180/angular/components/header/header-mobile/header-mobile.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  Injector,
  computed,
  effect,
  inject,
  input,
  output,
  viewChild,
  afterNextRender,
} from "@angular/core";
import { SearchBarProps } from "@design-system-rte/core";
import { buildHeaderHomeAriaLabel, type HeaderIconButtonConfig } from "@design-system-rte/core/components/header";
import { ESCAPE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { IconButtonComponent } from "../../icon-button/icon-button.component";
import { SearchbarComponent } from "../../searchbar/searchbar.component";

const DEFAULT_HOME_LINK = "/";
const DEFAULT_SEARCHBAR_ID = "rte-header-searchbar";

@Component({
  selector: "rte-header-mobile",
  imports: [CommonModule, IconButtonComponent, SearchbarComponent],
  standalone: true,
  templateUrl: "./header-mobile.component.html",
  styleUrl: "./header-mobile.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderMobileComponent {
  private readonly destroyRef = inject(DestroyRef);
  private readonly injector = inject(Injector);

  readonly appearance = input<"brand" | "neutral">("brand");
  readonly isCompact = input<boolean>(false);

  readonly hasLeftSection = input<boolean>(true);
  readonly hasRightSection = input<boolean>(true);
  readonly hasLogo = input<boolean>(true);
  readonly applicationName = input<string>("");
  readonly logoSrc = input<string | undefined>(undefined);
  readonly homeLink = input<string>(DEFAULT_HOME_LINK);
  readonly homeAriaLabel = input<string | undefined>(undefined);

  readonly hasSearchbar = input<boolean>(true);
  readonly searchbarProps = input<SearchBarProps | undefined>(undefined);
  readonly mobileSearchButtonAriaLabel = input<string>("Rechercher");

  readonly mobileMenuButton = input<HeaderIconButtonConfig | undefined>(undefined);

  readonly isSearchActive = input<boolean>(false);
  readonly isSearchActiveChange = output<boolean>();
  readonly mobileMenuClick = output<void>();

  readonly mobileSearchButtonRef = viewChild<ElementRef<HTMLButtonElement>>("mobileSearchButtonRef");
  readonly rootRef = viewChild<ElementRef<HTMLElement>>("rootRef");

  private outsidePointerDownCleanup: (() => void) | null = null;

  readonly shouldRenderLogo = computed(() => this.hasLogo() && !!this.logoSrc());

  readonly computedHomeAriaLabel = computed(() => {
    return this.homeAriaLabel() ?? buildHeaderHomeAriaLabel(this.applicationName());
  });

  readonly rightSectionWidth = computed(() => (this.isSearchActive() ? "calc(100% - 40px)" : "80px"));

  constructor() {
    effect(
      () => {
        if (!this.hasSearchbar()) {
          this.teardownOutsideCloseListener();
          return;
        }

        if (this.isSearchActive()) {
          this.ensureOutsideCloseListener();
          afterNextRender(
            () => {
              this.focusSearchInput();
            },
            { injector: this.injector },
          );
          return;
        }

        this.teardownOutsideCloseListener();
      },
      { allowSignalWrites: true },
    );
  }

  handleRootKeyDown(event: KeyboardEvent): void {
    if (event.key !== ESCAPE_KEY) {
      return;
    }
    if (!this.isSearchActive()) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    this.emitCloseMobileSearch();
  }

  openMobileSearch(): void {
    if (!this.hasSearchbar()) {
      return;
    }
    this.isSearchActiveChange.emit(true);
  }

  emitCloseMobileSearch(): void {
    this.isSearchActiveChange.emit(false);
    queueMicrotask(() => {
      this.mobileSearchButtonRef()?.nativeElement.focus();
    });
  }

  handleMobileMenuClick(): void {
    this.mobileMenuClick.emit();
  }

  private ensureOutsideCloseListener(): void {
    if (this.outsidePointerDownCleanup) {
      return;
    }
    const handler = (event: PointerEvent): void => {
      if (!this.isSearchActive()) {
        return;
      }
      const rootElement = this.rootRef()?.nativeElement;
      if (!rootElement) {
        return;
      }
      const target = event.target as Node | null;
      if (target && rootElement.contains(target)) {
        return;
      }
      this.emitCloseMobileSearch();
    };

    document.addEventListener("pointerdown", handler, { capture: true });
    this.outsidePointerDownCleanup = () => {
      document.removeEventListener("pointerdown", handler, { capture: true } as AddEventListenerOptions);
      this.outsidePointerDownCleanup = null;
    };

    this.destroyRef.onDestroy(() => {
      this.teardownOutsideCloseListener();
    });
  }

  private teardownOutsideCloseListener(): void {
    this.outsidePointerDownCleanup?.();
  }

  private focusSearchInput(): void {
    const searchbarId = this.searchbarProps()?.id || DEFAULT_SEARCHBAR_ID;
    const inputEl = document.getElementById(searchbarId) as HTMLInputElement | null;
    if (inputEl) {
      inputEl.focus();
    }
  }
}

<div
  #rootRef
  class="rte-header-mobile"
  [attr.data-appearance]="appearance()"
  [attr.data-compact]="isCompact()"
  [attr.data-search-state]="isSearchActive() ? 'open' : 'closed'"
  [attr.data-has-logo]="shouldRenderLogo() ? 'true' : null"
  [attr.data-has-searchbar]="hasSearchbar() ? 'true' : null"
  (keydown)="handleRootKeyDown($event)"
>
  @if (hasLeftSection()) {
    <div class="left-section">
      <a class="rte-header-home" [href]="homeLink()" [attr.aria-label]="computedHomeAriaLabel()">
        @if (shouldRenderLogo()) {
          <img class="rte-header-logo" alt="" aria-hidden="true" [src]="logoSrc()" />
        }

        <span class="rte-header-app-name" [attr.aria-hidden]="isSearchActive() ? 'true' : null">
          {{ applicationName() }}
        </span>
      </a>

      <div class="right-section-placeholder" [style.width]="rightSectionWidth()"></div>
    </div>
  }

  @if (hasRightSection()) {
    <div class="right-section" [class.expanded]="isSearchActive()">
      @if (hasSearchbar()) {
        <div class="rte-header-mobile-search-wrapper" [style.width]="isSearchActive() ? 'calc(100% - 40px)' : '80px'">
          @if (isSearchActive()) {
            <rte-searchbar
              [id]="searchbarProps()?.id || 'rte-header-searchbar'"
              [label]="searchbarProps()?.label || 'Rechercher'"
              [disabled]="searchbarProps()?.disabled ?? false"
              [showResetButton]="searchbarProps()?.showResetButton ?? true"
              [value]="searchbarProps()?.value || ''"
              [assistiveText]="searchbarProps()?.assistiveText || ''"
              [appearance]="appearance() === 'neutral' ? 'secondary' : 'primary'"
              [compactSpacing]="isCompact()"
              [width]="isSearchActive() ? 'calc(100% - 40px)' : '80px'"
            />
          } @else {
            <div class="rte-header-mobile-search">
              <rte-icon-button
                #mobileSearchButtonRef
                size="m"
                appearance="outlined"
                name="search"
                variant="text"
                [ariaLabel]="mobileSearchButtonAriaLabel()"
                (clickEvent)="openMobileSearch()"
              />
            </div>
          }
        </div>
      }

      <rte-icon-button
        size="l"
        variant="neutral"
        [name]="mobileMenuButton()?.iconName ?? 'menu'"
        [ariaLabel]="mobileMenuButton()?.ariaLabel ?? 'Menu'"
        [disabled]="mobileMenuButton()?.disabled ?? false"
        (clickEvent)="handleMobileMenuClick()"
      />
    </div>
  }
</div>

// packages/react/src/components/header/headerMobile/HeaderMobile.tsx
import { Alignment, DropdownItemProps, HeaderIconButtonConfig, Position } from "@design-system-rte/core";
import { useState, useRef, useEffect } from "react";
import { RegularIconIdKey, TogglableIconIdKey } from "src/components/icon/Icon";

import useAnimatedMount from "../../../hooks/useAnimatedMount";
import { useClickAway } from "../../../hooks/useClickAway";
import { BaseDropdown } from "../../dropdown/BaseDropdown";
import Dropdown from "../../dropdown/Dropdown";
import DropdownItem from "../../dropdown/dropdownItem/DropdownItem";
import IconButton from "../../iconButton/IconButton";
import Searchbar from "../../searchbar/Searchbar";
import { concatClassNames } from "../../utils";

import styles from "./HeaderMobile.module.scss";

interface HeaderMobileProps {
  homeLink?: string;
  logoSrc?: string;
  applicationName?: string;
  compactSpacing?: boolean;
  hasLeftSection?: boolean;
  appearance?: "brand" | "neutral";
  hasMiddleSection?: boolean;
  hasRightSection?: boolean;
  leftSectionContent?: React.ReactNode;
  middleSectionContent?: React.ReactNode;
  rightSectionContent?: React.ReactNode;
  mobileSearchButtonAriaLabel?: string;
  onSearchActiveChange?: (isActive: boolean) => void;
  mobileMenuContent?: React.ReactNode;
  onMobileMenuClick?: () => void;
  isMobileMenuOpen?: boolean;
  mobileMenuItems?: DropdownItemProps[];
  onMobileMenuClose?: () => void;
  mobileMenuIconProps?: HeaderIconButtonConfig<RegularIconIdKey | TogglableIconIdKey>;
  hasSearchbar?: boolean;
}

const HeaderMobile = ({
  homeLink,
  hasLeftSection,
  leftSectionContent,
  logoSrc,
  applicationName,
  compactSpacing,
  appearance,
  mobileSearchButtonAriaLabel,
  onSearchActiveChange,
  mobileMenuContent,
  onMobileMenuClick,
  isMobileMenuOpen,
  mobileMenuItems,
  onMobileMenuClose,
  mobileMenuIconProps,
  hasSearchbar,
}: HeaderMobileProps) => {
  const [isSearchbarExpanded, setIsSearchbarExpanded] = useState(false);
  const headerRef = useRef<HTMLDivElement>(null);
  const searchbarRef = useRef<HTMLInputElement>(null);

  useClickAway(() => {
    setIsSearchbarExpanded((prev) => {
      if (!prev) return prev;
      onSearchActiveChange?.(false);
      return false;
    });
  }, headerRef.current!);

  useEffect(() => {
    if (!isSearchbarExpanded) return;
    if (searchbarRef.current) {
      searchbarRef.current.focus();
    }
  }, [isSearchbarExpanded]);

  const { isAnimating: isSearchbarExpandedAnimating } = useAnimatedMount(isSearchbarExpanded, 200);

  const dropdownProps = {
    id: "mobile-menu-dropdown",
    onClose: () => onMobileMenuClose?.(),
    isList: false,
    isOpen: isMobileMenuOpen,
    position: "bottom" as Position,
    alignment: "end" as Alignment,
    trigger: (
      <IconButton
        name={mobileMenuIconProps?.iconName || "menu"}
        aria-expanded={isMobileMenuOpen}
        aria-label={mobileMenuIconProps?.ariaLabel || "Menu"}
        variant="neutral"
        compactSpacing={compactSpacing}
        onClick={onMobileMenuClick}
      />
    ),
  };

  return (
    <div
      ref={headerRef}
      className={concatClassNames(styles["rte-header-mobile"], "rte-header-mobile")}
      data-compact={compactSpacing}
      data-search-state={isSearchbarExpanded ? "open" : "closed"}
    >
      <div className={styles["rte-header-left"]}>
        {hasLeftSection ? (
          leftSectionContent || (
            <>
              {logoSrc && (
                <a href={homeLink} aria-label="Home" className={styles["rte-header-home"]}>
                  <img src={logoSrc} alt="Logo" className={styles["rte-header-logo"]} />
                </a>
              )}
            </>
          )
        ) : (
          <></>
        )}
      </div>
      <div className={styles["rte-header-middle"]}>
        {applicationName && (
          <span
            className={styles["rte-header-app-name"]}
            data-is-searchbar-expanded={isSearchbarExpandedAnimating}
            aria-hidden={isSearchbarExpandedAnimating}
          >
            {applicationName}
          </span>
        )}

        {hasSearchbar && (
          <div className={styles["rte-header-search"]}>
            <div
              className={styles["rte-search-icon-container"]}
              data-is-searchbar-expanded={isSearchbarExpandedAnimating}
            >
              <IconButton
                role="button"
                name="search"
                variant="text"
                onClick={() => {
                  setIsSearchbarExpanded((prev) => {
                    const newState = !prev;
                    onSearchActiveChange?.(newState);
                    return newState;
                  });
                }}
                compactSpacing={compactSpacing}
                aria-label={mobileSearchButtonAriaLabel}
              />
            </div>
            <div
              className={styles["rte-searchbar-container"]}
              data-is-searchbar-expanded={isSearchbarExpandedAnimating}
            >
              <Searchbar
                ref={searchbarRef}
                compactSpacing={compactSpacing}
                appearance={appearance === "brand" ? "primary" : "secondary"}
                width={"100%"}
              />
            </div>
          </div>
        )}
      </div>
      <div className={styles["rte-header-right"]}>
        {mobileMenuContent ? (
          <BaseDropdown {...dropdownProps}>{mobileMenuContent}</BaseDropdown>
        ) : mobileMenuItems ? (
          <Dropdown {...dropdownProps}>
            {mobileMenuItems.map((item, index) => (
              <DropdownItem key={index} {...item} />
            ))}
          </Dropdown>
        ) : (
          <></>
        )}
      </div>
    </div>
  );
};

export default HeaderMobile;
