// packages/angular/projects/ds-rte-lib/src/lib/components/side-nav/base-side-nav/base-side-nav.component.ts
import { CommonModule } from "@angular/common";
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  OnDestroy,
  viewChild,
} from "@angular/core";
import { sideNavCollapsedSize, sideNavPanelSize } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavAppearance } from "@design-system-rte/core/components/side-nav/side-nav.interface";

type SideNavSize = "s" | "m" | "l";

@Component({
  selector: "rte-base-side-nav",
  imports: [CommonModule],
  standalone: true,
  templateUrl: "./base-side-nav.component.html",
  styleUrl: "./base-side-nav.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BaseSideNavComponent implements AfterViewInit, OnDestroy {
  private readonly elementRef = inject(ElementRef<HTMLElement>);

  readonly contentRef = viewChild<ElementRef<HTMLDivElement>>("contentRef");

  private readonly collapsedSize = sideNavCollapsedSize;
  private readonly panelSize = sideNavPanelSize;

  readonly size = input<SideNavSize>("m");
  readonly appearance = input<SideNavAppearance>("brand");
  readonly collapsed = input<boolean>(false);
  readonly showHeader = input<boolean>(true);
  readonly showFooter = input<boolean>(true);

  readonly minWidth = computed<string>(() => {
    return this.collapsed() ? `${this.collapsedSize}px` : `${this.panelSize[this.size()]}px`;
  });

  private resizeObserver?: ResizeObserver;
  private resizeHandler?: () => void;

  ngAfterViewInit(): void {
    this.setupResizeObserver();
  }

  ngOnDestroy(): void {
    this.cleanupResizeObserver();
  }

  private setupResizeObserver(): void {
    const containerEl = this.elementRef.nativeElement;
    const contentEl = this.contentRef()?.nativeElement;
    if (!containerEl || !contentEl) {
      return;
    }

    const setHeightVar = (): void => {
      const height = contentEl.offsetHeight;
      containerEl.style.setProperty("--content-height", `${height}px`);
    };

    this.resizeHandler = setHeightVar;
    setHeightVar();

    this.resizeObserver = new ResizeObserver(() => {
      setHeightVar();
    });
    this.resizeObserver.observe(contentEl);

    window.addEventListener("resize", setHeightVar);
  }

  private cleanupResizeObserver(): void {
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = undefined;
    }
    if (this.resizeHandler) {
      window.removeEventListener("resize", this.resizeHandler);
      this.resizeHandler = undefined;
    }
  }
}

<div class="side-nav-container">
  <nav
    class="side-nav"
    [ngClass]="{ collapsed: collapsed() }"
    [attr.data-appearance]="appearance()"
    [attr.data-contrast]="contrast()"
    [style.min-width]="minWidth()"
  >
    @if (showHeader()) {
      <div class="side-nav-header">
        <ng-content select="[side-nav-header]"></ng-content>
      </div>
    }

    <div class="side-nav-body">
      <ng-content select="[side-nav-body]"></ng-content>
    </div>

    @if (showFooter()) {
      <div class="side-nav-footer">
        <ng-content select="[side-nav-footer]"></ng-content>
      </div>
    }
  </nav>
  <div class="side-nav-content">
    <ng-content select="[side-nav-content]"></ng-content>
  </div>
</div>

// packages/react/src/components/sideNav/baseSideNav/BaseSideNav.tsx
import { sideNavCollapsedSize, sideNavPanelSize } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavProps as CoreSideNavProps } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ForwardedRef, forwardRef, ReactNode, useLayoutEffect, useRef } from "react";

import { concatClassNames } from "../../utils";

import style from "./BaseSideNav.module.scss";

interface BaseSideNavProps
  extends Partial<Omit<CoreSideNavProps, "items">>,
    Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  header?: ReactNode;
  body?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
}

const BaseSideNav = forwardRef<HTMLElement | HTMLDivElement, BaseSideNavProps>(
  (
    {
      size = "m",
      header,
      body,
      footer,
      showHeader = true,
      showFooter = true,
      children,
      appearance = "brand",
      collapsed,
    },
    ref,
  ) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const contentRef = useRef<HTMLDivElement>(null);

    useLayoutEffect(() => {
      const containerEl = containerRef.current;
      const contentEl = contentRef.current;
      if (!containerEl || !contentEl) return;

      const setHeightVar = () => {
        const height = contentEl.offsetHeight;
        containerEl.style.setProperty("--content-height", `${height}px`);
      };

      setHeightVar();

      const resizeObserver = new ResizeObserver(() => setHeightVar());
      resizeObserver.observe(contentEl);

      window.addEventListener("resize", setHeightVar);

      return () => {
        resizeObserver.disconnect();
        window.removeEventListener("resize", setHeightVar);
      };
    }, [children]);

    return (
      <div ref={containerRef} className={style.sideNavContainer}>
        <nav
          ref={ref as ForwardedRef<HTMLDivElement>}
          className={concatClassNames(style.sideNav, collapsed ? style.collapsed : "", appearance && style[appearance])}
          style={{
            minWidth: collapsed ? sideNavCollapsedSize : sideNavPanelSize[size],
          }}
        >
          {showHeader && header && <div className={style.sideNavHeader}>{header}</div>}
          {body && <div className={style.sideNavBody}>{body}</div>}
          {showFooter && footer && <div className={style.sideNavFooter}>{footer}</div>}
        </nav>

        {children && (
          <div ref={contentRef} className={style.sideNavContent}>
            {children}
          </div>
        )}
      </div>
    );
  },
);

BaseSideNav.displayName = "BaseSideNav";
export default BaseSideNav;
