// packages/angular/projects/ds-rte-lib/src/lib/components/tag/tag.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, computed } from "@angular/core";
import { TagProps } from "@design-system-rte/core/components/tag/tag.interface";

import { isValidIconName } from "../icon/icon-map";
import { IconComponent } from "../icon/icon.component";
import { RegularIconIdKey, TogglableIconIdKey } from "../icon/icon.service";

@Component({
  selector: "rte-tag",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./tag.component.html",
  styleUrl: "./tag.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TagComponent {
  readonly tagType = input<TagProps["tagType"]>("status");
  readonly status = input<TagProps["status"]>("success");
  readonly color = input<TagProps["color"]>("brand");
  readonly compactSpacing = input<boolean>(false);
  readonly label = input<string>("");
  readonly showLeftIcon = input<boolean>(false);
  readonly iconName = input<RegularIconIdKey | TogglableIconIdKey>();

  readonly computedIconName = computed(() => {
    if (this.tagType() === "status") {
      const statusIconMap: Record<string, RegularIconIdKey | TogglableIconIdKey> = {
        success: "check",
        information: "info",
        warning: "warning",
        alert: "dangerous",
      };
      const statusValue = this.status();
      if (statusValue && statusIconMap[statusValue]) {
        return statusIconMap[statusValue];
      }
    }
    return this.iconName() ?? "check";
  });

  readonly isValidIconName = computed(() => {
    const iconName = this.computedIconName();
    return !!iconName && isValidIconName(iconName);
  });
}

<div
  class="rte-tag"
  [attr.data-tag-type]="tagType()"
  [attr.data-status]="status()"
  [attr.data-color]="color()"
  [attr.data-compact-spacing]="compactSpacing()"
  [attr.aria-label]="ariaLabel()"
>
  <ng-container *ngIf="isValidIconName() && (tagType() === 'status' || showLeftIcon())">
    <rte-icon [name]="computedIconName()" [size]="16"></rte-icon>
  </ng-container>
  <ng-container *ngIf="label">
    <span class="tag-label" [attr.data-compact-spacing]="compactSpacing()">{{ label() }}</span>
  </ng-container>
</div>

// packages/react/src/components/tag/Tag.tsx
import { TagProps } from "@design-system-rte/core/components/tag/tag.interface";
import { forwardRef } from "react";

import Icon, { RegularIconIdKey, TogglableIconIdKey } from "../icon/Icon";
import { isValidIconName } from "../icon/IconMap";

import style from "./Tag.module.scss";

const Tag = forwardRef<HTMLDivElement, TagProps>(
  ({ tagType = "status", status, color, CompactSpacing, label, showLeftIcon = false, iconName, ...props }, ref) => {
    if (tagType === "status") {
      const statusIconMap: Record<string, string> = {
        success: "check",
        information: "info",
        warning: "warning",
        alert: "dangerous",
      };
      if (status && statusIconMap[status]) {
        iconName = statusIconMap[status];
      }
    }

    if (iconName && !isValidIconName(iconName)) {
      console.warn(`Tag: Invalid icon name "${iconName}". Please use a valid icon key.`);
      return null;
    }

    return (
      <div
        ref={ref}
        className={style["tag"]}
        data-tag-type={tagType}
        data-status={status}
        data-color={color}
        data-compact-spacing={CompactSpacing}
        {...props}
      >
        {showLeftIcon && iconName && isValidIconName(iconName) && (
          <Icon name={iconName as RegularIconIdKey | TogglableIconIdKey} size={16} />
        )}
        {label && <label className={style["tag-label"]}>{label}</label>}
      </div>
    );
  },
);

export default Tag;
