// test-apps/react/src/App.tsx
import {
  Button,
  Icon,
  IconButtonToggle,
  SplitButton,
  Tooltip,
  TextInput,
  Chip,
  Badge,
  Textarea,
  Divider,
  Switch,
  SegmentedControl,
  Breadcrumbs,
  Banner,
  Popover,
  Modal,
  SideNav,
  Card,
  Toast,
  ToastQueueProvider
} from "@design-system-rte/react";
import "./App.css";
import { useState } from "react";

function App() {
  const [isIconButtonToggleSelected, setIsIconButtonToggleSelected] = useState(false);
  const [inputValue, setInputValue] = useState("");
  const [segmentedControlValue, setSegmentedControlValue] = useState("label-1");
  const [isInfoBannerVisible, setIsInfoBannerVisible] = useState(true);
  const [isAlertBannerVisible, setIsAlertBannerVisible] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [activeItem, setActiveItem] = useState("home");
  const [isErrorOpen, setIsErrorOpen] = useState(false);

  const handleIconButtonToggleClick = () => {
    setIsIconButtonToggleSelected(!isIconButtonToggleSelected);
  };

  const handleInputChange = (value: string) => {
    setInputValue(value);
  };

  const handleSegmentedControlClick = (
    event: React.MouseEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>
  ) => {
    const newValue = event.currentTarget.getAttribute("id") || "";
    setSegmentedControlValue(newValue);
  };

  const toggleInfoBanner = () => {
    setIsInfoBannerVisible((prev) => !prev);
  };

  const toggleAlertBanner = () => {
    setIsAlertBannerVisible((prev) => !prev);
  };

  const defaultSegmentedButtonOptions = [
    { id: "option-1", label: "Option 1", onClick: () => console.log("Option 1 clicked") },
    { id: "option-2", label: "Option 2", onClick: () => console.log("Option 2 clicked") },
    { id: "option-3", label: "Option 3", onClick: () => console.log("Option 3 clicked") }
  ];

  const headerConfig = {
    identifier: "DS",
    title: "Design System",
    version: "V1.0.0",
    icon: "home",
    link: "/"
  };

  const navigationItems = [
    { id: "home", label: "Home", icon: "home", showIcon: true, onClick: () => setActiveItem("home") },
    {
      id: "dashboard",
      label: "Dashboard",
      icon: "dashboard",
      showIcon: true,
      onClick: () => setActiveItem("dashboard")
    },
    {
      id: "analytics",
      label: "Analytics",
      icon: "analytics",
      showIcon: true,
      onClick: () => setActiveItem("analytics")
    },
    { id: "settings", label: "Settings", icon: "settings", showIcon: true, onClick: () => setActiveItem("settings") },
    {
      id: "profile",
      label: "Profile",
      icon: "user",
      showIcon: true,
      link: "/profile",
      onClick: () => setActiveItem("profile")
    }
  ];

  const footerItems = [
    {
      id: "footer-settings",
      label: "Settings",
      icon: "settings",
      showIcon: true,
      onClick: () => {
        console.log("Footer Settings clicked");
        setActiveItem("footer-settings");
      }
    },
    {
      id: "footer-help",
      label: "Help & Support",
      icon: "help",
      showIcon: true,
      link: "/help",
      onClick: () => setActiveItem("footer-help")
    },
    {
      id: "footer-account",
      label: "Account",
      icon: "user",
      showIcon: true,
      items: [
        { id: "footer-profile", label: "Profile", link: "/profile" },
        { id: "footer-preferences", label: "Preferences" },
        { id: "footer-logout", label: "Logout", onClick: () => console.log("Logout clicked") }
      ]
    }
  ];

  return (
    <SideNav
      headerConfig={headerConfig}
      items={navigationItems}
      footerItems={footerItems}
      collapsible={true}
      appearance="brand"
      activeItem={activeItem}
    >
      <div>
        <div>
          <h3>Card</h3>
          <div style={{ display: "flex", flexDirection: "column", gap: "16px", alignItems: "flex-start" }}>
            <Card size="m" cardType="default">
              <div style={{ padding: "16px" }}>
                <h4 style={{ margin: "0 0 12px 0", fontSize: "18px", fontWeight: "600" }}>Default Card</h4>
                <p style={{ margin: "0", color: "#666", lineHeight: "1.5" }}>
                  This is a default card with medium size. It uses elevation shadow styling.
                </p>
              </div>
            </Card>
          </div>
          <div>
            <h3>Banner</h3>
            <Banner
              type="default"
              title="Info Banner"
              message="This is an info banner"
              closable
              isOpen={isInfoBannerVisible}
            />
            <Banner
              type="alert"
              title="Alert Banner"
              message="This is an alert banner"
              closable
              isOpen={isAlertBannerVisible}
            />
            <Button label={isInfoBannerVisible ? "Close info banner" : "Show info banner"} onClick={toggleInfoBanner} />
            <Button
              label={isAlertBannerVisible ? "Close alert banner" : "Show alert banner"}
              onClick={toggleAlertBanner}
            />
          </div>
          <div>
            <h3>Icon</h3>
            <Icon name="check" />
          </div>
          <hr />
          <div>
            <h3>Button</h3>
            <Button label="Click me" />
          </div>
          <hr />
          <div>
            <h3>SplitButton</h3>
            <SplitButton
              appearance="primary"
              ariaLabelRight="Open menu"
              label="Button Label"
              position="bottom-start"
              options={defaultSegmentedButtonOptions}
            >
              <Button label="Click me" />
            </SplitButton>
          </div>
          <hr />
          <div>
            <h3>Tooltip</h3>
            <Tooltip label="Tooltip">
              <Button label="Click me" />
            </Tooltip>
          </div>
          <hr />
          <div>
            <h3>TextInput</h3>
            <TextInput label="Label" value={inputValue} onChange={handleInputChange} />
            <h4>The input is : {inputValue}</h4>
          </div>
          <hr />
          <div>
            <h3>Icon Button Toggle</h3>
            <IconButtonToggle
              onClick={handleIconButtonToggleClick}
              selected={isIconButtonToggleSelected}
              name="settings"
            />
          </div>
          <hr />
          <div>
            <h3>Chip</h3>
            <Chip label="Chip Label" type="single" onClick={() => console.log("Chip clicked")} />
          </div>
          <hr />
          <div>
            <h3>Badge</h3>
            <div style={{ display: "inline-block", backgroundColor: "bisque" }}>
              <Badge count={1}>A badge host</Badge>
            </div>
          </div>
          <hr />
          <div>
            <h3>Textarea</h3>
            <Textarea
              label="This is a textarea"
              labelPosition="top"
              assistiveTextLabel="This is a label"
              assistiveTextAppearance="description"
              required
            />
          </div>
          <hr />
          <h3>Divider</h3>
          <p> First text </p>
          <Divider />
          <p> Second text </p>
          <Divider thickness="medium" />
          <div style={{ display: "flex", flexDirection: "row" }}>
            <p style={{ margin: "20px" }}> left text </p>
            <Divider orientation="vertical" />
            <p style={{ margin: "20px" }}> middle text </p>
            <Divider orientation="vertical" thickness="medium" />
            <p style={{ margin: "20px" }}> right text </p>
            <Divider orientation="vertical" thickness="bold" />
          </div>
          <Divider orientation="horizontal" thickness="bold" />
          <hr />
          <div>
            <h3>Switch</h3>
            <Switch
              label="Switch Label"
              appearance="brand"
              showLabel={true}
              showIcon={true}
              disabled={false}
              readOnly={false}
            />
            <Switch
              label="Disabled Switch"
              appearance="brand"
              showLabel={true}
              showIcon={true}
              disabled={true}
              readOnly={false}
            />
            <Switch
              label="Read-Only Switch"
              appearance="brand"
              showLabel={true}
              showIcon={true}
              disabled={false}
              readOnly={true}
            />
          </div>
          <hr />
          <div>
            <h3>Segmented Control</h3>
            <SegmentedControl
              options={[
                { id: "label-1", label: "Label 1" },
                { id: "label-2", label: "Label 2" },
                { id: "label-3", label: "Label 3" }
              ]}
              selected={segmentedControlValue}
              onClick={handleSegmentedControlClick}
            />
          </div>
          <hr />
          <div>
            <h3>Breadcrumbs</h3>
            <Breadcrumbs
              items={[
                { link: "/", label: "Home" },
                { link: "/products", label: "Products" },
                { link: "/electronics", label: "Electronics" },
                { link: "/smartphones", label: "Smartphones" }
              ]}
            />
          </div>
          <hr />
          <Popover
            content="This is the popover content"
            primaryButtonLabel="Confirm"
            secondaryButtonLabel="Cancel"
            title="Popover Title"
          >
            <Button label="Open Popover" />
          </Popover>
          <Divider />
          <Button variant="primary" label="Open Modal" onClick={() => setIsModalOpen(true)} />
          <Modal
            title="Modal Title"
            description="This is the modal description"
            isOpen={isModalOpen}
            onClose={() => setIsModalOpen(false)}
            primaryButton={<Button variant="primary" label="Continue" onClick={() => setIsModalOpen(false)} />}
            secondaryButton={<Button variant="neutral" label="Cancel" onClick={() => setIsModalOpen(false)} />}
          >
            <div>
              <Badge count={5}>Modal Content Badge</Badge>
              <TextInput label="Modal Input" value={inputValue} onChange={handleInputChange} />
            </div>
          </Modal>
        </div>

        <Divider />
        <Button
          label="Toggle error toast"
          onClick={() => setIsErrorOpen(!isErrorOpen)}
          style={{ marginBottom: "16px" }}
          variant="danger"
        />
        <ToastQueueProvider>
          <Toast
            id="my-toast-error-z"
            type={"error"}
            autoDismiss={true}
            closable={true}
            isOpen={isErrorOpen}
            message="Error toast"
            // actionButton={<Button label="Mettre à jour" variant={"text"} />}
            onClose={() => {
              setIsErrorOpen(false);
            }}
          />
        </ToastQueueProvider>
      </div>
    </SideNav>
  );
}

export default App;

// test-apps/angular/src/app/app.component.ts
import { Component, computed, output, signal, inject } from "@angular/core";
import { RouterOutlet } from "@angular/router";
import {
  AccordionComponent,
  ButtonComponent,
  IconComponent,
  SplitButtonComponent,
  IconButtonToggleComponent,
  TooltipDirective,
  TextInputComponent,
  ChipComponent,
  BadgeDirective,
  TextareaComponent,
  LinkComponent,
  DividerComponent,
  SwitchComponent,
  SegmentedControlComponent,
  BreadcrumbsComponent,
  BannerComponent,
  PopoverDirective,
  ModalModule,
  SideNavComponent,
  TreeviewComponent,
  CardComponent,
  ToastService,
  SelectComponent,
  TabComponent,
  LoaderComponent,
  StepperComponent,
  DropdownModule,
  TimePickerComponent,
} from "@design-system-rte/angular";
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { Step } from "@design-system-rte/core/components/stepper/stepper.interface";
import type { TimeFormat } from "@design-system-rte/core/components/timepicker/timepicker.interface";
import { TreeviewItemProps } from "@design-system-rte/core/components/treeview";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    RouterOutlet,
    AccordionComponent,
    ButtonComponent,
    IconComponent,
    SplitButtonComponent,
    IconButtonToggleComponent,
    TooltipDirective,
    TextInputComponent,
    ChipComponent,
    BadgeDirective,
    TextareaComponent,
    LinkComponent,
    DividerComponent,
    SwitchComponent,
    SegmentedControlComponent,
    BreadcrumbsComponent,
    BannerComponent,
    PopoverDirective,
    ModalModule,
    SideNavComponent,
    TreeviewComponent,
    CardComponent,
    SelectComponent,
    TabComponent,
    LoaderComponent,
    StepperComponent,
    DropdownModule,
    TimePickerComponent,
  ],
  providers: [ToastService],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.scss",
})
export class AppComponent {
  title = "angular";

  readonly toastService = inject(ToastService);
  private currentOpenedToastId = "";

  readonly inputValue = signal("Hello");

  readonly timePickerValue = signal<TimeFormat>({ hh: "", mm: "", ss: "" });

  readonly activeStepId = signal("1");

  onTimePickerValueChange(time: TimeFormat): void {
    this.timePickerValue.set({ hh: time.hh, mm: time.mm, ss: time.ss });
  }

  handleInputChange(value: string) {
    this.inputValue.set(value);
  }
  selected = signal(false);

  readonly click = output<MouseEvent | KeyboardEvent>();

  toggleSelectState(): void {
    this.selected.set(!this.selected());
  }

  onClick(event: MouseEvent | KeyboardEvent): void {
    event.stopPropagation();
    this.click.emit(event);
    this.toggleSelectState();
  }

  readonly isInfoBannerVisible = signal(true);
  readonly isAlertBannerVisible = signal(true);

  toggleInfoBanner(): void {
    console.log("toggle info banner");
    this.isInfoBannerVisible.set(!this.isInfoBannerVisible());
  }

  toggleAlertBanner(): void {
    this.isAlertBannerVisible.set(!this.isAlertBannerVisible());
  }

  segments = [
    { id: "segment1", label: "Label 1" },
    { id: "segment2", label: "Label 2" },
    { id: "segment3", label: "Label 3" },
  ];

  selectedSegment = signal("segment1");

  onSegmentSelected(segmentId: string): void {
    this.selectedSegment.set(segmentId);
  }

  breadcrumbItems = [
    { label: "Home", link: "/" },
    { label: "Products", link: "/products" },
    { label: "Electronics", link: "/products/electronics" },
    { label: "Smartphones", link: "/products/electronics/smartphones" },
  ];

  readonly treeItems: TreeviewItemProps[] = [
    {
      id: "root-1",
      labelText: "Root item 1",
      isOpen: true,
      items: [
        {
          id: "child-1",
          labelText: "Child item 1",
        },
        {
          id: "child-2",
          labelText: "Child item 2",
        },
      ],
    },
    {
      id: "root-2",
      labelText: "Root item 2",
    },
  ];

  handleModalPrimaryClick() {
    console.log("Primary button clicked");
  }

  handleModalSecondaryClick() {
    console.log("Secondary button clicked");
  }

  rteSplitButtonOptions = [
    { id: "option-1", label: "Option 1", onClick: () => console.log("Option 1 clicked") },
    { id: "option-2", label: "Option 2", onClick: () => console.log("Option 2 clicked") },
    { id: "option-3", label: "Option 3", onClick: () => console.log("Option 3 clicked") },
  ];

  readonly activeItem = signal<string>("home");

  readonly headerConfig = {
    identifier: "DS",
    title: "Design System",
    version: "V1.0.0",
    icon: "home",
    link: "/",
  };

  readonly baseNavigationItems: NavItemProps[] = [
    { id: "home", label: "Home", icon: "home", showIcon: true },
    { id: "dashboard", label: "Dashboard", icon: "dashboard", showIcon: true },
    { id: "analytics", label: "Analytics", icon: "analytics", showIcon: true },
    { id: "settings", label: "Settings", icon: "settings", showIcon: true },
    { id: "profile", label: "Profile", icon: "user", showIcon: true, link: "/profile" },
  ];

  readonly navigationItems = computed<NavItemProps[]>(() => {
    return this.baseNavigationItems.map((item) => ({
      ...item,
      active: item.id === this.activeItem(),
      onClick: () => {
        this.activeItem.set(item.id || "");
      },
    }));
  });

  readonly baseFooterItems: NavItemProps[] = [
    {
      id: "footer-settings",
      label: "Settings",
      icon: "settings",
      showIcon: true,
    },
    {
      id: "footer-help",
      label: "Help & Support",
      icon: "help",
      showIcon: true,
      link: "/help",
    },
    {
      id: "footer-account",
      label: "Account",
      icon: "user",
      showIcon: true,
      items: [
        { id: "footer-profile", label: "Profile", link: "/profile" },
        { id: "footer-preferences", label: "Preferences" },
        { id: "footer-logout", label: "Logout", onClick: () => console.log("Logout clicked") },
      ],
    },
  ];

  readonly footerItems = computed<NavItemProps[]>(() => {
    return this.baseFooterItems.map((item) => ({
      ...item,
      active: item.id === this.activeItem(),
    }));
  });

  handleItemClick(itemId: string): void {
    if (itemId === "footer-settings") {
      console.log("Footer Settings clicked");
    }
    this.activeItem.set(itemId);
  }
  toggleToast() {
    console.log("Toast toggled from app component");
    if (this.toastService.isInQueue(this.currentOpenedToastId)) {
      this.toastService.removeFromQueue(this.currentOpenedToastId);
      return;
    }
    this.currentOpenedToastId = this.toastService.addToQueue({
      message: "This is a toast message from AppComponent",
      type: "success",
      placement: "top-right",
      autoDismiss: true,
      duration: "medium",
      closable: true,
      showActionButton: false,
    });
  }

  readonly selectOptions = [
    { value: "option1", label: "Option 1" },
    { value: "option2", label: "Option 2" },
    { value: "option3", label: "Option 3" },
  ];

  readonly tabOptions = [
    { id: "tab-1", label: "Onglet 1", panelId: "panel-1" },
    { id: "tab-2", label: "Onglet 2", panelId: "panel-2" },
    { id: "tab-3", label: "Onglet 3", panelId: "panel-3" },
  ];

  selectedTabId = signal("tab-1");

  readonly dropdownItems = [
    { label: "Edit", leftIcon: "edit" },
    { label: "Duplicate", leftIcon: "copy" },
    { label: "Share", leftIcon: "share", hasSeparator: true },
    { label: "Delete", leftIcon: "delete" },
  ];

  selectedDropdownItem = signal<string | null>(null);

  onDropdownItemClick(event: { event: Event; id: string }): void {
    this.selectedDropdownItem.set(event.id);
  }

  onTabChange(tabId: string): void {
    this.selectedTabId.set(tabId);
  }
  readonly allClickableSteps: Step[] = [
    {
      id: "1",
      name: "Étape 1",
      completionState: "complete",
      onClick: () => this.activeStepId.set("1"),
      clickableCompleteStep: true,
    },
    { id: "2", name: "Étape 2", completionState: "incomplete", onClick: () => this.activeStepId.set("2") },
    { id: "3", name: "Étape 3", completionState: "unvisited", onClick: () => this.activeStepId.set("3") },
    { id: "4", name: "Étape 4", completionState: "unvisited", onClick: () => this.activeStepId.set("4") },
    { id: "5", name: "Étape 5", completionState: "unvisited", onClick: () => this.activeStepId.set("5") },
    { id: "6", name: "Étape 6", completionState: "unvisited", onClick: () => this.activeStepId.set("6") },
    { id: "7", name: "Étape 7", completionState: "unvisited", onClick: () => this.activeStepId.set("7") },
  ];
}

<rte-side-nav
  [headerConfig]="headerConfig"
  [items]="navigationItems()"
  [footerItems]="footerItems()"
  [collapsible]="true"
  [appearance]="'brand'"
  (itemClicked)="handleItemClick($event)"
>
  <div content>
    <rte-header
      appearance="brand"
      [isSticky]="true"
      [showAtScrollUp]="true"
      [applicationName]="'Design System RTE'"
      [hasSearchbar]="false"
      [navigationItems]="headerNavigationItems()"
      [subHeaderConfig]="headerSubHeaderConfig"
      [actionButton]="headerActionButton"
      [iconButtons]="headerIconButtons"
      [avatarProps]="headerAvatar"
      (navigationItemClick)="handleHeaderNavigationItemClick($event)"
      (actionButtonClick)="handleHeaderActionButtonClick()"
      (iconButtonClick)="handleHeaderIconButtonClick($event)"
      (avatarClick)="handleHeaderAvatarClick()"
    />
    <section
      style="
        max-width: 560px;
        margin: 16px 0;
        padding: 20px;
        border: 1px solid #c7dbf0;
        border-radius: 8px;
        font-family: Arial;
      "
    >
      <h3 style="margin: 0 0 4px 0">Reactive form integration</h3>
      <p style="margin: 0 0 20px 0; color: #666; font-size: 14px">
        All form-capable DS components bound with <code>formControlName</code> inside a single Angular reactive form.
      </p>

      <form
        [formGroup]="profileForm"
        (ngSubmit)="onFormSubmit()"
        style="display: flex; flex-direction: column; gap: 16px"
      >
        <rte-text-input
          formControlName="fullName"
          id="form-full-name"
          label="Full name"
          [required]="true"
          assistiveTextLabel="Required, min. 3 characters."
        />

        <rte-select
          formControlName="role"
          id="form-role"
          label="Role"
          [options]="selectOptions"
          [required]="true"
          [showResetButton]="true"
          placeholder="Select a role"
        />

        <rte-textarea
          formControlName="bio"
          id="form-bio"
          label="Bio"
          [showCounter]="true"
          [maxLength]="200"
          assistiveTextLabel="Max. 200 characters."
        />

        <rte-datepicker
          formControlName="appointmentDate"
          id="form-appointment-date"
          labelText="Appointment date"
          [hasLabel]="true"
          locale="fr-FR"
        />

        <rte-daterangepicker
          formControlName="period"
          id="form-period"
          labelText="Availability period"
          [hasLabel]="true"
          locale="fr-FR"
        />

        <rte-time-picker
          formControlName="appointmentTime"
          id="form-appointment-time"
          labelId="form-appointment-time-label"
          label="Appointment time"
          [showLabel]="true"
        />

        <div style="display: flex; gap: 12px; flex-wrap: wrap">
          <button rteButton type="submit" [disabled]="profileForm.invalid">Submit</button>
          <button rteButton rteButtonVariant="neutral" type="button" (click)="resetForm()">Reset</button>
          <button rteButton rteButtonVariant="neutral" type="button" (click)="toggleFormDisabled()">
            {{ profileForm.disabled ? "Enable all" : "Disable all" }}
          </button>
        </div>
      </form>

      <div style="margin-top: 20px; font-family: monospace; font-size: 13px; color: #333">
        <p style="margin: 0">status: {{ profileForm.status }}</p>
        <p style="margin: 4px 0 0 0">
          valid: {{ profileForm.valid }} | touched: {{ profileForm.touched }} | dirty: {{ profileForm.dirty }}
        </p>
        <pre style="white-space: pre-wrap; margin: 8px 0 0 0">{{ formSummary() }}</pre>
        @if (submittedValue()) {
          <p style="margin: 8px 0 0 0; color: #1a7f37">Submitted:</p>
          <pre style="white-space: pre-wrap; margin: 4px 0 0 0; color: #1a7f37">{{ submittedValue() }}</pre>
        }
      </div>
    </section>
    <div style="width: 400px; background: #c7dbf0; padding: 16px">
      <rte-accordion icon="power-wind" appearance="brand" alignement="right" size="small">
        <p style="margin: 0; font-family: Arial">
          Base accordion case in Angular test app to validate library integration with host applications.
        </p>
      </rte-accordion>
    </div>
    <hr />
    <rte-tab [options]="tabOptions" [selectedTabId]="selectedTabId()" (change)="onTabChange($event)"></rte-tab>
    <div style="height: 16px">
      <p>Content for {{ selectedTabId() }}</p>
    </div>
    <div rteDropdown (menuEvent)="onDropdownItemClick($event)">
      <button rteDropdownTrigger rteButton buttonType="button">Dropdown</button>
      <rte-dropdown-menu [items]="dropdownItems" />
    </div>
    @if (selectedDropdownItem()) {
      <span style="margin-left: 8px">Selected: {{ selectedDropdownItem() }}</span>
    }
    <hr />
    <rte-card>
      <div style="padding: 16px">
        <h4 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600">Default Card</h4>
        <p style="margin: 0; color: #666; line-height: 1.5">
          This is a default card with medium size. It uses elevation shadow styling.
        </p>
      </div>
    </rte-card>
    <rte-stepper [steps]="allClickableSteps" [activeStepId]="activeStepId()" orientation="horizontal"></rte-stepper>
    <hr />
    <rte-treeview [items]="treeItems"></rte-treeview>
    <rte-banner
      type="info"
      message="This is an info banner"
      [closable]="true"
      title="Info Banner"
      [isOpen]="isInfoBannerVisible()"
    ></rte-banner>
    <rte-banner
      type="error"
      message="This is an alert banner"
      [closable]="true"
      title="Alert Banner"
      [isOpen]="isAlertBannerVisible()"
    ></rte-banner>
    <button
      rteButton
      [disabled]="false"
      ariaLabel="Home"
      ariaLabelledBy="home"
      buttonType="button"
      (click)="toggleAlertBanner()"
    >
      Toggle alert banner
    </button>
    <button
      rteButton
      [disabled]="false"
      ariaLabel="Home"
      ariaLabelledBy="home"
      buttonType="button"
      (click)="toggleInfoBanner()"
    >
      Toggle info banner
    </button>
    <hr />
    <button rteButton [disabled]="false" icon="home" ariaLabel="Home" ariaLabelledBy="home" buttonType="button">
      Button
    </button>

    <rte-icon name="home" />

    <hr />

    <rte-split-button label="Split Button" [options]="rteSplitButtonOptions" />

    <hr />

    <rte-icon-button-toggle name="home" [selected]="selected()" (click)="onClick($event)" />

    <hr />

    <span rteTooltip="Tooltip">Tooltip</span>

    <hr />

    <rte-text-input label="Text Input" [value]="inputValue()" (valueChange)="handleInputChange($event)" />
    <h4>The input is : {{ inputValue() }}</h4>
    <hr />
    <section style="max-width: 360px">
      <h4 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600">Time picker</h4>
      <p style="margin: 0 0 12px 0; color: #666; line-height: 1.5; font-size: 14px">
        Bundled library smoke test: dropdown, focus trap, and segment inputs.
      </p>
      <rte-time-picker
        id="integration-time-picker"
        labelId="integration-time-picker-label"
        label="Appointment time"
        [showLabel]="true"
        assistiveTextLabel="24-hour format."
        assistiveAppearance="description"
        [value]="timePickerValue()"
        (valueChange)="onTimePickerValueChange($event)"
      />
      <p style="margin: 12px 0 0 0; font-family: monospace; font-size: 13px; color: #333">
        segments: {{ timePickerValue().hh }} / {{ timePickerValue().mm }} / {{ timePickerValue().ss }}
      </p>
    </section>
    <hr />
    <section style="max-width: 500px">
      <h4 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600">Date picker</h4>
      <p style="margin: 0 0 12px 0; color: #666; line-height: 1.5; font-size: 14px">
        Bundled library smoke test: segmented field, calendar overlay, and confirm/cancel actions.
      </p>
      <rte-datepicker
        id="integration-datepicker"
        labelText="Date"
        [hasLabel]="true"
        assistiveTextLabel="French locale (fr-FR)."
        [hasAssistiveText]="true"
        locale="fr-FR"
        [(ngModel)]="datepickerValue"
        (valueChange)="onDatepickerValueChange($event)"
      />
      <p style="margin: 12px 0 0 0; font-family: monospace; font-size: 13px; color: #333">
        value: {{ formatPickerDate(datepickerValue) }}
      </p>
    </section>
    <hr />
    <section style="max-width: 500px">
      <h4 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600">Date range picker</h4>
      <p style="margin: 0 0 12px 0; color: #666; line-height: 1.5; font-size: 14px">
        Bundled library smoke test: dual segmented fields, range selection, and calendar overlay.
      </p>
      <rte-daterangepicker
        id="integration-daterangepicker"
        labelText="Période"
        [hasLabel]="true"
        assistiveTextLabel="Select a start and end date."
        [hasAssistiveText]="true"
        locale="fr-FR"
        [(ngModel)]="dateRangeValue"
        (valueChange)="onDateRangeValueChange($event)"
      />
      <p style="margin: 12px 0 0 0; font-family: monospace; font-size: 13px; color: #333">
        value: {{ dateRangeSummary() }}
      </p>
    </section>
    <hr />
    <rte-chip label="Chip Label" type="single"></rte-chip>
    <hr />

    <p style="display: inline-block; background-color: bisque" rteBadge [rteBadgeCount]="1">A badge host</p>
    <hr />
    <rte-textarea
      label="Enter text"
      labelPosition="top"
      assistiveTextLabel="This is a label"
      assistiveTextAppearance="link"
      assistiveTextLinkLabel="Learn more"
      assistiveTextLink="https://example.com"
      [required]="true"
    />
    <hr />
    <rte-link href="https://example.com" label="Link" [subtle]="false" />

    <p>Divider</p>
    <rte-divider />
    <div style="display: flex; flex-direction: row">
      <p style="margin: 20px">left text</p>
      <rte-divider orientation="vertical" />
      <p style="margin: 20px">middle text</p>
      <rte-divider orientation="vertical" thickness="medium" />
      <p style="margin: 20px">right text</p>
      <rte-divider orientation="vertical" thickness="bold" />
    </div>

    <hr />

    <rte-switch label="Switch" [disabled]="false" [readOnly]="false" [appearance]="'brand'" />
    <rte-switch
      label="Switch ReadOnly"
      [disabled]="false"
      [readOnly]="true"
      [appearance]="'brand'"
      [showIcon]="true"
    />
    <rte-switch
      label="Switch disabled"
      [disabled]="true"
      [readOnly]="false"
      [appearance]="'brand'"
      [showLabel]="true"
      [checked]="true"
    />
    <rte-divider orientation="vertical" thickness="bold"></rte-divider>
    <hr />
    <div style="width: 380px; display: flex; flex-direction: column; gap: 10px">
      <rte-segmented-control
        [options]="segments"
        [selectedSegment]="selectedSegment()"
        (change)="onSegmentSelected($event)"
      />
    </div>
    <hr />
    <rte-breadcrumbs [items]="breadcrumbItems" />
    <hr />
    <div style="margin-top: 100px; display: flex; justify-content: center">
      <button
        rteButton
        buttonType="button"
        rtePopover
        rtePopoverPrimaryButtonLabel="Primary"
        rtePopoverContent="This is the popover content"
        rtePopoverTitle="Popover Title"
      >
        Hover me
      </button>
    </div>
    <rte-divider />
    <div
      rteModal
      [rteModalId]="'rte-modal-1'"
      [rteModalTitle]="'Modal title'"
      [rteModalDescription]="'This is a description for the modal.'"
    >
      <button rteButton rteButtonVariant="primary" rteModalTrigger>Open Modal</button>
      <ng-template #primaryButton>
        <button rteButton rteButtonVariant="primary" (click)="handleModalPrimaryClick()">Continue</button>
      </ng-template>
      <ng-template #secondaryButton>
        <button rteButton rteButtonVariant="neutral" (click)="handleModalSecondaryClick()">Cancel</button>
      </ng-template>
      <rte-divider />
      <div>
        <button rteButton rteButtonVariant="neutral" (click)="toggleToast()">Toggle Toast</button>
      </div>
      <rte-divider />
      <rte-select label="Select an option" [options]="selectOptions" [showResetButton]="true" />
    </div>
    <rte-loader [size]="'medium'" />
  </div>
</rte-side-nav>
