// packages/react/src/components/sideNav/SideNav.tsx
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { getDividerAppearanceBySideNavTheme } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavProps as CoreSideNavProps } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { forwardRef, Fragment, ReactNode, useEffect, useState } from "react";

import { useActiveKeyboard } from "../../hooks/useActiveKeyboard";
import Divider from "../divider/Divider";

import BaseSideNav from "./baseSideNav/BaseSideNav";
import NavItem from "./navItem/NavItem";
import NavMenu from "./navMenu/NavMenu";
import style from "./SideNav.module.scss";

interface SideNavProps extends Partial<CoreSideNavProps>, Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  children?: ReactNode;
  defaultCollapsed?: boolean;
  onCollapsedChange?: (collapsed: boolean) => void;
}

const TRANSITION_DURATION = 300;

const SideNav = forwardRef<HTMLElement | HTMLDivElement, SideNavProps>(
  (
    {
      size = "m",
      collapsible,
      children,
      headerConfig,
      items,
      footerItems,
      isCollapsed: controlledIsCollapsed,
      defaultCollapsed = false,
      onCollapsedChange,
      appearance = "brand",
      contrast = "high",
      activeItem,
    }: SideNavProps,
    ref,
  ) => {
    const [isCollapsed, setIsCollapsed] = useState(controlledIsCollapsed ?? defaultCollapsed);
    const [shouldShowTitle, setShouldShowTitle] = useState(true);

    useEffect(() => {
      if (controlledIsCollapsed !== undefined) {
        setIsCollapsed(controlledIsCollapsed);
      }
    }, [controlledIsCollapsed]);

    useEffect(() => {
      if (isCollapsed) {
        setShouldShowTitle(false);
      } else {
        const timer = setTimeout(() => {
          setShouldShowTitle(true);
        }, TRANSITION_DURATION);
        return () => clearTimeout(timer);
      }
    }, [isCollapsed]);

    const collapseSideNav = () => {
      const newCollapsed = !isCollapsed;
      if (controlledIsCollapsed === undefined) {
        setIsCollapsed(newCollapsed);
      }
      onCollapsedChange?.(newCollapsed);
    };

    const collapseIcon = isCollapsed ? "arrow-double-right" : "arrow-double-left";

    const dividerAppearance = getDividerAppearanceBySideNavTheme(appearance, contrast);

    const handleHeaderKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      if ([SPACE_KEY, ENTER_KEY].includes(e.key)) {
        e.preventDefault();
        if (headerConfig?.onClick) {
          headerConfig.onClick();
        }
      }
    };

    const { onKeyDown: headerOnKeyDown } = useActiveKeyboard<HTMLDivElement>(
      { onKeyDown: handleHeaderKeyDown },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY],
      },
    );

    const headerTitleContent = (
      <div className={style.sideNavHeaderTitle}>
        <div className={style.sideNavHeaderIdentifier}>{headerConfig?.identifier}</div>
        {isCollapsed ? "" : <h1 data-hidden={!shouldShowTitle}>{headerConfig?.title}</h1>}
      </div>
    );

    const ariaLabel = headerConfig?.ariaLabel;

    const headerTitleLink = (
      <a
        href={headerConfig?.link ?? ""}
        className={style.sideNavHeaderTitleContainer}
        onClick={headerConfig?.onClick}
        aria-label={ariaLabel}
      >
        {headerTitleContent}
      </a>
    );

    const clickableHeaderTitle = (
      <div
        className={style.sideNavHeaderTitleContainer}
        tabIndex={0}
        onClick={headerConfig?.onClick}
        onKeyDown={headerOnKeyDown}
        role="button"
        aria-label={ariaLabel}
      >
        {headerTitleContent}
      </div>
    );

    const headerTitle = headerConfig?.link ? (
      headerTitleLink
    ) : headerConfig?.onClick ? (
      clickableHeaderTitle
    ) : (
      <div className={style.sideNavHeaderTitleContainer}>{headerTitleContent}</div>
    );

    function renderNavItems(itemsToRender: NavItemProps[] | undefined) {
      if (!itemsToRender?.length) {
        return null;
      }

      return (
        <ul>
          {itemsToRender.map((item: NavItemProps) => {
            const hasNestedItems = item.items?.length;
            if (hasNestedItems) {
              return (
                <NavMenu
                  key={item.id}
                  id={item.id}
                  badge={item.badge}
                  label={item.label}
                  icon={item.icon}
                  hasLeadingIcon={item.hasLeadingIcon}
                  isCollapsed={isCollapsed}
                  link={item.link}
                  onClick={item.onClick}
                  items={item.items || []}
                  open={(item as NavMenuProps).open}
                  active={item.active}
                  appearance={appearance}
                  contrast={contrast}
                  hasDivider={item.hasDivider}
                />
              );
            }
            return (
              <Fragment key={item.id}>
                <li>
                  <NavItem
                    id={item.id}
                    badge={item.badge}
                    label={item.label}
                    icon={item.icon}
                    hasLeadingIcon={item.hasLeadingIcon}
                    isCollapsed={isCollapsed}
                    link={item.link}
                    onClick={item.onClick}
                    appearance={appearance}
                    active={item.id === activeItem && !!activeItem}
                  />
                </li>
                {item.hasDivider && <Divider appearance={dividerAppearance} />}
              </Fragment>
            );
          })}
        </ul>
      );
    }

    return (
      <BaseSideNav
        ref={ref}
        size={size}
        isCollapsed={isCollapsed}
        appearance={appearance}
        contrast={contrast}
        className={style.sideNavContainer}
        header={
          <div className={style.sideNavHeaderContainer}>
            <div className={style.sideNavHeader} data-collapsed={isCollapsed} data-appearance={appearance}>
              {headerTitle}
              <div className={style.sideNavHeaderVersion} data-hidden={!shouldShowTitle}>
                <span>{headerConfig?.version}</span>
              </div>
            </div>
            <Divider appearance={dividerAppearance} />
          </div>
        }
        body={<div className={style.sideNavBody}>{renderNavItems(items)}</div>}
        footer={
          (footerItems?.length || collapsible) && (
            <div className={style.sideNavFooterContainer}>
              {footerItems?.length && <div className={style.sideNavFooterItems}>{renderNavItems(footerItems)}</div>}
              <Divider appearance={dividerAppearance} />
              <div className={style.sideNavFooter}>
                {collapsible && (
                  <div className={style.collapsibleSection}>
                    <NavItem
                      id="collapse-button"
                      icon={collapseIcon}
                      hasLeadingIcon={true}
                      isCollapsed={isCollapsed}
                      onClick={collapseSideNav}
                      label={isCollapsed ? "Ouvrir le menu" : "Réduire le menu"}
                      appearance={appearance}
                      role="button"
                    />
                  </div>
                )}
              </div>
            </div>
          )
        }
      >
        {children}
      </BaseSideNav>
    );
  },
);

export default SideNav;

// packages/angular/projects/ds-rte-lib/src/lib/components/side-nav/side-nav.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, input, output, signal } from "@angular/core";
import { getDividerAppearanceBySideNavTheme } from "@design-system-rte/core";
import { SideNavAppearance, SideNavContrast, SideNavHeaderConfig } from "@design-system-rte/core";
import { DividerAppearance } from "@design-system-rte/core/components/divider/divider.interface";
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { SideNavSize } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { DividerComponent } from "../divider/divider.component";

import { BaseSideNavComponent } from "./base-side-nav/base-side-nav.component";
import { NavItemComponent } from "./nav-item/nav-item.component";
import { NavMenuComponent, NavMenuOpenChangeEvent } from "./nav-menu/nav-menu.component";

const TRANSITION_DURATION = 300;

@Component({
  selector: "rte-side-nav",
  imports: [CommonModule, BaseSideNavComponent, DividerComponent, NavItemComponent, NavMenuComponent],
  standalone: true,
  templateUrl: "./side-nav.component.html",
  styleUrl: "./side-nav.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SideNavComponent {
  readonly size = input<SideNavSize>("m" as SideNavSize);
  readonly collapsible = input<boolean>(false);
  readonly headerConfig = input<SideNavHeaderConfig | undefined>();
  readonly items = input<NavItemProps[]>([]);
  readonly footerItems = input<NavItemProps[] | undefined>();
  readonly isCollapsed = input<boolean>(false);
  readonly appearance = input<SideNavAppearance>("brand");
  readonly contrast = input<SideNavContrast>("high");

  readonly collapsedState = signal<boolean>(false);
  readonly shouldShowTitle = signal<boolean>(true);

  readonly itemClicked = output<string>();

  private titleTimeoutId: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    effect(
      () => {
        this.collapsedState.set(this.isCollapsed());
      },
      { allowSignalWrites: true },
    );

    effect(
      () => {
        if (this.titleTimeoutId) {
          clearTimeout(this.titleTimeoutId);
          this.titleTimeoutId = null;
        }

        if (this.collapsedState()) {
          this.shouldShowTitle.set(false);
        } else {
          this.titleTimeoutId = setTimeout(() => {
            this.shouldShowTitle.set(true);
            this.titleTimeoutId = null;
          }, TRANSITION_DURATION);
        }
      },
      { allowSignalWrites: true },
    );
  }

  readonly collapseIcon = computed<string>(() => {
    return this.collapsedState() ? "arrow-double-right" : "arrow-double-left";
  });

  readonly dividerAppearance = computed<DividerAppearance>(() => {
    return getDividerAppearanceBySideNavTheme(this.appearance(), this.contrast());
  });

  handleHeaderKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      const config = this.headerConfig();
      if (config?.onClick) {
        config.onClick();
      }
    }
  }

  handleHeaderClick(): void {
    const config = this.headerConfig();
    if (config?.onClick) {
      config.onClick();
    }
  }

  hasNestedItems(item: NavItemProps): item is NavMenuProps {
    return !!item.items?.length;
  }

  handleItemClick(itemId: string): void {
    this.itemClicked.emit(itemId);
  }

  handleFooterItemClick(itemId: string): void {
    this.itemClicked.emit(itemId);
  }

  handleMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const targetMenu = this.items().find((item) => item.id === event.id || item.label === event.id);
    if (targetMenu) {
      (targetMenu as NavMenuProps).open = event.open;
    }
  }

  handleFooterMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const targetMenu = this.footerItems()?.find((item) => item.id === event.id || item.label === event.id);
    if (targetMenu) {
      (targetMenu as NavMenuProps).open = event.open;
    }
  }

  handleCollapseClick(): void {
    this.collapsedState.set(!this.collapsedState());
  }
}

<rte-base-side-nav [size]="size()" [isCollapsed]="collapsedState()" [appearance]="appearance()" [contrast]="contrast()">
  <div side-nav-header>
    <div class="side-nav-header-container" [attr.data-compact]="headerConfig()?.isCompact ?? false">
      <div
        class="side-nav-header {{ appearance() }}"
        [ngClass]="{ collapsed: collapsedState() }"
        [attr.data-compact]="headerConfig()?.isCompact ?? false"
      >
        @if (headerIsInternalRoute()) {
          <a
            class="side-nav-header-title-container"
            [routerLink]="headerRoute()!"
            [attr.aria-label]="headerConfig()?.ariaLabel"
            (click)="handleHeaderClick()"
          >
            <div class="side-nav-header-title">
              <div class="side-nav-header-identifier">{{ headerConfig()?.identifier }}</div>
              @if (!collapsedState()) {
                <h1 [ngClass]="{ hidden: !shouldShowTitle() }">{{ headerConfig()?.title }}</h1>
              }
            </div>
          </a>
        } @else if (headerRoute() && headerConfig()?.external) {
          <a
            class="side-nav-header-title-container"
            target="_blank"
            rel="noopener noreferrer"
            [href]="headerRoute()!"
            [attr.aria-label]="headerConfig()?.ariaLabel"
            (click)="handleHeaderClick()"
          >
            <div class="side-nav-header-title">
              <div class="side-nav-header-identifier">{{ headerConfig()?.identifier }}</div>
              @if (!collapsedState()) {
                <h1 [ngClass]="{ hidden: !shouldShowTitle() }">{{ headerConfig()?.title }}</h1>
              }
            </div>
          </a>
        } @else if (headerConfig()?.onClick) {
          <button
            type="button"
            class="side-nav-header-title-container"
            [attr.aria-label]="headerConfig()?.ariaLabel"
            (click)="handleHeaderClick()"
            (keydown)="handleHeaderKeyDown($event)"
          >
            <div class="side-nav-header-title">
              <div class="side-nav-header-identifier">{{ headerConfig()?.identifier }}</div>
              @if (!collapsedState()) {
                <h1 [ngClass]="{ hidden: !shouldShowTitle() }">{{ headerConfig()?.title }}</h1>
              }
            </div>
          </button>
        } @else {
          <div class="side-nav-header-title-container">
            <div class="side-nav-header-title">
              <div class="side-nav-header-identifier">{{ headerConfig()?.identifier }}</div>
              @if (!collapsedState()) {
                <h1 [ngClass]="{ hidden: !shouldShowTitle() }">{{ headerConfig()?.title }}</h1>
              }
            </div>
          </div>
        }
        @if (!headerConfig()?.isCompact) {
          <div class="side-nav-header-version" [ngClass]="{ hidden: !shouldShowTitle() }">
            <span>{{ headerConfig()?.version }}</span>
          </div>
        }
      </div>
      <rte-divider [appearance]="dividerAppearance()" />
    </div>
  </div>
  <div side-nav-body>
    <div class="side-nav-body">
      <ul>
        @for (item of items(); track item.id || item.label) {
          @if (isNavGroup(item)) {
            <rte-nav-menu
              [id]="item.id"
              [label]="item.label"
              [icon]="item.icon"
              [hasLeadingIcon]="item.hasLeadingIcon ?? true"
              [isCollapsed]="collapsedState()"
              [route]="item.route"
              [external]="item.external ?? false"
              [open]="item.open"
              [active]="item.active ?? false"
              [items]="item.items"
              [appearance]="appearance()"
              [contrast]="contrast()"
              [badge]="item.badge"
              [hasDivider]="item.hasDivider ?? false"
              (itemClick)="handleItemClick($event)"
              (openChange)="handleMenuOpenChange($event)"
            />
          } @else if (isNavLink(item)) {
            <li>
              <rte-nav-item
                kind="link"
                [id]="item.id"
                [label]="item.label"
                [icon]="item.icon"
                [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                [isCollapsed]="collapsedState()"
                [route]="item.route"
                [external]="item.external ?? false"
                [appearance]="appearance()"
                [active]="item.active ?? false"
                [badge]="item.badge"
                (itemClick)="handleItemClick(item.id || item.label)"
              />
            </li>
            @if (item.hasDivider) {
              <rte-divider [appearance]="dividerAppearance()" />
            }
          } @else if (isNavAction(item)) {
            <li>
              <rte-nav-item
                kind="action"
                [id]="item.id"
                [label]="item.label"
                [icon]="item.icon"
                [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                [isCollapsed]="collapsedState()"
                [appearance]="appearance()"
                [active]="item.active ?? false"
                [badge]="item.badge"
                (itemClick)="handleItemActivate(item, item.id || item.label)"
              />
            </li>
            @if (item.hasDivider) {
              <rte-divider [appearance]="dividerAppearance()" />
            }
          }
        }
      </ul>
    </div>
  </div>
  @if (footerItems()?.length || collapsible()) {
    <div side-nav-footer>
      <div class="side-nav-footer-container">
        @if (footerItems()?.length) {
          <div class="side-nav-footer-items">
            <ul>
              @for (item of footerItems()!; track item.id || item.label) {
                @if (isNavGroup(item)) {
                  <rte-nav-menu
                    [id]="item.id"
                    [label]="item.label"
                    [icon]="item.icon"
                    [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                    [isCollapsed]="collapsedState()"
                    [route]="item.route"
                    [external]="item.external ?? false"
                    [open]="item.open"
                    [active]="item.active ?? false"
                    [items]="item.items"
                    [appearance]="appearance()"
                    [contrast]="contrast()"
                    [badge]="item.badge"
                    [hasDivider]="item.hasDivider ?? false"
                    (itemClick)="handleItemClick($event)"
                    (openChange)="handleFooterMenuOpenChange($event)"
                  />
                } @else if (isNavLink(item)) {
                  <li>
                    <rte-nav-item
                      kind="link"
                      [id]="item.id"
                      [label]="item.label"
                      [icon]="item.icon"
                      [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                      [isCollapsed]="collapsedState()"
                      [route]="item.route"
                      [external]="item.external ?? false"
                      [appearance]="appearance()"
                      [active]="item.active ?? false"
                      [badge]="item.badge"
                      (itemClick)="handleItemClick(item.id || item.label)"
                    />
                  </li>
                  @if (item.hasDivider) {
                    <rte-divider [appearance]="dividerAppearance()" />
                  }
                } @else if (isNavAction(item)) {
                  <li>
                    <rte-nav-item
                      kind="action"
                      [id]="item.id"
                      [label]="item.label"
                      [icon]="item.icon"
                      [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                      [isCollapsed]="collapsedState()"
                      [appearance]="appearance()"
                      [active]="item.active ?? false"
                      [badge]="item.badge"
                      (itemClick)="handleItemActivate(item, item.id || item.label)"
                    />
                  </li>
                  @if (item.hasDivider) {
                    <rte-divider [appearance]="dividerAppearance()" />
                  }
                }
              }
            </ul>
          </div>
        }
        <rte-divider [appearance]="dividerAppearance()" />
        @if (collapsible()) {
          <div class="side-nav-footer">
            <div class="collapsible-section">
              <ul>
                <li>
                  <rte-nav-item
                    kind="action"
                    [label]="collapsedState() ? 'Ouvrir le menu' : 'Réduire le menu'"
                    [icon]="collapseIcon()"
                    [isCollapsed]="collapsedState()"
                    [appearance]="appearance()"
                    (itemClick)="handleCollapseClick()"
                  />
                </li>
              </ul>
            </div>
          </div>
        }
      </div>
    </div>
  }
  <div side-nav-content>
    <ng-content select="[content]"></ng-content>
  </div>
</rte-base-side-nav>
