// preview/sidenav-design-dev/angular/components/side-nav/nav-menu/nav-menu.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input, signal } from "@angular/core";
import { BadgeProps } from "@design-system-rte/core/components/badge/badge.interface";
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { dividerAppearanceBySideNavAppearance } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavAppearance } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, ESCAPE_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { BadgeComponent } from "../../badge/badge.component";
import { DividerComponent } from "../../divider/divider.component";
import { IconComponent } from "../../icon/icon.component";
import { TooltipDirective } from "../../tooltip/tooltip.directive";
import { NavItemComponent } from "../nav-item/nav-item.component";

function getNavTabIndex(parentMenuOpen?: boolean): number {
  return parentMenuOpen === false ? -1 : 0;
}

@Component({
  selector: "rte-nav-menu",
  imports: [CommonModule, IconComponent, BadgeComponent, DividerComponent, NavItemComponent, TooltipDirective],
  standalone: true,
  templateUrl: "./nav-menu.component.html",
  styleUrl: "./nav-menu.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavMenuComponent {
  readonly icon = input<string | undefined>();
  readonly showIcon = input<boolean>(true);
  readonly label = input.required<string>();
  readonly collapsed = input<boolean>(false);
  readonly link = input<string | undefined>();
  readonly onClick = input<(() => void) | undefined>();
  readonly items = input.required<NavItemProps[]>();
  readonly open = input<boolean | undefined>();
  readonly showMenuIcon = input<boolean>(true);
  readonly isNested = input<boolean>(false);
  readonly parentMenuOpen = input<boolean | undefined>();
  readonly appearance = input<SideNavAppearance>("brand");
  readonly badge = input<BadgeProps | undefined>();
  readonly showDivider = input<boolean>(false);

  readonly internalOpen = signal<boolean>(false);

  readonly isOpen = computed<boolean>(() => {
    const controlledOpen = this.open();
    return controlledOpen !== undefined ? controlledOpen : this.internalOpen();
  });

  readonly isControlled = computed<boolean>(() => this.open() !== undefined);

  readonly hasNestedItems = computed<boolean>(() => this.items().length > 0);
  readonly shouldShowMenu = computed<boolean>(() => !this.collapsed() && this.hasNestedItems());
  readonly nestedItemsParentMenuOpen = computed<boolean>(() => this.isOpen());
  readonly tabIndex = computed<number>(() => getNavTabIndex(this.parentMenuOpen()));

  readonly dividerAppearance = computed(() => dividerAppearanceBySideNavAppearance[this.appearance()]);

  readonly iconSize = computed<number>(() => {
    return this.isNested() ? 16 : this.collapsed() ? 24 : 20;
  });

  readonly containerClasses = computed<string>(() => {
    const classes: string[] = ["nav-menu-container", this.appearance()];
    if (this.collapsed()) {
      classes.push("collapsed");
    }
    if (this.isOpen()) {
      classes.push("open");
    }
    if (this.isNested()) {
      classes.push("nested");
    }
    return classes.join(" ");
  });

  readonly menuIconClasses = computed<string>(() => {
    const classes: string[] = ["menu-icon"];
    if (this.isOpen()) {
      classes.push("menu-icon-open");
    }
    return classes.join(" ");
  });

  readonly nestedMenuClasses = computed<string>(() => {
    const classes: string[] = ["nested-menu"];
    if (this.isOpen()) {
      classes.push("nested-menu-open");
    }
    return classes.join(" ");
  });

  toggleMenu(): void {
    if (!this.isControlled()) {
      this.internalOpen.set(!this.internalOpen());
    }
    const onClickFn = this.onClick();
    if (onClickFn) {
      onClickFn();
    }
  }

  handleEscape(): void {
    if (this.isOpen() && !this.isControlled()) {
      this.internalOpen.set(false);
    }
  }

  handleKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      this.toggleMenu();
    }
    if (event.key === ESCAPE_KEY) {
      event.preventDefault();
      this.handleEscape();
    }
  }

  hasNestedItemsForItem(item: NavItemProps): boolean {
    return !!(item.items && item.items.length > 0);
  }
}

@if (collapsed() && label()) {
  <li rteTooltip rteTooltipPosition="right" rteTooltipAlignment="center" [class]="containerClasses()" [rteTooltip]="label()" [rteTooltipArrow]="false" [rteTooltipShouldFocusTrigger]="false">
    <ng-container [ngTemplateOutlet]="menuContentTemplate"></ng-container>
    <ng-container [ngTemplateOutlet]="nestedMenuTemplate"></ng-container>
  </li>
} @else {
  <li [class]="containerClasses()">
    <ng-container [ngTemplateOutlet]="menuContentTemplate"></ng-container>
    <ng-container [ngTemplateOutlet]="nestedMenuTemplate"></ng-container>
  </li>
}

<ng-template #menuContentTemplate>
  @if (link()) {
    <a
      class="nav-menu"
      [href]="link()!"
      [attr.tabindex]="tabIndex()"
      [attr.aria-label]="label()"
      (click)="toggleMenu()">
      <div class="menu-content-left">
        @if (showIcon() && icon()) {
          <rte-icon class="icon" [name]="icon()!" [size]="iconSize()"></rte-icon>
        }
        @if (!collapsed()) {
          <span>{{ label() }}</span>
        }
      </div>
      <div class="menu-content-right">
        @if (badge()) {
          <rte-badge
            [badgeType]="badge()!.badgeType || 'brand'"
            [badgeSize]="badge()!.size || 'm'"
            [badgeContent]="badge()!.content || 'number'"
            [count]="badge()!.count"
            [icon]="badge()!.icon || 'notification'"></rte-badge>
        }
        @if (shouldShowMenu() && showMenuIcon()) {
          <rte-icon name="arrow-chevron-right" [class]="menuIconClasses()"></rte-icon>
        }
      </div>
    </a>
  } @else {
    <span
      class="nav-menu"
      [attr.tabindex]="tabIndex()"
      [attr.aria-label]="label()"
      (click)="toggleMenu()"
      (keydown)="handleKeyDown($event)">
      <div class="menu-content-left">
        @if (showIcon() && icon()) {
          <rte-icon class="icon" [name]="icon()!" [size]="iconSize()"></rte-icon>
        }
        @if (!collapsed()) {
          <span>{{ label() }}</span>
        }
      </div>
      <div class="menu-content-right">
        @if (badge()) {
          <rte-badge
            [badgeType]="badge()!.badgeType || 'brand'"
            [badgeSize]="badge()!.size || 'm'"
            [badgeContent]="badge()!.content || 'number'"
            [count]="badge()!.count"
            [icon]="badge()!.icon || 'notification'"></rte-badge>
        }
        @if (shouldShowMenu() && showMenuIcon()) {
          <rte-icon name="arrow-chevron-right" [class]="menuIconClasses()"></rte-icon>
        }
      </div>
    </span>
  }
</ng-template>

<ng-template #nestedMenuTemplate>
  @if (shouldShowMenu()) {
    <ul [class]="nestedMenuClasses()">
      @for (item of items(); track item.id || item.label) {
        @if (hasNestedItemsForItem(item)) {
          <rte-nav-menu
            [label]="item.label"
            [icon]="item.icon"
            [showIcon]="item.showIcon"
            [collapsed]="collapsed()"
            [link]="item.link"
            [onClick]="item.onClick"
            [items]="item.items || []"
            [showMenuIcon]="showMenuIcon()"
            [isNested]="true"
            [parentMenuOpen]="nestedItemsParentMenuOpen()"
            [appearance]="appearance()"
            [badge]="item.badge"></rte-nav-menu>
        } @else {
          <li>
            <rte-nav-item
              [id]="item.id"
              [label]="item.label"
              [icon]="item.icon"
              [showIcon]="item.showIcon"
              [collapsed]="collapsed()"
              [link]="item.link"
              [onClick]="item.onClick"
              [isNested]="true"
              [parentMenuOpen]="nestedItemsParentMenuOpen()"
              [appearance]="appearance()"
              [badge]="item.badge"></rte-nav-item>
          </li>
          @if (item.showDivider) {
            <rte-divider [appearance]="dividerAppearance()"></rte-divider>
          }
        }
      }
    </ul>
  }
</ng-template>

@if (showDivider()) {
  <rte-divider [appearance]="dividerAppearance()"></rte-divider>
}

// packages/react/src/components/sideNav/navMenu/NavMenu.tsx
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps as CoreNavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { dividerAppearanceBySideNavAppearance } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import {
  ARROW_DOWN_KEY,
  ARROW_UP_KEY,
  ENTER_KEY,
  ESCAPE_KEY,
  SPACE_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { forwardRef, HTMLAttributes, ReactNode, useState } from "react";

import { useActiveKeyboard } from "../../../hooks/useActiveKeyboard";
import Badge from "../../badge/Badge";
import Divider from "../../divider/Divider";
import Icon from "../../icon/Icon";
import Tooltip from "../../tooltip/Tooltip";
import { concatClassNames } from "../../utils";
import NavItem from "../navItem/NavItem";

import style from "./NavMenu.module.scss";

interface NavMenuProps extends CoreNavMenuProps, Omit<HTMLAttributes<HTMLLIElement>, "onClick"> {
  children?: ReactNode;
  isNested?: boolean;
  parentMenuOpen?: boolean;
}

interface NavMenuContentProps {
  link?: string;
  label: string;
  tabIndex: number;
  onClick: () => void;
  onKeyDown: (e: React.KeyboardEvent<HTMLElement>) => void;
  children: ReactNode;
}

const NavMenuContent = ({ link, label, tabIndex, onClick, onKeyDown, children }: NavMenuContentProps) => {
  const commonProps = {
    className: style.navMenu,
    onClick,
    tabIndex,
    label,
    onKeyDown: onKeyDown as React.KeyboardEventHandler<HTMLElement>,
  };

  if (link) {
    return (
      <a href={link} {...commonProps}>
        {children}
      </a>
    );
  }

  return (
    <span aria-label={label} {...commonProps}>
      {children}
    </span>
  );
};

const NavMenu = forwardRef<HTMLLIElement, NavMenuProps>(
  (
    {
      icon,
      showIcon = true,
      onClick,
      label,
      collapsed,
      link,
      items = [],
      open: controlledOpen,
      showMenuIcon = true,
      isNested,
      parentMenuOpen,
      appearance = "brand",
      badge,
      showDivider,
      ...props
    }: NavMenuProps,
    ref,
  ) => {
    const [internalOpen, setInternalOpen] = useState(false);
    const isOpen = controlledOpen !== undefined ? controlledOpen : internalOpen;
    const isControlled = controlledOpen !== undefined;

    const toggleMenu = () => {
      if (!isControlled) {
        setInternalOpen(!internalOpen);
      }
      if (onClick) {
        onClick();
      }
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLElement>) => {
      if ([SPACE_KEY, ENTER_KEY].includes(e.key)) {
        e.preventDefault();
        toggleMenu();
      }
      if (e.key === ESCAPE_KEY && isOpen) {
        e.preventDefault();
        if (!isControlled) {
          setInternalOpen(false);
        }
      }
    };

    const { onKeyDown } = useActiveKeyboard<HTMLElement>(
      { onKeyDown: handleKeyDown },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY, ESCAPE_KEY, ARROW_DOWN_KEY, ARROW_UP_KEY],
      },
    );

    const hasNestedItems = items.length;
    const shouldShowMenu = !collapsed && hasNestedItems;
    const nestedItemsParentMenuOpen = isOpen;
    const tabIndex = parentMenuOpen === false ? -1 : 0;

    const chevronIcon =
      shouldShowMenu && showMenuIcon ? (
        <Icon name="arrow-chevron-right" className={concatClassNames(style.menuIcon, isOpen && style.menuIconOpen)} />
      ) : null;

    const menuContent = (
      <>
        <div className={style.menuContentLeft}>
          <NavMenuLabel icon={icon} showIcon={showIcon} label={label} collapsed={collapsed} isNested={isNested} />
        </div>
        <div className={style.menuContentRight}>
          {badge && <Badge badgeType={badge.badgeType} size={badge.size} content={badge.content} count={badge.count} />}
          {chevronIcon}
        </div>
      </>
    );

    const listItem = (
      <li
        className={concatClassNames(
          style.navMenuContainer,
          appearance && style[appearance],
          collapsed && style.collapsed,
          isOpen && style.open,
          isNested && style.nested,
        )}
        ref={ref}
        {...props}
      >
        <NavMenuContent link={link} label={label} tabIndex={tabIndex} onClick={toggleMenu} onKeyDown={onKeyDown}>
          {menuContent}
        </NavMenuContent>
        {shouldShowMenu && (
          <ul className={concatClassNames(style.nestedMenu, isOpen && style.nestedMenuOpen)}>
            {items.map((item: NavItemProps) => {
              const hasNestedItems = !!item.items?.length;
              if (hasNestedItems) {
                return (
                  <NavMenu
                    key={item.id || item.label}
                    label={item.label}
                    icon={item.icon}
                    showIcon={item.showIcon}
                    collapsed={collapsed}
                    link={item.link}
                    onClick={item.onClick}
                    items={item.items || []}
                    showMenuIcon={showMenuIcon}
                    isNested={true}
                    parentMenuOpen={nestedItemsParentMenuOpen}
                    appearance={appearance}
                    badge={item.badge}
                  />
                );
              }
              return (
                <>
                  <li key={item.id || item.label}>
                    <NavItem
                      label={item.label}
                      icon={item.icon}
                      showIcon={item.showIcon}
                      collapsed={collapsed}
                      link={item.link}
                      onClick={item.onClick}
                      isNested={true}
                      parentMenuOpen={nestedItemsParentMenuOpen}
                      appearance={appearance}
                      badge={item.badge}
                    />
                  </li>
                  {item.showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
                </>
              );
            })}
          </ul>
        )}
      </li>
    );

    if (collapsed && label) {
      return (
        <>
          <Tooltip
            label={label}
            position="right"
            alignment="center"
            arrow={false}
            shouldFocusTrigger={false}
            triggerStyles={{ outline: "none" }}
            gap={12}
          >
            {listItem}
          </Tooltip>
          {showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
        </>
      );
    }

    return (
      <>
        {listItem}
        {showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
      </>
    );
  },
);

const NavMenuLabel = ({ isNested, ...props }: Omit<NavMenuProps, "children" | "items" | "open" | "showMenuIcon">) => {
  const iconSize = isNested ? 16 : props.collapsed ? 24 : 20;
  return (
    <>
      {props.showIcon && props.icon && <Icon name={props.icon} className={style.icon} size={iconSize} />}
      {props.collapsed ? null : <span>{props.label}</span>}
    </>
  );
};

export default NavMenu;
