// packages/react/src/components/sideNav/baseSideNav/BaseSideNav.tsx
import { sideNavCollapsedSize, sideNavPanelSize } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { BaseSideNavProps as CoreSideNavProps } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { forwardRef, ReactNode } from "react";

import style from "./BaseSideNav.module.scss";

interface BaseSideNavProps
  extends Partial<Omit<CoreSideNavProps, "items">>, Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  header?: ReactNode;
  body?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
}

const BaseSideNav = forwardRef<HTMLElement | HTMLDivElement, BaseSideNavProps>(
  (
    {
      size = "m",
      header,
      body,
      footer,
      showHeader = true,
      showFooter = true,
      children,
      appearance = "brand",
      contrast = "high",
      isCollapsed,
      className,
      ...props
    },
    ref,
  ) => {
    const containerClassName = [style.sideNavContainer, className].filter(Boolean).join(" ");

    return (
      <div className={containerClassName} {...props}>
        <nav
          ref={ref}
          className={style.sideNav}
          data-collapsed={isCollapsed}
          data-appearance={appearance}
          data-contrast={contrast}
          style={{
            minWidth: isCollapsed ? sideNavCollapsedSize : sideNavPanelSize[size],
          }}
        >
          {showHeader && header && <div className={style.sideNavHeader}>{header}</div>}
          {body && <div className={style.sideNavBody}>{body}</div>}
          {showFooter && footer && <div className={style.sideNavFooter}>{footer}</div>}
        </nav>

        {children && <div className={style.sideNavContent}>{children}</div>}
      </div>
    );
  },
);

export default BaseSideNav;

// preview/dsr-662/angular/components/side-nav/base-side-nav/base-side-nav.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import { sideNavCollapsedSize, sideNavPanelSize } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavAppearance, SideNavContrast } from "@design-system-rte/core/components/side-nav/side-nav.interface";

type SideNavSize = "s" | "m" | "l";

@Component({
  selector: "rte-base-side-nav",
  imports: [CommonModule],
  standalone: true,
  templateUrl: "./base-side-nav.component.html",
  styleUrl: "./base-side-nav.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BaseSideNavComponent {
  private readonly collapsedSize = sideNavCollapsedSize;
  private readonly panelSize = sideNavPanelSize;

  readonly size = input<SideNavSize>("m");
  readonly appearance = input<SideNavAppearance>("brand");
  readonly contrast = input<SideNavContrast>("high");
  readonly isCollapsed = input<boolean>(false);
  readonly showHeader = input<boolean>(true);
  readonly showFooter = input<boolean>(true);

  readonly minWidth = computed<string>(() => {
    return this.isCollapsed() ? `${this.collapsedSize}px` : `${this.panelSize[this.size()]}px`;
  });
}
