// packages/angular/projects/ds-rte-lib/src/lib/components/switch/switch.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input, signal } from "@angular/core";
import { switchHeight, switchWidth } from "@design-system-rte/core/components/switch/switch.constants";
import { SwitchProps } from "@design-system-rte/core/components/switch/switch.interface";

import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-switch",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./switch.component.html",
  styleUrl: "./switch.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchComponent {
  readonly label = input("");
  readonly appearance = input<SwitchProps["appearance"]>("brand");
  readonly showLabel = input(true);
  readonly showIcon = input(true);
  readonly disabled = input(false);
  readonly readOnly = input(false);

  switchHeight = switchHeight;
  switchWidth = switchWidth;

  checked = signal(false);

  handleClick = (event: MouseEvent) => {
    if (this.readOnly() || this.disabled()) {
      event.stopPropagation();
    } else {
      this.checked.set(!this.checked());
    }
  };
}

<div
    class="switch-container appearance-{{appearance()}}"
    [ngClass]="{
        'disabled': disabled(),
        'read-only': readOnly(),
        'checked': isChecked()
    }"
    (click)="handleClick($event)"
>
    <input
        aria-checked="{{ isChecked() }}"
        type="checkbox"
        role="switch"
        class="switch"
        [attr.aria-label]="label()"
        [attr.aria-checked]="isChecked()"
        [attr.aria-disabled]="disabled()"
        [attr.aria-readonly]="readOnly()"
        [ariaLabel]="label()"
        [name]="label()"
        [ngClass]="{
        'disabled': disabled(),
        'read-only': readOnly(),
        'checked': isChecked()
    }"
        [style.min-height.px]="switchHeight"
        [style.min-width.px]="switchWidth"
        [disabled]="disabled()"
        [checked]="isChecked()"
    />
    <div class="switch-icon-check" [ngClass]="{'checked': isChecked() }" (click)="handleClick($event)">
        @if (showIcon()) {
            <rte-icon
            class="icon"
            [name]="isChecked() ? 'check' : 'close'"
            [size]="16"
            (click)="handleClick($event)"
            ></rte-icon>
        }
    </div>
    @if (showLabel() && label()) {
        <label
            class="switch-label"
            [for]="label()"
        >
        {{ label() }}
    </label>
    }
</div>

// packages/react/src/components/switch/Switch.tsx
import { switchHeight, switchWidth } from "@design-system-rte/core/components/switch/switch.constants";
import { SwitchProps as CoreSwitchProps } from "@design-system-rte/core/components/switch/switch.interface";
import { InputHTMLAttributes, useState } from "react";

import Icon from "../icon/Icon";
import { concatClassNames } from "../utils";

import style from "./Switch.module.scss";

interface SwitchProps extends CoreSwitchProps, InputHTMLAttributes<HTMLInputElement> {}

const Switch = ({
  label,
  appearance = "brand",
  showLabel = true,
  showIcon = true,
  disabled = false,
  readOnly = false,
  checked = false,
  ...props
}: SwitchProps) => {
  const [isChecked, setIsChecked] = useState(checked);

  return (
    <div
      className={style["switch-container"]}
      data-appearance={appearance}
      data-disabled={disabled}
      data-read-only={readOnly}
      data-checked={isChecked}
      onClick={(e) => {
        if (readOnly || disabled) {
          e.stopPropagation();
        } else {
          setIsChecked(!isChecked);
        }
      }}
    >
      <input
        aria-label={label}
        type="checkbox"
        role="switch"
        name={label}
        className={style["switch"]}
        disabled={disabled}
        checked={isChecked}
        readOnly={readOnly}
        style={{
          minHeight: switchHeight,
          minWidth: switchWidth,
        }}
        {...props}
      />
      <div className={style["switch-icon-check"]} data-checked={isChecked}>
        {showIcon && isChecked && <Icon name="check" size={16} />}
        {showIcon && !isChecked && <Icon name="close" size={16} />}
      </div>
      {showLabel && label && (
        <label htmlFor={label} className={concatClassNames(style["switch-label"])}>
          {label}
        </label>
      )}
    </div>
  );
};

export default Switch;
