// packages/angular/projects/ds-rte-lib/src/lib/components/tab/tab.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  input,
  computed,
  signal,
  viewChildren,
  ElementRef,
  SimpleChanges,
  output,
  AfterViewInit,
  OnChanges,
  viewChild,
  OnDestroy,
} from "@angular/core";
import { Direction } from "@design-system-rte/core/components/common/common-types";
import { TabAlignment, TabItemProps, TabProps } from "@design-system-rte/core/components/tab/tab.interface";
import { scrollToSelectedTab } from "@design-system-rte/core/components/tab/tab.utils";
import {
  ARROW_DOWN_KEY,
  ARROW_LEFT_KEY,
  ARROW_RIGHT_KEY,
  ARROW_UP_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { IconButtonComponent } from "../icon-button/icon-button.component";

import { TabItemComponent } from "./tab-item/tab-item.component";

@Component({
  selector: "rte-tab",
  imports: [CommonModule, TabItemComponent, IconButtonComponent],
  standalone: true,
  templateUrl: "./tab.component.html",
  styleUrl: "./tab.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabComponent implements AfterViewInit, OnChanges, OnDestroy {
  readonly alignment = input<TabAlignment>("start");
  readonly direction = input<Direction>("horizontal");
  readonly options = input<TabProps["options"]>([]);
  readonly selectedTabId = input<TabProps["selectedTabId"]>();
  readonly compactSpacing = input<TabProps["compactSpacing"]>(false);
  readonly overflowType = input<TabProps["overflowType"]>("scrollable");
  readonly inverted = input<boolean>(false);

  readonly sliderLeft = signal(0);
  readonly sliderWidth = signal(0);
  readonly sliderTop = signal(0);
  readonly sliderHeight = signal(0);

  readonly tabItemRefs = viewChildren<TabItemComponent>("tabItem");
  readonly containerRef = viewChild<ElementRef<HTMLDivElement>>("tabList");
  readonly hoverIndicatorRefs = viewChildren<ElementRef<HTMLDivElement>>("hoverIndicator");

  readonly selectedTabRef = computed(() => {
    const idx = this.options().findIndex((opt) => opt.id === this.selectedTabId());
    const tabItem = this.tabItemRefs()[idx];
    return tabItem;
  });

  readonly hoverIndicatorStyle = signal<{
    width?: number;
    left?: number;
    top?: number;
    height?: number;
    opacity?: number;
  } | null>(null);

  readonly change = output<string>();

  readonly isScrollable = signal(false);
  private readonly isOverflowingLeft = signal(false);
  private readonly isOverflowingRight = signal(false);
  private readonly isOverflowingTop = signal(false);
  private readonly isOverflowingBottom = signal(false);

  readonly canScrollBackward = computed(() => {
    return this.isOverflowingLeft() || this.isOverflowingTop();
  });

  readonly canScrollForward = computed(() => {
    return this.isOverflowingRight() || this.isOverflowingBottom();
  });

  readonly shouldDisplayDropdown = computed(
    () => this.overflowType() === "dropdown" && this.direction() === "horizontal",
  );

  displayBadge = (option: TabItemProps): boolean => {
    return (
      !!option.showBadge ||
      (option.badgeCount !== undefined && option.badgeCount > 0 && option.badgeAppearance === "text") ||
      (option.badgeAppearance === "icon" && !!option.badgeIcon)
    );
  };

  isSelected(id: string): boolean {
    return this.selectedTabId() === id;
  }

  readonly tabItemSelectedIndicatorStyle = computed(() => ({
    left: `${this.sliderLeft()}px`,
    top: `${this.sliderTop()}px`,
    width: `${this.sliderWidth()}px`,
    height: `${this.sliderHeight()}px`,
  }));

  ngAfterViewInit() {
    this.updateSelectedTabItemIndicator();
    this.computeScrollableSignals();
    window.addEventListener("resize", this.updateSelectedTabItemIndicator.bind(this));
    window.addEventListener("resize", this.computeScrollableSignals.bind(this));
    if (this.containerRef()) {
      this.containerRef()?.nativeElement.addEventListener("scroll", this.computeScrollableSignals.bind(this));
    }
    this.hoverIndicatorRefs().forEach((hoverIndicator) => {
      hoverIndicator.nativeElement.style.opacity = "0";
    });
  }

  ngOnDestroy() {
    window.removeEventListener("resize", this.updateSelectedTabItemIndicator.bind(this));
    window.removeEventListener("resize", this.computeScrollableSignals.bind(this));
    if (this.containerRef()) {
      this.containerRef()?.nativeElement.removeEventListener("scroll", this.computeScrollableSignals.bind(this));
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["selectedTabId"]) {
      this.updateSelectedTabItemIndicator();
    }
  }

  onKeydownTabItem = (event: KeyboardEvent) => {
    const isVertical = this.direction() === "vertical";

    const isDownKeyPressed = isVertical && event.key === ARROW_DOWN_KEY;
    const isUpKeyPressed = isVertical && event.key === ARROW_UP_KEY;
    const isRightKeyPressed = !isVertical && event.key === ARROW_RIGHT_KEY;
    const isLeftKeyPressed = !isVertical && event.key === ARROW_LEFT_KEY;

    const isArrowNext = isDownKeyPressed || isRightKeyPressed;
    const isArrowPrev = isUpKeyPressed || isLeftKeyPressed;

    if (isArrowNext || isArrowPrev) {
      event.preventDefault();
      this.focusItem(isArrowNext ? "next" : "previous");
    }
  };

  onClickTabItem = (id: string) => {
    if (id !== this.selectedTabId()) {
      this.change.emit(id);
      const newTab = this.getTabItem(id)?.tabItemRef()?.nativeElement;
      if (newTab) {
        const container = this.containerRef()?.nativeElement;
        if (container) {
          scrollToSelectedTab(newTab, container, this.direction());
        }
      }
    }
  };

  scrollBackward() {
    if (this.containerRef() && this.containerRef()?.nativeElement) {
      const scrollObject = this.direction() === "horizontal" ? { left: -300 } : { top: -300 };
      this.containerRef()?.nativeElement.scrollBy({ ...scrollObject, behavior: "smooth" });
    }
  }

  scrollForward() {
    if (this.containerRef() && this.containerRef()?.nativeElement) {
      const scrollObject = this.direction() === "horizontal" ? { left: 300 } : { top: 300 };
      this.containerRef()?.nativeElement.scrollBy({ ...scrollObject, behavior: "smooth" });
    }
  }

  private getTabItem = (id: string) => {
    return this.tabItemRefs().find((tab) => tab.option()?.id === id);
  };

  private focusItem = (direction: "next" | "previous") => {
    const currentIndex = this.tabItemRefs().findIndex((tab) => tab === this.selectedTabRef());
    const maxIterations = this.tabItemRefs().length;
    let newIndex = this.computeNextItemIndex(currentIndex, maxIterations, direction);
    let counter = 0;
    while (
      this.tabItemRefs()[newIndex].tabItemRef()?.nativeElement.getAttribute("data-disabled") === "true" &&
      counter < maxIterations
    ) {
      newIndex = this.computeNextItemIndex(newIndex, maxIterations, direction);
      counter++;
    }
    this.tabItemRefs()[newIndex].tabItemRef()?.nativeElement.focus();
    this.tabItemRefs()[newIndex].tabItemRef()?.nativeElement.click();
  };

  private computeNextItemIndex(currentIndex: number, totalItems: number, direction: "next" | "previous") {
    return direction === "next" ? (currentIndex + 1) % totalItems : (currentIndex - 1 + totalItems) % totalItems;
  }

  private computeIndicatorStyle(tabItem: HTMLElement) {
    if (this.direction() === "horizontal") {
      return {
        width: tabItem.offsetWidth,
        left: tabItem.offsetLeft,
        top: tabItem.offsetTop + tabItem.offsetHeight,
      };
    } else {
      return {
        left: 0,
        top: tabItem.offsetTop,
        height: tabItem.offsetHeight,
        width: 2,
      };
    }
  }

  private updateSelectedTabItemIndicator() {
    const idx = this.options().findIndex((opt) => opt.id === this.selectedTabId());
    const tabItem = this.tabItemRefs()[idx];
    if (tabItem && tabItem.tabItemRef) {
      if (tabItem.option()?.disabled) {
        return;
      }
      const tabItemRef = tabItem.tabItemRef?.();
      if (tabItemRef && tabItemRef.nativeElement) {
        const tabItemElement = tabItemRef.nativeElement;
        const indicatorStyle = this.computeIndicatorStyle(tabItemElement);
        this.sliderHeight.set(indicatorStyle.height ?? 2);
        this.sliderTop.set(indicatorStyle.top);
        this.sliderWidth.set(indicatorStyle.width ?? 2);
        this.sliderLeft.set(indicatorStyle.left);
      }
    }
  }

  private computeScrollableSignals = () => {
    this.computeIsScrollable();
    this.computeIsOverflowingLeft();
    this.computeIsOverflowingRight();
    this.computeIsOverflowingTop();
    this.computeIsOverflowingBottom();
  };

  private computeIsScrollable() {
    if (this.containerRef() && this.containerRef()?.nativeElement) {
      const containerNativeElement = this.containerRef()?.nativeElement;
      if (containerNativeElement) {
        this.isScrollable.set(
          containerNativeElement.offsetWidth < containerNativeElement.scrollWidth ||
            containerNativeElement.offsetHeight < containerNativeElement.scrollHeight,
        );
      }
    }
    return false;
  }

  private computeIsOverflowingLeft() {
    const containerNativeElement = this.containerRef()?.nativeElement;
    if (containerNativeElement) {
      const isOverFlowingLeft = containerNativeElement.scrollLeft > 0;
      this.isOverflowingLeft.set(this.isScrollable() && isOverFlowingLeft);
    }
  }

  private computeIsOverflowingRight() {
    const containerNativeElement = this.containerRef()?.nativeElement;
    if (containerNativeElement) {
      const isOverflowingRight =
        containerNativeElement.scrollWidth - containerNativeElement.clientWidth - containerNativeElement.scrollLeft > 0;
      return this.isOverflowingRight.set(this.isScrollable() && isOverflowingRight);
    }
  }

  private computeIsOverflowingTop() {
    const containerNativeElement = this.containerRef()?.nativeElement;
    if (containerNativeElement) {
      const isOverFlowingTop = containerNativeElement.scrollTop > 0;
      this.isOverflowingTop.set(this.isScrollable() && isOverFlowingTop);
    }
  }
  private computeIsOverflowingBottom() {
    const containerNativeElement = this.containerRef()?.nativeElement;
    if (containerNativeElement) {
      const isOverflowingBottom =
        containerNativeElement.scrollHeight - containerNativeElement.clientHeight - containerNativeElement.scrollTop >
        0;
      return this.isOverflowingBottom.set(this.isScrollable() && isOverflowingBottom);
    }
  }
}

<div class="rte-tab-container" [attr.data-direction]="direction()">
  <div
    class="rte-tab-border-vertical"
    aria-hidden="true"
    role="presentation"
    [attr.data-direction]="direction()"
  ></div>
  <div
    [ngStyle]="{
      position: 'relative',
      display: 'flex',
      'align-items': 'center',
      'flex-direction': direction() === 'horizontal' ? 'row' : 'column',
    }"
  >
    <rte-icon-button
      *ngIf="isScrollable() && !shouldDisplayDropdown()"
      aria-label="Previous tabs"
      variant="transparent"
      size="l"
      [name]="
        direction() === 'horizontal' ? 'arrow-chevron-left' : 'arrow-chevron-up'
      "
      [ngStyle]="{
        'z-index': 11,
        opacity: canScrollBackward() ? '1' : '0',
        'pointer-events': canScrollBackward() ? 'auto' : 'none',
      }"
      (click)="scrollBackward()"
    />
    <div
      #tabList
      role="tablist"
      aria-label="Sample Tabs"
      class="rte-tab"
      [attr.data-alignment]="shouldDisplayDropdown() ? 'start' : alignment()"
      [attr.data-direction]="direction()"
      [attr.data-overflow-type]="overflowType()"
    >
      <span
        class="rte-tab-selected-indicator"
        [ngStyle]="tabItemSelectedIndicatorStyle()"
      ></span>
      <rte-dropdown
        *ngIf="shouldDisplayDropdown() && options().length > 0"
        #dropdown="rteDropdown"
        [autoclose]="true"
        [ariaLabel]="'Select tab'"
        [offset]="10"
      >
        <button
          class="rte-tab-dropdown-button"
          dropdownTrigger
          [attr.data-inverted]="inverted()"
          [attr.data-overflow-type]="overflowType()"
          (click)="dropdown.open()"
        >
          <rte-icon
            *ngIf="selectedTab()?.icon"
            appearance="filled"
            [name]="selectedTab()?.icon!"
          />
          {{ selectedTab()?.label || "Select tab" }}
          <rte-badge
            *ngIf="
              selectedTab()?.badgeCount &&
              selectedTab()?.badgeCount! > 0 &&
              selectedTab()?.badgeAppearance === 'text'
            "
            [badgeType]="selectedTab()?.badgeType!"
            [badgeAppearance]="selectedTab()?.badgeAppearance!"
            [count]="selectedTab()?.badgeCount"
            [simpleBadge]="true"
          />
          <rte-icon name="arrow-chevron-down" appearance="outlined" />
        </button>
        <rte-dropdown-item
          *ngFor="let option of dropdownFilteredOptions()"
          [label]="option?.label || ''"
          [leftIcon]="option.icon"
          (click)="onClickTabItem(option.id)"
        ></rte-dropdown-item>
      </rte-dropdown>
      <ng-container *ngFor="let option of options(); let idx = index">
        <rte-tab-item
          #tabItem
          [option]="option"
          [direction]="direction()"
          [compactSpacing]="compactSpacing()"
          [isSelected]="isSelected(option.id)"
          [inverted]="inverted()"
          [attr.data-hidden]="shouldDisplayDropdown()"
          [isHidden]="shouldDisplayDropdown()"
          (keydown)="onKeydownTabItem($event)"
          (click)="onClickTabItem(option.id)"
        ></rte-tab-item>
      </ng-container>
    </div>
    <rte-icon-button
      *ngIf="isScrollable() && !shouldDisplayDropdown()"
      aria-label="Next tabs"
      variant="transparent"
      size="l"
      [name]="
        direction() === 'horizontal'
          ? 'arrow-chevron-right'
          : 'arrow-chevron-down'
      "
      [ngStyle]="{
        'z-index': 11,
        opacity: canScrollForward() ? '1' : '0',
        'pointer-events': canScrollForward() ? 'auto' : 'none',
      }"
      (click)="scrollForward()"
    />
  </div>
  <div
    class="rte-tab-border-horizontal"
    aria-hidden="true"
    role="presentation"
    [attr.data-direction]="direction()"
    [attr.data-compact-spacing]="compactSpacing()"
    [attr.data-scrollable]="
      isScrollable() && overflowType() === 'scrollable' ? true : undefined
    "
  ></div>
</div>

// packages/react/src/components/tab/Tab.tsx
import { TabProps as CoreTabProps } from "@design-system-rte/core/components/tab/tab.interface";
import { scrollToSelectedTab } from "@design-system-rte/core/components/tab/tab.utils";
import {
  forwardRef,
  HTMLAttributes,
  MutableRefObject,
  useRef,
  MouseEvent,
  KeyboardEvent,
  useEffect,
  useState,
  useCallback,
} from "react";

import useSelectedIndicatorPosition from "../../hooks/useSelectedIndicatorPosition";
import Badge from "../badge/Badge";
import { Dropdown } from "../dropdown/Dropdown";
import { DropdownItem } from "../dropdown/dropdownItem/DropdownItem";
import Icon from "../icon/Icon";
import IconButton from "../iconButton/IconButton";

import style from "./Tab.module.scss";
import TabItem from "./tabitem/TabItem";

interface TabProps extends CoreTabProps, Omit<HTMLAttributes<HTMLDivElement>, "onChange"> {
  onChange: (id: string) => void;
}

const Tab = forwardRef<HTMLDivElement, TabProps>(
  (
    {
      options,
      onChange,
      direction = "horizontal",
      alignment = "start",
      selectedTabId,
      compactSpacing,
      overflowType = "scrollable",
      inverted = false,
    },
    ref,
  ) => {
    const [isScrollableLeft, setIsScrollableLeft] = useState(false);
    const [isScrollableRight, setIsScrollableRight] = useState(false);
    const [isScrollableBottom, setIsScrollableBottom] = useState(false);
    const [isScrollableTop, setIsScrollableTop] = useState(false);
    const [isScrollable, setIsScrollable] = useState(false);
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);

    const containerRef: MutableRefObject<HTMLDivElement | null> = useRef<HTMLDivElement>(null);

    const sliderStyle = useSelectedIndicatorPosition(
      containerRef,
      selectedTabId,
      direction === "horizontal" ? "bottom" : "left",
    );

    const isHorizontalScrollable = direction === "horizontal" && (isScrollableLeft || isScrollableRight);

    const shouldDisplayDropdown = isHorizontalScrollable && overflowType === "dropdown";

    const computeScrollableState = useCallback(() => {
      if (containerRef.current) {
        const isScrollable =
          containerRef.current.offsetWidth < containerRef.current.scrollWidth ||
          containerRef.current.offsetHeight < containerRef.current.scrollHeight;

        const isOverFlowingLeft = containerRef.current.scrollLeft > 0;
        const isOverFlowingRight =
          containerRef.current.scrollWidth - containerRef.current.clientWidth - containerRef.current.scrollLeft > 0;
        const isOverFlowingTop = containerRef.current.scrollTop > 0;
        const isOverFlowingBottom =
          containerRef.current.scrollHeight - containerRef.current.clientHeight - containerRef.current.scrollTop > 0;
        setIsScrollableLeft(isOverFlowingLeft);
        setIsScrollableRight(isOverFlowingRight);
        setIsScrollableTop(isOverFlowingTop);
        setIsScrollableBottom(isOverFlowingBottom);
        setIsScrollable(isScrollable);
      }
    }, [containerRef]);

    useEffect(() => {
      computeScrollableState();
      window.addEventListener("resize", computeScrollableState);
      containerRef.current?.addEventListener("scroll", computeScrollableState);
      return () => {
        window.removeEventListener("resize", computeScrollableState);
        containerRef.current?.removeEventListener("scroll", computeScrollableState);
      };
    }, [computeScrollableState]);

    useEffect(() => {
      if (!selectedTabId && options.length > 0) {
        onChange(options[0].id);
      }
    }, [selectedTabId, options, onChange]);

    const handleOnClick = (
      event:
        | MouseEvent<HTMLButtonElement>
        | MouseEvent<HTMLLIElement>
        | KeyboardEvent<HTMLButtonElement>
        | KeyboardEvent<HTMLLIElement>,
    ) => {
      const target = event.currentTarget;
      const id = target.getAttribute("id") || "";
      onChange(id);
      setIsDropdownOpen(false);
      const container = containerRef.current;
      if (container) {
        scrollToSelectedTab(target, container, direction);
      }
    };

    const scrollBackward = () => {
      if (containerRef.current) {
        const scrollObject = direction === "horizontal" ? { left: -300 } : { top: -300 };
        containerRef.current.scrollBy({ ...scrollObject, behavior: "smooth" });
      }
    };

    const scrollForward = () => {
      if (containerRef.current) {
        const scrollObject = direction === "horizontal" ? { left: 300 } : { top: 300 };
        containerRef.current.scrollBy({ ...scrollObject, behavior: "smooth" });
      }
    };

    const selectedOption = options.find((option) => option.id === selectedTabId);

    return (
      <div className={style["tab-container"]} data-direction={direction}>
        <div
          className={style["tab-border-vertical"]}
          aria-hidden="true"
          role="presentation"
          data-direction={direction}
          data-compact-spacing={compactSpacing}
          data-scrollable={isScrollable && overflowType === "scrollable" ? true : undefined}
        ></div>
        <div
          style={{
            position: "relative",
            display: "flex",
            alignItems: "center",
            flexDirection: direction === "horizontal" ? "row" : "column",
          }}
        >
          {isScrollable && !shouldDisplayDropdown && (
            <IconButton
              name={direction === "horizontal" ? "arrow-chevron-left" : "arrow-chevron-up"}
              aria-label="Previous tabs"
              variant="transparent"
              size="l"
              style={{
                zIndex: 11,
                opacity: isScrollableLeft || isScrollableTop ? 1 : 0,
                pointerEvents: isScrollableLeft || isScrollableTop ? "auto" : "none",
              }}
              onClick={scrollBackward}
            />
          )}
          <div
            ref={(node) => {
              containerRef.current = node;
              if (typeof ref === "function") ref(node);
              else if (ref) ref.current = node;
            }}
            role="tablist"
            aria-label="Sample Tabs"
            className={style["tab"]}
            data-alignment={isScrollable ? "start" : alignment}
            data-direction={direction}
            data-overflow-type={overflowType}
          >
            <div
              className={style["tab-selected-indicator"]}
              style={{
                left: shouldDisplayDropdown ? 0 : sliderStyle.left,
                width: (sliderStyle.width ?? 0) + (shouldDisplayDropdown ? 16 : 0),
                top: sliderStyle.top,
                height: sliderStyle.height,
              }}
            ></div>
            {shouldDisplayDropdown && selectedOption && (
              <Dropdown
                autoClose
                dropdownId={"tab-dropdown"}
                onClose={() => setIsDropdownOpen(false)}
                offset={10}
                trigger={
                  <button
                    type="button"
                    className={style["tab-dropdown-button"]}
                    onClick={() => setIsDropdownOpen((prev) => !prev)}
                    aria-label="Select tab"
                    data-inverted={inverted}
                  >
                    {selectedOption && selectedOption.icon && <Icon name={selectedOption.icon} appearance="filled" />}
                    {selectedOption && <div style={{ flexShrink: 0 }}>{selectedOption?.label}</div>}
                    {selectedOption.badgeCount &&
                      selectedOption.badgeCount > 0 &&
                      selectedOption.badgeAppearance === "text" && (
                        <Badge
                          badgeType={selectedOption.badgeType}
                          appearance={selectedOption.badgeAppearance}
                          count={selectedOption.badgeCount}
                        />
                      )}
                    <Icon style={{ flexShrink: 0 }} name="arrow-chevron-down"></Icon>
                  </button>
                }
                isOpen={isDropdownOpen}
              >
                {options
                  .filter((option) => option.id !== selectedTabId)
                  .map((option, idx) => (
                    <DropdownItem
                      key={`${option.id}-dropdown-${idx}`}
                      id={option.id}
                      label={option.label}
                      onClick={handleOnClick}
                      disabled={option.disabled}
                      leftIcon={option.icon}
                    />
                  ))}
              </Dropdown>
            )}

            {options.map((option, index) => (
              <TabItem
                key={`${option.id}-${index}`}
                onClick={handleOnClick}
                isSelected={selectedTabId === option.id}
                compactSpacing={compactSpacing}
                direction={direction}
                data-hidden={shouldDisplayDropdown}
                inverted={inverted}
                {...option}
              />
            ))}
          </div>
          {isScrollable && !shouldDisplayDropdown && (
            <IconButton
              name={direction === "horizontal" ? "arrow-chevron-right" : "arrow-chevron-down"}
              aria-label="Next tabs"
              variant="transparent"
              size="l"
              style={{
                zIndex: 11,
                opacity: isScrollableRight || isScrollableBottom ? 1 : 0,
                pointerEvents: isScrollableRight || isScrollableBottom ? "auto" : "none",
              }}
              onClick={scrollForward}
            />
          )}
        </div>
        <div
          className={style["tab-border-horizontal"]}
          aria-hidden="true"
          role="presentation"
          data-direction={direction}
          data-compact-spacing={compactSpacing}
          data-scrollable={isScrollable && overflowType === "scrollable" ? true : undefined}
        ></div>
      </div>
    );
  },
);

export default Tab;
