// packages/angular/projects/ds-rte-lib/src/lib/components/dropdown/dropdown-item/dropdown-item.component.ts
import { CommonModule } from "@angular/common";
import { Component, computed, EventEmitter, input, output } from "@angular/core";
import { shouldDisplayBadge } from "@design-system-rte/core/components/badge/badge.utils";
import { DropdownItemProps } from "@design-system-rte/core/components/dropdown/dropdown.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { BadgeComponent } from "../../badge/badge.component";
import { DividerComponent } from "../../divider/divider.component";
import { IconComponent } from "../../icon/icon.component";

export interface DropdownItemConfig extends Omit<DropdownItemProps, "onClick"> {
  id?: string;
  click?: EventEmitter<Event>;
}

@Component({
  selector: "rte-dropdown-item",
  imports: [CommonModule, IconComponent, DividerComponent, BadgeComponent],
  standalone: true,
  templateUrl: "./dropdown-item.component.html",
  styleUrl: "./dropdown-item.component.scss",
})
export class DropdownItemComponent {
  readonly item = input<DropdownItemConfig>();
  readonly menuId = input<string>();
  readonly itemEvent = output<{ event: Event; id: string }>();

  readonly shouldDisplayBadge = computed(() => {
    const item = this.item();
    return shouldDisplayBadge({
      showBadge: !!item?.showBadge,
      badgeContent: item?.badgeContent,
      badgeCount: item?.badgeCount,
      badgeIcon: item?.badgeIcon,
    });
  });

  handleClick(event: Event): void {
    if (this.item()?.disabled) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    this.itemEvent.emit({ event, id: this.item()?.id || this.item()?.label || "" });
  }

  handleKeyDown(event: KeyboardEvent): void {
    event.preventDefault();

    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      if (this.item()?.link) {
        const link = (event.target as HTMLElement).closest("li")?.querySelector("a");
        link?.click();
      } else {
        this.itemEvent.emit({ event, id: this.item()?.id || this.item()?.label || "" });
      }
    }
  }
}

<ng-container>
  @if (hasSubItems()) {
    <div #subDropdown rteDropdown [rteDropdownId]="menuId() + '-' + item()?.id" [rteDropdownHasParent]="true">
      <li
        #itemRef
        rteDropdownTrigger
        class="rte-dropdown-item"
        role="menuitem"
        tabindex="0"
        [rteDropdownTriggerActivateWithMouseEnter]="true"
        [attr.data-disabled]="item()?.disabled"
        [attr.data-active]="item()?.selected"
        (click)="handleClick($event)"
        (keydown)="handleKeyDown($event)"
        (mouseout)="handleMouseOut()"
      >
        <span *ngIf="item()?.hasIndent && !item()?.leftIcon" style="width: 20px"></span>
        <rte-icon *ngIf="item()?.leftIcon" [name]="item()?.leftIcon ?? ''" />
        <ng-container [ngSwitch]="!!item()?.link">
          <a *ngSwitchCase="true" style="flex: 2; text-decoration: none; color: inherit" [href]="item()?.link"
            >{{ item()?.label }}
          </a>
          <span *ngSwitchDefault style="flex: 2">{{ item()?.label }}</span>
        </ng-container>
        <div *ngIf="item()?.trailingText">{{ item()?.trailingText }}</div>
        <rte-badge
          *ngIf="shouldDisplayBadge()"
          [badgeType]="item()?.badgeType!"
          [badgeContent]="item()?.badgeContent!"
          [count]="item()?.badgeCount"
          [simpleBadge]="true"
          [icon]="item()?.badgeIcon ?? ''"
          [badgeSize]="item()?.badgeSize!"
        ></rte-badge>
        <rte-icon *ngIf="hasSubItems()" name="arrow-chevron-right" />
      </li>
      <rte-dropdown-menu [items]="item()?.sub!" />
    </div>
  } @else {
    <li
      #itemRef
      class="rte-dropdown-item"
      role="menuitem"
      tabindex="0"
      [attr.data-disabled]="item()?.disabled"
      [attr.data-active]="item()?.selected"
      (click)="handleClick($event)"
      (keydown)="handleKeyDown($event)"
    >
      <span *ngIf="item()?.hasIndent && !item()?.leftIcon" style="width: 20px"></span>
      <rte-icon *ngIf="item()?.leftIcon" [name]="item()?.leftIcon ?? ''" />
      <ng-container [ngSwitch]="!!item()?.link">
        <a *ngSwitchCase="true" style="flex: 2; text-decoration: none; color: inherit" [href]="item()?.link"
          >{{ item()?.label }}
        </a>
        <span *ngSwitchDefault style="flex: 2">{{ item()?.label }}</span>
      </ng-container>
      <div *ngIf="item()?.trailingText">{{ item()?.trailingText }}</div>
      <rte-badge
        *ngIf="shouldDisplayBadge()"
        [badgeType]="item()?.badgeType!"
        [badgeContent]="item()?.badgeContent!"
        [count]="item()?.badgeCount"
        [simpleBadge]="true"
        [icon]="item()?.badgeIcon ?? ''"
        [badgeSize]="item()?.badgeSize!"
      ></rte-badge>
    </li>
    <div *ngIf="item()?.hasSeparator" class="dropdown-divider">
      <rte-divider />
    </div>
  }
</ng-container>

// packages/react/src/components/dropdown/dropdownItem/DropdownItem.tsx
import { shouldDisplayBadge } from "@design-system-rte/core/components/badge/badge.utils";
import { DropdownItemProps as CoreDropdownItemProps } from "@design-system-rte/core/components/dropdown/dropdown.interface";
import { DropdownManager } from "@design-system-rte/core/components/dropdown/DropdownManager";
import {
  ARROW_DOWN_KEY,
  ARROW_UP_KEY,
  ENTER_KEY,
  ESCAPE_KEY,
  SPACE_KEY,
  TAB_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { useContext } from "react";

import { useActiveKeyboard } from "../../../hooks/useActiveKeyboard";
import Badge from "../../badge/Badge";
import Divider from "../../divider/Divider";
import Icon from "../../icon/Icon";
import { DropdownParentContext } from "../context/DropdownContext";
import { Dropdown } from "../Dropdown";
import { focusDropdownFirstElement, focusParentDropdownFirstElement } from "../DropdownUtils";
import { useDropdownState } from "../hooks/useDropdownState";

import styles from "./DropdownItem.module.scss";

interface DropdownItemProps extends Omit<CoreDropdownItemProps, "onClick">, React.HTMLAttributes<HTMLLIElement> {
  onClick?: (event: React.MouseEvent<HTMLLIElement> | React.KeyboardEvent<HTMLLIElement>) => void;
}

export const DropdownItem = ({
  label,
  link,
  leftIcon,
  trailingText,
  disabled,
  hasSeparator,
  hasIndent,
  children,
  badgeCount,
  badgeContent,
  badgeIcon,
  badgeType,
  badgeSize,
  showBadge,
  isSelected,
  onClick,
  ...props
}: DropdownItemProps) => {
  const { dropdownId, autoClose, closeRoot } = useContext(DropdownParentContext) || {};
  const childDropdownId = `${dropdownId}-${label && label.replace(/\s+/g, "")}`;
  const { isOpen, open } = useDropdownState(childDropdownId);

  const handleMouseOver = () => {
    if (!dropdownId) return;
    DropdownManager.closeSubMenus(dropdownId);
    open();
  };

  const handleOnFocus = () => {
    if (!dropdownId) return;
    DropdownManager.closeSubMenus(dropdownId);
  };

  if (hasIndent && leftIcon) {
    console.warn(
      `DropdownItem: 'hasIndent' prop is ignored when 'leftIcon' is provided : displaying icon '${leftIcon}' for dropdownitem with label '${label}' without indentation.`,
    );
  }

  const handleOnClick = (event: React.MouseEvent<HTMLLIElement> | React.KeyboardEvent<HTMLLIElement>) => {
    if (disabled) return;
    if (onClick) {
      onClick(event);
    }
    if (autoClose && closeRoot) {
      closeRoot();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLLIElement>) => {
    if ([SPACE_KEY, ENTER_KEY].includes(e.key)) {
      if (link) {
        const linkElement = e.currentTarget.querySelector("a");
        if (linkElement) {
          linkElement.click();
        }
      } else {
        if (disabled) return;
        if (onClick) {
          handleOnClick(e as unknown as React.KeyboardEvent<HTMLLIElement>);
        }
        if (children) {
          open();
        }
      }
    }
  };

  const handleKeyUp = (e: React.KeyboardEvent<HTMLLIElement>) => {
    e.preventDefault();
    if (e.key === TAB_KEY) {
      if (isOpen) {
        focusDropdownFirstElement(childDropdownId);
      }
      if (e.shiftKey) {
        if (dropdownId) {
          focusParentDropdownFirstElement(dropdownId);
        }
      }
    }
  };

  const { onKeyUp, onFocus, onKeyDown } = useActiveKeyboard<HTMLLIElement>(
    { onKeyUp: handleKeyUp, onFocus: handleOnFocus, onKeyDown: handleKeyDown },
    {
      interactiveKeyCodes: [SPACE_KEY, ENTER_KEY, TAB_KEY, ARROW_DOWN_KEY, ARROW_UP_KEY, ESCAPE_KEY],
    },
  );

  if (children) {
    return (
      <Dropdown
        hasParent
        dropdownId={childDropdownId}
        isOpen={isOpen}
        trigger={
          <>
            <li
              className={styles["dropdown-item"]}
              data-active={isOpen}
              data-disabled={disabled}
              role="menuitem"
              onMouseOver={handleMouseOver}
              onKeyUp={onKeyUp}
              onKeyDown={onKeyDown}
              onFocus={onFocus}
              tabIndex={0}
            >
              {hasIndent && <span style={{ width: "20px" }} />}
              {leftIcon && (
                <Icon
                  name={leftIcon}
                  className={styles["dropdown-item-icon"]}
                  appearance={isOpen ? "filled" : "outlined"}
                />
              )}
              {link ? (
                <a href={link} style={{ flex: "2", textDecoration: "none", color: "inherit" }}>
                  {label}
                </a>
              ) : (
                <span style={{ flex: "2" }}>{label}</span>
              )}
              <Icon name="arrow-chevron-right" className={styles["dropdown-item-icon"]} />
            </li>
            {hasSeparator && (
              <div className={styles["dropdown-divider"]}>
                <Divider />
              </div>
            )}
          </>
        }
      >
        {children}
      </Dropdown>
    );
  }
  return (
    <>
      <li
        className={styles["dropdown-item"]}
        data-disabled={disabled}
        data-active={isSelected}
        role="menuitem"
        onClick={handleOnClick}
        onMouseOver={handleMouseOver}
        onKeyUp={onKeyUp}
        onKeyDown={onKeyDown}
        onFocus={onFocus}
        tabIndex={0}
        {...props}
      >
        {hasIndent && !leftIcon && <span style={{ width: "20px" }} />}
        {leftIcon && <Icon name={leftIcon} className={styles["dropdown-item-icon"]} />}
        {link ? (
          <a href={link} style={{ flex: "2", textDecoration: "none", color: "inherit" }}>
            {label}
          </a>
        ) : (
          <span style={{ flex: "2" }}>{label}</span>
        )}
        {trailingText && <div>{trailingText}</div>}
        {shouldDisplayBadge({ showBadge: !!showBadge, badgeContent, badgeCount, badgeIcon }) && (
          <Badge count={badgeCount} content={badgeContent} icon={badgeIcon} badgeType={badgeType} size={badgeSize} />
        )}
      </li>
      {hasSeparator && (
        <div className={styles["dropdown-divider"]}>
          <Divider />
        </div>
      )}
    </>
  );
};
