// packages/react/src/components/searchbar/Searchbar.tsx
import {
  APPEARANCE_CONFIG,
  SEARCHBAR_BORDER_RADIUS,
  SEARCHBAR_BUTTON_HEIGHT_COMPACT,
  SEARCHBAR_BUTTON_WIDTH,
  SEARCHBAR_PADDING_LEFT,
} from "@design-system-rte/core/components/searchbar/searchbar.constants";
import {
  SearchBarProps as CoreSearchBarProps,
  SearchBarAppearance,
} from "@design-system-rte/core/components/searchbar/searchbar.interface";
import { ENTER_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import {
  CSSProperties,
  InputHTMLAttributes,
  KeyboardEvent,
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import IconButton from "../iconButton/IconButton";
import BaseTextInput from "../textInput/baseTextInput/BaseTextInput";

import styles from "./Searchbar.module.scss";

interface SearchbarProps
  extends
    CoreSearchBarProps,
    Omit<InputHTMLAttributes<HTMLInputElement>, "id" | "onChange" | "value" | "defaultValue" | "placeholder"> {
  onSearch?: (input: string | undefined) => void;
  onChange?: (input: string | undefined) => void;
  onClear?: () => void;
}

function getTextInputStyles(appearance: SearchBarAppearance, hasLeftIcon: boolean): CSSProperties {
  const baseStyles: CSSProperties = {};

  if (appearance === "primary") {
    baseStyles.borderRight = "none";
    baseStyles.borderRadius = `${SEARCHBAR_BORDER_RADIUS} 0 0 ${SEARCHBAR_BORDER_RADIUS}`;
    if (!hasLeftIcon) {
      baseStyles.paddingLeft = SEARCHBAR_PADDING_LEFT;
    }
  } else if (appearance === "secondary") {
    baseStyles.borderRadius = SEARCHBAR_BORDER_RADIUS;
  }

  return baseStyles;
}

function getSearchButtonStyles(hasCompactSpacing?: boolean): CSSProperties {
  return {
    width: SEARCHBAR_BUTTON_WIDTH,
    borderRadius: `0 ${SEARCHBAR_BORDER_RADIUS} ${SEARCHBAR_BORDER_RADIUS} 0`,
    height: hasCompactSpacing ? SEARCHBAR_BUTTON_HEIGHT_COMPACT : undefined,
  };
}

const Searchbar = forwardRef<HTMLInputElement, SearchbarProps>(
  (
    {
      onSearch,
      onChange,
      onClear,
      id,
      label = "Rechercher",
      disabled = false,
      showResetButton = true,
      appearance = "primary",
      compactSpacing,
      value,
      assistiveText,
      style: customInputStyle,
      width,
      ...props
    }: SearchbarProps,
    ref,
  ) => {
    const appearanceConfig = APPEARANCE_CONFIG[appearance];

    const [hasFocusWithin, setHasFocusWithin] = useState(false);
    const wrapperRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
      const wrapper = wrapperRef.current;
      if (!wrapper) return;

      const handleFocusIn = () => {
        setHasFocusWithin(true);
      };

      const handleFocusOut = (event: FocusEvent) => {
        const next = event.relatedTarget as Node | null;
        if (next && wrapper.contains(next)) {
          return;
        }
        setHasFocusWithin(false);
      };

      wrapper.addEventListener("focusin", handleFocusIn);
      wrapper.addEventListener("focusout", handleFocusOut);

      return () => {
        wrapper.removeEventListener("focusin", handleFocusIn);
        wrapper.removeEventListener("focusout", handleFocusOut);
      };
    }, []);

    const handleChange = useCallback(
      (newValue: string) => {
        onChange?.(newValue);
      },
      [onChange],
    );

    const handleClick = useCallback(() => {
      onSearch?.(value);
    }, [onSearch, value]);

    const handleEnter = useCallback(
      (e: KeyboardEvent<HTMLInputElement>) => {
        if (e.key === ENTER_KEY) {
          onSearch?.(value);
        }
      },
      [onSearch, value],
    );

    const handleClear = useCallback(() => {
      onChange?.("");
      onClear?.();
    }, [onChange, onClear]);

    const placeholder = useMemo(() => (disabled ? "Recherche indisponible" : label), [disabled, label]);

    const textInputProps = useMemo(
      () => ({
        disabled,
        value,
        onChange: handleChange,
        onKeyUp: onSearch ? handleEnter : undefined,
        showRightIcon: showResetButton,
        rightIconAction: "clean" as const,
        onRightIconClick: handleClear,
        assistiveTextLabel: assistiveText,
        compactSpacing,
        placeholder,
        leftIcon: appearanceConfig.showLeftIcon ? "search" : undefined,
        ...props,
      }),
      [
        disabled,
        value,
        handleChange,
        onSearch,
        handleEnter,
        showResetButton,
        handleClear,
        assistiveText,
        compactSpacing,
        placeholder,
        appearanceConfig.showLeftIcon,
        props,
      ],
    );

    const textInputStyles = useMemo(
      () => ({
        ...getTextInputStyles(appearance, appearanceConfig.showLeftIcon),
        ...(customInputStyle ?? {}),
      }),
      [appearance, appearanceConfig.showLeftIcon, customInputStyle],
    );

    const searchButtonStyles = useMemo(() => getSearchButtonStyles(compactSpacing), [compactSpacing]);

    return (
      <div className={styles.searchbarContainer} role="search" data-appearance={appearance}>
        <div ref={wrapperRef} className={styles.textInputWrapper} data-disabled={disabled}>
          <BaseTextInput
            id={id ?? ""}
            width={width}
            {...textInputProps}
            style={textInputStyles}
            highlighted={hasFocusWithin}
            ref={ref}
            rightSlot={
              appearanceConfig.showSearchButton && (
                <IconButton
                  name="search"
                  size="m"
                  variant="primary"
                  appearance="filled"
                  onClick={handleClick}
                  disabled={disabled}
                  aria-label={label}
                  className={styles.searchButton}
                  compactSpacing={compactSpacing}
                  style={searchButtonStyles}
                />
              )
            }
          />
        </div>
      </div>
    );
  },
);

export default Searchbar;

// preview/dsr-139/angular/components/searchbar/searchbar.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from "@angular/core";
import {
  APPEARANCE_CONFIG,
  SEARCHBAR_BORDER_RADIUS,
  SEARCHBAR_BUTTON_HEIGHT_COMPACT,
  SEARCHBAR_BUTTON_WIDTH,
  SEARCHBAR_PADDING_LEFT,
} from "@design-system-rte/core/components/searchbar/searchbar.constants";
import { SearchBarAppearance } from "@design-system-rte/core/components/searchbar/searchbar.interface";
import { ENTER_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { IconButtonComponent } from "../icon-button/icon-button.component";
import { BaseTextInputComponent } from "../text-input/base-text-input/base-text-input.component";

@Component({
  selector: "rte-searchbar",
  imports: [CommonModule, BaseTextInputComponent, IconButtonComponent],
  standalone: true,
  templateUrl: "./searchbar.component.html",
  styleUrl: "./searchbar.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SearchbarComponent {
  readonly id = input<string>();
  readonly label = input<string>("Rechercher");
  readonly disabled = input<boolean>(false);
  readonly showResetButton = input<boolean>(true);
  readonly appearance = input<SearchBarAppearance>("primary");
  readonly compactSpacing = input<boolean>(false);
  readonly value = input<string>("");
  readonly assistiveText = input<string>("");

  readonly valueChange = output<string>();
  readonly searchEvent = output<string | undefined>();
  readonly clear = output<void>();

  readonly hasFocusWithin = signal<boolean>(false);

  readonly appearanceConfig = computed(() => APPEARANCE_CONFIG[this.appearance()]);

  readonly placeholder = computed(() => (this.disabled() ? "Recherche indisponible" : this.label()));

  readonly textInputStyles = computed(() => {
    const styles: Record<string, string> = {};
    const hasLeftIcon = this.appearanceConfig().showLeftIcon;

    if (this.appearance() === "primary") {
      styles["border-right"] = "none";
      styles["border-radius"] = `${SEARCHBAR_BORDER_RADIUS} 0 0 ${SEARCHBAR_BORDER_RADIUS}`;
      if (!hasLeftIcon) {
        styles["padding-left"] = SEARCHBAR_PADDING_LEFT;
      }
    } else if (this.appearance() === "secondary") {
      styles["border-radius"] = SEARCHBAR_BORDER_RADIUS;
    }

    return styles;
  });

  readonly searchButtonStyles = computed(() => {
    const styles: Record<string, string> = {
      width: SEARCHBAR_BUTTON_WIDTH,
      "border-radius": `0 ${SEARCHBAR_BORDER_RADIUS} ${SEARCHBAR_BORDER_RADIUS} 0`,
      display: "flex",
      "justify-content": "center",
    };
    if (this.compactSpacing()) {
      styles["height"] = SEARCHBAR_BUTTON_HEIGHT_COMPACT;
    }
    return styles;
  });

  handleChange(value: string): void {
    this.valueChange.emit(value);
  }

  handleSearch(): void {
    this.searchEvent.emit(this.value());
  }

  handleEnter(event: KeyboardEvent): void {
    if (event.key === ENTER_KEY) {
      this.handleSearch();
    }
  }

  handleClear(): void {
    this.valueChange.emit("");
    this.clear.emit();
  }

  handleFocusIn(): void {
    this.hasFocusWithin.set(true);
  }

  handleFocusOut(event: FocusEvent): void {
    const next = event.relatedTarget as Node | null;
    const currentTarget = event.currentTarget as Node;
    if (next && currentTarget.contains(next)) {
      return;
    }
    this.hasFocusWithin.set(false);
  }
}

<div class="searchbar-container" role="search" [ngClass]="appearance()">
  <div class="searchbar-wrapper">
    <div
      class="text-input-wrapper"
      [ngClass]="{ focused: isFocused() }"
      [attr.data-disabled]="disabled()"
    >
      <div
        rteDropdown
        rteDropdownPosition="bottom"
        [rteDropdownIsOpen]="isOpenComputed()"
        [rteDropdownOffset]="DROPDOWN_OFFSET"
        [rteDropdownWidth]="textInputWidth()"
        [rteDropdownAutofocus]="false"
        [attr.data-dropdown-id]="dropdownId()"
        (menuEvent)="onMenuEvent($event)"
      >
        <div class="dropdown-trigger" rteDropdownTrigger>
          <rte-text-input
            #textInput
            placeholder="Rechercher"
            [id]="id() ?? ''"
            [label]="label()"
            [disabled]="disabled()"
            [value]="internalValue()"
            [showRightIcon]="showResetButton()"
            [rightIconAction]="'clean'"
            [assistiveTextLabel]="assistiveText()"
            [compactSpacing]="compactSpacing()"
            [leftIcon]="appearanceConfig().showLeftIcon ? 'search' : null"
            (valueChange)="handleChange($event)"
            (rightIconClick)="handleClear()"
          />
          @if (appearanceConfig().showSearchButton) {
            <rte-icon-button
              name="search"
              size="m"
              variant="primary"
              appearance="filled"
              ariaLabel="Search"
              class="search-button"
              [disabled]="disabled()"
              [compactSpacing]="compactSpacing()"
              [ngClass]="{ 'compact-spacing': compactSpacing() }"
              (click)="handleSearch()"
            />
          }
        </div>
        @if (dropdownItems().length > 0) {
          <rte-dropdown-menu [items]="dropdownItems()" />
        }
      </div>
    </div>
  </div>
</div>
