// packages/react/src/components/drawer/Drawer.tsx
import {
  getDrawerConfigurationIssues,
  DRAWER_PADDING,
  DRAWER_TRANSITION_DURATION,
  shouldUseDrawerDefaultFooter,
  shouldUseDrawerDefaultHeader,
} from "@design-system-rte/core";
import { DrawerProps as coreDrawerProps } from "@design-system-rte/core/components/drawer/drawer.interface";
import { computeTransform } from "@design-system-rte/core/components/drawer/drawer.utils";
import { RefObject, useRef } from "react";

import Backdrop from "../../abstract/backdrop/Backdrop";
import BaseFooter from "../../abstract/baseFooter/BaseFooter";
import BaseHeader from "../../abstract/baseHeader/BaseHeader";
import useAnimatedMount from "../../hooks/useAnimatedMount";
import { useClickAway } from "../../hooks/useClickAway";
import { useFocusTrap } from "../../hooks/useFocusTrap";
import { useKeydownEscape } from "../../hooks/useKeydownEscape";
import Button from "../button/Button";
import Divider from "../divider/Divider";
import IconButton from "../iconButton/IconButton";
import { Overlay } from "../overlay/Overlay";

import styles from "./Drawer.module.scss";

interface DrawerProps extends coreDrawerProps, Omit<React.HTMLAttributes<HTMLDivElement>, "id" | "content"> {
  header?: React.ReactNode | React.ReactNode[];
  footer?: React.ReactNode | React.ReactNode[];
  content?: React.ReactNode | React.ReactNode[];
  children?: React.ReactNode | React.ReactNode[];
  width?: string;
}

const PADDING = 4;

const Header = ({
  isCollapsible,
  iconToggleCloseContainerRef,
  isOpen,
  isAnimating,
  handleOnClickToggle,
  shouldDisplayDefaultHeader,
  id,
  title,
  icon,
  iconAppearance,
  onClose,
  isClosable,
  header,
  drawerLeftPosition,
}: {
  isCollapsible: boolean;
  iconToggleCloseContainerRef: RefObject<HTMLButtonElement>;
  isOpen: boolean;
  isAnimating: boolean;
  handleOnClickToggle: () => void;
  shouldDisplayDefaultHeader: boolean;
  id: string;
  title?: string;
  icon?: string;
  iconAppearance?: "outlined" | "filled";
  onClose: () => void;
  isClosable: boolean;
  header?: React.ReactNode | React.ReactNode[];
  drawerLeftPosition: number;
}) => (
  <>
    {isCollapsible && (
      <IconButton
        ref={iconToggleCloseContainerRef}
        className={styles["drawer-toggle"]}
        style={{
          transition: "none",
          transform: computeTransform(isAnimating, drawerLeftPosition, PADDING),
        }}
        name={isOpen ? "right-panel-close" : "right-panel-open"}
        size="l"
        variant="primary"
        onClick={handleOnClickToggle}
        aria-label={`Close drawer ${id}`}
      />
    )}
    {shouldDisplayDefaultHeader ? (
      <BaseHeader
        id={id}
        title={title!}
        icon={icon}
        iconAppearance={iconAppearance}
        onClose={onClose}
        isClosable={isClosable}
      />
    ) : (
      <>{header}</>
    )}
  </>
);

const Content = ({
  content,
  fixedHeader,
}: {
  content?: React.ReactNode | React.ReactNode[];
  fixedHeader?: boolean;
}) => (
  <div className={styles["drawer-content"]} data-fixed-header={fixedHeader} tabIndex={-1}>
    {content}
  </div>
);

const HeaderWithContent = ({
  fixedHeader,
  id,
  title,
  icon,
  iconAppearance,
  isCollapsible,
  iconToggleCloseContainerRef,
  isOpen,
  isAnimating,
  handleOnClickToggle,
  shouldDisplayDefaultHeader,
  onClose,
  isClosable,
  header,
  drawerLeftPosition,
  content,
}: {
  fixedHeader?: boolean;
  id: string;
  title?: string;
  icon?: string;
  iconAppearance?: "outlined" | "filled";
  isCollapsible: boolean;
  iconToggleCloseContainerRef: RefObject<HTMLButtonElement>;
  isOpen: boolean;
  isAnimating: boolean;
  handleOnClickToggle: () => void;
  shouldDisplayDefaultHeader: boolean;
  onClose: () => void;
  isClosable: boolean;
  header?: React.ReactNode | React.ReactNode[];
  drawerLeftPosition: number;
  content?: React.ReactNode | React.ReactNode[];
}) => (
  <>
    {fixedHeader ? (
      <>
        <Header
          id={id}
          title={title}
          icon={icon}
          iconAppearance={iconAppearance}
          isCollapsible={isCollapsible}
          iconToggleCloseContainerRef={iconToggleCloseContainerRef}
          isOpen={isOpen}
          isAnimating={isAnimating}
          handleOnClickToggle={handleOnClickToggle}
          shouldDisplayDefaultHeader={!!shouldDisplayDefaultHeader}
          onClose={onClose}
          isClosable={isClosable}
          header={header}
          drawerLeftPosition={drawerLeftPosition}
        />
        <Content content={content} fixedHeader={fixedHeader} />
      </>
    ) : (
      <div className={styles["drawer-header-content"]}>
        <Header
          id={id}
          title={title}
          icon={icon}
          iconAppearance={iconAppearance}
          isCollapsible={isCollapsible}
          iconToggleCloseContainerRef={iconToggleCloseContainerRef}
          isOpen={isOpen}
          isAnimating={isAnimating}
          handleOnClickToggle={handleOnClickToggle}
          shouldDisplayDefaultHeader={!!shouldDisplayDefaultHeader}
          onClose={onClose}
          isClosable={isClosable}
          header={header}
          drawerLeftPosition={drawerLeftPosition}
        />
        <Content content={content} />
      </div>
    )}
  </>
);

const Footer = ({
  fixedHeader,
  shouldDisplayDefaultFooter,
  primaryButtonLabel,
  secondaryButtonLabel,
  footer,
  onClickPrimaryButton,
  onClickSecondaryButton,
}: {
  fixedHeader?: boolean;
  shouldDisplayDefaultFooter: boolean;
  primaryButtonLabel?: string;
  secondaryButtonLabel?: string;
  footer?: React.ReactNode | React.ReactNode[];
  onClickPrimaryButton?: () => void;
  onClickSecondaryButton?: () => void;
}) => (
  <div className={styles["drawer-footer"]} data-fixed-header={fixedHeader}>
    {shouldDisplayDefaultFooter ? (
      <BaseFooter
        primaryButton={<Button label={primaryButtonLabel!} variant="primary" onClick={onClickPrimaryButton} />}
        secondaryButton={
          secondaryButtonLabel ? (
            <Button label={secondaryButtonLabel} variant="secondary" onClick={onClickSecondaryButton} />
          ) : undefined
        }
      />
    ) : (
      footer && <>{footer}</>
    )}
  </div>
);

const Drawer = ({
  id,
  title,
  icon,
  iconAppearance,
  isOpen,
  onClose,
  onClickToggle,
  closeOnOverlayClick = false,
  primaryButtonLabel,
  secondaryButtonLabel,
  isCollapsible = false,
  content,
  header,
  footer,
  position,
  width,
  children,
  fixedHeader,
  closeOnEscape = false,
  isClosable = true,
  onClickPrimaryButton,
  onClickSecondaryButton,
  ...props
}: DrawerProps) => {
  const { shouldRender, isAnimating } = useAnimatedMount(isOpen, DRAWER_TRANSITION_DURATION);
  const drawerRef = useRef<HTMLDivElement | null>(null);
  const iconToggleOpenContainerRef = useRef<HTMLButtonElement | null>(null);
  const iconToggleCloseContainerRef = useRef<HTMLButtonElement | null>(null);

  const drawerLeftPosition = drawerRef.current?.clientWidth || 0;

  useClickAway(closeOnOverlayClick && position === "modal" ? onClose : () => {}, drawerRef.current!);
  useKeydownEscape(closeOnEscape ? onClose : () => {});
  useFocusTrap(drawerRef.current!, shouldRender);

  const shouldDisplayDefaultHeader = shouldUseDrawerDefaultHeader(header, title);
  const shouldDisplayDefaultFooter = shouldUseDrawerDefaultFooter(footer, primaryButtonLabel);

  const configurationIssues = getDrawerConfigurationIssues({
    hasCustomHeader: header !== undefined,
    hasTitle: !!title,
    hasCustomFooter: footer !== undefined,
    hasPrimaryButtonLabel: !!primaryButtonLabel,
    position,
    hasMainContent: !!children,
  });
  if (configurationIssues) {
    console.warn(configurationIssues);
    return null;
  }

  const computeTransform = (padding: number = 0) => {
    return isAnimating ? `translateX(-${drawerLeftPosition + padding}px)` : "none";
  };

  const handleOnClickToggle = () => {
    if (isOpen && iconToggleOpenContainerRef.current) {
      iconToggleOpenContainerRef.current.focus();
    }
    if (!isOpen && iconToggleCloseContainerRef.current) {
      iconToggleCloseContainerRef.current.focus();
    }
    onClickToggle();
  };

  const headerWithContentProps = {
    fixedHeader,
    id,
    title,
    icon,
    iconAppearance,
    isCollapsible,
    iconToggleCloseContainerRef,
    isOpen,
    isAnimating,
    handleOnClickToggle,
    shouldDisplayDefaultHeader: !!shouldDisplayDefaultHeader,
    onClose,
    isClosable,
    header,
    drawerLeftPosition,
    content,
  };

  const footerProps = {
    fixedHeader,
    shouldDisplayDefaultFooter: !!shouldDisplayDefaultFooter,
    primaryButtonLabel,
    secondaryButtonLabel,
    footer,
    onClickPrimaryButton,
    onClickSecondaryButton,
  };

  return (
    <>
      {position === "responsive" ? (
        <>
          <div className={styles["drawer-responsive-container"]}>
            {isCollapsible && (
              <IconButton
                className={styles["drawer-toggle"]}
                style={{
                  position: "absolute",
                  top: 24,
                  right: 4,
                  transition: "transform 240ms ease-out",
                  opacity: isAnimating ? 0 : 1,
                  transform: computeTransform(DRAWER_PADDING),
                }}
                name="right-panel-open"
                size="l"
                variant="primary"
                onClick={handleOnClickToggle}
                aria-label={`Close drawer ${id}`}
              />
            )}
            <Divider
              orientation="vertical"
              style={{
                position: "absolute",
                right: "0px",
                transition: "transform 240ms ease-out",
                visibility: isAnimating ? "visible" : "hidden",
                transform: computeTransform(),
              }}
            />
            <div
              className={styles["drawer"]}
              ref={drawerRef}
              data-open={isAnimating}
              role="region"
              aria-labelledby={`${id}-drawer-title`}
              data-position={position}
              data-fixed-header={fixedHeader}
              style={{
                width,
                transform: isAnimating ? `none` : `translateX(${width || "100%"})`,
                visibility: isAnimating ? "visible" : "hidden",
              }}
              {...props}
            >
              <HeaderWithContent {...headerWithContentProps} />
              <Footer {...footerProps} />
            </div>
            <div
              className={styles["drawer-children"]}
              data-open={isAnimating}
              style={{
                height: "100%",
                transition: "margin-right 240ms ease-out",
                marginRight: isAnimating ? width : 0,
                maxHeight: isAnimating ? "100vh" : undefined,
                overflowY: isAnimating ? "auto" : undefined,
              }}
            >
              {children}
            </div>
          </div>
        </>
      ) : (
        <>
          {isCollapsible && (
            <IconButton
              ref={iconToggleOpenContainerRef}
              className={styles["drawer-toggle"]}
              style={{
                position: "absolute",
                top: 24,
                right: 4,
                opacity: isAnimating ? 0 : 1,
              }}
              name={"right-panel-open"}
              size="l"
              variant="primary"
              onClick={handleOnClickToggle}
              aria-label={`Close drawer ${id}`}
            />
          )}
          {shouldRender && (
            <Overlay>
              <div className={styles["drawer-modal-layer"]}>
                <Backdrop isAnimating={isAnimating} />
                <div
                  ref={drawerRef}
                  className={styles["drawer"]}
                  data-open={isAnimating}
                  data-fixed-header={fixedHeader}
                  role="dialog"
                  aria-modal="true"
                  aria-labelledby={`${id}-drawer-title`}
                  style={{
                    width,
                  }}
                  {...props}
                >
                  <HeaderWithContent {...headerWithContentProps} />
                  <Footer {...footerProps} />
                </div>
              </div>
            </Overlay>
          )}
        </>
      )}
    </>
  );
};

export default Drawer;

// preview/dsr-649/angular/components/drawer/drawer.component.ts
import { CommonModule } from "@angular/common";
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  Injector,
  input,
  OnDestroy,
  output,
  signal,
  TemplateRef,
  untracked,
  viewChild,
} from "@angular/core";
import {
  DRAWER_PADDING,
  DRAWER_TRANSITION_DURATION,
  shouldUseDrawerDefaultFooter,
  shouldUseDrawerDefaultHeader,
} from "@design-system-rte/core";
import type { DrawerPosition } from "@design-system-rte/core/components/drawer/drawer.interface";
import { IconSize } from "@design-system-rte/core/components/icon/icon.constants";

import { FocusTrapService } from "../../services/focus-trap.service";
import { ButtonComponent } from "../button/button.component";
import { DividerComponent } from "../divider/divider.component";
import { IconComponent } from "../icon/icon.component";
import { IconButtonComponent } from "../icon-button/icon-button.component";

@Component({
  selector: "rte-drawer",
  imports: [CommonModule, ButtonComponent, DividerComponent, IconComponent, IconButtonComponent],
  standalone: true,
  templateUrl: "./drawer.component.html",
  styleUrl: "./drawer.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DrawerComponent implements OnDestroy {
  readonly id = input.required<string>();
  readonly title = input<string>();
  readonly icon = input<string>();
  readonly iconAppearance = input<"outlined" | "filled">("outlined");
  readonly isOpen = input<boolean>(false);
  readonly position = input<DrawerPosition>("modal");
  readonly width = input<string | undefined>();
  readonly closeOnOverlayClick = input<boolean>(false);
  readonly primaryButtonLabel = input<string>();
  readonly secondaryButtonLabel = input<string>();
  readonly isCollapsible = input<boolean>(false);
  readonly fixedHeader = input<boolean>(false);
  readonly closeOnEscape = input<boolean>(false);
  readonly isClosable = input<boolean>(true);
  readonly modalHostMode = input<boolean>(false);

  readonly drawerContent = input<TemplateRef<unknown> | null>(null);
  readonly drawerHeader = input<TemplateRef<unknown> | null>(null);
  readonly drawerFooter = input<TemplateRef<unknown> | null>(null);
  readonly drawerContextContent = input<TemplateRef<unknown> | null>(null);

  readonly closed = output<void>();
  readonly clickToggle = output<void>();

  readonly iconSize = signal(IconSize["xl"]);

  readonly drawerPanelModal = viewChild<ElementRef<HTMLElement>>("drawerPanelModal");
  readonly drawerPanelResponsive = viewChild<ElementRef<HTMLElement>>("drawerPanelResponsive");

  readonly isAnimating = signal(false);
  readonly shouldRenderModalLayer = signal(false);

  readonly shouldDisplayDefaultHeader = computed(() =>
    shouldUseDrawerDefaultHeader(!!this.drawerHeader(), this.title()),
  );
  readonly shouldDisplayDefaultFooter = computed(() =>
    shouldUseDrawerDefaultFooter(!!this.drawerFooter(), this.primaryButtonLabel()),
  );

  readonly panelWidthPx = signal(0);

  readonly collapsibleToggleTransform = computed(() => {
    const widthPx = this.panelWidthPx();
    return this.isAnimating() ? `translateX(-${widthPx + DRAWER_PADDING}px)` : "none";
  });

  readonly responsiveDividerTransform = computed(() => {
    const widthPx = this.panelWidthPx();
    return this.isAnimating() ? `translateX(-${widthPx}px)` : "none";
  });

  readonly floatingToggleOpacity = computed(() => (this.isAnimating() ? 0 : 1));

  readonly collapsibleToggleIconName = computed(() =>
    this.isOpen() ? ("right-panel-close" as const) : ("right-panel-open" as const),
  );

  readonly responsiveMainMarginRight = computed(() => (this.isAnimating() ? (this.width() ?? "0") : "0"));

  private readonly focusTrap = inject(FocusTrapService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly injector = inject(Injector);
  private resizeObserver: ResizeObserver | null = null;
  private focusTrapActive = false;

  constructor() {
    effect(
      () => {
        const open = this.isOpen();
        const modal = this.position() === "modal";

        if (!modal) {
          if (open) {
            this.isAnimating.set(false);
            untracked(() => {
              requestAnimationFrame(() => {
                requestAnimationFrame(() => {
                  this.isAnimating.set(true);
                  afterNextRender(
                    () => {
                      const native = this.drawerPanelResponsive()?.nativeElement;
                      if (native && !this.focusTrapActive) {
                        this.focusTrap.activate(native);
                        this.focusTrapActive = true;
                      }
                    },
                    { injector: this.injector },
                  );
                });
              });
            });
          } else {
            this.isAnimating.set(false);
            if (this.focusTrapActive) {
              this.focusTrap.deactivate();
              this.focusTrapActive = false;
            }
          }
          return;
        }

        if (open) {
          this.shouldRenderModalLayer.set(true);
          this.isAnimating.set(false);
          untracked(() => {
            requestAnimationFrame(() => {
              requestAnimationFrame(() => {
                this.isAnimating.set(true);
                afterNextRender(
                  () => {
                    const native =
                      this.drawerPanelModal()?.nativeElement ?? this.drawerPanelResponsive()?.nativeElement;
                    if (native && !this.focusTrapActive) {
                      this.focusTrap.activate(native);
                      this.focusTrapActive = true;
                    }
                  },
                  { injector: this.injector },
                );
              });
            });
          });
        } else {
          this.isAnimating.set(false);
          if (this.focusTrapActive) {
            this.focusTrap.deactivate();
            this.focusTrapActive = false;
          }
          if (this.shouldRenderModalLayer()) {
            setTimeout(() => {
              this.shouldRenderModalLayer.set(false);
            }, DRAWER_TRANSITION_DURATION);
          }
        }
      },
      { allowSignalWrites: true },
    );

    effect(
      () => {
        const modalPanel = this.drawerPanelModal()?.nativeElement;
        const responsivePanel = this.drawerPanelResponsive()?.nativeElement;
        const panel = modalPanel ?? responsivePanel;
        if (!panel) {
          untracked(() => {
            this.resizeObserver?.disconnect();
            this.resizeObserver = null;
          });
          return;
        }
        untracked(() => {
          this.resizeObserver?.disconnect();
          this.resizeObserver = new ResizeObserver(() => {
            this.panelWidthPx.set(panel.clientWidth);
          });
          this.resizeObserver.observe(panel);
          this.panelWidthPx.set(panel.clientWidth);
        });
      },
      { allowSignalWrites: true },
    );

    this.destroyRef.onDestroy(() => {
      this.resizeObserver?.disconnect();
      if (this.focusTrapActive) {
        this.focusTrap.deactivate();
        this.focusTrapActive = false;
      }
    });
  }

  onClose(): void {
    this.closed.emit();
  }

  onClickToggle(): void {
    this.clickToggle.emit();
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
    if (this.focusTrapActive) {
      this.focusTrap.deactivate();
      this.focusTrapActive = false;
    }
  }
}

@let pos = position();
@let responsive = pos === "responsive";
@let modal = pos === "modal";

<div class="rte-drawer-root" [class.rte-drawer-modal-host-layer]="modal && modalHostMode()" [attr.data-position]="pos">
  @if (isCollapsible() && modal) {
    <rte-icon-button
      class="drawer-toggle drawer-toggle--floating"
      [name]="'right-panel-open'"
      [size]="'l'"
      [variant]="'primary'"
      [ariaLabel]="'Close drawer ' + id()"
      [customStyle]="{
        position: 'absolute',
        top: '24px',
        right: '4px',
        opacity: floatingToggleOpacity().toString(),
      }"
      (clickEvent)="onClickToggle()"
    />
  }

  @if (responsive) {
    <div class="drawer-responsive-container">
      @if (isCollapsible()) {
        <rte-icon-button
          class="drawer-toggle drawer-toggle--responsive-floating"
          [name]="'right-panel-open'"
          [size]="'l'"
          [variant]="'primary'"
          [ariaLabel]="'Close drawer ' + id()"
          [customStyle]="{
            position: 'absolute',
            top: '24px',
            right: '4px',
            opacity: isAnimating() ? '0' : '1',
            transform: collapsibleToggleTransform(),
          }"
          (clickEvent)="onClickToggle()"
        />
      }
      <div
        class="drawer-responsive-divider-wrap"
        [style.visibility]="isAnimating() ? 'visible' : 'hidden'"
        [style.transform]="responsiveDividerTransform()"
        [style.transition]="'transform 240ms ease-out'"
      >
        <rte-divider orientation="vertical" />
      </div>
      <div
        #drawerPanelResponsive
        class="drawer"
        data-drawer-panel
        role="region"
        [attr.data-open]="isAnimating() ? 'true' : 'false'"
        [attr.data-position]="pos"
        [attr.data-fixed-header]="fixedHeader() ? 'true' : 'false'"
        [attr.aria-labelledby]="id() + '-drawer-title'"
        [style.width]="width()"
        [style.transform]="isAnimating() ? 'none' : 'translateX(' + (width() ?? '100%') + ')'"
        [style.visibility]="isAnimating() ? 'visible' : 'hidden'"
      >
        <ng-container *ngTemplateOutlet="headerAndContent" />
        <ng-container *ngTemplateOutlet="footerBlock" />
      </div>
      <div
        class="drawer-children"
        [attr.data-open]="isAnimating() ? 'true' : 'false'"
        [style.marginRight]="responsiveMainMarginRight()"
        [style.maxHeight]="isAnimating() ? '100vh' : undefined"
        [style.overflowY]="isAnimating() ? 'auto' : undefined"
        [style.height]="'100%'"
        [style.transition]="'margin-right 240ms ease-out'"
      >
        <ng-container *ngTemplateOutlet="drawerMainContent() ?? null" />
      </div>
    </div>
  }

  @if (modal && shouldRenderModalLayer()) {
    <div class="rte-drawer-modal-layer">
      <div class="rte-drawer-backdrop" [attr.data-open]="isAnimating() ? 'true' : 'false'"></div>
      <div
        #drawerPanelModal
        class="drawer"
        data-drawer-panel
        role="dialog"
        aria-modal="true"
        [attr.data-open]="isAnimating() ? 'true' : 'false'"
        [attr.data-fixed-header]="fixedHeader() ? 'true' : 'false'"
        [attr.aria-labelledby]="id() + '-drawer-title'"
        [style.width]="width()"
      >
        <ng-container *ngTemplateOutlet="headerAndContent" />
        <ng-container *ngTemplateOutlet="footerBlock" />
      </div>
    </div>
  }
</div>

<ng-template #headerAndContent>
  @if (fixedHeader()) {
    <ng-container *ngTemplateOutlet="headerBlock" />
    <ng-container *ngTemplateOutlet="contentBlock" />
  } @else {
    <div class="drawer-header-content">
      <ng-container *ngTemplateOutlet="headerBlock" />
      <ng-container *ngTemplateOutlet="contentBlock" />
    </div>
  }
</ng-template>

<ng-template #headerBlock>
  @if (isCollapsible()) {
    <rte-icon-button
      class="drawer-toggle"
      [name]="collapsibleToggleIconName()"
      [size]="'l'"
      [variant]="'primary'"
      [customStyle]="{ transform: collapsibleToggleTransform() }"
      [ariaLabel]="'Close drawer ' + id()"
      (clickEvent)="onClickToggle()"
    />
  }
  @if (shouldDisplayDefaultHeader()) {
    <div class="rte-drawer-base-header">
      <div class="rte-drawer-base-header-text">
        @if (icon()) {
          <rte-icon [name]="icon() ?? ''" [size]="iconSize()" [appearance]="iconAppearance()" />
        }
        <h2 class="rte-drawer-base-header-title" [id]="id() + '-drawer-title'">
          {{ title() }}
        </h2>
        @if (isClosable()) {
          <rte-icon-button
            data-testid="drawer-close-button"
            name="close"
            size="l"
            class="rte-drawer-close-icon"
            variant="neutral"
            [ariaLabel]="'Close drawer ' + id()"
            (clickEvent)="onClose()"
          />
        }
      </div>
      <rte-divider />
    </div>
  } @else {
    <ng-container *ngTemplateOutlet="drawerHeader() ?? null" />
  }
</ng-template>

<ng-template #contentBlock>
  <div class="drawer-content" tabindex="-1" [attr.data-fixed-header]="fixedHeader() ? 'true' : 'false'">
    <ng-container *ngTemplateOutlet="drawerContent() ?? null" />
  </div>
</ng-template>

<ng-template #footerBlock>
  <div class="drawer-footer" [attr.data-fixed-header]="fixedHeader() ? 'true' : 'false'">
    @if (shouldDisplayDefaultFooter()) {
      <div class="rte-drawer-base-footer">
        @if (secondaryButtonLabel()) {
          <button rteButton rteButtonVariant="neutral">
            {{ secondaryButtonLabel() }}
          </button>
        }
        <button rteButton rteButtonVariant="primary">
          {{ primaryButtonLabel() }}
        </button>
      </div>
    } @else {
      <ng-container *ngTemplateOutlet="drawerFooter() ?? null" />
    }
  </div>
</ng-template>
