// packages/angular/projects/ds-rte-lib/src/lib/components/header/header.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  contentChild,
  effect,
  inject,
  input,
  output,
  signal,
} from "@angular/core";
import { BadgeSize } from "@design-system-rte/core/components/badge/badge.interface";
import { ButtonSize, type ButtonVariant } from "@design-system-rte/core/components/button/common/common-button";
import {
  HEADER_DEFAULT_BREADCRUMBS_ARIA_LABEL,
  HEADER_DEFAULT_NAV_ARIA_LABEL,
  HEADER_DESKTOP_BREAKPOINT_PX,
  HeaderSubHeaderConfig,
  resolveScrollDirection,
  type HeaderActionButtonConfig,
  type HeaderAppearance,
  type HeaderAvatarConfig,
  type HeaderIconButtonConfig,
  type HeaderLeftSectionConfig,
  type HeaderNavigationItem,
  type ScrollDirectionState,
} from "@design-system-rte/core/components/header";
import { SearchBarAppearance, SearchBarProps } from "@design-system-rte/core/components/searchbar";

import { AvatarComponent } from "../avatar/avatar.component";
import { BreadcrumbsComponent } from "../breadcrumbs/breadcrumbs.component";
import { ButtonComponent } from "../button/button.component";
import { DividerComponent } from "../divider/divider.component";
import type { DropdownItemConfig } from "../dropdown/dropdown.types";
import { IconComponent } from "../icon/icon.component";
import { RegularIconIdKey, TogglableIconIdKey } from "../icon/icon.service";
import { IconButtonComponent } from "../icon-button/icon-button.component";
import { SearchbarComponent } from "../searchbar/searchbar.component";

import { HeaderLeftSectionComponent } from "./header-left-section/header-left-section.component";
import { HeaderLeftDirective } from "./header-left.directive";
import { HeaderMobileComponent } from "./header-mobile/header-mobile.component";
import { HeaderMobileMenuDirective } from "./header-mobile-menu.directive";
import { HeaderRightDirective } from "./header-right.directive";

const DEFAULT_HOME_LINK = "/";

@Component({
  selector: "rte-header",
  imports: [
    CommonModule,
    IconButtonComponent,
    ButtonComponent,
    SearchbarComponent,
    AvatarComponent,
    IconComponent,
    BreadcrumbsComponent,
    HeaderMobileComponent,
    HeaderLeftSectionComponent,
    HeaderRightDirective,
    DividerComponent,
  ],
  templateUrl: "./header.component.html",
  styleUrl: "./header.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {
  private readonly destroyRef = inject(DestroyRef);

  readonly appearance = input<HeaderAppearance>("brand");
  readonly isCompact = input<boolean>(false);
  readonly hasLeftSection = input<boolean>(true);
  readonly hasRightSection = input<boolean>(true);
  readonly hasSubHeader = input<boolean>(true);
  readonly subHeaderConfig = input<HeaderSubHeaderConfig | undefined>(undefined);

  readonly isSticky = input<boolean>(false);
  readonly showAtScrollUp = input<boolean>(false);

  readonly hasLogo = input<boolean>(true);
  readonly applicationName = input<string>("");
  readonly logoSrc = input<string | undefined>(undefined);
  readonly homeLink = input<string>(DEFAULT_HOME_LINK);
  readonly homeAriaLabel = input<string | undefined>(undefined);

  readonly hasMidSection = input<boolean>(true);
  readonly navigationAriaLabel = input<string>(HEADER_DEFAULT_NAV_ARIA_LABEL);
  readonly navigationItems = input<HeaderNavigationItem[]>([]);

  readonly hasSearchbar = input<boolean>(true);
  readonly searchbarProps = input<SearchBarProps | undefined>(undefined);

  readonly hasActionButton = input<boolean>(true);
  readonly actionButton = input<HeaderActionButtonConfig | undefined>(undefined);

  readonly hasIconButtons = input<boolean>(true);
  readonly iconButtons = input<HeaderIconButtonConfig<RegularIconIdKey | TogglableIconIdKey>[] | undefined>(undefined);

  readonly hasAvatar = input<boolean>(true);
  readonly avatarProps = input<HeaderAvatarConfig | undefined>(undefined);

  readonly mobileMenuButton = input<HeaderIconButtonConfig<RegularIconIdKey | TogglableIconIdKey> | undefined>(
    undefined,
  );
  readonly mobileMenuItems = input<DropdownItemConfig[]>([]);
  readonly mobileSearchButtonAriaLabel = input<string>("Rechercher");

  readonly isSearchActive = input<boolean>(false);
  readonly isSearchActiveChange = output<boolean>();

  readonly hasDivider = input<boolean>(false);

  readonly internalIsSearchActive = signal<boolean>(false);
  private readonly lastSeenExternalIsSearchActive = signal<boolean>(false);

  readonly navigationItemClick = output<string | undefined>();
  readonly searchEvent = output<string | undefined>();
  readonly actionButtonClick = output<void>();
  readonly iconButtonClick = output<string | undefined>();
  readonly avatarClick = output<void>();
  readonly mobileMenuClick = output<void>();
  readonly mobileMenuItemEvent = output<{ event: Event; id: string; item?: DropdownItemConfig }>();

  readonly isDesktop = signal<boolean>(HeaderComponent.readIsDesktopFromWindow());
  readonly isVisible = signal<boolean>(true);

  readonly projectedLeftSection = contentChild(HeaderLeftDirective);
  readonly projectedMobileMenu = contentChild(HeaderMobileMenuDirective);

  readonly computedLeftSectionConfig = computed<HeaderLeftSectionConfig | undefined>(() => {
    return {
      hasLogo: this.hasLogo(),
      applicationName: this.applicationName(),
      logoSrc: this.logoSrc(),
      homeLink: this.homeLink(),
      homeAriaLabel: this.homeAriaLabel(),
    };
  });

  readonly shouldRenderSubheader = computed(() => this.hasSubHeader() && !!this.subHeaderConfig()?.items?.length);

  readonly breadcrumbsAriaLabel = computed(
    () => this.subHeaderConfig()?.ariaLabel || HEADER_DEFAULT_BREADCRUMBS_ARIA_LABEL,
  );

  readonly actionButtonSize = computed<Exclude<ButtonSize, "l">>(() => (this.isCompact() ? "s" : "m"));

  readonly iconButtonSize = computed<ButtonSize>(() => (this.isCompact() ? "m" : "l"));

  readonly badgeSize = computed<BadgeSize>(() => (this.isCompact() ? "m" : "l"));

  readonly searchbarAppearance = computed<SearchBarAppearance>(() =>
    this.appearance() === "neutral" ? "secondary" : "primary",
  );

  readonly actionButtonVariant = computed<ButtonVariant>(() =>
    this.appearance() === "neutral" ? "neutral" : "primary",
  );

  readonly rightSectionIconButtonsVariant = computed<ButtonVariant>(() =>
    this.appearance() === "neutral" ? "neutral" : "text",
  );

  private scrollState: ScrollDirectionState = { lastScrollY: 0, lastDirection: "up" };

  private static readIsDesktopFromWindow(): boolean {
    if (typeof globalThis === "undefined") {
      return true;
    }
    const windowReference = (globalThis as { window?: Window }).window;
    if (!windowReference || typeof windowReference.innerWidth !== "number") {
      return true;
    }
    return windowReference.innerWidth >= HEADER_DESKTOP_BREAKPOINT_PX;
  }

  constructor() {
    this.internalIsSearchActive.set(this.isSearchActive());
    this.lastSeenExternalIsSearchActive.set(this.isSearchActive());

    effect(() => this.syncViewportMode());

    effect(() => {
      const nextExternal = this.isSearchActive();
      if (nextExternal === this.lastSeenExternalIsSearchActive()) {
        return;
      }
      this.lastSeenExternalIsSearchActive.set(nextExternal);
      this.internalIsSearchActive.set(nextExternal);
    });

    effect((onCleanup) => {
      const teardown = this.setupScrollBehavior();
      onCleanup(teardown);
    });

    effect(() => {
      if (this.isDesktop()) {
        if (this.internalIsSearchActive()) {
          this.handleIsSearchActiveChange(false);
        }
      }
    });
  }

  private syncViewportMode(): void {
    const update = (): void => {
      this.isDesktop.set(window.innerWidth >= HEADER_DESKTOP_BREAKPOINT_PX);
    };

    update();
    window.addEventListener("resize", update);
    this.destroyRef.onDestroy(() => {
      window.removeEventListener("resize", update);
    });
  }

  private setupScrollBehavior(): () => void {
    const isSticky = this.isSticky();
    const showAtScrollUp = this.showAtScrollUp();

    this.isVisible.set(true);
    this.scrollState = { lastScrollY: window.scrollY || 0, lastDirection: "up" };

    if (!isSticky || !showAtScrollUp) {
      return () => {};
    }

    const onScroll = (): void => {
      const nextScrollY = window.scrollY || 0;
      this.scrollState = resolveScrollDirection(this.scrollState, nextScrollY, 2);

      if (nextScrollY <= 0) {
        this.isVisible.set(true);
        return;
      }

      this.isVisible.set(this.scrollState.lastDirection === "up");
    };

    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }

  handleNavigationItemClick(item: HeaderNavigationItem, event: MouseEvent): void {
    if (item.disabled) {
      event.preventDefault();
      return;
    }
    this.navigationItemClick.emit(item.id || item.label);
  }

  handleSearchEvent(value: string | undefined): void {
    this.searchEvent.emit(value);
  }

  handleActionButtonClick(): void {
    this.actionButtonClick.emit();
  }

  handleIconButtonClick(button: HeaderIconButtonConfig): void {
    this.iconButtonClick.emit(button.id);
  }

  handleAvatarClick(): void {
    this.avatarClick.emit();
  }

  handleMobileMenuClick(): void {
    this.mobileMenuClick.emit();
  }

  handleMobileMenuItemEvent(event: { event: Event; id: string; item?: DropdownItemConfig }): void {
    this.mobileMenuItemEvent.emit(event);
  }

  handleIsSearchActiveChange(nextValue: boolean): void {
    this.internalIsSearchActive.set(nextValue);
    this.isSearchActiveChange.emit(nextValue);
  }
}

<header
  #headerRootRef
  class="rte-header"
  role="banner"
  [attr.data-appearance]="appearance()"
  [attr.data-compact]="isCompact()"
  [attr.data-sticky]="isSticky()"
  [attr.data-visible]="isVisible()"
>
  <div class="rte-header-main">
    @if (hasLeftSection()) {
      <div class="rte-header-left">
        @if (leftSectionType() === "default") {
          <a class="rte-header-home" [href]="homeLink()" [attr.aria-label]="computedHomeAriaLabel()">
            @if (hasLogo() && logoSrc()) {
              <img class="rte-header-logo" alt="" aria-hidden="true" [src]="logoSrc()!" />
            }
            <span class="rte-header-app-name">{{ applicationName() }}</span>
          </a>
        } @else {
          <div class="rte-header-left-placeholder">
            <ng-content select="[rteHeaderLeft]"></ng-content>
          </div>
        }
      </div>
    }

    <div class="rte-header-mid">
      @if (shouldRenderMidSection()) {
        <nav class="rte-header-nav" [attr.aria-label]="navigationAriaLabel()">
          <ul class="rte-header-nav-list">
            @for (item of navigationItems(); track item.id || item.href) {
              <li
                class="rte-header-nav-item"
                [attr.data-disabled]="item.disabled"
                [attr.data-active]="item.active ?? null"
              >
                <a
                  class="rte-header-nav-link"
                  [href]="item.href"
                  [attr.aria-label]="item.ariaLabel"
                  [attr.aria-disabled]="item.disabled ? 'true' : null"
                  [attr.aria-current]="item.active ? 'page' : null"
                  [attr.tabindex]="item.disabled ? -1 : null"
                  (click)="handleNavigationItemClick(item, $event)"
                >
                  {{ item.label }}
                </a>
              </li>
            }
          </ul>
        </nav>
      }
    </div>

    @if (hasRightSection()) {
      <div class="rte-header-right">
        @if (isDesktop()) {
          @if (hasSearchbar()) {
            <rte-searchbar
              appearance="secondary"
              [id]="searchbarProps()?.id || 'rte-header-searchbar'"
              [label]="searchbarProps()?.label || 'Rechercher'"
              [disabled]="searchbarProps()?.disabled ?? false"
              [showResetButton]="searchbarProps()?.showResetButton ?? true"
              [value]="searchbarProps()?.value || ''"
              [assistiveText]="searchbarProps()?.assistiveText || ''"
              [compactSpacing]="isCompact()"
            />
          }

          @if (hasActionButton() && actionButton()) {
            <button
              rteButton
              type="button"
              [rteButtonSize]="'m'"
              [rteButtonVariant]="'primary'"
              [disabled]="actionButton()!.disabled ?? false"
              (click)="handleActionButtonClick()"
            >
              @if (actionButton()!.iconName) {
                <rte-icon class="rte-header-action-button-icon" size="m" [name]="actionButton()!.iconName!" />
              }
              {{ actionButton()!.label }}
            </button>
          }

          @if (hasIconButtons() && iconButtons()?.length) {
            <div class="rte-header-icon-buttons" role="group">
              @for (button of iconButtons()!; track button.id || button.ariaLabel) {
                <div class="rte-header-icon-button-wrapper">
                  @if (button.badge?.count) {
                    <rte-badge
                      badgeContent="number"
                      [badgeType]="button.badge?.type ?? 'indicator'"
                      [badgeSize]="button.badge?.size ?? 'l'"
                      [count]="button.badge?.count"
                    />
                  }
                  <rte-icon-button
                    size="m"
                    variant="neutral"
                    appearance="outlined"
                    [name]="button.iconName"
                    [ariaLabel]="button.ariaLabel"
                    [disabled]="button.disabled ?? false"
                    (clickEvent)="handleIconButtonClick(button)"
                  />
                </div>
              }
            </div>
          }

          @if (hasAvatar() && avatarProps()) {
            <rte-avatar
              [size]="avatarProps()!.size ?? 32"
              [imgSrc]="avatarProps()!.imgSrc"
              [alt]="avatarProps()!.alt ?? 'Avatar'"
              [initials]="avatarProps()!.initials"
              [isInteractive]="avatarProps()!.isInteractive ?? true"
              (avatarClick)="handleAvatarClick()"
            />
          }

          <div class="rte-header-right-slot">
            <ng-content select="[rteHeaderRight]"></ng-content>
          </div>
        } @else {
          <div class="rte-header-mobile-right" (keydown)="handleMobileSearchKeyDown($event)">
            @if (hasSearchbar()) {
              <div
                class="rte-header-mobile-search"
                [attr.data-active]="isSearchActive()"
                [style.--search-transition-ms]="mobileSearchTransitionMs"
              >
                @if (!isSearchActive()) {
                  <rte-icon-button
                    #mobileSearchButtonRef
                    size="m"
                    variant="neutral"
                    appearance="outlined"
                    name="search"
                    [ariaLabel]="mobileSearchButtonAriaLabel()"
                    (clickEvent)="openMobileSearch()"
                  />
                } @else {
                  <rte-searchbar
                    appearance="secondary"
                    [id]="searchbarProps()?.id || 'rte-header-searchbar'"
                    [label]="searchbarProps()?.label || 'Rechercher'"
                    [disabled]="searchbarProps()?.disabled ?? false"
                    [showResetButton]="searchbarProps()?.showResetButton ?? true"
                    [value]="searchbarProps()?.value || ''"
                    [assistiveText]="searchbarProps()?.assistiveText || ''"
                    [compactSpacing]="isCompact()"
                  />
                }
              </div>
            }

            <rte-icon-button
              size="m"
              variant="neutral"
              appearance="outlined"
              [name]="mobileMenuButton()?.iconName ?? 'menu'"
              [ariaLabel]="mobileMenuButton()?.ariaLabel ?? 'Menu'"
              [disabled]="mobileMenuButton()?.disabled ?? false"
              (clickEvent)="handleMobileMenuClick()"
            />
          </div>
        }
      </div>
    }
  </div>

  @if (shouldRenderSubheader()) {
    <div class="rte-header-subheader" [style.height.px]="subheaderHeightPx()">
      <nav class="rte-header-breadcrumbs" [attr.aria-label]="breadcrumbsAriaLabel()">
        <rte-breadcrumbs [items]="subHeaderConfig()?.items ?? []" [ariaLabel]="breadcrumbsAriaLabel()" />
      </nav>
    </div>
  }
</header>

// packages/react/src/components/header/Header.tsx
import {
  DropdownItemProps,
  HEADER_DEFAULT_BREADCRUMBS_ARIA_LABEL,
  HEADER_DEFAULT_NAV_ARIA_LABEL,
  HeaderActionButtonConfig,
  HeaderAvatarConfig,
  HeaderIconButtonConfig,
  HeaderNavigationItem,
  HeaderSubHeaderConfig,
} from "@design-system-rte/core";

import Avatar from "../avatar/Avatar";
import Breadcrumbs from "../breadcrumbs/Breadcrumbs";
import Button from "../button/Button";
import Divider from "../divider/Divider";
import IconButton from "../iconButton/IconButton";
import Searchbar from "../searchbar/Searchbar";

import styles from "./Header.module.scss";
import HeaderMobile from "./headerMobile/HeaderMobile";
import { useBreakpoints } from "./hooks/useBreakpoints";
import useHeaderScrollBehavior from "./hooks/useScrollBehavior";

interface HeaderProps {
  logoSrc?: string;
  applicationName?: string;
  compactSpacing?: boolean;
  hasLeftSection?: boolean;
  appearance?: "brand" | "neutral";
  hasRightSection?: boolean;
  leftSectionContent?: React.ReactNode;
  rightSectionContent?: React.ReactNode;
  hasDivider?: boolean;
  subHeaderConfig?: HeaderSubHeaderConfig;
  hasSearchbar?: boolean;
  searchbarProps?: React.ComponentProps<typeof Searchbar>;
  actionButton?: HeaderActionButtonConfig;
  iconButtons?: HeaderIconButtonConfig[];
  navigationAriaLabel?: string;
  navigationItems?: HeaderNavigationItem[];
  hasAvatar?: boolean;
  avatarProps?: HeaderAvatarConfig;
  onClickAvatar?: () => void;
  isSticky?: boolean;
  showAtScrollUp?: boolean;
  homeLink?: string;
  mobileSearchButtonAriaLabel?: string;
  onSearchActiveChange?: (isActive: boolean) => void;
  mobileMenuContent?: React.ReactNode;
  onMobileMenuClick?: () => void;
  isMobileMenuOpen?: boolean;
  mobileMenuItems?: DropdownItemProps[];
  onMobileMenuClose?: () => void;
  mobileMenuIconProps?: HeaderIconButtonConfig;
}

const Header = ({
  logoSrc,
  applicationName,
  leftSectionContent,
  hasLeftSection = true,
  hasRightSection = true,
  appearance = "brand",
  compactSpacing = false,
  rightSectionContent,
  hasDivider = false,
  subHeaderConfig,
  hasSearchbar = true,
  searchbarProps,
  actionButton,
  iconButtons,
  navigationAriaLabel = HEADER_DEFAULT_NAV_ARIA_LABEL,
  navigationItems = [],
  hasAvatar = true,
  avatarProps,
  onClickAvatar,
  isSticky = false,
  showAtScrollUp = false,
  homeLink = "/",
  mobileSearchButtonAriaLabel = "Rechercher",
  onSearchActiveChange,
  mobileMenuContent,
  onMobileMenuClick,
  isMobileMenuOpen = false,
  mobileMenuItems,
  onMobileMenuClose,
  mobileMenuIconProps,
}: HeaderProps) => {
  const { isMobile } = useBreakpoints();

  const hasIconButtons = iconButtons && iconButtons.length > 0;

  const hasMiddleSection = navigationItems && navigationItems.length > 0;

  const { isVisible } = useHeaderScrollBehavior({ isSticky, showAtScrollUp });

  const handleAvatarOnClick = () => {
    if (avatarProps?.isInteractive) {
      onClickAvatar?.();
    }
  };

  return (
    <header
      role="banner"
      className={styles["rte-header"]}
      data-compact={compactSpacing}
      data-appearance={appearance}
      data-sticky={isSticky}
      data-visible={isVisible}
    >
      <div className={styles["rte-header-main"]} data-compact={compactSpacing}>
        {isMobile ? (
          <HeaderMobile
            logoSrc={logoSrc}
            applicationName={applicationName}
            hasLeftSection={hasLeftSection}
            leftSectionContent={leftSectionContent}
            compactSpacing={compactSpacing}
            appearance={appearance}
            mobileSearchButtonAriaLabel={mobileSearchButtonAriaLabel}
            onSearchActiveChange={onSearchActiveChange}
            mobileMenuContent={mobileMenuContent}
            onMobileMenuClick={onMobileMenuClick}
            isMobileMenuOpen={isMobileMenuOpen}
            mobileMenuItems={mobileMenuItems}
            onMobileMenuClose={onMobileMenuClose}
            mobileMenuIconProps={mobileMenuIconProps}
          />
        ) : (
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%" }}>
            <div className={styles["rte-header-left"]}>
              {hasLeftSection ? (
                leftSectionContent || (
                  <a href={homeLink} className={styles["rte-header-home"]}>
                    {logoSrc && <img src={logoSrc} alt="Logo" className={styles["rte-header-logo"]} />}
                    {applicationName && <span className={styles["rte-header-app-name"]}>{applicationName}</span>}
                  </a>
                )
              ) : (
                <></>
              )}
            </div>
            {hasMiddleSection && (
              <div className={styles["rte-header-middle"]}>
                <div className={styles["rte-header-nav"]} aria-label={navigationAriaLabel}>
                  <ul className={styles["rte-header-nav-list"]}>
                    {navigationItems.map((item, index) => (
                      <li key={index} className={styles["rte-header-nav-item"]}>
                        <a
                          href={item.href}
                          aria-label={item.ariaLabel || item.label}
                          className={styles["rte-header-nav-link"]}
                          aria-disabled={item.disabled}
                          aria-current={item.active ? "page" : undefined}
                          tabIndex={item.disabled ? -1 : 0}
                        >
                          {item.label}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
            {hasRightSection && (
              <div className={styles["rte-header-right"]}>
                <div>
                  {hasSearchbar && (
                    <Searchbar
                      {...searchbarProps}
                      appearance={appearance === "brand" ? "primary" : "secondary"}
                      compactSpacing={compactSpacing}
                    />
                  )}
                </div>
                {actionButton && (
                  <Button
                    type="button"
                    label={actionButton.label}
                    icon={actionButton.iconName}
                    disabled={actionButton.disabled}
                    size={compactSpacing ? "s" : "m"}
                    variant={appearance === "brand" ? "primary" : "neutral"}
                  />
                )}
                {hasIconButtons && (
                  <div className={styles["rte-header-icon-buttons"]}>
                    {iconButtons.map((iconButton, index) => (
                      <div key={index} className={styles["rte-header-icon-button-wrapper"]}>
                        <IconButton
                          name={iconButton.iconName}
                          aria-label={iconButton.ariaLabel}
                          disabled={iconButton.disabled}
                          size={compactSpacing ? "m" : "l"}
                          variant={appearance === "brand" ? "text" : "neutral"}
                          badgeCount={iconButton.badge?.count}
                          badgeContent={iconButton.badge?.content}
                          badgeIcon={iconButton.badge?.icon}
                          badgeType={iconButton.badge?.badgeType}
                        />
                      </div>
                    ))}
                  </div>
                )}

                {hasAvatar && avatarProps && (
                  <Avatar
                    size={compactSpacing ? 24 : 32}
                    imgSrc={avatarProps.imgSrc}
                    alt={avatarProps.alt}
                    initials={avatarProps.initials}
                    onClick={handleAvatarOnClick}
                    colorType={avatarProps.colorType}
                    layout={avatarProps.layout}
                  />
                )}
                {rightSectionContent}
              </div>
            )}
          </div>
        )}
      </div>
      {hasDivider && <Divider />}

      <div className={styles["rte-header-subheader"]} data-is-compact={compactSpacing}>
        <nav
          className={styles["rte-header-breadcrumbs"]}
          aria-label={subHeaderConfig?.ariaLabel || HEADER_DEFAULT_BREADCRUMBS_ARIA_LABEL}
        >
          <Breadcrumbs
            items={subHeaderConfig?.items || []}
            aria-label={subHeaderConfig?.ariaLabel || HEADER_DEFAULT_BREADCRUMBS_ARIA_LABEL}
          />
        </nav>
      </div>
    </header>
  );
};

export default Header;
