// packages/angular/projects/ds-rte-lib/src/lib/components/card/card.component.ts
import { CommonModule } from "@angular/common";
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  output,
  signal,
  viewChild,
} from "@angular/core";
import {
  CARD_MISSING_ACCESSIBLE_NAME_ERROR,
  DEFAULT_CARD_WIDTH,
} from "@design-system-rte/core/components/card/card.constants";
import { CardType } from "@design-system-rte/core/components/card/card.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { logError } from "@design-system-rte/core/utils/log-handlers";

@Component({
  selector: "rte-card",
  imports: [CommonModule],
  templateUrl: "./card.component.html",
  styleUrl: "./card.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardComponent implements AfterViewInit {
  private readonly cardElement = viewChild<ElementRef<HTMLDivElement>>("cardElement");
  readonly shouldRender = signal(true);
  readonly width = input<string>(DEFAULT_CARD_WIDTH);
  readonly height = input<string>("auto");
  readonly cardType = input<CardType>("default");
  readonly clickable = input<boolean>(false);
  readonly disabled = input<boolean>(false);

  readonly ariaLabel = input<string | undefined>(undefined);
  readonly ariaLabelledby = input<string | undefined>(undefined);
  readonly ariaRole = input<string | undefined>(undefined);

  readonly cardClicked = output<void>();

  readonly tabIndex = computed(() => (this.clickable() && !this.disabled() ? 0 : -1));

  ngAfterViewInit(): void {
    const hasAccessibleName =
      !!this.ariaLabel() || !!this.ariaLabelledby() || !!this.cardElement()?.nativeElement.textContent?.trim();

    if (this.clickable() && !hasAccessibleName) {
      logError("Card", CARD_MISSING_ACCESSIBLE_NAME_ERROR);
      this.shouldRender.set(false);
    }
  }

  onClick(): void {
    if (!this.disabled() && this.clickable()) {
      this.cardClicked.emit();
    }
  }

  onKeyDown(event: KeyboardEvent): void {
    if (!this.disabled() && this.clickable()) {
      if ([ENTER_KEY, SPACE_KEY].includes(event.key)) {
        event.preventDefault();
        this.cardClicked.emit();
      }
    }
  }
}

@if (shouldRender()) {
  <div
    #cardElement
    class="card card-{{ cardType() }}"
    [style.width]="width()"
    [style.height]="height()"
    [attr.disabled]="disabled()"
    [attr.aria-label]="ariaLabel()"
    [attr.aria-labelledby]="ariaLabelledby()"
    [attr.role]="ariaRole() || (clickable() ? 'button' : null)"
    [ngClass]="{ clickable: clickable() }"
    [tabIndex]="tabIndex()"
    (click)="onClick()"
    (keydown)="onKeyDown($event)"
  >
    <ng-content />
  </div>
}

// packages/react/src/components/card/Card.tsx
import {
  CARD_MISSING_ACCESSIBLE_NAME_ERROR,
  DEFAULT_CARD_WIDTH,
} from "@design-system-rte/core/components/card/card.constants";
import { CardProps as CardPropsCore } from "@design-system-rte/core/components/card/card.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { logError } from "@design-system-rte/core/utils/log-handlers";
import { HTMLAttributes, forwardRef, useLayoutEffect, useRef, useState, KeyboardEvent } from "react";

import { useActiveKeyboard } from "../../hooks/useActiveKeyboard";

import styles from "./Card.module.scss";

interface CardProps extends CardPropsCore, Omit<HTMLAttributes<HTMLDivElement>, "onClick"> {
  onClick?: () => void;
}

const Card = forwardRef<HTMLDivElement, CardProps>(
  (
    {
      width = DEFAULT_CARD_WIDTH,
      height = "auto",
      cardType = "default",
      clickable = false,
      disabled = false,
      children,
      onClick,
      role,
      "aria-label": ariaLabel,
      "aria-labelledby": ariaLabelledby,
      ...props
    },
    ref,
  ) => {
    const cardRef = useRef<HTMLDivElement | null>(null);
    const [shouldRender, setShouldRender] = useState(true);

    useLayoutEffect(() => {
      if (clickable && !ariaLabel && !ariaLabelledby && !cardRef.current?.textContent?.trim()) {
        logError("Card", CARD_MISSING_ACCESSIBLE_NAME_ERROR);
        setShouldRender(false);
      }
    }, [ariaLabel, ariaLabelledby, clickable]);

    const keyboardHandler = (event: KeyboardEvent<HTMLDivElement>) => {
      if (!disabled && clickable && (event.key === SPACE_KEY || event.key === ENTER_KEY)) {
        event.preventDefault();
        onClick?.();
      }
    };

    const handleOnClick = () => {
      if (!disabled && clickable) {
        onClick?.();
      }
    };

    const { onKeyDown, onKeyUp, onBlur } = useActiveKeyboard<HTMLDivElement>(
      { onKeyUp: keyboardHandler },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY],
      },
    );

    if (!shouldRender) {
      return null;
    }

    return (
      <div
        ref={(element) => {
          cardRef.current = element;
          if (typeof ref === "function") {
            ref(element);
          } else if (ref) {
            ref.current = element;
          }
        }}
        className={styles.card}
        style={{ width, height }}
        data-card-type={cardType}
        data-clickable={clickable}
        data-disabled={disabled}
        tabIndex={clickable ? 0 : -1}
        role={role ?? (clickable ? "button" : undefined)}
        aria-label={ariaLabel}
        aria-labelledby={ariaLabelledby}
        onClick={handleOnClick}
        onKeyDown={onKeyDown}
        onKeyUp={onKeyUp}
        onBlur={onBlur}
        {...props}
      >
        {children}
      </div>
    );
  },
);

export default Card;
