// packages/react/src/components/requiredindicator/RequiredIndicator.tsx
import { REQUIREMENT_INDICATOR_VALUE } from "@design-system-rte/core/components/required-indicator/required-indicator.constant";

import styles from "./RequiredIndicator.module.scss";

interface RequiredIndicatorProps {
  required: boolean;
  showLabelRequirement: boolean;
}

const RequiredIndicator = ({ required, showLabelRequirement }: RequiredIndicatorProps) => {
  const computedRequirementIndicatorValue = required
    ? showLabelRequirement
      ? REQUIREMENT_INDICATOR_VALUE.required
      : REQUIREMENT_INDICATOR_VALUE.requiredIcon
    : REQUIREMENT_INDICATOR_VALUE.optional;

  return (
    <>
      {(showLabelRequirement || required) && (
        <span
          className={styles["requirement-indicator"]}
          data-required={required}
          data-show-label-requirement={showLabelRequirement}
          aria-hidden="true"
        >
          {computedRequirementIndicatorValue}
        </span>
      )}
    </>
  );
};

export default RequiredIndicator;

// preview/dsr-1037/angular/components/input/required-indicator/required-indicator.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, ChangeDetectionStrategy } from "@angular/core";
import { REQUIREMENT_INDICATOR_VALUE } from "@design-system-rte/core";

@Component({
  selector: "rte-required-indicator",
  imports: [CommonModule],
  standalone: true,
  templateUrl: "./required-indicator.component.html",
  styleUrl: "./required-indicator.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RequiredIndicatorComponent {
  readonly required = input<boolean>(false);
  readonly showLabelRequirement = input<boolean>(false);

  readonly requirementIndicatorValue = computed(() =>
    this.required()
      ? this.showLabelRequirement()
        ? REQUIREMENT_INDICATOR_VALUE.required
        : REQUIREMENT_INDICATOR_VALUE.requiredIcon
      : REQUIREMENT_INDICATOR_VALUE.optional,
  );
}
