// packages/react/src/components/modal/Modal.tsx
import { IconSize } from "@design-system-rte/core/components/icon/icon.constants";
import type { ModalProps as coreModalProps } from "@design-system-rte/core/components/modal/modal.interface";
import { forwardRef, useCallback, useState } from "react";

import useAnimatedMount from "../../hooks/useAnimatedMount";
import { useClickAway } from "../../hooks/useClickAway";
import { useFocusTrap } from "../../hooks/useFocusTrap";
import { useKeydownEscape } from "../../hooks/useKeydownEscape";
import Button from "../button/Button";
import Divider from "../divider/Divider";
import Icon from "../icon/Icon";
import IconButton from "../iconButton/IconButton";
import { Overlay } from "../overlay/Overlay";
import { concatClassNames } from "../utils";

import styles from "./Modal.module.scss";

type DSButtonElement = React.ReactElement<React.ComponentProps<typeof Button>, typeof Button>;

interface ModalProps extends coreModalProps, Omit<React.HTMLAttributes<HTMLDivElement>, "id" | "title"> {
  onClose: () => void;
  closeOnOverlayClick?: boolean;
  isOpen: boolean;
  children?: React.ReactNode | React.ReactNode[];
  primaryButton: DSButtonElement;
  secondaryButton?: DSButtonElement;
}

const Modal = forwardRef<HTMLDivElement, ModalProps>(
  (
    {
      id,
      isOpen,
      title,
      icon,
      iconAppearance,
      description,
      primaryButton,
      secondaryButton,
      size = "m",
      closeOnOverlayClick = true,
      onClose,
      className,
      children,
      ...props
    },
    ref,
  ) => {
    const { shouldRender, isAnimating } = useAnimatedMount(isOpen, 150);
    const [modalElement, setModalElement] = useState<HTMLDivElement | null>(null);

    const modalCallbackRef = useCallback(
      (node: HTMLDivElement | null) => {
        setModalElement(node);
        if (typeof ref === "function") ref(node);
        else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = node;
      },
      [ref],
    );

    useClickAway(closeOnOverlayClick ? onClose : () => {}, modalElement!);
    useKeydownEscape(onClose);
    useFocusTrap(modalElement!, shouldRender);

    return (
      <>
        {shouldRender && (
          <Overlay freezeNavigation={true}>
            <div className={styles["modal-backdrop"]} data-open={isAnimating}></div>
            <div
              ref={modalCallbackRef}
              className={concatClassNames(styles["modal-container"], className)}
              role="dialog"
              aria-modal="true"
              aria-labelledby={`${id}-modal-title`}
              aria-describedby={description ? `${id}-modal-desc` : props["aria-describedby"]}
              data-size={size}
              data-open={isAnimating}
            >
              <div className={styles["modal-header"]}>
                <div className={styles["modal-header-text"]}>
                  {icon && <Icon name={icon} size={IconSize["xl"]} appearance={iconAppearance} />}
                  <h2 id={`${id}-modal-title`} className={styles["modal-title"]}>
                    {title}
                  </h2>
                  <IconButton
                    data-testid="modal-close-button"
                    name="close"
                    size="l"
                    className={styles["close-icon"]}
                    variant="neutral"
                    onClick={onClose}
                    aria-label={`Close modal ${id}`}
                  />
                </div>
                <Divider />
              </div>
              {(description || children) && (
                <div className={styles["modal-content"]}>
                  <p className={styles["modal-content-description"]} id={`${id}-modal-desc`}>
                    {description}
                  </p>
                  {children}
                </div>
              )}
              <div className={styles["modal-footer"]}>
                {secondaryButton}
                {primaryButton}
              </div>
            </div>
          </Overlay>
        )}
      </>
    );
  },
);

export default Modal;

// packages/angular/projects/ds-rte-lib/src/lib/components/modal/modal.component.ts
import { CommonModule } from "@angular/common";
import {
  Component,
  ElementRef,
  input,
  TemplateRef,
  OnDestroy,
  viewChild,
  AfterViewInit,
  output,
  inject,
} from "@angular/core";

import { FocusTrapService } from "../../services/focus-trap.service";
import { ButtonComponent } from "../button/button.component";
import { DividerComponent } from "../divider/divider.component";
import { IconComponent } from "../icon/icon.component";
import { IconButtonComponent } from "../icon-button/icon-button.component";

@Component({
  selector: "rte-modal",
  imports: [CommonModule, IconButtonComponent, IconComponent, DividerComponent],
  standalone: true,
  templateUrl: "./modal.component.html",
  styleUrl: "./modal.component.scss",
})
export class ModalComponent implements AfterViewInit, OnDestroy {
  readonly id = input<string | undefined>();
  readonly icon = input<string | undefined>();
  readonly title = input<string>();
  readonly description = input<string>();
  readonly secondaryButtonLabel = input<string>();
  readonly isOpen = input<boolean>(false);
  readonly size = input<"xs" | "s" | "m" | "l" | "xl">("m");
  readonly ariaDescribedby = input<string | undefined>(undefined);

  readonly primaryButton = input<TemplateRef<ButtonComponent> | null>(null);
  readonly secondaryButton = input<TemplateRef<ButtonComponent> | null>(null);
  readonly customContent = input<TemplateRef<unknown> | null>(null);

  private readonly elementRef = viewChild<ElementRef<HTMLDivElement>>("modal");

  private focusTrap = inject(FocusTrapService);

  constructor() {}

  readonly close = output<void>();

  ngAfterViewInit() {
    const native = this.elementRef()?.nativeElement;
    if (native) {
      this.focusTrap.activate(native);
    }
  }

  ngOnDestroy() {
    this.focusTrap.deactivate();
  }

  onClose() {
    this.close.emit();
  }
}

<div class="rte-modal-wrapper">
  <div
    #modalWrapper
    class="rte-modal-backdrop"
    [attr.data-open]="isOpen()"
  ></div>
  <div
    #modal
    class="rte-modal-container"
    role="dialog"
    [attr.aria-modal]="true"
    [attr.aria-labelledby]="id() + '-modal-title'"
    [attr.aria-describedby]="
      description() ? id() + '-modal-desc' : ariaDescribedby()
    "
    [attr.data-size]="size()"
    [attr.data-open]="isOpen()"
  >
    <div class="rte-modal-header">
      <div class="rte-modal-header-text">
        <rte-icon
          *ngIf="icon()"
          [name]="icon() ?? ''"
          [size]="iconSize()"
          [appearance]="iconAppearance()"
        />
        <h2 class="rte-modal-title" [id]="id() + '-modal-title'">
          {{ title() }}
        </h2>
        <rte-icon-button
          data-testid="modal-close-button"
          name="close"
          size="l"
          class="close-icon"
          variant="neutral"
          [ariaLabel]="'Close modal ' + id()"
          (click)="onClose()"
        />
      </div>
      <rte-divider />
    </div>
    <div *ngIf="description()" class="rte-modal-content">
      <p class="rte-modal-content-description" [id]="id() + '-modal-desc'">
        {{ description() }}
      </p>
      <ng-container [ngTemplateOutlet]="customContent()"></ng-container>
    </div>
    <div class="rte-modal-footer">
      <ng-container [ngTemplateOutlet]="secondaryButton()"></ng-container>
      <ng-container [ngTemplateOutlet]="primaryButton()"></ng-container>
    </div>
  </div>
</div>
