// packages/react/src/components/divider/Divider.tsx
import { DividerProps } from "@design-system-rte/core/components/divider/divider.interface";
import { forwardRef } from "react";

import style from "./Divider.module.scss";

const Divider = forwardRef<HTMLDivElement, DividerProps>(
  ({ orientation = "horizontal", thickness = "light", appearance = "default", endPoint = "round", ...props }, ref) => {
    return orientation === "horizontal" ? (
      <hr
        ref={ref as React.Ref<HTMLHRElement>}
        className={style.horizontal}
        data-thickness={thickness}
        data-appearance={appearance}
        data-end-point={endPoint}
        {...props}
      />
    ) : (
      <div
        ref={ref as React.Ref<HTMLDivElement>}
        role="separator"
        className={style.vertical}
        data-thickness={thickness}
        data-appearance={appearance}
        data-end-point={endPoint}
        {...props}
      />
    );
  },
);

export default Divider;

// packages/angular/projects/ds-rte-lib/src/lib/components/divider/divider.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import { DividerProps } from "@design-system-rte/core/components/divider/divider.interface";

@Component({
  selector: "rte-divider",
  imports: [CommonModule],
  templateUrl: "./divider.component.html",
  styleUrl: "./divider.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DividerComponent {
  readonly orientation = input<DividerProps["orientation"]>("horizontal");
  readonly thickness = input<DividerProps["thickness"]>("light");
  readonly appearance = input<DividerProps["appearance"]>("default");
  readonly endPoint = input<DividerProps["endPoint"]>("round");

  readonly isHorizontal = computed(() => this.orientation() === "horizontal");
}

<hr *ngIf="isHorizontal()" class="horizontal {{thickness()}} {{color()}}" />
<div *ngIf="!isHorizontal()" class="vertical {{thickness()}} {{color()}}" role="separator"></div>
