// packages/react/src/components/tooltip/Tooltip.tsx
import { TooltipProps as CoreTooltipProps } from "@design-system-rte/core/components/tooltip/tooltip.interface";
import { getAutoPlacement } from "@design-system-rte/core/components/utils/auto-placement";
import { forwardRef } from "react";

import { concatClassNames } from "../utils";

import style from "./Tooltip.module.scss";

interface TooltipProps extends CoreTooltipProps, Omit<React.HTMLAttributes<HTMLDivElement>, "children"> {
  children: React.ReactNode;
}

const Tooltip = forwardRef<HTMLDivElement, TooltipProps>(
  ({ children, position = "top", alignment = "center", label, arrow = true, className = "", ...props }, ref) => {
    const tooltipRef = (node: HTMLDivElement) => {
      if (ref && typeof ref === "function") {
        ref(node);
      } else if (ref) {
        (ref as React.MutableRefObject<HTMLDivElement | null>).current = node;
      }

      if (node && position === "auto") {
        const tooltipLabel = node.querySelector("[role='tooltip']");
        const autoPosition = getAutoPlacement(node, tooltipLabel!, "top");
        node.setAttribute("data-position", autoPosition);
      }
    };

    return (
      <div
        ref={tooltipRef}
        className={concatClassNames(style.tooltip, className)}
        data-position={position === "auto" ? undefined : position}
        data-alignment={alignment}
        data-arrow={arrow}
        {...props}
      >
        {label && (
          <span role="tooltip" className={style.tooltipLabel}>
            {label}
          </span>
        )}
        {children}
      </div>
    );
  },
);

export default Tooltip;

// packages/angular/src/components/tooltip/tooltip.component.ts
import { Component, input, ContentChild, ElementRef} from "@angular/core";
import { CommonModule } from "@angular/common";

import {getAutoPlacement} from "../../../../core/components/utils/auto-placement";

@Component({
  selector: 'rte-tooltip',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './tooltip.component.html',
  styleUrls: ['./tooltip.component.scss'],
})

export class TooltipComponent {

    label = input.required<string>();
    position = input('auto');
    alignment = input('center');
    arrow = input(true);

}
<div class="tooltip"
    [ngClass]="{ 'top': position() === 'top', 'bottom': position() === 'bottom', 'left': position() === 'left', 'right': position() === 'right', 'start':alignment() === 'start', 'end': alignment() === 'end', 'center': alignment() === 'center', 'no-arrow': !arrow() }">
    <ng-content />
    <span class="tooltip-label"> {{label()}} </span>
    {{position()}}
</div>
