// packages/react/src/components/checkbox/Checkbox.tsx
import { CheckboxProps as CoreCheckboxProps } from "@design-system-rte/core/components/checkbox/checkbox.interface";
import { useEffect, useRef } from "react";

import Icon from "../icon/Icon";

import styles from "./Checkbox.module.scss";

interface CheckboxProps extends CoreCheckboxProps, Omit<React.InputHTMLAttributes<HTMLInputElement>, "id"> {}

const Checkbox = ({
  id,
  label,
  showLabel,
  disabled,
  description,
  error,
  errorMessage,
  readOnly,
  indeterminate,
  ...props
}: CheckboxProps) => {
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = !!indeterminate;
    }
  }, [indeterminate]);

  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.code === "Space") {
      if (readOnly) {
        event.preventDefault();
      }
    }
  };
  return (
    <div className={styles["container"]}>
      <input
        type="checkbox"
        id={id}
        className={styles["checkbox"]}
        disabled={disabled}
        ref={inputRef}
        data-read-only={readOnly}
        data-error={!!error}
        onKeyDown={handleKeyDown}
        {...props}
      />
      <div className={`${styles["checkbox-icon-selected"]} ${styles["checkbox-icons"]}`}>
        <Icon name="check-small" size={16} />
      </div>
      <div className={`${styles["checkbox-icon-indeterminated"]} ${styles["checkbox-icons"]}`}>
        <Icon name="check-indeterminate" size={16} />
      </div>
      <div className={styles["checkbox-text-container"]} data-disabled={disabled}>
        {showLabel && <label htmlFor={id}>{label}</label>}
        <p className={styles["checkbox-description"]}>{description}</p>
        {error && errorMessage && <p className={styles["checkbox-error"]}>{errorMessage}</p>}
      </div>
    </div>
  );
};

export default Checkbox;

// preview/main/angular/components/checkbox/checkbox.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, effect, input, output, signal } from "@angular/core";

import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-checkbox",
  imports: [CommonModule, IconComponent],
  templateUrl: "./checkbox.component.html",
  styleUrl: "./checkbox.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxComponent {
  readonly id = input.required<string>();
  readonly label = input.required<string>();
  readonly value = input("");
  readonly indeterminate = input(false);
  readonly description = input("");
  readonly showLabel = input(true);
  readonly disabled = input(false);
  readonly error = input(false);
  readonly errorMessage = input("");
  readonly readOnly = input(false);
  readonly checked = input(false);
  readonly tabindex = input<string | number | undefined>(undefined);
  readonly ariaLabel = input<string | undefined>(undefined);

  readonly checkedChange = output<boolean>();

  readonly internalChecked = signal<boolean>(false);

  constructor() {
    effect(() => {
      this.internalChecked.set(this.checked());
    });
  }

  onClick(event: MouseEvent) {
    if (this.readOnly()) {
      event.preventDefault();
      event.stopPropagation();
    }
  }

  onChange(event: Event) {
    if (this.readOnly() || this.disabled()) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    const inputElement = event.target as HTMLInputElement | null;
    const isChecked = !!inputElement?.checked;
    this.internalChecked.set(isChecked);
    this.checkedChange.emit(isChecked);
  }

  onKeydown(event: KeyboardEvent) {
    if (event.code === "Space") {
      if (this.readOnly()) {
        event.preventDefault();
      }
    }
  }
}

    <div class="rte-checkbox-container">
        <input
            type="checkbox"
            class="rte-checkbox"
            [id]="id()"
            [value]="value()"
            [ngClass]="{'error': error(), 'read-only': readOnly()}"
            [disabled]="disabled()"
            [indeterminate]="indeterminate()"
            [checked]="checked()"
            (keydown)="onKeydown($event)"
        />
            <rte-icon class="rte-checkbox-icons rte-checkbox-icon-selected" name="check-small" [size]="16"/> 
            <rte-icon class="rte-checkbox-icons rte-checkbox-icon-indeterminated" name="check-indeterminate" [size]="16" /> 
        <div class="rte-checkbox-text-container">
            <label 
            *ngIf="showLabel()" 
            class="rte-checkbox-label" 
            [for]="id()"
            [ngClass]="{
                'error': error(),
                'read-only': readOnly(),
                'disabled': disabled()
            }"
            >
                {{ label() }}
            </label>
            <p class="rte-checkbox-description">{{ description() }}</p>
            <p *ngIf="error() && errorMessage()" class="rte-checkbox-error">{{ errorMessage() }}</p>
        </div>
    </div>
