// packages/react/src/components/toast/Toast.tsx
import { generateId } from "@design-system-rte/core";
import { IconSize, IconTypeMap } from "@design-system-rte/core/components/icon/icon.constants";
import { ToastProps as coreToastProps } from "@design-system-rte/core/components/toast/toast.interface";
import { forwardRef, MouseEventHandler, useCallback, useEffect, useState } from "react";

import useAnimatedMount from "../../hooks/useAnimatedMount";
import Button from "../button/Button";
import Icon from "../icon/Icon";
import { isValidIconName } from "../icon/IconMap";
import IconButton from "../iconButton/IconButton";
import { Overlay } from "../overlay/Overlay";
import { concatClassNames } from "../utils";

import useHandleQueueChanges from "./hooks/useHandleQueueChanges";
import useHandleTimer from "./hooks/useHandleTimer";
import styles from "./Toast.module.scss";
import useToastQueueContext from "./toastQueue/useToastQueueContext";

interface ToastProps extends coreToastProps, React.HTMLAttributes<HTMLDivElement> {
  showActionButton?: boolean;
}

const Toast = forwardRef<HTMLDivElement, ToastProps>(
  (
    {
      id,
      message,
      type = "error",
      closable = false,
      placement = "bottom-right",
      isOpen = true,
      autoDismiss = true,
      actionButtonLabel,
      onActionButtonClick,
      duration = "medium",
      onClose,
      iconName,
      showLeftIcon = true,
      showActionButton = true,
      ...props
    },
    ref,
  ) => {
    const hasActionButton = !!actionButtonLabel && showActionButton;

    const isAutoDismiss = autoDismiss && !hasActionButton;

    const [internalId] = useState<string>(id || generateId());

    const { isInternalOpen, hideToast } = useHandleQueueChanges(internalId, isOpen);
    const { addToQueue, removeFromQueue } = useToastQueueContext();
    const { shouldRender, isAnimating } = useAnimatedMount(isInternalOpen, 300);
    const { initializeTimer, removeTimer } = useHandleTimer(
      { shouldStartTimer: isAutoDismiss && isInternalOpen, duration },
      () => {
        handleOnClose();
      },
    );

    const [position, alignment] = placement.split("-");

    const handleOnClose = useCallback(() => {
      hideToast();
      removeTimer();
      removeFromQueue(internalId);
      onClose?.();
    }, [hideToast, removeTimer, removeFromQueue, internalId, onClose]);

    useEffect(() => {
      if (isOpen) {
        addToQueue({ id: internalId, hasActionButton: hasActionButton, type });
      } else {
        handleOnClose();
      }
    }, [isOpen, hasActionButton, type, isAutoDismiss, internalId, addToQueue, handleOnClose]);

    const handleOnClickCloseButton = () => {
      handleOnClose();
    };

    const handleOnMouseHover: MouseEventHandler<HTMLDivElement> = (e) => {
      e.stopPropagation();
      if (isAutoDismiss && isOpen) {
        removeTimer();
      }
    };

    const handleOnMouseOut: MouseEventHandler<HTMLDivElement> = (e) => {
      e.stopPropagation();
      if (isAutoDismiss) {
        initializeTimer();
      }
    };

    const displayDefaultIcon = showLeftIcon && type !== "neutral";
    const displayCustomIcon = showLeftIcon && iconName && isValidIconName(iconName);

    return (
      shouldRender && (
        <Overlay>
          <div
            role="status"
            className={concatClassNames(styles["toast"], props.className)}
            data-type={type}
            data-position={position}
            data-alignment={alignment}
            data-open={isAnimating || undefined}
            ref={ref}
            onMouseOver={handleOnMouseHover}
            onMouseOut={handleOnMouseOut}
            {...props}
          >
            <div className={styles["toast-content"]}>
              {displayDefaultIcon ? (
                <Icon
                  name={IconTypeMap[type]}
                  size={IconSize["xl"]}
                  className={styles["toast-icon"]}
                  aria-hidden="true"
                />
              ) : (
                displayCustomIcon && (
                  <Icon name={iconName} size={IconSize["xl"]} className={styles["toast-icon"]} aria-hidden="true" />
                )
              )}
              <span className={styles["toast-message"]}>{message}</span>
            </div>
            {hasActionButton && (
              <Button
                variant={type === "neutral" ? "reverse" : "transparent"}
                onClick={onActionButtonClick}
                label={actionButtonLabel}
              />
            )}
            {closable && (
              <IconButton
                data-testid="toast-close-button"
                name="close"
                variant={type === "neutral" ? "reverse" : "neutral"}
                onClick={handleOnClickCloseButton}
              />
            )}
          </div>
        </Overlay>
      )
    );
  },
);

export default Toast;

// packages/angular/projects/ds-rte-lib/src/lib/components/toast/toast.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, computed, signal, output } from "@angular/core";
import { IconSize, IconTypeMap } from "@design-system-rte/core/components/icon/icon.constants";
import { ToastProps, ToastType } from "@design-system-rte/core/components/toast/toast.interface";

import { ButtonComponent } from "../button/button.component";
import { IconComponent } from "../icon/icon.component";
import { IconButtonComponent } from "../icon-button/icon-button.component";

@Component({
  selector: "rte-toast",
  imports: [CommonModule, IconComponent, IconButtonComponent, ButtonComponent],
  standalone: true,
  templateUrl: "./toast.component.html",
  styleUrl: "./toast.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToastComponent {
  readonly id = input<string>("");
  readonly message = input<string>("");
  readonly type = input<ToastType>("info");
  readonly duration = input<ToastProps["duration"]>("medium");
  readonly isOpen = input<boolean>(false);
  readonly placement = input<ToastProps["placement"]>("bottom-right");
  readonly closable = input<ToastProps["closable"]>(true);
  readonly autoDismiss = input<ToastProps["autoDismiss"]>(true);
  readonly showActionButton = input<ToastProps["showActionButton"]>(true);
  readonly iconName = input<ToastProps["iconName"]>("");
  readonly showLeftIcon = input<ToastProps["showLeftIcon"]>(true);

  readonly actionButtonLabel = input<ToastProps["actionButtonLabel"]>("");
  readonly onActionButtonClick = input<ToastProps["onActionButtonClick"]>(() => {});

  readonly close = output<void>();

  readonly displayCustomIcon = computed(() => {
    console.log("iconName", this.iconName());
    return this.showLeftIcon() && !!this.iconName();
  });

  readonly displayLeftIcon = computed(() => {
    return this.showLeftIcon() && IconTypeMap[this.type()];
  });

  readonly displayActionButton = computed(() => {
    return this.showActionButton() && this.actionButtonLabel() && !!this.onActionButtonClick();
  });

  onClickActionButton(): void {
    const action = this.onActionButtonClick();
    if (action) {
      action();
    }
  }

  clickCloseButton(): void {
    this.close.emit();
  }

  readonly position = computed(() => this.placement()?.split("-")[0]);
  readonly alignment = computed(() => this.placement()?.split("-")[1]);

  readonly visible = signal(false);

  readonly defaultIconName = computed(() => IconTypeMap[this.type()]);
  readonly iconSize = IconSize["xl"];
}

<div
  class="rte-toast {{ type() }} {{ position() }} {{ alignment() }}"
  role="status"
  ref="{ref}"
  [ngClass]="{ open: isOpen(), close: !isOpen() }"
>
  <div class="rte-toast-content">
    <rte-icon
      class="rte-toast-icon"
      aria-hidden="true"
      [name]="defaultIconName()"
      [size]="iconSize"
    />
    <span class="rte-toast-message">{{ message() }}</span>
  </div>
  @if (showActionButton() && actionButtonLabel() && onActionButtonClick()) {
    <button
      rteButton
      rteButtonVariant="text"
      class="rte-toast-action-button"
      (click)="onClickActionButton()"
    >
      {{ actionButtonLabel() }}
    </button>
  }
  @if (closable()) {
    <rte-icon-button
      name="close"
      [attr.data-testid]="'toast-close-button'"
      [variant]="type() === 'neutral' ? 'reverse' : 'neutral'"
      (click)="clickCloseButton()"
    />
  }
</div>
