// packages/react/src/components/button/Button.tsx
import { forwardRef } from 'react';

import { ButtonProps as CoreButtonProps } from '@design-system-rte/core/components/button/button.interface';
import { IconKeys } from '@design-system-rte/core/components/icon/icon.interface';
import { buttonIconSize } from '@design-system-rte/core/components/button/button.constants';
import style from './Button.module.scss';
import { concatClassNames } from '../utils';
import Icon from '../icon/Icon';

interface ButtonProps
  extends Omit<CoreButtonProps, 'disabled'>,
    Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onClick'> {
  icon?: IconKeys;
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      size = 'm',
      label,
      variant = 'primary',
      className = '',
      icon,
      iconPosition = 'left',
      onClick,
      type = 'button',
      ...props
    },
    ref,
  ) => {
    return (
      <button
        ref={ref}
        type={type}
        className={concatClassNames(style.button, className)}
        data-size={size}
        data-variant={variant}
        onClick={onClick}
        {...props}
      >
        {icon && iconPosition === 'left' && <Icon name={icon} size={buttonIconSize[size]} />}
        <span data-size={size} className={style.label}>
          {label}
        </span>
        {icon && iconPosition === 'right' && <Icon name={icon} size={buttonIconSize[size]} />}
      </button>
    );
  },
);

export default Button;

// packages/angular/projects/ds-rte-lib/src/lib/components/button/button.component.ts
import { Component, input, output } from '@angular/core';

import { ButtonSize, ButtonVariant } from '@design-system-rte/core/components/button/button.interface';


@Component({
  selector: "rte-button",
  imports: [],
  standalone: true,
  templateUrl: "./button.component.html",
  styleUrl: "./button.component.scss",
})
export class ButtonComponent {
  label = input("");
  variant = input<ButtonVariant>("primary");
  size = input<ButtonSize>("m");
  disabled = input(false);
  icon = input<string>('');

  click = output<void>();

  onClick(event: MouseEvent | KeyboardEvent): void {
    event.stopPropagation();
    this.click.emit();
  }
}

<button
    class="rte-button {{ variant() }} size-{{ size() }}"
    [disabled]="disabled()"
    (click)="onClick($event)"
>
    <span class="rte-button-label">{{ label() }}</span>
    <ng-container *ngIf="icon()">
        <ds-icon name="add_circle_filled"></ds-icon>
    </ng-container>
</button>
<ds-icon name="add_circle_filled"></ds-icon>
