// packages/react/src/components/radioButton/RadioButton.tsx
import { labelSize } from "@design-system-rte/core/components/radio-button/radio-button.constants";
import { RadioButtonProps as CoreRadioButtonProps } from "@design-system-rte/core/components/radio-button/radio-button.interface";
import React, { forwardRef } from "react";

import { concatClassNames } from "../utils";

import style from "./RadioButton.module.scss";

interface RadioButtonProps extends CoreRadioButtonProps, React.InputHTMLAttributes<HTMLInputElement> {}

const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
  (
    { label, groupName, showLabel = true, disabled = false, error = false, readOnly = false, className = "", ...props },
    ref,
  ) => {
    if (disabled && error) {
      return;
    }

    return (
      <div className={style.radioButtonContainer}>
        <input
          ref={ref}
          type="radio"
          id={label}
          value={label}
          size={labelSize}
          name={groupName}
          className={concatClassNames(style.radioButton, className)}
          disabled={disabled}
          data-error={error}
          data-read-only={readOnly}
          {...props}
        />
        {showLabel && (
          <label
            htmlFor={label}
            className={concatClassNames(style.radioButtonLabel, className)}
            data-disabled={disabled}
            data-error={error}
            data-read-only={readOnly}
            data-show-label={showLabel}
          >
            {label}
          </label>
        )}
      </div>
    );
  },
);

export default RadioButton;

// packages/angular/src/components/radioButton/radioButton.component.ts
import { Component,input } from "@angular/core";
import { labelSize } from "@design-system-rte/core/components/radio-button/radio-button.constants";
import { CommonModule } from "@angular/common";

@Component({
  selector: 'rte-radio-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './radioButton.component.html',
  styleUrl: './radioButton.component.scss',
})

export class RadioButtonComponent {
    label = input('');
    groupName = input('');
    showLabel = input(true);
    disabled = input(false);
    error = input(false);
    readOnly = input(false);
    labelSize = labelSize;
    }
    <div *ngIf="!disabled() || !error()" class="rte-radio-button-container">
        <input
            type="radio"
            [id]="label()"
            [value]="label()"
            [size]="labelSize"
            [name]="groupName()"
            class="
                rte-radio-button 
                {{ error() ? 'error' : '' }} 
                {{ readOnly() ? 'read-only' : '' }} 
                "
            [disabled]="disabled()"
        />
        <label 
            *ngIf="showLabel()" 
            [for]="label()" 
            class="
                rte-radio-button-label
                {{ disabled() ? 'disabled' : '' }}
                {{ error() ? 'error' : '' }} 
                {{ readOnly() ? 'read-only' : '' }} 
                "
        >
            {{ label() }}
        </label>
    </div>
