// packages/angular/projects/ds-rte-lib/src/lib/components/text-input/base-text-input/base-text-input.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, output, signal, computed, effect } from "@angular/core";

import { IconComponent } from "../../icon/icon.component";
import { RegularIconIdKey, TogglableIconIdKey } from "../../icon/icon.service";
import { IconButtonComponent } from "../../icon-button/icon-button.component";
import { LinkComponent } from "../../link/link.component";

@Component({
  selector: "rte-base-text-input",
  imports: [CommonModule, IconComponent, IconButtonComponent, LinkComponent],
  standalone: true,
  templateUrl: "./base-text-input.component.html",
  styleUrl: "./base-text-input.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BaseTextInputComponent {
  readonly id = input<string>();
  readonly label = input<string>("");
  readonly labelPosition = input<"top" | "side">("top");
  readonly placeholder = input<string>("");
  readonly required = input<boolean>(false);
  readonly showCounter = input<boolean>(false);
  readonly value = input<string>("");
  readonly internalValue = signal<string>(this.value());
  readonly leftIcon = input<RegularIconIdKey | TogglableIconIdKey | null>(null);
  readonly showRightIcon = input<boolean>(true);
  readonly rightIconAction = input<"clean" | "visibilityOn" | "visibilityOff">("clean");
  readonly showLabelRequirement = input<boolean>(false);
  readonly assistiveAppearance = input<"description" | "error" | "success" | "link">("description");
  readonly showAssistiveIcon = input<boolean>(false);
  readonly assistiveTextLabel = input<string>("");
  readonly error = input<boolean>(false);
  readonly maxLength = input<number>(150);
  readonly disabled = input<boolean>(false);
  readonly readOnly = input<boolean>(false);
  readonly width = input<string>("300px");
  readonly ariaLabel = input<string>("");
  readonly ariaRequired = input<boolean>(false);
  readonly ariaLabelledby = input<string>("");
  readonly compactSpacing = input<boolean>(false);
  readonly customStyle = input<Record<string, string>>();
  readonly autocomplete = input<string>("");

  readonly valueChange = output<string>();
  readonly rightIconClick = output<void>();

  readonly characterCount = signal<number>(this.internalValue().length);
  readonly isHiddenInput = signal<boolean>(this.showRightIcon() && this.rightIconAction() === "visibilityOn");
  readonly displayedLeftIcon = computed(() => (this.error() ? "error" : this.leftIcon()));

  readonly displayCounter = computed(() => this.showCounter() && typeof this.maxLength() === "number");

  readonly rightIconName = computed(() => {
    if (["visibilityOn", "visibilityOff"].includes(this.rightIconAction())) {
      return this.isHiddenInput() ? "visibility-show" : "visibility-hide";
    }
    return "cancel";
  });

  readonly rightIconAriaLabel = computed(() => {
    if (["visibilityOn", "visibilityOff"].includes(this.rightIconAction())) {
      return this.isHiddenInput() ? "show text" : "hide text";
    } else if (this.rightIconAction() === "clean") {
      return "clear";
    }
    return "";
  });

  readonly shouldShowRightIcon = computed(() => {
    if (this.readOnly() || this.disabled()) {
      return false;
    }
    if (this.rightIconAction() === "clean") {
      return !!this.internalValue()?.length && this.showRightIcon();
    }
    return this.showRightIcon() && !!this.rightIconAction();
  });

  private lastParentValue = this.value();

  constructor() {
    effect(
      () => {
        const parentValue = this.value();
        if (parentValue !== this.lastParentValue) {
          this.lastParentValue = parentValue;
          this.internalValue.set(parentValue);
        }
      },
      { allowSignalWrites: true },
    );
  }

  handleChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    const newValue = input.value;
    this.internalValue.set(newValue);
    if (this.maxLength()) {
      this.characterCount.set(newValue.length);
    }
    this.valueChange.emit(newValue);
  }

  onRightIconClickHandler(): void {
    this.rightIconClick.emit();
    this.triggerRightIconAction();
  }

  private toggleInputVisibility(): void {
    this.isHiddenInput.set(!this.isHiddenInput());
  }

  private triggerRightIconAction(): void {
    if (this.rightIconAction() === "clean") {
      this.internalValue.set("");
      this.valueChange.emit("");
      this.characterCount.set(0);
    }
    if (["visibilityOn", "visibilityOff"].includes(this.rightIconAction())) {
      this.toggleInputVisibility();
    }
  }
}

<div
  class="container {{labelPosition()}}"
  [ngClass]="{'error': error(), 'compact-spacing': compactSpacing()}"
  [style.width]="width()"
>
  <ng-container *ngIf="label()">
    <div class="text">
      <div class="label-container">
        <label class="input-label" [id]="'input-label-' + id" [for]="id()">
          {{ label() }}
        </label>
        <ng-container *ngIf="required()">
          <ng-container *ngIf="showLabelRequirement(); else requiredIcon">
            <span class="required-text">(obligatoire)</span>
          </ng-container>
          <ng-template #requiredIcon>
            <span class="required-icon-container">
              <rte-icon name="asterisk" [size]="8" />
            </span>
          </ng-template>
        </ng-container>
        <ng-container *ngIf="!required() && showLabelRequirement()">
          <span class="required-text">(optionnel)</span>
        </ng-container>
      </div>
      <ng-container *ngIf="displayCounter() && labelPosition() === 'top'">
        <p class="input-counter" data-testid="input-counter">
          {{ characterCount() }}/{{ maxLength() }}
        </p>
      </ng-container>
    </div>
  </ng-container>

  <div class="input-container">
    <div
      class="input {{labelPosition()}}"
      [ngClass]="{'disabled': disabled(), 'read-only': readOnly()}"
    >
      <div class="input-bar" [ngClass]="{'with-left-icon': displayedLeftIcon(), 'with-right-icon': rightIconAction()}">
        <ng-container *ngIf="displayedLeftIcon()">
          <rte-icon
            appearance="outlined"
            class="left-icon"
            aria-hidden="true"
            [name]="displayedLeftIcon()!"
          />
        </ng-container>

        <input
          #inputRef
          class="input-field"
          [id]="id()"
          [ngClass]="{'error': error()}"
          [ngStyle]="customStyle()"
          [attr.aria-label]="ariaLabel()"
          [attr.aria-labelledby]="ariaLabelledby()"
          [attr.aria-required]="ariaRequired()"
          [type]="isHiddenInput() ? 'password' : 'text'"
          [maxLength]="maxLength()"
          [disabled]="disabled()"
          [readOnly]="readOnly()"
          [value]="internalValue()"
          [placeholder]="placeholder()"
          [attr.autocomplete]="autocomplete()"
          (input)="handleChange($event)"
        />

        <ng-container *ngIf="shouldShowRightIcon()">
          <rte-icon-button
            appearance="outlined"
            variant="neutral"
            size="s"
            class="right-icon"
            data-testid="right-icon"
            [compactSpacing]="true"
            [name]="rightIconName()"
            [ariaLabel]="rightIconAriaLabel()"
            (clickEvent)="onRightIconClickHandler()"
          />
        </ng-container>
      </div>
    </div>

    <ng-container *ngIf="assistiveTextLabel()">
      <div class="assistive-text">
        <ng-container *ngIf="showAssistiveIcon() && assistiveAppearance() === 'error'">
          <rte-icon name="error" appearance="outlined" class="assistive-icon-error" [size]="12" />
        </ng-container>
        <ng-container *ngIf="showAssistiveIcon() && assistiveAppearance() === 'success'">
          <rte-icon name="check" appearance="outlined" class="assistive-icon-success" [size]="12" />
        </ng-container>
        <ng-container *ngIf="assistiveAppearance() === 'link'; else assistiveLabel">
          <rte-link [label]="assistiveTextLabel()" />
        </ng-container>
        <ng-template #assistiveLabel>
          <p class="assistive-label" [ngClass]="assistiveAppearance()">
            {{ assistiveTextLabel() }}
          </p>
        </ng-template>
      </div>
    </ng-container>
  </div>

  <ng-container *ngIf="displayCounter() && labelPosition() === 'side'">
    <p class="input-counter" data-testid="input-counter">
      {{ characterCount() }}/{{ maxLength() }}
    </p>
  </ng-container>
</div>

// packages/react/src/components/textInput/baseTextInput/BaseTextInput.tsx
import {
  BaseTextInputProps as CoreTextInputProps,
  RightIconAction,
  RightIconName,
} from "@design-system-rte/core/components/text-input/text-input.interface";
import {
  ChangeEvent,
  CSSProperties,
  forwardRef,
  InputHTMLAttributes,
  ReactNode,
  useEffect,
  useRef,
  useState,
} from "react";

import AssistiveText from "../../assistivetext/AssistiveText";
import Icon from "../../icon/Icon";
import IconButton from "../../iconButton/IconButton";
import Label from "../../label/Label";
import { concatClassNames } from "../../utils";

import style from "./BaseTextInput.module.scss";

interface BaseTextInputProps
  extends
    CoreTextInputProps,
    Omit<InputHTMLAttributes<HTMLInputElement>, "id" | "onChange" | "value" | "defaultValue" | "placeholder"> {
  onChange?: (value: string) => void;
  rightSlot?: ReactNode;
  inputStyle?: CSSProperties;
  highlighted?: boolean;
  onEnterKeyDown?: (value: string) => void;
}

const BaseTextInput = forwardRef<HTMLInputElement, BaseTextInputProps>(
  (
    {
      id,
      label,
      labelPosition = "top",
      required = false,
      showCounter,
      value,
      leftIcon,
      showRightIcon = true,
      rightIconAction = "clean",
      showLabelRequirement = false,
      assistiveAppearance = "description",
      showAssistiveIcon = false,
      assistiveTextLabel = "",
      error = false,
      maxLength,
      disabled,
      readOnly,
      width,
      onChange,
      onRightIconClick,
      compactSpacing,
      placeholder,
      rightSlot,
      highlighted,
      onEnterKeyDown,
      ...props
    }: BaseTextInputProps,
    ref,
  ) => {
    const inputRef = useRef<HTMLInputElement | null>(null);

    const getRightIconName = (rightIconActionType: RightIconAction): RightIconName => {
      if (["visibilityOn", "visibilityOff"].includes(rightIconActionType)) {
        return isHiddenInput ? "visibility-show" : "visibility-hide";
      } else if (rightIconActionType === "clean") {
        return "cancel";
      }
      return "" as RightIconName;
    };

    const getRightIconAriaLabel = (rightIconActionType: RightIconAction): string => {
      if (["visibilityOn", "visibilityOff"].includes(rightIconActionType)) {
        return isHiddenInput ? "show text" : "hide text";
      } else if (rightIconActionType === "clean") {
        return "clear";
      }
      return "";
    };

    const [inputValue, setInputValue] = useState(value ?? "");
    const [characterCount, setCharacterCount] = useState(inputValue.length);
    const [isHiddenInput, setIsHiddenInput] = useState(!!showRightIcon && rightIconAction === "visibilityOn");

    useEffect(() => {
      if (value !== undefined) {
        setInputValue(value);
        setCharacterCount(value.length);
      }
    }, [value]);

    useEffect(() => {
      setIsHiddenInput(!!showRightIcon && rightIconAction === "visibilityOn");
    }, [showRightIcon, rightIconAction]);

    const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
      const newValue = event.target.value;
      setInputValue(newValue);
      setCharacterCount(newValue.length);
      if (onChange) {
        onChange(newValue);
      }
    };

    const triggerRightIconAction = () => {
      if (rightIconAction === "clean") {
        setInputValue("");
        setCharacterCount(0);
        if (onChange) {
          onChange("");
        }
      }
      if (["visibilityOn", "visibilityOff"].includes(rightIconAction)) {
        toggleInputVisibility();
      }
    };

    const onRightIconClickHandler = () => {
      if (onRightIconClick) {
        onRightIconClick();
      }
      triggerRightIconAction();
    };

    const toggleInputVisibility = () => {
      setIsHiddenInput(!isHiddenInput);
    };

    const computedLeftIcon = error ? "error" : leftIcon;

    const computedInputBarClassName = concatClassNames(
      style.inputBar,
      computedLeftIcon ? style.withLeftIcon : "",
      rightIconAction ? style.withRightIcon : "",
    );

    const displayCounter = showCounter && typeof maxLength === "number";
    const rightIconName = getRightIconName(rightIconAction);
    const rightIconAriaLabel = getRightIconAriaLabel(rightIconAction);

    const shouldShowRightIcon = () => {
      if (readOnly || disabled) {
        return false;
      }
      if (rightIconAction === "clean") {
        return !!inputValue?.length && showRightIcon;
      }
      return showRightIcon && !!rightIconAction;
    };

    const handleOnKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
      if (event.key === "Enter" && onEnterKeyDown) {
        onEnterKeyDown(inputValue);
      }
    };

    return (
      <div
        className={style.container}
        data-label-position={labelPosition}
        data-disabled={disabled}
        data-error={error}
        style={{ width }}
        data-compact-spacing={compactSpacing}
      >
        {label && (
          <div className={style.text}>
            <Label id={id} label={label} required={required} showLabelRequirement={showLabelRequirement} />
            {displayCounter && labelPosition === "top" && (
              <p className={style.inputCounter} data-testid="input-counter">
                {" "}
                {characterCount}/{maxLength}
              </p>
            )}
          </div>
        )}
        <div className={style.inputContainer}>
          <div
            className={style.input}
            data-label-position={labelPosition}
            data-disabled={disabled}
            data-read-only={readOnly}
          >
            <div className={computedInputBarClassName} data-compact-spacing={compactSpacing}>
              {computedLeftIcon && (
                <Icon
                  name={computedLeftIcon}
                  appearance="outlined"
                  className={style.leftIcon}
                  aria-hidden="true"
                  data-testid={`left-icon ${computedLeftIcon}`}
                />
              )}
              <input
                id={id}
                ref={(node) => {
                  inputRef.current = node;
                  if (typeof ref === "function") {
                    ref(node);
                  } else if (ref) {
                    ref.current = node;
                  }
                }}
                type={isHiddenInput ? "password" : "text"}
                data-error={error}
                data-highlighted={highlighted}
                className={style.inputField}
                maxLength={maxLength}
                onChange={handleChange}
                disabled={disabled}
                readOnly={readOnly}
                value={disabled ? "" : inputValue}
                placeholder={placeholder}
                onKeyDown={handleOnKeyDown}
                {...props}
              />

              {shouldShowRightIcon() && (
                <IconButton
                  name={rightIconName}
                  appearance="outlined"
                  variant="neutral"
                  size="s"
                  compactSpacing={true}
                  className={style.rightIcon}
                  aria-label={rightIconAriaLabel}
                  disabled={disabled}
                  onClick={onRightIconClickHandler}
                  data-testid="right-icon"
                />
              )}
            </div>
            {rightSlot && <div className={style.rightSlot}>{rightSlot}</div>}
          </div>
          {assistiveTextLabel && (
            <AssistiveText label={assistiveTextLabel} appearance={assistiveAppearance} showIcon={showAssistiveIcon} />
          )}
        </div>
        {displayCounter && labelPosition == "side" && (
          <p className={style.inputCounter} data-testid="input-counter">
            {" "}
            {characterCount}/{maxLength}{" "}
          </p>
        )}
      </div>
    );
  },
);

export default BaseTextInput;
