// preview/main/angular/components/banner/banner.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  input,
  output,
  signal,
  SimpleChanges,
  OnInit,
  OnChanges,
  computed,
} from "@angular/core";
import { CloseButtonAriaLabel } from "@design-system-rte/core";
import { BannerPosition, BannerType } from "@design-system-rte/core/components/banner/banner.interface";
import { ButtonSize } from "@design-system-rte/core/components/button/common/common-button";

import { ButtonComponent } from "../button/button.component";
import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-banner",
  imports: [CommonModule, IconComponent, ButtonComponent],
  templateUrl: "./banner.component.html",
  styleUrls: ["./banner.component.scss", "../icon-button/icon-button.component.scss"],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BannerComponent implements OnInit, OnChanges {
  readonly type = input<BannerType>("info");
  readonly message = input.required<string>();
  readonly position = input<BannerPosition>("push");
  readonly title = input<string>();
  readonly closable = input<boolean>(false);
  readonly isOpen = input<boolean>(true);
  readonly isCompact = input<boolean>(false);
  readonly actionLabel = input<string>();

  readonly click = output<void>();

  readonly visible = signal(false);
  readonly rendering = signal(false);

  readonly close = output<void>();

  readonly iconTypeMap: Record<string, string> = {
    info: "info",
    error: "dangerous",
    success: "check-circle",
    warning: "warning",
  };

  readonly iconName = computed(() => {
    return this.iconTypeMap[this.type()];
  });

  readonly actionButtonSize = computed<ButtonSize>(() => (this.isCompact() ? "s" : "m"));

  readonly closeButtonAriaLabel = CloseButtonAriaLabel;

  ngOnInit() {
    this.visible.set(this.isOpen());
    this.rendering.set(this.isOpen());
    if (this.closable() === false && this.position() === "overlay") {
      console.warn("Banner: 'closable' and 'close' props must be set when 'position' has 'overlay' value.");
      return;
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes["isOpen"]) {
      if (this.isOpen()) this.openBanner();
      else {
        this.closeBanner();
      }
    }
  }

  clickAction() {
    this.click.emit();
  }

  closeBanner() {
    this.visible.set(false);
    setTimeout(() => {
      this.rendering.set(false);
      this.close.emit();
    }, 200);
  }

  private openBanner() {
    if (this.rendering()) return;
    this.rendering.set(true);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => this.visible.set(true));
    });
  }
}

<section
  *ngIf="rendering()"
  class="rte-banner-container {{ type() }} {{ position() }}"
  class="rte-banner"
  [ngClass]="{ open: visible(), close: !visible() }"
  [attr.role]="type() === 'error' ? 'alert' : 'status'"
>
  <div class="rte-banner-icon">
    <rte-icon [name]="iconName()" [size]="32" />
  </div>
  <div class="rte-banner-content">
    <span *ngIf="title()" class="rte-banner-title">{{ title() }}</span>
    <div *ngIf="message()" class="rte-banner-message">
      <span>{{ message() }}</span>
    </div>
  </div>
  <button
    *ngIf="actionLabel()"
    rteButton
    rteButtonVariant="text"
    rteButtonSize="s"
    [attr.aria-label]="actionLabel()!"
    (click)="clickAction()"
  >
    {{ actionLabel() }}
  </button>
  <div *ngIf="closable()" class="rte-banner-close-icon">
    <rte-icon-button name="close" variant="neutral" ariaLabel="close banner" (click)="closeBanner()" />
  </div>
</section>

// packages/react/src/components/banner/Banner.tsx
import { BannerProps as CoreBannerProps } from "@design-system-rte/core/components/banner/banner.interface";
import { IconSize } from "@design-system-rte/core/components/icon/icon.constants";
import { forwardRef, useEffect, useState } from "react";

import useAnimatedMount from "../../hooks/useAnimatedMount";
import Button from "../button/Button";
import Icon from "../icon/Icon";
import iconButtonStyle from "../iconButton/IconButton.module.scss";
import { concatClassNames } from "../utils";

import style from "./Banner.module.scss";

interface BannerProps extends CoreBannerProps, React.HTMLAttributes<HTMLDivElement> {}

const Banner = forwardRef<HTMLDivElement, BannerProps>(
  (
    {
      title,
      message,
      type = "alert",
      closable = false,
      onClose,
      position = "push",
      actionCallback,
      actionLabel,
      className = "",
      isOpen = true,
      isCompact = false,
      ...props
    },
    ref,
  ) => {
    const [isInternalOpen, setIsInternalOpen] = useState(isOpen);
    const ariaRole = type === "error" ? "alert" : "status";
    const { shouldRender, isAnimating } = useAnimatedMount(isInternalOpen, 200);

    const iconTypeMap: Record<string, string> = {
      info: "info",
      error: "dangerous",
      success: "check-circle",
      warning: "warning",
    };

    useEffect(() => {
      setIsInternalOpen(isOpen);
    }, [isOpen]);

    if (closable === false && position === "overlay") {
      console.warn("Banner: 'closable' and 'onClose' props must be set when 'position' has 'overlay' value.");
      return null;
    }

    const handleOnClose = () => {
      setIsInternalOpen(false);
      onClose?.();
    };

    return (
      shouldRender && (
        <section
          role={ariaRole}
          className={concatClassNames(style["banner"], className)}
          ref={ref}
          data-type={type}
          data-position={position}
          data-compact={isCompact ? "true" : undefined}
          data-open={isAnimating || undefined}
          {...props}
        >
          <div className={style["banner-icon"]}>
            <Icon name={iconTypeMap[type]} size={32} />
          </div>
          <div className={style["banner-content"]}>
            {title && <span className={style["banner-title"]}>{title}</span>}
            {message && (
              <div className={style["banner-message"]}>
                <span>{message}</span>
              </div>
            )}
          </div>
          {actionCallback && actionLabel && (
            <Button
              label={actionLabel}
              onClick={actionCallback}
              variant="text"
              aria-label={actionLabel}
              size={isCompact ? "s" : "m"}
            />
          )}
          {closable && (
            <button
              type="button"
              className={concatClassNames(iconButtonStyle["icon-button"], style["banner-close-button"])}
              data-size="m"
              data-variant="neutral"
              data-compact-spacing={true}
              aria-label="close banner"
              onClick={handleOnClose}
            >
              <Icon name="close" size={IconSize["m"]} />
            </button>
          )}
        </section>
      )
    );
  },
);

export default Banner;
