// preview/badge-component/angular/components/badge/badge.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, ChangeDetectionStrategy } from "@angular/core";
import { BadgeAppearance, BadgeSize, BadgeType } from "@design-system-rte/core/components/badge/badge.interface";
import {
  getBadgeIconSize,
  getDisplayCount,
  getShowBadge,
  getShowIcon,
  getShowText,
} from "@design-system-rte/core/components/badge/badge.utils";

import { isValidIconName } from "../icon/icon-map";
import { IconComponent } from "../icon/icon.component";
import { RegularIconIdKey, TogglableIconIdKey } from "../icon/icon.service";

@Component({
  selector: "rte-badge",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./badge.component.html",
  styleUrl: "./badge.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BadgeComponent {
  readonly badgeType = input<BadgeType>("brand");
  readonly badgeSize = input<BadgeSize>("m");
  readonly badgeAppearance = input<BadgeAppearance>("text");
  readonly count = input<number | undefined>();
  readonly icon = input<RegularIconIdKey | TogglableIconIdKey>("settings");

  readonly isValidIconName = computed(() => isValidIconName(this.icon()));

  readonly showIcon = computed(() =>
    getShowIcon({
      size: this.badgeSize(),
      appearance: this.badgeAppearance(),
      iconSize: this.iconSize(),
    }),
  );

  readonly showText = computed(() =>
    getShowText({
      size: this.badgeSize(),
      appearance: this.badgeAppearance(),
      count: this.count(),
    }),
  );

  readonly displayCount = computed(() => getDisplayCount(this.count()));
  readonly iconSize = computed(() => getBadgeIconSize(this.badgeSize()));

  readonly showBadge = computed(() =>
    getShowBadge({
      size: this.badgeSize(),
      appearance: this.badgeAppearance(),
      count: this.count(),
      iconSize: this.iconSize(),
    }),
  );
}

<div
    class="badge size-{{ badgeSize() }} type-{{ badgeType() }}"
    data-testid="badge"
    [ngClass]="{'hidden': !showBadge(), 'count-overflow': countOverflow()}"
>
    <rte-icon
        *ngIf="showIcon()"
        class="badge-icon"
        [name]="icon()"
        [size]="iconSize()!"
    />
    <p *ngIf="showText()" class="badge-text">
        {{displayCount()}}
    </p>
</div>

// packages/react/src/components/badge/Badge.tsx
import { BadgeProps as BadgePropsCore } from "@design-system-rte/core/components/badge/badge.interface";
import {
  getBadgeIconSize,
  getDisplayCount,
  getShowBadge,
  getShowIcon,
  getShowText,
} from "@design-system-rte/core/components/badge/badge.utils";
import { forwardRef } from "react";

import Icon, { RegularIconIdKey, TogglableIconIdKey } from "../icon/Icon";
import { isValidIconName } from "../icon/IconMap";
import { concatClassNames } from "../utils";

import style from "./Badge.module.scss";

export interface BadgeProps extends BadgePropsCore, Omit<React.HTMLAttributes<HTMLDivElement>, "children"> {
  children: React.ReactNode;
  icon?: RegularIconIdKey | TogglableIconIdKey;
}

const Badge = forwardRef<HTMLDivElement, BadgeProps>(
  ({ badgeType = "brand", size = "m", appearance = "text", count, icon = "notification", children, ...props }, ref) => {
    if (appearance == "icon" && icon && !isValidIconName(icon)) {
      console.warn(`Badge: Invalid icon name "${icon}". Please use a valid icon key.`);
      return null;
    }

    const iconSize = getBadgeIconSize(size);

    const showIcon = getShowIcon({ size, appearance, iconSize });
    const showText = getShowText({ size, appearance, count });

    const showBadge = getShowBadge({ size, appearance, count, iconSize });
    const countOverflow = showText && getDisplayCount(count)?.length > 2;

    return (
      <div ref={ref} className={style.badgeContainer} {...props}>
        <div
          data-badge-type={badgeType}
          data-size={size}
          data-testid="badge"
          className={concatClassNames(
            style.badge,
            showBadge ? "" : style.hidden,
            countOverflow ? style.countOverflow : "",
          )}
        >
          {showIcon && <Icon name={icon} className={style.icon} size={iconSize} />}
          {showText && (
            <p className={style.count} key={count}>
              {getDisplayCount(count)}
            </p>
          )}
        </div>
        {children}
      </div>
    );
  },
);

export default Badge;
