// preview/Renovate_node-24.x-lockfile/angular/components/radio-button/radio-button.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, input, output } from "@angular/core";
import { labelSize } from "@design-system-rte/core/components/radio-button/radio-button.constants";
import {
  getRadioButtonAccessibleName,
  RADIO_BUTTON_MISSING_ACCESSIBLE_NAME_ERROR,
} from "@design-system-rte/core/components/radio-button/radio-button.utils";

@Component({
  selector: "rte-radio-button",
  imports: [CommonModule],
  templateUrl: "./radio-button.component.html",
  styleUrl: "./radio-button.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RadioButtonComponent {
  readonly label = input("");
  readonly ariaLabel = input("");
  readonly value = input("");
  readonly groupName = input("");
  readonly showLabel = input(true);
  readonly disabled = input(false);
  readonly error = input(false);
  readonly readOnly = input(false);
  labelSize = labelSize;
  readonly isChecked = input(false);

  readonly accessibleLabel = computed(() => getRadioButtonAccessibleName(this.label(), this.ariaLabel()));

  readonly isDisplayed = computed(() => {
    if (this.disabled() && this.error()) {
      console.warn("RadioButton cannot be both disabled and in an error state. Please choose one state or the other.");
      return false;
    }
    return this.accessibleLabel() !== null;
  });

  readonly changeEvent = output<string>();

  constructor() {
    effect(() => {
      if (!this.accessibleLabel()) {
        console.error(RADIO_BUTTON_MISSING_ACCESSIBLE_NAME_ERROR);
      }
    });
  }

  onChange() {
    if (this.disabled() || this.readOnly()) {
      return;
    }
    this.changeEvent.emit(this.value());
  }
}

// packages/react/src/components/radioButton/RadioButton.tsx
import { labelSize } from "@design-system-rte/core/components/radio-button/radio-button.constants";
import { RadioButtonProps as CoreRadioButtonProps } from "@design-system-rte/core/components/radio-button/radio-button.interface";
import {
  getRadioButtonAccessibleName,
  RADIO_BUTTON_MISSING_ACCESSIBLE_NAME_ERROR,
} from "@design-system-rte/core/components/radio-button/radio-button.utils";
import React, { forwardRef } from "react";

import { concatClassNames } from "../utils";

import style from "./RadioButton.module.scss";

interface RadioButtonProps extends CoreRadioButtonProps, Omit<React.InputHTMLAttributes<HTMLInputElement>, "value"> {}

const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
  (
    {
      label,
      groupName,
      showLabel = true,
      disabled = false,
      error = false,
      readOnly = false,
      className = "",
      onChange,
      value,
      isChecked,
      ...props
    },
    ref,
  ) => {
    if (disabled && error) {
      console.warn("RadioButton cannot be both disabled and in an error state. Please choose one state or the other.");
      return null;
    }

    const accessibleLabel = getRadioButtonAccessibleName(label, props["aria-label"]);

    if (!accessibleLabel) {
      console.error(RADIO_BUTTON_MISSING_ACCESSIBLE_NAME_ERROR);
      return null;
    }

    const handleOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      if (disabled || readOnly) {
        return;
      }

      if (onChange) {
        onChange(event);
      }
    };

    return (
      <div className={style.radioButtonContainer} data-disabled={disabled} data-read-only={readOnly} data-error={error}>
        <input
          ref={ref}
          type="radio"
          id={value}
          value={value}
          size={labelSize}
          name={groupName}
          className={concatClassNames(style.radioButton, className)}
          disabled={disabled}
          data-error={error}
          data-read-only={readOnly}
          onChange={handleOnChange}
          checked={isChecked}
          aria-label={accessibleLabel}
          {...props}
        />
        <div
          className={style.radioButtonBackground}
          data-disabled={disabled}
          data-error={error}
          data-read-only={readOnly}
        >
          <div className={style.radioButtonOuter}></div>
          <div className={style.radioButtonInner}></div>
        </div>
        {showLabel && (
          <label
            htmlFor={value}
            className={concatClassNames(style.radioButtonLabel, className)}
            data-disabled={disabled}
            data-error={error}
            data-read-only={readOnly}
            data-show-label={showLabel}
          >
            {label}
          </label>
        )}
      </div>
    );
  },
);

export default RadioButton;
