// packages/react/src/components/fileupload/FileUpload.tsx
import { FileUploadProps, generateId } from "@design-system-rte/core";
import { useRef, useState } from "react";

import AssistiveText from "../assistivetext/AssistiveText";
import Button from "../button/Button";
import Label from "../label/Label";

import FileItem from "./file-item/FileItem";
import styles from "./FileUpload.module.scss";

const FileUpload = ({
  id,
  compactSpacing,
  label,
  required = false,
  showLabelRequirement = false,
  disabled = false,
  assistiveTextLabel,
  assistiveAppearance = "description",
  showAssistiveText = true,
  showAssistiveIcon,
  assistiveTextLink,
  isError,
  multiple = false,
  buttonLabel,
  accept,
  onChange,
  onUpload,
  uploadErrorMessage = "Erreur lors du téléchargement du fichier.",
  errorFilesMap = [],
  onRemovingFile,
}: FileUploadProps) => {
  const localId = id ?? generateId();
  const labelId = generateId();

  const buttonRef = useRef<HTMLButtonElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const [selectedFiles, setSelectedFiles] = useState<File[] | null>(null);
  const [loadingFiles, setLoadingFiles] = useState<Set<File>>(new Set());
  const [removalAnnouncement, setRemovalAnnouncement] = useState("");

  const [uploadErrors, setUploadErrors] = useState<Map<File, string>>(new Map());

  const shouldDisplayAssistiveText =
    showAssistiveText &&
    assistiveTextLabel &&
    assistiveAppearance &&
    errorFilesMap.length === 0 &&
    uploadErrors.size === 0;

  const handleOnChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);
    onChange?.(files);
    if (multiple) {
      setSelectedFiles((prev) => {
        const next = prev ? [...prev, ...files] : files;
        return next;
      });
    } else {
      setSelectedFiles(files);
      setUploadErrors(new Map());
    }

    if (onUpload) {
      await Promise.all(files.map((file) => handleUploadFile(file)));
    }
  };

  const handleOnClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.stopPropagation();
    const fileInput = document.getElementById(localId);
    if (fileInput) {
      fileInput.click();
    }
  };

  const handleRemoveFile = (file: File) => {
    if (selectedFiles) {
      const index = selectedFiles.indexOf(file);
      if (index !== -1) {
        const newFiles = selectedFiles.filter((_, i) => i !== index);
        setSelectedFiles(newFiles);
        setRemovalAnnouncement(
          `${file.name} a été supprimé. ${newFiles.length} fichier${newFiles.length > 1 ? "s" : ""} restant${newFiles.length > 1 ? "s" : ""}.`,
        );
        setLoadingFiles((prev) => {
          const next = new Set(prev);
          next.delete(file);
          return next;
        });
        setUploadErrors((prev) => {
          const next = new Map(prev);
          next.delete(file);
          return next;
        });
        onRemovingFile?.(file);
        onChange?.(newFiles);
        if (buttonRef.current) {
          if (inputRef.current) {
            inputRef.current.value = "";
          }
          buttonRef.current?.focus();
        }
      }
    }
  };

  const handleUploadFile = (file: File) => {
    setLoadingFiles((prev) => new Set(prev).add(file));
    return onUpload!(file)
      .then(() => {
        setLoadingFiles((prev) => {
          const next = new Set(prev);
          next.delete(file);
          return next;
        });
      })
      .catch((error: unknown) => {
        setLoadingFiles((prev) => {
          const next = new Set(prev);
          next.delete(file);
          return next;
        });
        const message = typeof uploadErrorMessage === "function" ? uploadErrorMessage(file, error) : uploadErrorMessage;
        setUploadErrors((prev) => new Map(prev).set(file, message));
      });
  };

  return (
    <div className={styles["rte-file-upload"]}>
      <input
        ref={inputRef}
        type="file"
        multiple={multiple}
        id={localId}
        className={styles["rte-file-upload-input"]}
        onChange={handleOnChange}
        aria-labelledby={label ? labelId : `${localId}-button`}
        aria-describedby={shouldDisplayAssistiveText ? `${localId}-assistive-text` : undefined}
        disabled={disabled}
        accept={accept}
      />
      {label && (
        <Label
          htmlFor={localId}
          id={labelId}
          label={label}
          required={required}
          showLabelRequirement={showLabelRequirement}
        />
      )}
      {shouldDisplayAssistiveText && (
        <AssistiveText
          id={`${localId}-assistive-text`}
          label={assistiveTextLabel}
          appearance={isError ? "error" : assistiveAppearance}
          showIcon={showAssistiveIcon}
          href={assistiveTextLink}
        />
      )}

      <Button
        id={`${localId}-button`}
        disabled={disabled}
        variant="primary"
        label={buttonLabel}
        onClick={handleOnClick}
        icon="upload"
        iconPosition="left"
        ref={buttonRef}
        size={compactSpacing ? "s" : "m"}
        className={compactSpacing ? styles["rte-file-upload-button-compact"] : undefined}
      />

      <div style={{ width: buttonRef.current?.offsetWidth ?? undefined }}>
        {selectedFiles?.map((file, index) => (
          <FileItem
            key={file.lastModified + index}
            file={file}
            removeFile={() => handleRemoveFile(file)}
            isLoading={loadingFiles.has(file)}
            isError={errorFilesMap[index] !== undefined || uploadErrors.has(file)}
            errorMessage={uploadErrors.get(file) ?? errorFilesMap[index]}
            compact={compactSpacing}
          />
        ))}
      </div>
      <div role="status" aria-live="polite" aria-atomic="true" className={styles["sr-only"]}>
        {removalAnnouncement}
      </div>
    </div>
  );
};

export default FileUpload;

// angular/components/file-upload/file-upload.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  OnDestroy,
  output,
  signal,
  viewChild,
} from "@angular/core";
import { generateId } from "@design-system-rte/core";
import { AssistiveTextProps } from "@design-system-rte/core/components/assistive-text/assistive-text.interface";

import { AssistiveTextComponent } from "../assistive-text/assistive-text.component";
import { ButtonComponent } from "../button/button.component";
import { RequiredIndicatorComponent } from "../input/required-indicator/required-indicator.component";

import { FileItemComponent } from "./file-item/file-item.component";

@Component({
  selector: "rte-file-upload",
  imports: [CommonModule, ButtonComponent, AssistiveTextComponent, FileItemComponent, RequiredIndicatorComponent],
  templateUrl: "./file-upload.component.html",
  styleUrl: "./file-upload.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileUploadComponent implements OnDestroy {
  readonly id = input.required<string>();
  readonly label = input.required<string>();
  readonly buttonLabel = input.required<string>();
  readonly showLabel = input<boolean>(true);
  readonly compactSpacing = input<boolean>(false);
  readonly multiple = input<boolean>(false);
  readonly accept = input<string>();
  readonly required = input<boolean>(false);
  readonly showLabelRequirement = input<boolean>(false);
  readonly disabled = input<boolean>(false);
  readonly assistiveTextLabel = input<string>();
  readonly assistiveAppearance = input<AssistiveTextProps["appearance"]>("description");
  readonly showAssistiveText = input<boolean>(true);
  readonly showAssistiveIcon = input<boolean>(false);
  readonly assistiveTextLink = input<string>();
  readonly isError = input<boolean>(false);
  readonly errorFilesMap = input<string[]>([]);
  readonly onUploadFile = input<(file: File) => Promise<void>>();
  readonly uploadErrorMessage = input<string | ((file: File, error: unknown) => string)>(
    "Erreur lors du téléchargement du fichier.",
  );

  readonly inputRef = viewChild<ElementRef<HTMLInputElement>>("inputRef");
  readonly buttonRef = viewChild("buttonRef", { read: ElementRef });

  readonly filesChange = output<File[]>();
  readonly fileRemoved = output<File>();

  readonly selectedFiles = signal<File[]>([]);
  readonly loadingFiles = signal<Set<File>>(new Set());
  readonly removingFiles = signal<Set<File>>(new Set());
  readonly uploadErrors = signal<Map<File, string>>(new Map());
  readonly removalAnnouncement = signal("");

  private readonly removalTimers = new Map<File, ReturnType<typeof setTimeout>>();

  readonly shouldDisplayAssistiveText = computed(() => {
    return (
      this.showAssistiveText() &&
      !!this.assistiveTextLabel() &&
      this.errorFilesMap().length === 0 &&
      this.uploadErrors().size === 0
    );
  });

  readonly buttonSize = computed(() => (this.compactSpacing() ? "s" : "m"));

  readonly internalId = computed(() => this.id() ?? generateId());

  ngOnDestroy(): void {
    this.removalTimers.forEach((timer) => clearTimeout(timer));
  }

  isFileLoading(file: File): boolean {
    return this.loadingFiles().has(file);
  }

  isFileRemoving(file: File): boolean {
    return this.removingFiles().has(file);
  }

  isFileError(index: number): boolean {
    return this.errorFilesMap()[index] !== undefined || this.uploadErrors().has(this.selectedFiles()[index]);
  }

  getFileErrorMessage(index: number): string | undefined {
    return this.uploadErrors().get(this.selectedFiles()[index]) ?? this.errorFilesMap()[index];
  }

  async handleOnChange(event: Event): Promise<void> {
    const fileInput = event.target as HTMLInputElement;
    const files = Array.from(fileInput.files || []);
    if (this.multiple()) {
      this.selectedFiles.update((previousFiles) => [...previousFiles, ...files]);
    } else {
      this.selectedFiles.set(files);
      this.uploadErrors.set(new Map());
    }
    this.filesChange.emit(files);
    fileInput.focus();

    const onUpload = this.onUploadFile();
    if (onUpload) {
      await Promise.all(files.map((file) => this.handleUploadFile(file, onUpload)));
    }
  }

  private handleUploadFile(file: File, onUpload: (file: File) => Promise<void>): Promise<void> {
    this.loadingFiles.update((prev) => new Set(prev).add(file));
    return onUpload(file)
      .then(() => {
        this.loadingFiles.update((prev) => {
          const next = new Set(prev);
          next.delete(file);
          return next;
        });
      })
      .catch((error: unknown) => {
        this.loadingFiles.update((prev) => {
          const next = new Set(prev);
          next.delete(file);
          return next;
        });
        const errorMessage = this.uploadErrorMessage();
        const message = typeof errorMessage === "function" ? errorMessage(file, error) : errorMessage;
        this.uploadErrors.update((previousErrors) => {
          if (!this.selectedFiles().includes(file)) return previousErrors;
          return new Map(previousErrors).set(file, message);
        });
      });
  }

  handleOnClick(event: MouseEvent): void {
    event.stopPropagation();
    this.inputRef()?.nativeElement.click();
  }

  handleRemoveFile(file: File): void {
    const files = this.selectedFiles();
    const index = files.indexOf(file);
    if (index !== -1 && !this.removingFiles().has(file)) {
      const newFiles = files.filter((_, i) => i !== index);
      this.removingFiles.update((previousFiles) => new Set(previousFiles).add(file));
      this.removalAnnouncement.set(
        `${file.name} a été supprimé. ${newFiles.length} fichier${newFiles.length > 1 ? "s" : ""} restant${newFiles.length > 1 ? "s" : ""}.`,
      );
      const input = this.inputRef()?.nativeElement;
      const button = this.buttonRef()?.nativeElement as HTMLButtonElement | undefined;
      if (input) {
        input.value = "";
      }
      if (button) {
        button.focus();
      }

      const timer = setTimeout(() => {
        this.uploadErrors.update((previousErrors) => {
          const next = new Map(previousErrors);
          next.delete(file);
          return next;
        });
        this.loadingFiles.update((previousFiles) => {
          const next = new Set(previousFiles);
          next.delete(file);
          return next;
        });
        this.selectedFiles.set(newFiles);
        this.removingFiles.update((previousFiles) => {
          const next = new Set(previousFiles);
          next.delete(file);
          return next;
        });
        this.fileRemoved.emit(file);
        this.filesChange.emit(newFiles);
        this.removalTimers.delete(file);
      }, 200);
      this.removalTimers.set(file, timer);
    }
  }
}
