// packages/react/src/components/radioButtonGroup/RadioButtonGroup.tsx
import React, { forwardRef } from "react";
import { RadioButtonGroupProps as CoreRadioButtonGroupProps } from "@design-system-rte/core/components/radio-button-group/radio-button-group.interface";
import { concatClassNames } from "../utils";
import RadioButton from "../radioButton/RadioButton";
import style from "./RadioButtonGroup.module.scss";

interface RadioButtonGroupProps
    extends CoreRadioButtonGroupProps,
    React.InputHTMLAttributes<HTMLDivElement> { }

const RadioButtonGroup = forwardRef<HTMLDivElement, RadioButtonGroupProps>(({
    groupName,
    items,
    direction = "horizontal",
    showItemsLabel = true,
    groupTitle = '',
    showGroupTitle = false,
    groupHelpText = '',
    showHelpText = false,
    errorMessage = '',
    error = false,
    disabled = false,
    readOnly = false,
    className = "",
    ...props
}, ref) => {

    if (disabled && error) {
        return;
    }

    return (
        <div
            ref={ref}
            className={concatClassNames(style.radioButtonGroupContainer, className)}
            {...props}
        >
            <div className={style.radioButtonGroupHeader}
            data-error={error}
            data-disabled={disabled}
            data-read-only={readOnly}>
                {groupTitle && showGroupTitle && (
                    <h3 className={style.groupTitle}>{groupTitle}</h3>
                )}
                {groupHelpText && showHelpText && (
                    <p className={style.groupHelpText}>{groupHelpText}</p>
                )}
                {errorMessage && error && (
                    <p className={style.errorMessage}>{errorMessage}</p>
                )}
            </div>
            <div className={style.radioButtonGroup}
                data-direction={direction}>
                {items.map((item, index) => (
                    <RadioButton
                        key={index}
                        label={item}
                        groupName={groupName}
                        showLabel={showItemsLabel}
                        disabled={disabled}
                        error={error}
                        readOnly={readOnly}
                    />
                ))}
            </div>
        </div>
    );
})

export default RadioButtonGroup;

// packages/angular/src/components/radio-button-group/radio-button-group.component.ts
import { Component, computed, input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RadioButtonComponent } from "../radio-button/radio-button.component";

@Component({
  selector: 'rte-radio-button-group',
  standalone: true,
  imports: [CommonModule, RadioButtonComponent],
  templateUrl: './radio-button-group.component.html',
  styleUrls: ['./radio-button-group.component.scss'],
})

export class RadioButtonGroupComponent {
    groupName = input('');
    items = input<string[]>([]);
    direction = input('horizontal');
    showItemsLabel = input(true);
    groupTitle = input('');
    showGroupTitle = input(false);
    groupHelpText = input('');
    showHelpText = input(false);
    errorMessage = input('');
    error = input(false);
    disabled = input(false);
    readOnly = input(false);

    isInteractive = computed(() => !(this.disabled()==true && this.error()==true));

}


<div  
    *ngIf="isInteractive()"
    class="radio-button-group-container">
    <div
        class="radio-button-group-header"
        [ngClass]="{
            'disabled': disabled(),
            'error': error(),
            'read-only': readOnly(),
        }">
        <h3
            *ngIf="showGroupTitle()"
            class="group-title"
            >
            {{ groupTitle() }}
        </h3>
        <p
            *ngIf="showHelpText()"
            class="group-help-text"
            >
            {{ groupHelpText() }}

        </p>
        <p
            *ngIf="error()"
            class="group-error-message"
            >
            {{ errorMessage() }}
        </p>
    </div>
    <div class="radio-button-group" 
        [ngClass]="{'horizontal': direction() === 'horizontal', 'vertical': direction() === 'vertical'}">
        <ng-container 
        *ngFor="let item of items()">
            <rte-radio-button
                [label]="item"
                [groupName]="groupName()"
                [showLabel]="showItemsLabel()"
                [disabled]="disabled()"
                [error]="error()"
                [readOnly]="readOnly()"
            />
        </ng-container>
    </div>
</div>
