// packages/react/src/components/sideNav/navMenu/NavMenu.tsx
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps as CoreNavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { dividerAppearanceBySideNavAppearance } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import {
  ARROW_DOWN_KEY,
  ARROW_UP_KEY,
  ENTER_KEY,
  ESCAPE_KEY,
  SPACE_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { forwardRef, HTMLAttributes, ReactNode, useState } from "react";

import { useActiveKeyboard } from "../../../hooks/useActiveKeyboard";
import Badge from "../../badge/Badge";
import Divider from "../../divider/Divider";
import Icon from "../../icon/Icon";
import Tooltip from "../../tooltip/Tooltip";
import { concatClassNames } from "../../utils";
import NavItem from "../navItem/NavItem";

import style from "./NavMenu.module.scss";

interface NavMenuProps extends CoreNavMenuProps, Omit<HTMLAttributes<HTMLLIElement>, "onClick"> {
  children?: ReactNode;
  isNested?: boolean;
  parentMenuOpen?: boolean;
}

interface NavMenuContentProps {
  link?: string;
  label: string;
  tabIndex: number;
  onClick: () => void;
  onKeyDown: (e: React.KeyboardEvent<HTMLElement>) => void;
  children: ReactNode;
}

const NavMenuContent = ({ link, label, tabIndex, onClick, onKeyDown, children }: NavMenuContentProps) => {
  const commonProps = {
    className: style.navMenu,
    onClick,
    tabIndex,
    label,
    onKeyDown: onKeyDown as React.KeyboardEventHandler<HTMLElement>,
  };

  if (link) {
    return (
      <a href={link} {...commonProps}>
        {children}
      </a>
    );
  }

  return (
    <span aria-label={label} {...commonProps}>
      {children}
    </span>
  );
};

const NavMenu = forwardRef<HTMLLIElement, NavMenuProps>(
  (
    {
      icon,
      showIcon = true,
      onClick,
      label,
      collapsed,
      link,
      items = [],
      open: controlledOpen,
      showMenuIcon = true,
      isNested,
      parentMenuOpen,
      appearance = "brand",
      badge,
      showDivider,
      ...props
    }: NavMenuProps,
    ref,
  ) => {
    const [internalOpen, setInternalOpen] = useState(false);
    const isOpen = controlledOpen !== undefined ? controlledOpen : internalOpen;
    const isControlled = controlledOpen !== undefined;

    const toggleMenu = () => {
      if (!isControlled) {
        setInternalOpen(!internalOpen);
      }
      if (onClick) {
        onClick();
      }
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLElement>) => {
      if ([SPACE_KEY, ENTER_KEY].includes(e.key)) {
        e.preventDefault();
        toggleMenu();
      }
      if (e.key === ESCAPE_KEY && isOpen) {
        e.preventDefault();
        if (!isControlled) {
          setInternalOpen(false);
        }
      }
    };

    const { onKeyDown } = useActiveKeyboard<HTMLElement>(
      { onKeyDown: handleKeyDown },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY, ESCAPE_KEY, ARROW_DOWN_KEY, ARROW_UP_KEY],
      },
    );

    const hasNestedItems = items.length;
    const shouldShowMenu = !collapsed && hasNestedItems;
    const nestedItemsParentMenuOpen = isOpen;
    const tabIndex = parentMenuOpen === false ? -1 : 0;

    const chevronIcon =
      shouldShowMenu && showMenuIcon ? (
        <Icon name="arrow-chevron-right" className={concatClassNames(style.menuIcon, isOpen && style.menuIconOpen)} />
      ) : null;

    const menuContent = (
      <>
        <div className={style.menuContentLeft}>
          <NavMenuLabel icon={icon} showIcon={showIcon} label={label} collapsed={collapsed} isNested={isNested} />
        </div>
        <div className={style.menuContentRight}>
          {badge && <Badge badgeType={badge.badgeType} size={badge.size} content={badge.content} count={badge.count} />}
          {chevronIcon}
        </div>
      </>
    );

    const listItem = (
      <li
        className={concatClassNames(
          style.navMenuContainer,
          appearance && style[appearance],
          collapsed && style.collapsed,
          isOpen && style.open,
          isNested && style.nested,
        )}
        ref={ref}
        {...props}
      >
        <NavMenuContent link={link} label={label} tabIndex={tabIndex} onClick={toggleMenu} onKeyDown={onKeyDown}>
          {menuContent}
        </NavMenuContent>
        {shouldShowMenu && (
          <ul className={concatClassNames(style.nestedMenu, isOpen && style.nestedMenuOpen)}>
            {items.map((item: NavItemProps) => {
              const hasNestedItems = !!item.items?.length;
              if (hasNestedItems) {
                return (
                  <NavMenu
                    key={item.id || item.label}
                    label={item.label}
                    icon={item.icon}
                    showIcon={item.showIcon}
                    collapsed={collapsed}
                    link={item.link}
                    onClick={item.onClick}
                    items={item.items || []}
                    showMenuIcon={showMenuIcon}
                    isNested={true}
                    parentMenuOpen={nestedItemsParentMenuOpen}
                    appearance={appearance}
                    badge={item.badge}
                  />
                );
              }
              return (
                <>
                  <li key={item.id || item.label}>
                    <NavItem
                      label={item.label}
                      icon={item.icon}
                      showIcon={item.showIcon}
                      collapsed={collapsed}
                      link={item.link}
                      onClick={item.onClick}
                      isNested={true}
                      parentMenuOpen={nestedItemsParentMenuOpen}
                      appearance={appearance}
                      badge={item.badge}
                    />
                  </li>
                  {item.showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
                </>
              );
            })}
          </ul>
        )}
      </li>
    );

    if (collapsed && label) {
      return (
        <>
          <Tooltip
            label={label}
            position="right"
            alignment="center"
            arrow={false}
            shouldFocusTrigger={false}
            triggerStyles={{ outline: "none" }}
            gap={12}
          >
            {listItem}
          </Tooltip>
          {showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
        </>
      );
    }

    return (
      <>
        {listItem}
        {showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
      </>
    );
  },
);

const NavMenuLabel = ({ isNested, ...props }: Omit<NavMenuProps, "children" | "items" | "open" | "showMenuIcon">) => {
  const iconSize = isNested ? 16 : props.collapsed ? 24 : 20;
  return (
    <>
      {props.showIcon && props.icon && <Icon name={props.icon} className={style.icon} size={iconSize} />}
      {props.collapsed ? null : <span>{props.label}</span>}
    </>
  );
};

export default NavMenu;

// preview/dsr-662/angular/components/side-nav/nav-menu/nav-menu.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, input, output } from "@angular/core";
import { BadgeProps } from "@design-system-rte/core/components/badge/badge.interface";
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { getNavItemLabelIconSize } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.utils";
import { NavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { getDividerAppearanceBySideNavTheme } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavAppearance, SideNavContrast } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, ESCAPE_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { BadgeComponent } from "../../badge/badge.component";
import { DividerComponent } from "../../divider/divider.component";
import { IconComponent } from "../../icon/icon.component";
import { TooltipDirective } from "../../tooltip/tooltip.directive";
import { NavItemComponent } from "../nav-item/nav-item.component";

function getNavTabIndex(parentMenuOpen?: boolean): number {
  return parentMenuOpen === false ? -1 : 0;
}

export interface NavMenuOpenChangeEvent {
  id: string;
  open: boolean;
}

@Component({
  selector: "rte-nav-menu",
  imports: [CommonModule, IconComponent, BadgeComponent, DividerComponent, NavItemComponent, TooltipDirective],
  standalone: true,
  templateUrl: "./nav-menu.component.html",
  styleUrl: "./nav-menu.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavMenuComponent {
  readonly id = input<string | undefined>();
  readonly icon = input<string | undefined>();
  readonly hasLeadingIcon = input<boolean>(true);
  readonly label = input.required<string>();
  readonly isCollapsed = input<boolean>(false);
  readonly link = input<string | undefined>();
  readonly items = input.required<NavItemProps[]>();
  readonly open = input<boolean | undefined>(false);
  readonly hasMenuIcon = input<boolean>(true);
  readonly isNested = input<boolean>(false);
  readonly parentMenuOpen = input<boolean | undefined>();
  readonly appearance = input<SideNavAppearance>("brand");
  readonly contrast = input<SideNavContrast>("high");
  readonly badge = input<BadgeProps | undefined>();
  readonly hasDivider = input<boolean>(false);

  readonly itemClick = output<string>();
  readonly openChange = output<NavMenuOpenChangeEvent>();

  constructor() {
    effect(
      () => {
        if (this.parentMenuOpen() === false && this.open()) {
          this.closeMenu();
        }
      },
      { allowSignalWrites: true },
    );
  }

  readonly hasNestedItems = computed<boolean>(() => !!this.items().length);
  readonly shouldShowMenu = computed<boolean>(() => !this.isCollapsed() && this.hasNestedItems());
  readonly tabIndex = computed<number>(() => getNavTabIndex(this.parentMenuOpen()));

  readonly dividerAppearance = computed(() => getDividerAppearanceBySideNavTheme(this.appearance(), this.contrast()));

  readonly iconSize = computed<number>(() => {
    return getNavItemLabelIconSize(this.isNested(), this.isCollapsed());
  });

  toggleMenu(): void {
    this.openChange.emit({ id: this.id() || this.label(), open: !this.open() });
  }

  handleEscape(): void {
    if (this.open()) {
      this.closeMenu();
    }
  }

  handleKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      this.toggleMenu();
    }
    if (event.key === ESCAPE_KEY) {
      event.preventDefault();
      this.handleEscape();
    }
  }

  hasNestedItemsForItem(item: NavItemProps): item is NavMenuProps {
    return !!item.items?.length;
  }

  handleMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const targetMenu = this.items().find((item) => item.id === event.id);
    if (targetMenu) {
      (targetMenu as NavMenuProps).open = event.open;
    }
  }

  handleMenuClick(itemId: string): void {
    const item = this.items().find((i) => i.id === itemId || i.label === itemId);
    if (item?.onClick) {
      item.onClick();
    }
  }

  private closeMenu(): void {
    this.openChange.emit({ id: this.id() || this.label(), open: false });
  }
}

@if (isCollapsed() && label()) {
  <li
    class="nav-menu-container {{ appearance() }}"
    rteTooltip
    rteTooltipPosition="right"
    rteTooltipAlignment="center"
    [rteTooltipGap]="12"
    [ngClass]="{ collapsed: isCollapsed(), open: open(), nested: isNested() }"
    [rteTooltip]="label()"
    [rteTooltipArrow]="false"
    [rteTooltipShouldFocusTrigger]="false"
  >
    <ng-container [ngTemplateOutlet]="menuContentTemplate"></ng-container>
    <ng-container [ngTemplateOutlet]="nestedMenuTemplate"></ng-container>
  </li>
} @else {
  <li
    class="nav-menu-container {{ appearance() }}"
    [ngClass]="{ collapsed: isCollapsed(), open: open(), nested: isNested() }"
  >
    <ng-container [ngTemplateOutlet]="menuContentTemplate"></ng-container>
    <ng-container [ngTemplateOutlet]="nestedMenuTemplate"></ng-container>
  </li>
}

<ng-template #menuContentTemplate>
  @if (link()) {
    <a
      class="nav-menu"
      [href]="link()!"
      [attr.tabindex]="tabIndex()"
      [attr.aria-label]="label()"
      (click)="toggleMenu()"
    >
      <div class="menu-content-left">
        @if (hasLeadingIcon() && icon()) {
          <rte-icon class="icon" [name]="icon()!" [size]="iconSize()" />
        }
        @if (!isCollapsed()) {
          <span>{{ label() }}</span>
        }
      </div>
      <div class="menu-content-right">
        @if (badge()) {
          <rte-badge
            [badgeType]="badge()!.badgeType || 'brand'"
            [badgeSize]="badge()!.size || 'm'"
            [badgeContent]="badge()!.content || 'number'"
            [count]="badge()!.count"
            [icon]="badge()!.icon || 'notification'"
            [simpleBadge]="true"
          />
        }
        @if (shouldShowMenu() && hasMenuIcon()) {
          <rte-icon name="arrow-chevron-right" class="menu-icon" [ngClass]="{ 'menu-icon-open': open() }" />
        }
      </div>
    </a>
  } @else {
    <span
      class="nav-menu"
      [attr.tabindex]="tabIndex()"
      [attr.aria-label]="label()"
      (click)="toggleMenu()"
      (keydown)="handleKeyDown($event)"
    >
      <div class="menu-content-left">
        @if (hasLeadingIcon() && icon()) {
          <rte-icon class="icon" [name]="icon()!" [size]="iconSize()" />
        }
        @if (!isCollapsed()) {
          <span>{{ label() }}</span>
        }
      </div>
      <div class="menu-content-right">
        @if (badge()) {
          <rte-badge
            [badgeType]="badge()!.badgeType || 'brand'"
            [badgeSize]="badge()!.size || 'm'"
            [badgeContent]="badge()!.content || 'number'"
            [count]="badge()!.count"
            [icon]="badge()!.icon || 'notification'"
            [simpleBadge]="true"
          />
        }
        @if (shouldShowMenu() && hasMenuIcon()) {
          <rte-icon name="arrow-chevron-right" class="menu-icon" [ngClass]="{ 'menu-icon-open': open() }" />
        }
      </div>
    </span>
  }
</ng-template>

<ng-template #nestedMenuTemplate>
  @if (shouldShowMenu()) {
    <ul class="nested-menu" [ngClass]="{ 'nested-menu-open': open() }">
      @if (open()) {
        @for (item of items(); track item.id || item.label) {
          @if (hasNestedItemsForItem(item)) {
            <rte-nav-menu
              [id]="item.id"
              [label]="item.label"
              [icon]="item.icon"
              [hasLeadingIcon]="item.hasLeadingIcon ?? true"
              [isCollapsed]="isCollapsed()"
              [link]="item.link"
              [items]="item.items || []"
              [hasMenuIcon]="hasMenuIcon()"
              [isNested]="true"
              [open]="item.open"
              [parentMenuOpen]="open()"
              [appearance]="appearance()"
              [hasDivider]="item.hasDivider!"
              [badge]="item.badge"
              (itemClick)="handleMenuClick($event)"
              (openChange)="handleMenuOpenChange($event)"
            />
          } @else {
            <li>
              <rte-nav-item
                [id]="item.id"
                [label]="item.label"
                [icon]="item.icon"
                [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                [isCollapsed]="isCollapsed()"
                [link]="item.link"
                [isNested]="true"
                [parentMenuOpen]="open()"
                [appearance]="appearance()"
                [hasDivider]="item.hasDivider!"
                [badge]="item.badge"
                (itemClick)="itemClick.emit($event)"
              />
            </li>
            @if (item.hasDivider) {
              <rte-divider [appearance]="dividerAppearance()" />
            }
          }
        }
      }
    </ul>
  }
</ng-template>

@if (hasDivider()) {
  <rte-divider [appearance]="dividerAppearance()" />
}
