// packages/react/src/components/segmentedControl/SegmentedControl.tsx
import {
  SegmentProps as CoreSegmentProps,
  SegmentedControlProps as CoreSegmentedControlProps,
} from "@design-system-rte/core/components/segmented-control/segmented-control.interface";
import { FOCUSABLE_ELEMENTS_QUERY } from "@design-system-rte/core/constants/dom/dom.constants";
import {
  ARROW_LEFT_KEY,
  ARROW_RIGHT_KEY,
  ENTER_KEY,
  SPACE_KEY,
  TAB_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { forwardRef, MutableRefObject, useEffect, useRef, useState } from "react";

import { useActiveKeyboard } from "../../hooks/useActiveKeyboard";
import Icon from "../icon/Icon";

import style from "./SegmentedControl.module.scss";

export interface SegmentProps extends CoreSegmentProps, Omit<React.HTMLAttributes<HTMLDivElement>, "id"> {
  onClick?: (event: React.MouseEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>) => void;
  parentRef?: MutableRefObject<HTMLDivElement | null>;
}

interface SegmentedControlProps
  extends CoreSegmentedControlProps,
    Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> {
  onChange: (id: string) => void;
}

const SegmentedControl = forwardRef<HTMLDivElement, SegmentedControlProps>(
  ({ options, onChange, selectedSegment, ...props }, ref) => {
    const containerRef: MutableRefObject<HTMLDivElement | null> = useRef<HTMLDivElement>(null);
    const [sliderStyle, setSliderStyle] = useState<{ left: number; width: number }>({ left: 0, width: 0 });

    const getSegmentPosition = (index: number, length: number): SegmentProps["position"] => {
      if (length === 2) return index === 0 ? "left" : "right";
      if (index === 0) return "left";
      if (index === length - 1) return "right";
      return "middle";
    };

    const handleOnClick = (event: React.MouseEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>) => {
      event.stopPropagation();
      const target = event.currentTarget as HTMLDivElement;
      const id = target.getAttribute("id") || "";
      onChange(id);
    };

    useEffect(() => {
      function updateSlider() {
        if (!containerRef.current) return;
        const idx = options.findIndex((opt) => opt.id === selectedSegment);
        if (idx === -1) return;
        const segmentNodes = containerRef.current.querySelectorAll(`.${style.segment}`);
        const node = segmentNodes[idx] as HTMLElement;
        if (node) {
          setSliderStyle({
            left: node.offsetLeft,
            width: node.offsetWidth,
          });
        }
      }
      updateSlider();
      window.addEventListener("resize", updateSlider);
      return () => {
        window.removeEventListener("resize", updateSlider);
      };
    }, [selectedSegment, options]);

    if (options.length <= 1 || options.length > 3) {
      console.warn("SegmentedControl: 'options' should have 2 or 3 items.");
      return null;
    }

    if (options.some((option) => option.icon && option.label)) {
      console.warn("SegmentedControl: Each option must have either 'icon' or 'label', not both.");
      return null;
    }

    return (
      <div
        ref={(node) => {
          containerRef.current = node;
          if (typeof ref === "function") ref(node);
          else if (ref) ref.current = node;
        }}
        role="radiogroup"
        className={style["segmented-control"]}
        {...props}
      >
        <div className={style["segment-slider"]} style={{ left: sliderStyle.left, width: sliderStyle.width }} />
        {options.map((option, index) => (
          <Segment
            key={`${option.id}-${index}`}
            position={getSegmentPosition(index, options.length)}
            onClick={handleOnClick}
            selected={selectedSegment === option.id}
            parentRef={containerRef || ref}
            {...option}
          />
        ))}
      </div>
    );
  },
);

const Segment = ({
  id,
  icon,
  iconAppearance,
  label,
  position,
  selected,
  onClick,
  parentRef,
  ...props
}: SegmentProps) => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const segmentRef = ref && "current" in ref ? ref.current : null;
    const handleFocus = (event: FocusEvent) => {
      if (event.target === segmentRef?.childNodes[0]) {
        if (segmentRef?.childNodes[0]) {
          const focusedElement = segmentRef.childNodes[0] as HTMLElement;
          if (focusedElement.getAttribute("data-selected") !== "true") {
            const elementToFocus = Array.from(document.querySelectorAll(`.${style.segment}`)).find(
              (el) => el.getAttribute("data-selected") === "true",
            );
            if (elementToFocus) {
              (elementToFocus as HTMLElement).focus();
            }
          }
        }
      }
    };

    if (segmentRef) {
      segmentRef.addEventListener("focus", handleFocus);
    }

    return () => {
      if (segmentRef) {
        segmentRef.removeEventListener("focus", handleFocus);
      }
    };
  }, [ref, id]);

  const keyboardHandler = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key === SPACE_KEY || event.key === ENTER_KEY) {
      event.stopPropagation();
      handleClick?.(event);
    } else if (event.key === ARROW_LEFT_KEY || event.key === ARROW_RIGHT_KEY) {
      event.stopPropagation();
      const segmentContainers = parentRef?.current?.querySelectorAll(`.${style["segment-container"]}`);
      if (segmentContainers) {
        const currentActiveElementParent = document.activeElement?.parentElement;
        const currentActiveElementParentIndex =
          currentActiveElementParent != null ? Array.from(segmentContainers).indexOf(currentActiveElementParent) : -1;
        const nextIndex =
          event.key === ARROW_LEFT_KEY ? currentActiveElementParentIndex - 1 : currentActiveElementParentIndex + 1;

        if (segmentContainers[nextIndex]) {
          const firstChild = segmentContainers[nextIndex].firstChild as HTMLElement | null;
          firstChild?.focus();
        }
      }
    }
  };

  const keyboardDownHandler = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key === TAB_KEY) {
      event.stopPropagation();
      const allFocusableElement = (document.querySelectorAll(FOCUSABLE_ELEMENTS_QUERY) ||
        []) as NodeListOf<HTMLDivElement>;

      const currentActiveElement = document.activeElement;

      const currentIndex = Array.from(allFocusableElement).indexOf(currentActiveElement as HTMLDivElement);
      if (event.shiftKey) {
        let previousIndex = currentIndex - 1;
        while (previousIndex > 0 && allFocusableElement[previousIndex].classList.contains(style.segment)) {
          previousIndex--;
        }
        if (previousIndex > 0) {
          allFocusableElement[previousIndex].focus();
        }
      } else {
        let nextIndex = currentIndex + 1;
        while (
          nextIndex < allFocusableElement.length &&
          allFocusableElement[nextIndex].classList.contains(style.segment)
        ) {
          nextIndex++;
        }
        if (nextIndex < allFocusableElement.length) {
          (allFocusableElement[nextIndex] as HTMLElement).focus();
        }
      }
    }
  };

  const { onBlur, onKeyDown, onKeyUp } = useActiveKeyboard<HTMLDivElement>(
    { onKeyUp: keyboardHandler, onKeyDown: keyboardDownHandler },
    {
      id,
      interactiveKeyCodes: [SPACE_KEY, ENTER_KEY, TAB_KEY, ARROW_LEFT_KEY, ARROW_RIGHT_KEY],
    },
  );

  const handleClick = (e: React.MouseEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>) => {
    e.stopPropagation();
    onClick?.(e);
  };

  return (
    <div
      id={id}
      ref={ref}
      role="radio"
      className={style["segment-container"]}
      data-position={position}
      onClick={handleClick}
      {...props}
    >
      <div
        id={id}
        aria-label={label || icon}
        aria-selected={selected}
        className={style.segment}
        data-segment-type={icon ? "icon" : "label"}
        data-selected={selected}
        onKeyDown={onKeyDown}
        onKeyUp={onKeyUp}
        onBlur={onBlur}
        tabIndex={0}
        ref={ref}
      >
        {selected && <Icon name="check-small" appearance="filled" size={24} className={style["selected-icon"]} />}
        <div className={style["segment-content"]}>
          {icon && <Icon name={icon} appearance={(iconAppearance ?? selected) ? "filled" : "outlined"} size={24} />}
          {!icon && label && <span className={style["segment-label"]}>{label}</span>}
        </div>
      </div>
    </div>
  );
};

export default SegmentedControl;

// packages/angular/projects/ds-rte-lib/src/lib/components/segmented-control/segmented-control.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  input,
  output,
  viewChildren,
  AfterViewInit,
  OnDestroy,
} from "@angular/core";
import { getSegmentPosition } from "@design-system-rte/core/components/segmented-control/segmented-control-utils";
import {
  SegmentOptions,
  SegmentProps,
} from "@design-system-rte/core/components/segmented-control/segmented-control.interface";
import { FOCUSABLE_ELEMENTS_QUERY } from "@design-system-rte/core/constants/dom/dom.constants";
import {
  ARROW_LEFT_KEY,
  ARROW_RIGHT_KEY,
  ENTER_KEY,
  SPACE_KEY,
  TAB_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-segmented-control",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./segmented-control.component.html",
  styleUrl: "./segmented-control.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SegmentedControlComponent implements AfterViewInit, OnDestroy {
  readonly options = input<SegmentOptions[]>([]);
  readonly change = output<string>();
  readonly selectedSegment = input<string>();
  readonly ariaLabel = input<string>();
  readonly ariaLabelledBy = input<string>();

  readonly segmentRefs = viewChildren<ElementRef<HTMLDivElement>>("segment");

  sliderLeft = 0;
  sliderWidth = 0;

  ngAfterViewInit() {
    this.updateSlider();
    window.addEventListener("resize", this.updateSlider.bind(this));
  }

  ngOnDestroy() {
    window.removeEventListener("resize", this.updateSlider.bind(this));
  }

  selectSegment(id: string) {
    this.change.emit(id);

    setTimeout(() => this.updateSlider());
  }

  handleKeyDown(event: KeyboardEvent) {
    if (event.key === TAB_KEY) {
      event.preventDefault();
      event.stopPropagation();
      const allFocusableElements = Array.from(document.querySelectorAll(FOCUSABLE_ELEMENTS_QUERY)) as HTMLElement[];
      const currentActiveElement = document.activeElement;
      const currentIndex = allFocusableElements.indexOf(currentActiveElement as HTMLElement);

      if (event.shiftKey) {
        this.focusPreviousNotSegmentElement(currentIndex, allFocusableElements);
      } else {
        this.focusNextNotSegmentElement(currentIndex, allFocusableElements);
      }
    }
  }

  handleKeyUp(event: KeyboardEvent) {
    event.preventDefault();
    event.stopPropagation();
    if (event.key === ARROW_RIGHT_KEY || event.key === ARROW_LEFT_KEY) {
      const allSegmentElements =
        (document.activeElement?.parentElement?.parentElement?.querySelectorAll(
          ".rte-segment",
        ) as NodeListOf<HTMLElement>) || [];

      const currentActiveSegmentElementIndex = Array.from(allSegmentElements).findIndex(
        (element) => element === document.activeElement,
      );

      if (event.key === ARROW_RIGHT_KEY) {
        this.focusNextSegmentElement(currentActiveSegmentElementIndex, allSegmentElements);
      } else if (event.key === ARROW_LEFT_KEY) {
        this.focusPreviousSegmentElement(currentActiveSegmentElementIndex, allSegmentElements);
      }
    } else if (event.key === SPACE_KEY || event.key === ENTER_KEY) {
      const target = event.target as HTMLElement;
      const dataId = target.getAttribute("data-id");
      this.selectSegment(dataId || "");
    }
  }

  getSegmentPosition(index: number): SegmentProps["position"] {
    return getSegmentPosition(index, this.options().length);
  }

  updateSlider() {
    const idx = this.options().findIndex((opt) => opt.id === this.selectedSegment());
    const segment = this.segmentRefs()[idx]?.nativeElement;
    if (segment) {
      this.sliderLeft = segment.offsetLeft;
      this.sliderWidth = segment.offsetWidth;
    }
  }

  private focusNextNotSegmentElement = (currentFocusedElementIndex: number, allFocusableElements: HTMLElement[]) => {
    let nextIndex = currentFocusedElementIndex < allFocusableElements.length - 2 ? currentFocusedElementIndex + 1 : 0;
    while (allFocusableElements[nextIndex]?.classList.contains("rte-segment")) {
      if (nextIndex < allFocusableElements.length - 1) {
        nextIndex++;
      } else {
        nextIndex = 0;
      }
    }

    allFocusableElements[nextIndex].focus();
  };

  private focusNextSegmentElement = (
    currentActiveSegmentElementIndex: number,
    allSegmentElements: NodeListOf<HTMLElement>,
  ) => {
    const nextIndex =
      currentActiveSegmentElementIndex < allSegmentElements.length - 1 ? currentActiveSegmentElementIndex + 1 : 0;

    allSegmentElements[nextIndex].focus();
  };

  private focusPreviousNotSegmentElement = (
    currentFocusedElementIndex: number,
    allFocusableElements: HTMLElement[],
  ) => {
    let previousIndex =
      currentFocusedElementIndex > 0 ? currentFocusedElementIndex - 1 : allFocusableElements.length - 1;

    while (allFocusableElements[previousIndex]?.classList.contains("rte-segment")) {
      if (previousIndex > 0) {
        previousIndex--;
      } else {
        previousIndex = allFocusableElements.length - 1;
      }
    }

    allFocusableElements[previousIndex].focus();
  };

  private focusPreviousSegmentElement = (
    currentActiveSegmentElementIndex: number,
    allSegmentElements: NodeListOf<HTMLElement>,
  ) => {
    const previousIndex =
      currentActiveSegmentElementIndex > 0 ? currentActiveSegmentElementIndex - 1 : allSegmentElements.length - 1;

    allSegmentElements[previousIndex].focus();
  };
}

<div *ngIf="isValidOptions()" class="rte-segmented-control" role="radiogroup" [attr.aria-label]="ariaLabel()">
  <span class="rte-segment-selected-indicator" [ngStyle]="segmentSelectedIndicatorStyle()"></span>
  <ng-container *ngFor="let option of options(); let idx = index">
    <div class="rte-segment-container" [attr.data-position]="getSegmentPosition(idx)">
      <div
        #segment
        role="radio"
        class="rte-segment"
        tabindex="0"
        [attr.data-id]="option.id"
        [attr.data-segment-type]="option.icon ? 'icon' : 'label'"
        [class.selected]="isSegmentSelected(option.id)"
        [attr.aria-checked]="isSegmentSelected(option.id)"
        [attr.aria-label]="option.label"
        (click)="selectSegment(option.id)"
        (keydown)="handleKeyDown($event)"
        (keyup)="handleKeyUp($event)"
      >
        <rte-icon *ngIf="isSegmentSelected(option.id)" name="check-small" class="rte-selected-icon" [size]="24" />
        <div class="rte-segment-content">
          <ng-container *ngIf="option.icon; else label">
            <rte-icon
              [name]="option.icon"
              [size]="24"
              [appearance]="isSegmentSelected(option.id) ? 'filled' : 'outlined'"
            ></rte-icon>
          </ng-container>
          <ng-template #label>
            <span class="rte-segment-label">{{ option.label }}</span>
          </ng-template>
        </div>
        <rte-badge
          *ngIf="shouldDisplayBadge(option)"
          [count]="option.badgeCount"
          [badgeContent]="option.badgeContent!"
          [icon]="option.badgeIcon"
          [badgeType]="option.badgeType!"
          [simpleBadge]="true"
        ></rte-badge>
        >>>>>>> 3210feae (feat(segmented control): add badge)
      </div>
    </div>
  </ng-container>
</div>
