// packages/react/src/components/requiredindicator/RequiredIndicator.tsx
import { REQUIREMENT_INDICATOR_VALUE } from "@design-system-rte/core/components/required-indicator/required-indicator.constant";
import { RequiredIndicatorProps } from "@design-system-rte/core/components/required-indicator/required-indicator.interface";

import Icon from "../icon/Icon";

import styles from "./RequiredIndicator.module.scss";

const RequiredIndicator = ({ required, showLabelRequirement }: RequiredIndicatorProps) => {
  const computedRequirementIndicatorValue = required
    ? showLabelRequirement
      ? REQUIREMENT_INDICATOR_VALUE.required
      : REQUIREMENT_INDICATOR_VALUE.requiredIcon
    : REQUIREMENT_INDICATOR_VALUE.optional;

  return (
    <>
      {(showLabelRequirement || required) && (
        <span
          className={styles["requirement-indicator"]}
          data-required={required}
          data-show-label-requirement={showLabelRequirement}
          aria-hidden="true"
        >
          {computedRequirementIndicatorValue === REQUIREMENT_INDICATOR_VALUE.requiredIcon ? (
            <Icon name="asterisk" size={8} />
          ) : (
            computedRequirementIndicatorValue
          )}
        </span>
      )}
    </>
  );
};

export default RequiredIndicator;

// packages/angular/projects/ds-rte-lib/src/lib/components/input/required-indicator/required-indicator.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, ChangeDetectionStrategy } from "@angular/core";
import { REQUIREMENT_INDICATOR_VALUE } from "@design-system-rte/core";

import { IconComponent } from "../../icon/icon.component";

@Component({
  selector: "rte-required-indicator",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./required-indicator.component.html",
  styleUrl: "./required-indicator.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RequiredIndicatorComponent {
  readonly required = input<boolean>(false);
  readonly showLabelRequirement = input<boolean>(false);

  readonly requirementIndicatorValue = computed(() =>
    this.required()
      ? this.showLabelRequirement()
        ? REQUIREMENT_INDICATOR_VALUE.required
        : REQUIREMENT_INDICATOR_VALUE.requiredIcon
      : REQUIREMENT_INDICATOR_VALUE.optional,
  );
}
