// angular/components/breadcrumbs/breadcrumbs.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import { BadgeProps } from "@design-system-rte/core/components/badge/badge.interface";
import { shouldDisplayBadge as coreShouldDisplayBadge } from "@design-system-rte/core/components/badge/badge.utils";
import { BREADCRUMBS_DEFAULT_ARIA_LABEL } from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.constants";
import {
  BreadcrumbItemProps,
  BreadcrumbsTruncatedItems,
} from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.interface";
import {
  getBreadcrumbsTruncatedItems,
  shouldTruncateBreadcrumbs,
} from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.utils";

import { BadgeComponent } from "../badge/badge.component";
import { DropdownModule } from "../dropdown";
import { IconButtonComponent } from "../icon-button/icon-button.component";

import { BreadcrumbItemComponent } from "./breadcrumb-item/breadcrumb-item.component";

@Component({
  selector: "rte-breadcrumbs",
  imports: [CommonModule, DropdownModule, IconButtonComponent, BreadcrumbItemComponent, BadgeComponent],
  templateUrl: "./breadcrumbs.component.html",
  styleUrl: "./breadcrumbs.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BreadcrumbsComponent {
  readonly items = input<BreadcrumbItemProps[]>([]);
  readonly ariaLabel = input<string>(BREADCRUMBS_DEFAULT_ARIA_LABEL);
  readonly breadcrumbItemMaxWidth = input<number>(150);
  readonly badgeContent = input<BadgeProps["content"]>();
  readonly badgeCount = input<number>();
  readonly badgeIcon = input<string>();
  readonly badgeType = input<BadgeProps["badgeType"]>();
  readonly showBadge = input<boolean>(false);
  readonly badgeSize = input<BadgeProps["size"]>("s");

  readonly truncatedItems = computed<BreadcrumbsTruncatedItems | null>(() => {
    if (shouldTruncateBreadcrumbs(this.items())) {
      return getBreadcrumbsTruncatedItems(this.items());
    }
    return null;
  });

  readonly shouldDisplayBadge = computed((): boolean => {
    return coreShouldDisplayBadge({
      showBadge: !!this.showBadge(),
      badgeContent: this.badgeContent(),
      badgeCount: this.badgeCount(),
      badgeIcon: this.badgeIcon(),
    });
  });
}

<nav
  class="breadcrumbs-container"
  role="navigation"
  [attr.aria-label]="ariaLabel()"
  [ngClass]="{ truncated: truncatedItems()?.truncated?.length }"
>
  @if (truncatedItems()?.truncated?.length) {
    <rte-breadcrumb-item
      [item]="truncatedItems()!.root"
      [breadcrumbItemMaxWidth]="breadcrumbItemMaxWidth()"
    />
    <span aria-hidden="true" class="separator">/</span>
    <span class="breadcrumb-item" rteDropdown [rteDropdownOffset]="8">
      <rte-icon-button
        rteDropdownTrigger
        name="more-horiz"
        role="menu"
        variant="neutral"
        aria-label="More items"
        data-testid="show-more"
        dropdownTrigger
        tabindex="-1"
        [compactSpacing]="true"
      />
      <rte-dropdown-menu [items]="truncatedItems()?.truncated ?? []" />
    </span>
    <span aria-hidden="true" class="separator">/</span>
    @for (
      item of truncatedItems()!.remaining;
      track item.link;
      let i = $index
    ) {
      <rte-breadcrumb-item
        [item]="item"
        [breadcrumbItemMaxWidth]="breadcrumbItemMaxWidth()"
        [isLast]="i === truncatedItems()!.remaining.length - 1"
      />
      @if (i < truncatedItems()!.remaining.length - 1) {
        <span aria-hidden="true" class="separator">/</span>
      }
    }
  } @else {
    @for (item of items(); track item.link; let i = $index) {
      <rte-breadcrumb-item
        [item]="item"
        [breadcrumbItemMaxWidth]="breadcrumbItemMaxWidth()"
        [isLast]="i === items().length - 1"
      />
      @if (i < items().length - 1) {
        <span aria-hidden="true" class="separator">/</span>
      }
    }
  }
</nav>

// packages/react/src/components/breadcrumbs/Breadcrumbs.tsx
import { shouldDisplayBadge } from "@design-system-rte/core/components/badge/badge.utils.ts";
import { BREADCRUMBS_DEFAULT_ARIA_LABEL } from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.constants";
import { BreadcrumbsProps as BreadcrumbsPropsCore } from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.interface";
import {
  getBreadcrumbsTruncatedItems,
  shouldTruncateBreadcrumbs,
} from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.utils";
import { forwardRef, useState, Fragment } from "react";

import Badge from "../badge/Badge.tsx";
import { Dropdown } from "../dropdown/Dropdown";
import { DropdownItem } from "../dropdown/dropdownItem/DropdownItem";
import IconButton from "../iconButton/IconButton";
import { concatClassNames } from "../utils";

import BreadcrumbItem from "./breadcrumbItem/BreadcrumbItem.tsx";
import style from "./Breadcrumbs.module.scss";

export interface BreadcrumbsProps extends BreadcrumbsPropsCore, React.HTMLAttributes<HTMLElement> {}

const Separator = () => (
  <span aria-hidden="true" className={style.separator}>
    /
  </span>
);

const Breadcrumbs = forwardRef<HTMLDivElement, BreadcrumbsProps>(
  (
    {
      items,
      ariaLabel = BREADCRUMBS_DEFAULT_ARIA_LABEL,
      breadcrumbItemMaxWidth,
      badgeContent,
      badgeCount,
      badgeIcon,
      badgeType,
      showBadge,
      ...props
    },
    ref,
  ) => {
    const [isTrucatedListOpened, setIsTruncatedListOpened] = useState<boolean>(false);

    if (shouldTruncateBreadcrumbs(items)) {
      const { root, truncated, remaining } = getBreadcrumbsTruncatedItems(items);

      return (
        <nav
          ref={ref}
          className={concatClassNames(style.breadcrumbsContainer, truncated.length ? style.truncated : "")}
          {...props}
          role="navigation"
          aria-label={ariaLabel}
        >
          <BreadcrumbItem item={root} isLast={false} breadcrumbItemMaxWidth={breadcrumbItemMaxWidth} />
          <Separator />

          <span className={style.breadcrumbItem}>
            <Dropdown
              dropdownId={"breadcrumbs-truncated-list" + ariaLabel}
              onClose={() => {
                setIsTruncatedListOpened(false);
              }}
              trigger={
                <div style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                  <IconButton
                    name="more-horiz"
                    data-testid="show-more"
                    variant="neutral"
                    compactSpacing
                    onClick={() => setIsTruncatedListOpened(!isTrucatedListOpened)}
                  />
                  {shouldDisplayBadge({ showBadge: !!showBadge, badgeContent, badgeCount, badgeIcon }) && (
                    <Badge count={badgeCount} content={badgeContent} icon={badgeIcon} badgeType={badgeType} />
                  )}
                </div>
              }
              isOpen={isTrucatedListOpened}
              offset={6}
            >
              {truncated.map((item, idx) => (
                <DropdownItem
                  key={item.label + idx}
                  label={item.label}
                  link={item.link}
                  badgeCount={item.badgeCount}
                  badgeContent={item.badgeContent}
                  badgeIcon={item.badgeIcon}
                  badgeType={item.badgeType}
                  showBadge={item.showBadge}
                />
              ))}
            </Dropdown>
          </span>
          <span aria-hidden="true" className={style.separator}>
            /
          </span>
          {remaining.map((item, index) => (
            <Fragment key={item.label + index}>
              <BreadcrumbItem
                item={item}
                isLast={index === remaining.length - 1}
                breadcrumbItemMaxWidth={breadcrumbItemMaxWidth}
              />
              {index < remaining.length - 1 && <Separator />}
            </Fragment>
          ))}
        </nav>
      );
    }

    return (
      <nav ref={ref} className={style.breadcrumbsBadge} {...props} role="navigation" aria-label="Fil d'Ariane">
        {items.map((item, index) => (
          <Fragment key={item.label + index}>
            <BreadcrumbItem
              item={item}
              isLast={index === items.length - 1}
              breadcrumbItemMaxWidth={breadcrumbItemMaxWidth}
            />
            {index < items.length - 1 && <Separator />}
          </Fragment>
        ))}
      </nav>
    );
  },
);

export default Breadcrumbs;
