// packages/angular/projects/ds-rte-lib/src/lib/components/breadcrumbs/breadcrumbs.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import {
  BreadcrumbProps,
  BreadcrumbsTruncatedItems,
} from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.interface";
import {
  getBreadcrumbsTruncatedItems,
  shouldTruncateBreadcrumbs,
} from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.utils";

import { LinkComponent } from "../link/link.component";
import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-breadcrumbs",
  imports: [CommonModule, LinkComponent, IconComponent],
  standalone: true,
  templateUrl: "./breadcrumbs.component.html",
  styleUrl: "./breadcrumbs.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BreadcrumbsComponent {
  readonly items = input<BreadcrumbProps[]>([]);

  truncatedItems = computed<BreadcrumbsTruncatedItems | null>(() => {
    if (shouldTruncateBreadcrumbs(this.items())) {
      return getBreadcrumbsTruncatedItems(this.items());
    }
    return null;
  });

  // TODO: replace this placeholder functionality for the Dropdown component
  truncatedItemsText = computed(() => {
    return this.truncatedItems()?.truncated.map((item) => item.label).join(", ");
  });
}

<nav class="breadcrumbs-container" role="navigation" aria-label="Fil d'Ariane">
  @if (truncatedItems()?.truncated?.length) {
    <div class="breadcrumbs-truncated">
      <div class="breadcrumb-item">
        <rte-link
        [href]="truncatedItems()!.root.link"
        [label]="truncatedItems()!.root.label"
        [subtle]="true"
      />
      </div>
      <span aria-hidden="true" class="separator">/</span>
      <span title="More items: {{ truncatedItemsText() }}" class="breadcrumb-item">
        <rte-icon name="more-horiz" [size]="12" tabIndex="0" role="menu" aria-label="More items" data-testid="show-more"/>
      </span>
      <span aria-hidden="true" class="separator">/</span>
      @for (item of truncatedItems()!.remaining; track item.link; let i = $index) {
        <div class="breadcrumb-item">
          @if (i === truncatedItems()!.remaining.length - 1) {
            <a role="link" [attr.aria-label]="item.label" aria-current="page" tabindex="0">
              {{ item.label }}
            </a>
          } @else {
            <rte-link [href]="item.link" [label]="item.label" [subtle]="true"/>
          }
        </div>
        @if (i < truncatedItems()!.remaining.length - 1) {
          <span aria-hidden="true" class="separator">/</span>
        }
      }
    </div>
  } @else {
      @for (item of items(); track item.link; let i = $index) {
        <div class="breadcrumb-item">
          @if (i === items().length - 1) {
            <a role="link" [attr.aria-label]="item.label" aria-current="page" tabindex="0">
              {{ item.label }}
            </a>
          } @else {
            <rte-link [href]="item.link" [label]="item.label" [subtle]="true"/>
          }
        </div>
        @if (i < items().length - 1) {
          <span aria-hidden="true" class="separator">/</span>
        }
      }
  }
</nav>

// packages/react/src/components/breadcrumbs/Breadcrumbs.tsx
import { BreadcrumbsProps as BreadcrumbsPropsCore } from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.interface";
import {
  getBreadcrumbsTruncatedItems,
  shouldTruncateBreadcrumbs,
} from "@design-system-rte/core/components/breadcrumbs/breadcrumbs.utils";
import { forwardRef } from "react";

import { Icon } from "../..";
import Link from "../link/Link";

import style from "./Breadcrumbs.module.scss";

export interface BreadcrumbsProps extends BreadcrumbsPropsCore, React.HTMLAttributes<HTMLDivElement> {}

const Breadcrumbs = forwardRef<HTMLDivElement, BreadcrumbsProps>(({ items, ...props }, ref) => {
  if (shouldTruncateBreadcrumbs(items)) {
    const { root, truncated, remaining } = getBreadcrumbsTruncatedItems(items);

    return (
      <nav ref={ref} className={style.breadcrumbsBadge} {...props} role="navigation" aria-label="Fil d'Ariane">
        <div className={style.breadcrumbsTruncated}>
          <Link
            subtle
            href={root.link}
            label={root.label}
            style={{ color: "var(--content-tertiary)" }}
            className={style.breadcrumbItem}
          />
          <span aria-hidden="true" className={style.separator}>
            /
          </span>
          <span
            title={`More items: ${truncated.map((item) => item.label).join(", ")}`}
            className={style.breadcrumbItem}
          >
            <Icon
              name="more-horiz"
              size={12}
              tabIndex={0}
              role="menu"
              aria-label="More items"
              data-testid="show-more"
            />
          </span>
          <span aria-hidden="true" className={style.separator}>
            /
          </span>
          {remaining.map((item, index) => (
            <div key={item.link} className={style.breadcrumbItem}>
              {index === remaining.length - 1 ? (
                <a role="link" aria-label={item.label} aria-current="page" tabIndex={0}>
                  {item.label}
                </a>
              ) : (
                <Link href={item.link} label={item.label} subtle style={{ color: "var(--content-tertiary)" }} />
              )}
              {index < remaining.length - 1 && (
                <span aria-hidden="true" className={style.separator}>
                  /
                </span>
              )}
            </div>
          ))}
        </div>
      </nav>
    );
  } else {
    return (
      <div ref={ref} className={style.breadcrumbsBadge} {...props} role="navigation" aria-label="Fil d'Ariane">
        {items.map((item, index) => (
          <div key={item.link} className={style.breadcrumbItem}>
            {index === items.length - 1 ? (
              <a role="link" aria-label={item.label} aria-current="page" tabIndex={0}>
                {item.label}
              </a>
            ) : (
              <Link href={item.link} label={item.label} subtle style={{ color: "var(--content-tertiary)" }} />
            )}
            {index < items.length - 1 && (
              <span aria-hidden="true" className={style.separator}>
                /
              </span>
            )}
          </div>
        ))}
      </div>
    );
  }
});

export default Breadcrumbs;
