// packages/angular/projects/ds-rte-lib/src/lib/components/textarea/textarea.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, output, ElementRef, viewChild } from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import {
  TEXTAREA_ICON_SIZE,
  TEXTAREA_REQUIREMENT_INDICATOR_VALUE,
} from "@design-system-rte/core/components/textarea/textarea.constants";
import type {
  TextareaAssistiveTextAppearance,
  TextareaLabelPosition,
} from "@design-system-rte/core/components/textarea/textarea.interface";

import { IconComponent } from "../icon/icon.component";
import { LinkComponent } from "../link/link.component";

@Component({
  selector: "rte-textarea",
  imports: [CommonModule, IconComponent, LinkComponent],
  standalone: true,
  templateUrl: "./textarea.component.html",
  styleUrl: "./textarea.component.scss",
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: TextareaComponent,
      multi: true,
    },
  ],
})
export class TextareaComponent {
  readonly id = input<string | undefined>(undefined);
  readonly name = input<string | undefined>(undefined);
  readonly ariaLabelledby = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly labelId = input<string | undefined>(undefined);
  readonly labelPosition = input<TextareaLabelPosition>("top");
  readonly assistiveTextLabel = input<string | undefined>(undefined);
  readonly assistiveTextAppearance = input<TextareaAssistiveTextAppearance>("description");
  readonly assistiveTextLink = input<string | undefined>(undefined);
  readonly required = input<boolean>(false);
  readonly showLabelRequirement = input<boolean>(false);
  readonly resizeable = input<boolean | string>(true);
  readonly maxLength = input<number | undefined>(undefined);
  readonly disabled = input<boolean>(false);
  readonly readOnly = input<boolean>(false);
  readonly value = input<string | undefined>(undefined);
  readonly rows = input<number>(3);
  readonly defaultValue = input<string | undefined>(undefined);
  readonly showCounter = input<boolean>(false);

  readonly assistiveTextIconSize = TEXTAREA_ICON_SIZE;

  readonly requirementIndicatorValue = computed(() =>
    this.required()
      ? this.showLabelRequirement()
        ? TEXTAREA_REQUIREMENT_INDICATOR_VALUE.required
        : TEXTAREA_REQUIREMENT_INDICATOR_VALUE.requiredIcon
      : TEXTAREA_REQUIREMENT_INDICATOR_VALUE.optional,
  );

  readonly change = output<Event>();
  readonly blur = output<FocusEvent>();

  readonly textareaRef = viewChild<ElementRef<HTMLTextAreaElement>>("textarea");

  readonly isAssistiveTextLinkVisible = computed(
    () => this.assistiveTextAppearance() === "link" && this.assistiveTextLink() !== undefined,
  );

  characterCount = 0;

  readonly isCounterVisible = computed(() => {
    return this.showCounter() && this.maxLength();
  });

  onInput(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    this.characterCount = target.value.length;
    this.change.emit(event);
  }

  onBlur(event: FocusEvent) {
    this.textareaRef()?.nativeElement?.scrollTo({ top: 0 });
    this.blur.emit(event);
  }
}

<div class="container" [attr.data-label-position]="labelPosition()"> 
  <label *ngIf="label() && labelPosition() === 'side'" [attr.data-label-position]="labelPosition()" [attr.id]="labelId()" [attr.for]="id()">{{label()}}<span *ngIf="required() || showLabelRequirement()" class="requirement-indicator" aria-hidden="true" [ngClass]="{'required': required(), 'show-label-requirement': showLabelRequirement() }">{{requirementIndicatorValue()}}</span></label>
  <div class="top-position-container" [attr.data-label-position]="labelPosition()">
    <div class="header-container" [attr.data-label-position]="labelPosition()">
      <label *ngIf="label() && labelPosition() === 'top'" [attr.id]="labelId()" [attr.for]="id()">{{label()}}<span *ngIf="required() || showLabelRequirement()" class="requirement-indicator" aria-hidden="true" [ngClass]="{'required': required(), 'show-label-requirement': showLabelRequirement() }">{{requirementIndicatorValue()}}</span></label>
      <span *ngIf="isCounterVisible()" class="character-counter">{{ characterCount }}/{{ maxLength() }}</span>
    </div>
    <div class="textarea-container" [attr.data-label-position]="labelPosition()">
      <textarea
      #textarea
      class="textarea {{ assistiveTextAppearance() }}"
      [class.resizeable]="resizeable()"
      [attr.id]="id()"
      [attr.name]="name()"
      [attr.aria-labelledby]="labelId() || ariaLabelledby()"
      [attr.required]="required() || null"
      [attr.maxLength]="maxLength() !== undefined ? maxLength() : null"
      [attr.disabled]="disabled() || null"
      [attr.readonly]="readOnly() || null"
      [value]="value() !== undefined ? value() : null"
      [defaultValue]="defaultValue() !== undefined ? defaultValue() : null"
      [attr.rows]="rows()"
      (input)="onInput($event)"
      (blur)="onBlur($event)"
      ></textarea>
      <rte-link *ngIf="isAssistiveTextLinkVisible()" class="assistive-text-link" [externalLink]="true" [href]="assistiveTextLink() || ''" [label]="assistiveTextLabel() || ''">
      </rte-link>
      <div *ngIf="assistiveTextAppearance() !== 'link'" class="assistive-text {{ assistiveTextAppearance() }}" [ngClass]="{'disabled' : disabled()}">
        <rte-icon *ngIf="assistiveTextAppearance() === 'error'" name="error" [size]="assistiveTextIconSize"></rte-icon>
        <rte-icon *ngIf="assistiveTextAppearance() === 'success'" name="check-circle" [size]="assistiveTextIconSize"></rte-icon>
        <span>{{ assistiveTextLabel() }}</span>
      </div>
    </div>
  </div>
</div>

// packages/react/src/components/textarea/Textarea.tsx
import {
  TEXTAREA_ICON_SIZE,
  TEXTAREA_REQUIREMENT_INDICATOR_VALUE,
} from "@design-system-rte/core/components/textarea/textarea.constants";
import type { TextareaProps as CoreTextareaProps } from "@design-system-rte/core/components/textarea/textarea.interface";
import { ChangeEvent, FocusEvent, forwardRef, MutableRefObject, TextareaHTMLAttributes, useRef, useState } from "react";

import Icon from "../icon/Icon";
import Link from "../link/Link";
import { concatClassNames } from "../utils";

import style from "./Textarea.module.scss";

interface TextareaProps
  extends CoreTextareaProps,
    Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, "onChange" | "value" | "defaultValue" | "placeholder"> {
  onChange?: (event: ChangeEvent<HTMLTextAreaElement>) => void;
}

const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      className = "",
      id,
      name,
      required = false,
      onChange,
      onBlur,
      label,
      labelId,
      labelPosition = "top",
      assistiveTextLabel,
      assistiveTextAppearance = "description",
      ["aria-labelledby"]: ariaLabelledby,
      assistiveTextLink,
      showLabelRequirement = false,
      resizeable = "true",
      maxLength,
      defaultValue,
      showCounter,
      value,
      ...props
    },
    ref,
  ) => {
    const [characterCount, setCharacterCount] = useState(value?.length || defaultValue?.length || 0);

    const textareaRef: MutableRefObject<HTMLTextAreaElement | null> = useRef<HTMLTextAreaElement>(null);

    const displayCounter = showCounter && maxLength;

    const handleBlur = (event: FocusEvent<HTMLTextAreaElement, Element>) => {
      if (onBlur) {
        onBlur(event);
      }
      textareaRef.current?.scrollTo({ top: 0 });
    };

    const handleChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
      if (onChange) {
        onChange(event);
      }
      if (maxLength) {
        setCharacterCount(event.target.value.length);
      }
    };

    const computedRequirementIndicatorValue = required
      ? showLabelRequirement
        ? TEXTAREA_REQUIREMENT_INDICATOR_VALUE.required
        : TEXTAREA_REQUIREMENT_INDICATOR_VALUE.requiredIcon
      : TEXTAREA_REQUIREMENT_INDICATOR_VALUE.optional;

    return (
      <div className={style.container} data-label-position={labelPosition}>
        {label && labelPosition === "side" && (
          <label id={labelId} className={style.label} htmlFor={id} data-label-position={labelPosition}>
            {label}
            {(showLabelRequirement || required) && (
              <span
                className={style["requirement-indicator"]}
                data-required={required}
                data-show-label-requirement={showLabelRequirement}
                aria-hidden="true"
              >
                {computedRequirementIndicatorValue}
              </span>
            )}
          </label>
        )}
        <div className={style["top-position-container"]} data-label-position={labelPosition}>
          <div className={style["header-container"]} data-label-position={labelPosition}>
            {label && labelPosition === "top" && (
              <label id={labelId} className={style.label} htmlFor={id} data-label-position={labelPosition}>
                {label}
                {(showLabelRequirement || required) && (
                  <span
                    className={style["requirement-indicator"]}
                    data-required={required}
                    data-show-label-requirement={showLabelRequirement}
                    aria-hidden="true"
                  >
                    {computedRequirementIndicatorValue}
                  </span>
                )}
              </label>
            )}
            {displayCounter && (
              <span className={style["character-counter"]}>
                {characterCount}/{maxLength}
              </span>
            )}
          </div>
          <div className={style["textarea-container"]} data-label-position={labelPosition}>
            <textarea
              ref={(node) => {
                textareaRef.current = node;
                if (typeof ref === "function") ref(node);
                else if (ref) ref.current = node;
              }}
              id={id}
              name={name}
              className={concatClassNames(style.textarea, className)}
              data-resizeable={resizeable}
              data-assistive-text-appearance={assistiveTextAppearance}
              onChange={handleChange}
              aria-labelledby={labelId || ariaLabelledby}
              maxLength={maxLength}
              onBlur={handleBlur}
              defaultValue={defaultValue}
              value={value}
              {...props}
            />
            {assistiveTextLabel && (
              <>
                {assistiveTextAppearance === "link" ? (
                  <Link
                    label={assistiveTextLabel}
                    href={assistiveTextLink}
                    externalLink
                    className={style["assistive-text-link"]}
                  />
                ) : (
                  <div
                    className={style["assistive-text"]}
                    data-assistive-text-appearance={assistiveTextAppearance}
                    data-disabled={props.disabled}
                  >
                    {assistiveTextAppearance === "error" ? (
                      <Icon name="error" size={TEXTAREA_ICON_SIZE} />
                    ) : assistiveTextAppearance === "success" ? (
                      <Icon name={"check-circle"} size={TEXTAREA_ICON_SIZE} />
                    ) : null}

                    <span>{assistiveTextLabel}</span>
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    );
  },
);

export default Textarea;
