// packages/angular/projects/ds-rte-lib/src/lib/components/dynamic-tab/dynamic-tab-item/dynamic-tab-item.component.ts
import { CommonModule } from "@angular/common";
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  effect,
  ElementRef,
  inject,
  input,
  OnDestroy,
  output,
  signal,
  viewChild,
} from "@angular/core";
import { waitForNextFrame } from "@design-system-rte/core/common/animation";
import {
  DYNAMIC_TAB_CLOSE_ANIMATION_MS,
  DYNAMIC_TAB_ITEM_SMALL_WIDTH,
  DYNAMIC_TAB_ITEM_XSMALL_WIDTH,
  DYNAMIC_TAB_MIN_WIDTH,
} from "@design-system-rte/core/components/dynamic-tab/dynamic-tab.constants";
import {
  DynamicTabAppearance,
  DynamicTabItemOption,
} from "@design-system-rte/core/components/dynamic-tab/dynamic-tab.interface";
import { ENTER_KEY, ESCAPE_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { getTextWidth } from "@design-system-rte/core/utils/string.utils";

import { BadgeComponent } from "../../badge/badge.component";
import { IconComponent } from "../../icon/icon.component";

@Component({
  selector: "rte-dynamic-tab-item",
  imports: [CommonModule, IconComponent, BadgeComponent],
  templateUrl: "./dynamic-tab-item.component.html",
  styleUrl: "./dynamic-tab-item.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "rte-dynamic-tab-item",
    role: "tab",
    "[attr.data-tab-id]": "option().id",
    "[attr.data-active]": "isActive()",
    "[attr.data-appearance]": "appearance()",
    "[attr.data-compact-spacing]": "compactSpacing()",
    "[attr.data-is-animating]": "isAnimating()",
    "[attr.data-is-disappearing]": "isDisappearing()",
    "[attr.aria-selected]": "isActive()",
    "[tabIndex]": "isActive() ? 0 : -1",
    "[style.width.px]": "tabWidth()",
    "[style.min-width.px]": "tabWidth()",
    "[style.max-width.px]": "tabWidth()",
    "(click)": "onTabClick()",
    "(keydown)": "onTabKeydown($event)",
    "(keyup)": "onTabKeyup($event)",
  },
})
export class DynamicTabItemComponent implements AfterViewInit, OnDestroy {
  readonly hostElement = inject(ElementRef<HTMLElement>);

  readonly option = input.required<DynamicTabItemOption>();
  readonly appearance = input<DynamicTabAppearance>("neutral");
  readonly isActive = input(false);
  readonly compactSpacing = input(false);
  readonly isEditable = input(true);
  readonly isClosable = input(true);
  readonly iconName = input<string | undefined>(undefined);
  readonly tabWidth = input(DYNAMIC_TAB_MIN_WIDTH);
  readonly isMoving = input(false);

  readonly tabClick = output<string>();
  readonly closeTab = output<string>();
  readonly changeTitle = output<{ id: string; title: string }>();
  readonly enterMoveMode = output<void>();
  readonly tabKeydown = output<KeyboardEvent>();

  readonly titleInputElement = viewChild<ElementRef<HTMLInputElement>>("titleInput");

  readonly isEditing = signal(false);
  readonly titleText = signal("");
  readonly previousTabTitle = signal("");
  readonly isAnimating = signal(false);
  readonly isDisappearing = signal(false);

  readonly shouldDisplayBadge = signal(false);
  readonly shouldDisplayIcon = signal(false);
  readonly shouldDisplayText = signal(false);
  readonly shouldDisplayCloseButton = signal(false);
  readonly isZeroToExtraSmall = signal(false);

  private resizeObserver: ResizeObserver | null = null;
  private closeAnimationTimeout: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    effect(() => {
      const title = this.option().title;

      if (!this.isEditing()) {
        this.titleText.set(title);
        this.previousTabTitle.set(title);
      }
    });
  }

  ngAfterViewInit(): void {
    this.isAnimating.set(true);
    this.updateDisplayElements(this.hostElement.nativeElement);
    this.resizeObserver = new ResizeObserver(() => this.updateDisplayElements(this.hostElement.nativeElement));
    this.resizeObserver.observe(this.hostElement.nativeElement);
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();

    if (this.closeAnimationTimeout) {
      clearTimeout(this.closeAnimationTimeout);
    }
  }

  onTabClick(): void {
    this.tabClick.emit(this.option().id);
  }

  onTabKeydown(event: KeyboardEvent): void {
    if (this.isEditing()) {
      this.handleEditingKeydown(event);
      return;
    }

    this.tabKeydown.emit(event);
  }

  onTabKeyup(event: KeyboardEvent): void {
    if (this.isEditing() || !this.isActive() || event.key !== SPACE_KEY) {
      return;
    }

    this.enterMoveMode.emit();
  }

  onTitleDoubleClick(): void {
    if (!this.isEditable() || !this.isActive()) {
      return;
    }

    this.enableEditingMode();
  }

  onTitleKeydown(event: KeyboardEvent): void {
    if (this.isEditing()) {
      return;
    }

    if ((event.key === ENTER_KEY || event.key === SPACE_KEY) && this.isActive() && this.isEditable()) {
      event.stopPropagation();
      this.enableEditingMode();
    }
  }

  onTitleInput(event: Event): void {
    const inputElement = event.target as HTMLInputElement;
    this.titleText.set(inputElement.value);
    this.updateInputWidth(inputElement);
  }

  onTitleBlur(): void {
    if (this.isEditable()) {
      this.commitTabTitle();
    }
  }

  onCloseClick(event: MouseEvent): void {
    event.stopPropagation();
    this.startCloseAnimation();
  }

  onCloseKeydown(event: KeyboardEvent): void {
    if (event.key === ENTER_KEY || event.key === SPACE_KEY) {
      event.preventDefault();
      event.stopPropagation();
      this.startCloseAnimation();
    }
  }

  onCloseKeyup(event: KeyboardEvent): void {
    if (event.key === ENTER_KEY || event.key === SPACE_KEY) {
      event.preventDefault();
      event.stopPropagation();
    }
  }

  hasBadgeContent(): boolean {
    const option = this.option();
    return !!(
      (option.badgeCount && option.badgeCount > 0 && option.badgeContent === "number") ||
      (option.badgeContent === "icon" && option.badgeIcon)
    );
  }

  private updateDisplayElements(hostElement: HTMLElement): void {
    const width = hostElement.offsetWidth || this.tabWidth();
    const isActive = this.isActive();
    const isClosable = this.isClosable();
    const hasBadge = this.hasBadgeContent();
    const hasIcon = !!this.iconName();

    if (width <= DYNAMIC_TAB_MIN_WIDTH && isActive) {
      this.isZeroToExtraSmall.set(true);
      this.shouldDisplayBadge.set(false);
      this.shouldDisplayIcon.set(false);
      this.shouldDisplayText.set(false);
      this.shouldDisplayCloseButton.set(isClosable);
      return;
    }

    const isZeroToExtraSmall = width <= DYNAMIC_TAB_ITEM_XSMALL_WIDTH;
    const isExtraSmallToSmall = width > DYNAMIC_TAB_ITEM_XSMALL_WIDTH && width <= DYNAMIC_TAB_ITEM_SMALL_WIDTH;
    const isSmallOrMore = width > DYNAMIC_TAB_ITEM_SMALL_WIDTH;

    this.isZeroToExtraSmall.set(isZeroToExtraSmall);
    this.shouldDisplayBadge.set(hasBadge && (!isZeroToExtraSmall || !isActive));
    this.shouldDisplayIcon.set(hasIcon && (isSmallOrMore || (isZeroToExtraSmall && !hasBadge) || isExtraSmallToSmall));
    this.shouldDisplayText.set(isExtraSmallToSmall || isSmallOrMore);
    this.shouldDisplayCloseButton.set(
      isClosable && (isSmallOrMore || ((isZeroToExtraSmall || isExtraSmallToSmall) && isActive)),
    );
  }

  private enableEditingMode(): void {
    this.isEditing.set(true);
    this.previousTabTitle.set(this.titleText());

    waitForNextFrame(() => {
      const inputElement = this.titleInputElement()?.nativeElement;

      if (inputElement) {
        this.updateInputWidth(inputElement);
        inputElement.focus();
        inputElement.select();
      }
    });
  }

  private handleEditingKeydown(event: KeyboardEvent): void {
    event.stopPropagation();

    if (event.key === ENTER_KEY) {
      this.commitTabTitle();
      return;
    }

    if (event.key === ESCAPE_KEY) {
      this.cancelEditing();
    }
  }

  private commitTabTitle(): void {
    this.isEditing.set(false);
    const trimmedTitle = this.titleText().trim();

    if (trimmedTitle === "") {
      this.titleText.set(this.previousTabTitle());
      return;
    }

    if (trimmedTitle !== this.previousTabTitle()) {
      this.changeTitle.emit({ id: this.option().id, title: trimmedTitle });
    }

    this.previousTabTitle.set(trimmedTitle);
  }

  private cancelEditing(): void {
    this.isEditing.set(false);
    this.titleText.set(this.previousTabTitle());
  }

  private updateInputWidth(inputElement: HTMLInputElement): void {
    const measure = getTextWidth(inputElement);
    inputElement.style.width = `${measure(this.titleText()) + 8}px`;
  }

  private startCloseAnimation(): void {
    this.isDisappearing.set(true);

    this.closeAnimationTimeout = setTimeout(() => {
      this.closeTab.emit(this.option().id);
    }, DYNAMIC_TAB_CLOSE_ANIMATION_MS);
  }
}

@if (shouldDisplayBadge() || shouldDisplayIcon() || shouldDisplayText()) {
  <div class="rte-dynamic-tab-item__content">
    @if (shouldDisplayBadge()) {
      <rte-badge
        badgeContent="empty"
        [simpleBadge]="true"
        [badgeType]="option().badgeType || 'neutral'"
        [icon]="option().badgeIcon || ''"
        [count]="option().badgeCount"
        [class.rte-dynamic-tab-item__badge-compact]="isZeroToExtraSmall()"
      />
    }

    @if (shouldDisplayIcon() && iconName()) {
      <rte-icon [name]="iconName()!" [appearance]="isActive() ? 'filled' : 'outlined'" />
    }

    @if (shouldDisplayText()) {
      <div
        #tabTitle
        class="rte-dynamic-tab-item__title"
        [tabIndex]="isActive() && isEditable() ? 0 : -1"
        (dblclick)="onTitleDoubleClick()"
        (keydown)="onTitleKeydown($event)"
      >
        @if (isEditing()) {
          <input
            #titleInput
            type="text"
            class="rte-dynamic-tab-item__title-input"
            [value]="titleText()"
            (input)="onTitleInput($event)"
            (blur)="onTitleBlur()"
          />
        } @else {
          <span [attr.data-is-animating]="isAnimating()">{{ titleText() }}</span>
        }
      </div>
    }
  </div>
}

@if (isClosable() && shouldDisplayCloseButton()) {
  <button
    type="button"
    class="rte-dynamic-tab-item__close-button"
    [attr.aria-label]="'Fermer l\'onglet ' + titleText()"
    (click)="onCloseClick($event)"
    (keydown)="onCloseKeydown($event)"
    (keyup)="onCloseKeyup($event)"
  >
    <rte-icon name="close" />
  </button>
}

// packages/react/src/components/dynamicTab/dynamicTabItem/DynamicTabItem.tsx
import {
  ARROW_LEFT_KEY,
  ARROW_RIGHT_KEY,
  DynamicTabItemProps,
  ENTER_KEY,
  ESCAPE_KEY,
  SPACE_KEY,
  waitForNextFrame,
  getTextWidth,
} from "@design-system-rte/core";
import { RestrictToHorizontalAxis } from "@dnd-kit/abstract/modifiers";
import { useSortable } from "@dnd-kit/react/sortable";
import { useRef, KeyboardEvent, useState, useEffect, useCallback } from "react";

import useAnimatedMount from "../../../hooks/useAnimatedMount";
import Badge from "../../badge/Badge";
import useDisplayTabItemElement from "../../dynamicTab/hooks/useDisplayTabItemElement";
import Icon from "../../icon/Icon";

import styles from "./DynamicTabItem.module.scss";

const DynamicTabItem = ({
  id,
  index,
  title,
  parentId,
  appearance = "neutral",
  isActive = false,
  onClick,
  onClickClose,
  onChangeTabTitle,
  compactSpacing = false,
  isEditable = true,
  badgeContent,
  badgeCount,
  badgeIcon,
  badgeType,
  iconName,
  isClosable = true,
  updateIndicator,
  isHidden = false,
  setIsMoving: setIsMovingExternal,
  isMoving: isMovingExternal,
}: DynamicTabItemProps) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const tabItemRef = useRef<HTMLLIElement | null>(null);
  const tabItemContentRef = useRef<HTMLDivElement | null>(null);
  const titleRef = useRef<HTMLDivElement | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [tabTitle, setTabTitle] = useState(title);
  const [previousTabTitle, setPreviousTabTitle] = useState(title);
  const [isRendering, setIsRendering] = useState(false);
  const [isDisappearing, setIsDisappearing] = useState(false);

  const { isAnimating } = useAnimatedMount(isRendering, 300);
  const { isAnimating: isAnimatingDisappearing } = useAnimatedMount(isDisappearing, 300);

  const hasBadgeContent = !!(
    (badgeCount && badgeCount > 0 && badgeContent === "number") ||
    (badgeContent === "icon" && badgeIcon)
  );

  const { shouldDisplayBadge, shouldDisplayIcon, shouldDisplayText, shouldDisplayCloseButton, isZeroToXS } =
    useDisplayTabItemElement({
      tabItem: tabItemRef,
      isActive,
      hasBadgeContent,
      iconName,
      isClosable,
    });

  const handleKeyDown = (event: KeyboardEvent<HTMLLIElement>) => {
    const key = event.key;

    if (isEditing) {
      event?.stopPropagation();
      handleKeyboardEditingMode(key);
      return;
    }

    if (key === ARROW_RIGHT_KEY || key === ARROW_LEFT_KEY) {
      event.preventDefault();
      if (!isMovingExternal) {
        focusItem(key === ARROW_RIGHT_KEY ? "next" : "previous");
      }
      return;
    }

    if (key === ENTER_KEY || key === SPACE_KEY) {
      event.preventDefault();

      onClick?.();
    }
  };

  const handleKeyUp = (event: KeyboardEvent<HTMLLIElement>) => {
    const key = event.key;
    if (key === SPACE_KEY) {
      if (isActive && !isEditing) {
        setIsMovingExternal?.(true);
        return;
      }
    }
  };

  const handleOnBlur = () => {
    if (isEditable) {
      commitTabTitle();
    }
  };

  const handleKeyboardEditingMode = (key: string) => {
    if (key === ENTER_KEY) {
      commitTabTitle();
      return;
    }
    if (key === ESCAPE_KEY) {
      setIsEditing(false);
      resetTabTitle();
      return;
    }
  };

  const handleOnKeyDownCloseTab = (event: React.KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === ENTER_KEY || event.key === SPACE_KEY) {
      event.preventDefault();
      event.stopPropagation();
      handleOnClickCloseTab(event as unknown as React.MouseEvent<HTMLButtonElement, MouseEvent>);
    }
  };

  const handleOnKeyUpCloseTab = (event: React.KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === ENTER_KEY || event.key === SPACE_KEY) {
      event.preventDefault();
      event.stopPropagation();
    }
  };

  const handleOnClickCloseTab = (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    event.stopPropagation();
    setIsDisappearing(true);
    updateIndicator?.();
    setTimeout(() => {
      onClickClose?.();
    }, 300);
  };

  const handleOnDoubleClick = () => {
    if (isEditable) {
      enableEditingMode();
    }
  };

  const handleOnChangeTabTitle = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newTitle = event.target.value;
    setTabTitle(newTitle);

    if (inputRef.current) {
      const inputElement = inputRef.current;
      const width = getTextWidth(inputElement);
      event.target.style.width = `${width(newTitle) + 8}px`;
    }
  };

  const handleOnTitleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if ((event.key === ENTER_KEY || event.key === SPACE_KEY) && !isEditing) {
      event.stopPropagation();
      enableEditingMode();
    }
  };

  const enableEditingMode = () => {
    setIsEditing(true);
    setPreviousTabTitle(tabTitle);
    waitForNextFrame(() => {
      inputRef.current?.focus();
    });
  };

  const commitTabTitle = () => {
    setIsEditing(false);
    if (tabTitle.trim() === "") {
      resetTabTitle();
    } else {
      validateTabTitle();
    }
  };

  const validateTabTitle = () => {
    onChangeTabTitle?.(tabTitle);
    setPreviousTabTitle(tabTitle);
  };

  const resetTabTitle = () => {
    setTabTitle(previousTabTitle);
  };

  const focusItem = (direction: "next" | "previous") => {
    const parent = document.getElementById(parentId);
    if (!parent) return;
    const allTabItems = Array.from(parent.querySelectorAll(`.${styles["rte-dynamic-tab-item"]}`)) as HTMLElement[];
    const currentIndex = allTabItems.findIndex((tab) => tab === document.activeElement);
    let newIndex = computeNextItemIndex(currentIndex, allTabItems.length, direction);
    let counter = 0;
    const maxIterations = allTabItems.length;
    while (allTabItems[newIndex].getAttribute("data-disabled") === "true" && counter < maxIterations) {
      newIndex = computeNextItemIndex(newIndex, allTabItems.length, direction);
      counter++;
    }
    allTabItems[newIndex].focus();
    allTabItems[newIndex].click();
  };

  const focusSelectedItem = useCallback(() => {
    const parent = document.getElementById(parentId);
    if (!parent) return;
    const allTabItems = Array.from(parent.querySelectorAll(`.${styles["rte-dynamic-tab-item"]}`)) as HTMLElement[];
    allTabItems.find((tab) => tab.getAttribute("aria-active") === "true")?.focus();
  }, [parentId]);

  const computeNextItemIndex = (currentIndex: number, totalItems: number, direction: "next" | "previous") => {
    return direction === "next" ? (currentIndex + 1) % totalItems : (currentIndex - 1 + totalItems) % totalItems;
  };

  const { ref } = useSortable({
    id,
    index,
    modifiers: [RestrictToHorizontalAxis],
  });

  useEffect(() => {
    setIsRendering(true);
    updateIndicator?.();
    focusSelectedItem();
  }, [focusSelectedItem, updateIndicator]);

  return (
    <li
      id={id}
      ref={(node) => {
        ref(node);
        tabItemRef.current = node;
      }}
      className={styles["rte-dynamic-tab-item"]}
      data-hidden={isHidden}
      data-is-animating={isAnimating}
      data-is-disappearing={isAnimatingDisappearing}
      data-appearance={appearance}
      data-active={isActive}
      data-compact-spacing={compactSpacing}
      data-tab-id={id}
      onClick={onClick}
      role="tab"
      tabIndex={isActive ? 0 : -1}
      aria-selected={isActive}
      onKeyDown={handleKeyDown}
      onKeyUp={handleKeyUp}
    >
      {(shouldDisplayBadge || shouldDisplayIcon || shouldDisplayText) && (
        <div
          ref={tabItemContentRef}
          style={{
            display: "flex",
            alignItems: "center",
            gap: "8px",
            width: isHidden ? "0" : "100%",
            overflow: "hidden",
            minWidth: "auto",
          }}
        >
          {shouldDisplayBadge && (
            <Badge
              content={"empty"}
              count={badgeCount}
              icon={badgeIcon}
              size={"s"}
              badgeType={badgeType}
              style={{
                marginLeft: isZeroToXS ? "4px" : undefined,
              }}
            />
          )}
          {shouldDisplayIcon && (
            <Icon name={iconName!} appearance={isActive ? "filled" : "outlined"} style={{ flex: "none" }} />
          )}
          {shouldDisplayText && (
            <div
              className={styles["rte-dynamic-tab-item__title"]}
              onDoubleClick={handleOnDoubleClick}
              ref={titleRef}
              tabIndex={isActive && isEditable ? 0 : -1}
              onKeyDown={handleOnTitleKeyDown}
            >
              {isEditing ? (
                <input
                  ref={inputRef}
                  type="text"
                  value={tabTitle}
                  onChange={handleOnChangeTabTitle}
                  onBlur={handleOnBlur}
                  style={{
                    width: `${inputRef.current ? getTextWidth(inputRef.current)(tabTitle) + 8 : 0}px`,
                    maxWidth: 100 + "%",
                  }}
                />
              ) : (
                <>{shouldDisplayText && <span data-is-animating={isAnimating}>{tabTitle}</span>}</>
              )}
            </div>
          )}
        </div>
      )}
      {isClosable && shouldDisplayCloseButton && (
        <button
          className={styles["rte-dynamic-tab-item__close-button"]}
          aria-label={`Close ${tabTitle} tab`}
          onClick={handleOnClickCloseTab}
          onKeyDown={handleOnKeyDownCloseTab}
          onKeyUp={handleOnKeyUpCloseTab}
        >
          <Icon name="close" />
        </button>
      )}
    </li>
  );
};

export default DynamicTabItem;
