// packages/react/src/components/stepper/Stepper.tsx
import { StepperProps as coreStepperProps } from "@design-system-rte/core/components/stepper/stepper.interface";
import {
  focusNextNotStepElement,
  focusNextStepElement,
  focusPreviousNotStepElement,
  focusPreviousStepElement,
} from "@design-system-rte/core/components/stepper/stepper.utils";
import {
  ARROW_DOWN_KEY,
  ARROW_LEFT_KEY,
  ARROW_RIGHT_KEY,
  ARROW_UP_KEY,
  TAB_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { forwardRef, Fragment, useCallback, useRef, useState } from "react";

import styles from "./Stepper.module.scss";
import StepperItem from "./stepperItem/StepperItem";
import stepperItemStyles from "./stepperItem/StepperItem.module.scss";
import StepperSeparator from "./stepperItem/stepperseparator/StepperSeparator";

interface StepperProps extends coreStepperProps, React.HTMLAttributes<HTMLElement> {
  activeStepId: string | null;
}

const Stepper = forwardRef<HTMLElement, StepperProps>(
  ({ steps, orientation = "horizontal", activeStepId, ...props }, ref) => {
    const [stepperElement, setStepperElement] = useState<HTMLElement | null>(null);

    const stepperRef = useRef<HTMLElement | null>(null);

    const stepperCallbackRef = useCallback(
      (node: HTMLDialogElement | null) => {
        stepperRef.current = node;
        setStepperElement(node);
        if (typeof ref === "function") ref(node);
        else if (ref) (ref as React.MutableRefObject<HTMLDialogElement | null>).current = node;
      },
      [ref],
    );

    const handleKeyUp = (event: React.KeyboardEvent) => {
      if ([ARROW_LEFT_KEY, ARROW_RIGHT_KEY, ARROW_UP_KEY, ARROW_DOWN_KEY].includes(event.key)) {
        event.preventDefault();
        event.stopPropagation();

        const allSteps = stepperElement?.querySelectorAll("button");
        if (allSteps) {
          const currentFocusSteppedIndex = Array.from(allSteps).findIndex((step) => step === document.activeElement);
          if (orientation === "horizontal") {
            switch (event.key) {
              case ARROW_LEFT_KEY: {
                focusPreviousStepElement(currentFocusSteppedIndex, Array.from(allSteps));
                break;
              }
              case ARROW_RIGHT_KEY: {
                focusNextStepElement(currentFocusSteppedIndex, Array.from(allSteps));
                break;
              }
              default:
                return;
            }
          } else {
            switch (event.key) {
              case ARROW_UP_KEY: {
                focusPreviousStepElement(currentFocusSteppedIndex, Array.from(allSteps));
                break;
              }
              case ARROW_DOWN_KEY: {
                focusNextStepElement(currentFocusSteppedIndex, Array.from(allSteps));
                break;
              }
              default:
                return;
            }
          }
        }
      }
    };

    const handleKeyDown = (event: React.KeyboardEvent) => {
      if (event.key === TAB_KEY) {
        event.preventDefault();
        if (event.shiftKey) {
          focusPreviousNotStepElement(stepperItemStyles.stepButton, stepperRef.current!);
        } else {
          focusNextNotStepElement(stepperItemStyles.stepButton, stepperRef.current!);
        }
      }
      if ([ARROW_LEFT_KEY, ARROW_RIGHT_KEY, ARROW_UP_KEY, ARROW_DOWN_KEY].includes(event.key)) {
        event.preventDefault();
      }
    };

    if (steps.length < 2 || steps.length > 7) {
      console.warn("Stepper component requires between 2 and 7 steps to function properly.");
      return null;
    }

    return (
      <nav aria-label="Progression" style={{ width: "100%", height: "100%" }} ref={stepperCallbackRef} {...props}>
        <ol className={styles.stepper} data-orientation={orientation}>
          {steps.map((step, index) => (
            <Fragment key={step.name + index}>
              <StepperItem
                id={step.id}
                number={index + 1}
                name={step.name}
                completionState={step.completionState}
                orientation={orientation}
                onKeyDown={handleKeyDown}
                onKeyUp={handleKeyUp}
                onClick={step.onClick}
                isActive={step.id === activeStepId}
                clickableCompleteStep={step.clickableCompleteStep}
              />
              {index < steps.length - 1 && (
                <StepperSeparator isComplete={step.completionState === "complete"} orientation={orientation} />
              )}
            </Fragment>
          ))}
        </ol>
      </nav>
    );
  },
);

export default Stepper;

// preview/dsr-204/angular/components/stepper/stepper.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  input,
  output,
  viewChildren,
  AfterViewInit,
  OnDestroy,
  inject,
} from "@angular/core";
import { IconSize } from "@design-system-rte/core/components/icon/icon.constants";
import { StepperProps } from "@design-system-rte/core/components/stepper/stepper.interface";
import {
  focusNextNotStepElement,
  focusNextStepElement,
  focusPreviousNotStepElement,
  focusPreviousStepElement,
  isStepClickable as coreIsStepClickable,
} from "@design-system-rte/core/components/stepper/stepper.utils";
import {
  ARROW_DOWN_KEY,
  ARROW_LEFT_KEY,
  ARROW_RIGHT_KEY,
  ARROW_UP_KEY,
  TAB_KEY,
} from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { IconComponent } from "../icon/icon.component";

const segmentClass = "rte-stepper-button";

@Component({
  selector: "rte-stepper",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./stepper.component.html",
  styleUrl: "./stepper.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class StepperComponent implements AfterViewInit, OnDestroy {
  readonly steps = input<StepperProps["steps"]>([]);
  readonly activeStepId = input<string>();
  readonly orientation = input<StepperProps["orientation"]>("horizontal");
  readonly stepRefs = viewChildren<ElementRef<HTMLLIElement>>("step");

  readonly iconSize = IconSize;

  private readonly stepperRef = inject(ElementRef);

  readonly clickStep = output<StepperProps["steps"][number]>();

  ngAfterViewInit() {
    window.addEventListener("keydown", this.onGlobalKeyDown.bind(this));

    this.stepRefs().forEach((stepElement) => {
      const stepButton = stepElement.nativeElement.querySelector("button");
      if (stepButton) {
        stepButton.addEventListener("focus", this.focusCurrentStepElement.bind(this));
      }
    });
  }

  ngOnDestroy() {
    window.removeEventListener("keydown", this.onGlobalKeyDown.bind(this));

    this.stepRefs().forEach((stepElement) => {
      const stepButton = stepElement.nativeElement.querySelector("button");
      if (stepButton) {
        stepButton.addEventListener("focus", this.focusCurrentStepElement.bind(this));
      }
    });
  }

  isStepActive(id: string): boolean {
    return this.activeStepId() === id;
  }

  isStepClickable(step: StepperProps["steps"][number]): boolean {
    return (
      !!step.onClick &&
      coreIsStepClickable({
        completionState: step.completionState,
        clickableCompleteStep: step.clickableCompleteStep || false,
      })
    );
  }

  isStepFocusable(step: StepperProps["steps"][number]): boolean {
    return this.isStepClickable(step) || this.isStepActive(step.id);
  }

  handleStepClick(step: StepperProps["steps"][number]) {
    if (this.isStepClickable(step) && !this.isStepActive(step.id) && step.onClick) {
      step.onClick();
      this.clickStep.emit(step);
    }
  }
  handleKeyUp = (event: KeyboardEvent) => {
    if ([ARROW_LEFT_KEY, ARROW_RIGHT_KEY, ARROW_UP_KEY, ARROW_DOWN_KEY].includes(event.key)) {
      event.preventDefault();
      event.stopPropagation();

      const allSteps = this.stepperRef.nativeElement.querySelectorAll("button");
      if (allSteps) {
        const currentFocusSteppedIndex = Array.from(allSteps).findIndex((step) => step === document.activeElement);
        if (this.orientation() === "horizontal") {
          switch (event.key) {
            case ARROW_LEFT_KEY: {
              focusPreviousStepElement(currentFocusSteppedIndex, Array.from(allSteps));
              break;
            }
            case ARROW_RIGHT_KEY: {
              focusNextStepElement(currentFocusSteppedIndex, Array.from(allSteps));
              break;
            }
            default:
              return;
          }
        } else {
          switch (event.key) {
            case ARROW_UP_KEY: {
              focusPreviousStepElement(currentFocusSteppedIndex, Array.from(allSteps));
              break;
            }
            case ARROW_DOWN_KEY: {
              focusNextStepElement(currentFocusSteppedIndex, Array.from(allSteps));
              break;
            }
            default:
              return;
          }
        }
      }
    }
  };

  handleKeyDown(event: KeyboardEvent) {
    if (event.key === TAB_KEY) {
      event.preventDefault();
    }
    if (event.key === TAB_KEY) {
      if (event.shiftKey) {
        focusPreviousNotStepElement(segmentClass, this.stepperRef.nativeElement);
      } else {
        focusNextNotStepElement(segmentClass, this.stepperRef.nativeElement);
      }
    }
  }

  private lastKeydown: string | null = null;

  private onGlobalKeyDown = (event: KeyboardEvent) => {
    this.lastKeydown = event.key;
  };

  private focusCurrentStepElement() {
    if (this.lastKeydown === "Tab") {
      const selectedStepElement = this.stepRefs()
        .find((segment) => segment.nativeElement.querySelector('[aria-current="step"] button'))
        ?.nativeElement.querySelector("button") as HTMLElement;
      if (selectedStepElement) {
        selectedStepElement.focus();
      }
    }
  }
}
