// packages/angular/.storybook/preview.ts
import { HttpClientModule } from "@angular/common/http";
import { importProvidersFrom } from "@angular/core";
import { setCompodocJson } from "@storybook/addon-docs/angular";
import { applicationConfig, type Preview, componentWrapperDecorator } from "@storybook/angular";
import { addons } from "@storybook/preview-api";

import docJson from "../documentation.json";
setCompodocJson(docJson);

const decorators = [
  applicationConfig({
    providers: [importProvidersFrom(HttpClientModule)],
  }),
];
const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    options: {
      storySort: {
        order: ["Composants"],
        method: "alphabetical",
        locales: "fr-FR",
      },
    },
  },
  decorators: [
    ...decorators,
    componentWrapperDecorator(
      (story) =>
        `<div style="padding: 20px; background-color: var(--background-default); width: auto; height: 100%;">${story}</div>`,
    ),
  ],
};

addons.getChannel().on("THEME_CHANGED", (theme) => {
  document.querySelector("html")?.setAttribute("data-mode", theme.theme);
  document.querySelector("html")?.setAttribute("data-theme", theme.color);
});

document.querySelector("html")?.setAttribute("data-theme", "bleu_iceberg");
document.querySelector("html")?.setAttribute("data-mode", "light");

export default preview;

// packages/react/.storybook/preview.ts
import { addons } from "@storybook/preview-api";
import type { Preview } from "@storybook/react";
import React from "react";

import "./preview.scss";

const preview: Preview = {
  decorators: [
    (Story) =>
      React.createElement(
        "div",
        { style: { padding: "50px", backgroundColor: "var(--background-default)", width: "auto", height: "100%" } },
        React.createElement(Story),
      ),
  ],

  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    options: {
      storySort: {
        order: ["Composants"],
        method: "alphabetical",
        locales: "fr-FR",
      },
    },
  },
};

addons.getChannel().on("THEME_CHANGED", (theme) => {
  document.querySelector("html")?.setAttribute("data-mode", theme.theme);
  document.querySelector("html")?.setAttribute("data-theme", theme.color);
});

document.querySelector("html")?.setAttribute("data-theme", "bleu_iceberg");
document.querySelector("html")?.setAttribute("data-mode", "light");

export default preview;
