// packages/react/src/components/button/Button.tsx
import { forwardRef } from "react";

import { ButtonProps as CoreButtonProps } from '@design-system-rte/core/components/button/button.interface';
import style from './Button.module.scss';
import { concatClassNames } from '../utils';

interface ButtonProps
  extends Omit<CoreButtonProps, "disabled">,
    Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> {
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ size = 'm', label, variant = 'primary', className = '', onClick, type = 'button', ...props }, ref) => {
    return (
        <button
          ref={ref}
          type={type}
          className={concatClassNames(style.button, className)}
          data-size={size}
          data-variant={variant}
          onClick={onClick}
          {...props}
        >
          <span data-size={size} className={style.label}>
            {label}
          </span>
        </button>
    );
  },
);

export default Button;

// packages/angular/src/components/button/button.component.ts
import { Component, input, output } from '@angular/core';
import { ButtonSize, ButtonVariant } from '@design-system-rte/core/components/button/button.interface';

@Component({
  selector: 'rte-button',
  standalone: true,
  imports: [],
  templateUrl: './button.component.html',
  styleUrl: './button.component.scss'
})
export class ButtonComponent {

  label = input('');
  variant = input<ButtonVariant>('filled');
  size = input<ButtonSize>('m');
  disabled = input(false);

  click = output<void>();

}

<button
    class="rte-button {{ variant() }} size-{{ size() }}"
    [disabled]="disabled()"
    (click)="click.emit()"
>
    <span class="rte-button-label">{{ label() }}</span>
</button>
