// packages/react/src/components/treeview/treeviewItemBorder/TreeviewItemBorder.tsx
import { TreeviewBorderType } from "@design-system-rte/core/components/treeview/treeview-item.interface";
import {
  TREEVIEW_BORDER_SVG_MAP,
  TREEVIEW_BORDER_SVG_MAP_COMPACT,
} from "@design-system-rte/core/components/treeview/treeview.constants";
import { Fragment } from "react/jsx-runtime";

import { concatClassNames } from "../../utils";

import styles from "./TreeviewItemBorder.module.scss";

const TreeviewItemBorder = ({ isCompact, borderType }: { isCompact: boolean; borderType: TreeviewBorderType }) => {
  const getSvgConfig = () => {
    const elements = isCompact ? TREEVIEW_BORDER_SVG_MAP_COMPACT : TREEVIEW_BORDER_SVG_MAP;
    return elements[borderType];
  };

  return (
    <div className={styles["rte-treeview-item-border-container"]} data-is-compact={isCompact}>
      <svg
        className={concatClassNames(styles["rte-treeview-item-border"])}
        fill="none"
        aria-hidden="true"
        width={getSvgConfig().width}
        height={getSvgConfig().height}
        viewBox={getSvgConfig().viewBox}
      >
        {getSvgConfig().elements.map((element, index) => (
          <Fragment key={index}>
            {element.kind === "path" ? (
              <path className={styles["rte-treeview-item-border-path"]} key={index} d={element.d} />
            ) : (
              <line
                className={styles["rte-treeview-item-border-path"]}
                key={index}
                x1={element.x1}
                y1={element.y1}
                x2={element.x2}
                y2={element.y2}
              />
            )}
          </Fragment>
        ))}
      </svg>
    </div>
  );
};

export default TreeviewItemBorder;

// packages/angular/projects/ds-rte-lib/src/lib/components/treeview/treeview-item/treeview-item-border/treeview-item-border.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import { SvgConfig } from "@design-system-rte/core/common/svg";
import { TREEVIEW_BORDER_SVG_MAP, TreeviewBorderType } from "@design-system-rte/core/components/treeview";

@Component({
  selector: "rte-treeview-item-border",
  standalone: true,
  templateUrl: "./treeview-item-border.component.html",
  styleUrl: "./treeview-item-border.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeviewItemBorderComponent {
  readonly borderType = input.required<TreeviewBorderType>();
  readonly dottedLine = input<boolean>(false);

  readonly svgConfig = computed<SvgConfig>(() => TREEVIEW_BORDER_SVG_MAP[this.borderType()]);
}

<svg
  class="treeview-item-border"
  width="16"
  height="32"
  viewBox="0 0 16 32"
  fill="none"
  aria-hidden="true"
  [class.treeview-item-border-dashed]="dottedLine()"
>
  @switch (borderType()) {
    @case ("vertical") {
      <path d="M8 32L8 0" class="treeview-item-border-path" />
    }
    @case ("branch") {
      <path d="M8 32L8 0" class="treeview-item-border-path" />
      <line x1="8" y1="15.5" x2="16" y2="15.5" class="treeview-item-border-path" />
    }
    @case ("corner") {
      <path d="M8 16L8 0" class="treeview-item-border-path" />
      <line x1="8" y1="15.5" x2="16" y2="15.5" class="treeview-item-border-path" />
    }
    @case ("horizontal") {
      <line x1="0" y1="15.5" x2="16" y2="15.5" class="treeview-item-border-path" />
    }
    @case ("spacer") {}
  }
</svg>
