// preview/dsr-272-react/angular/components/treeview/treeview-item/treeview-item.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  HostBinding,
  inject,
  input,
  output,
  signal,
  Signal,
} from "@angular/core";
import {
  TreeviewBorderType,
  TreeviewItemProps,
  TreeviewOpenChangeEvent,
  TreeviewNodePath,
} from "@design-system-rte/core/components/treeview/treeview-item.interface";
import {
  allDescendantsChecked,
  BuildTreeviewNodeIdParams,
  buildTreeviewNodeId,
  canToggleOpen,
  computeCheckboxId,
  computeConnectorBorderTypes,
  getChildBorderTypes,
  getTreeviewItemKey,
  hasChildren as hasChildrenUtil,
  isItemSelected,
  isNodeIndeterminate,
} from "@design-system-rte/core/components/treeview/treeview.utils";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { BadgeComponent } from "../../badge/badge.component";
import { CheckboxComponent } from "../../checkbox/checkbox.component";
import { DropdownMenuComponent } from "../../dropdown/dropdown-menu/dropdown-menu.component";
import { DropdownTriggerDirective } from "../../dropdown/dropdown-trigger/dropdown-trigger.directive";
import { DropdownDirective } from "../../dropdown/dropdown.directive";
import { DropdownItemConfig, DropdownItemEvent } from "../../dropdown/dropdown.types";
import { IconComponent } from "../../icon/icon.component";
import { TreeviewCheckService } from "../treeview-check.service";
import { TreeviewSelectionService } from "../treeview-selection.service";

import { TreeviewItemBorderComponent } from "./treeview-item-border/treeview-item-border.component";

@Component({
  selector: "li[rteTreeviewItem]",
  imports: [
    CommonModule,
    CheckboxComponent,
    IconComponent,
    BadgeComponent,
    TreeviewItemBorderComponent,
    DropdownDirective,
    DropdownTriggerDirective,
    DropdownMenuComponent,
  ],
  standalone: true,
  templateUrl: "./treeview-item.component.html",
  styleUrl: "./treeview-item.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeviewItemComponent {
  @HostBinding("class") get hostClasses(): string {
    const classes = ["treeview-item"];
    if (this.isCompact()) classes.push("compact");
    if (this.isSelected()) classes.push("selected");
    if (this.disabled()) classes.push("disabled");
    if (this.hasChildren()) classes.push("has-children");
    if (this.hasChildren() && this.isOpenSignal()) classes.push("is-expanded");
    if (this.dottedLine()) classes.push("dotted-line");
    if (this.effectiveDepth() === 0) classes.push("root-depth");
    return classes.join(" ");
  }

  @HostBinding("attr.role") readonly role = "treeitem";

  @HostBinding("attr.data-item-id") get dataItemId(): string {
    return this.itemId();
  }

  @HostBinding("attr.aria-level") get ariaLevel(): number {
    return this.effectiveDepth() + 1;
  }

  @HostBinding("attr.aria-expanded") get ariaExpanded(): boolean | undefined {
    return this.hasChildren() ? this.isOpenSignal() : undefined;
  }

  @HostBinding("attr.aria-selected") get ariaSelected(): boolean {
    return !!this.isSelected();
  }

  readonly treeId = input.required<string>();
  readonly nodePath = input<TreeviewNodePath>([]);
  readonly labelText = input.required<string>();
  readonly icon = input<string | undefined>();
  readonly disabled = input<boolean>(false);
  readonly isCompact = input<boolean>(false);
  readonly hasCheckbox = input<boolean>(false);
  readonly isOpen = input<boolean>(false);
  readonly hasIcon = input<boolean>(false);
  readonly hasBadge = input<boolean>(false);
  readonly dottedLine = input<boolean>(false);
  readonly items = input<TreeviewItemProps[]>([]);
  readonly rootItems = input<TreeviewItemProps[] | undefined>(undefined);
  readonly id = input<string | undefined>();
  readonly depth = input<number | undefined>(undefined);
  readonly isLastChild = input<boolean | undefined>(undefined);
  readonly borderTypes = input<TreeviewBorderType[]>([]);
  readonly actionIcon = input<string | undefined>();
  readonly actionMenuItems = input<DropdownItemConfig[] | undefined>();

  readonly isOpenSignal = signal<boolean>(false);

  readonly itemClick = output<string | undefined>();
  readonly openChange = output<TreeviewOpenChangeEvent>();
  readonly actionIconClick = output<{ itemId: string; event: Event }>();
  readonly actionMenuClick = output<{
    itemId: string;
    menuItemId: string;
    menuItemLabel: string;
    event: Event;
    item?: DropdownItemConfig;
  }>();

  private readonly parentItem = inject(TreeviewItemComponent, { optional: true, skipSelf: true });
  private readonly selectionService = inject(TreeviewSelectionService, { optional: true });
  private readonly checkService = inject(TreeviewCheckService, { optional: true });

  readonly hasChildren = computed(() => hasChildrenUtil(this.items()));

  readonly isChecked = computed(() => {
    const ids = this.checkService?.checkedIds() ?? new Set();
    const node = { id: this.itemId(), labelText: this.labelText(), items: this.items() };
    const hasChildren = hasChildrenUtil(this.items());
    return allDescendantsChecked(node, ids) || (ids.has(this.itemId()) && !hasChildren);
  });

  readonly isIndeterminate = computed(() => {
    const ids = this.checkService?.checkedIds() ?? new Set();
    const node = { id: this.itemId(), labelText: this.labelText(), items: this.items() };
    return isNodeIndeterminate(node, ids);
  });

  readonly itemId = computed(() => this.id() ?? this.labelText());

  readonly isSelected = computed(
    () => this.selectionService && !!isItemSelected(this.itemId(), this.selectionService.selectedId()),
  );

  readonly effectiveDepth: Signal<number> = computed(() => {
    const depthInput = this.depth();
    if (depthInput !== undefined) {
      return depthInput;
    }
    const parent = this.parentItem;
    return parent ? parent.effectiveDepth() + 1 : 0;
  });

  readonly nodeUid = computed(() =>
    buildTreeviewNodeId({
      treeId: this.treeId(),
      path: this.nodePath(),
      itemId: this.itemId(),
    } as BuildTreeviewNodeIdParams),
  );

  readonly checkboxId = computed(() => computeCheckboxId(this.nodeUid()));

  readonly resolvedBorderTypes = computed(() => {
    const inputBorderTypes = this.borderTypes();
    return inputBorderTypes.length > 0 ? inputBorderTypes : [];
  });

  readonly connectorBorderTypes = computed(() =>
    computeConnectorBorderTypes({
      depth: this.effectiveDepth(),
      isCompact: this.isCompact(),
      resolvedBorderTypes: this.resolvedBorderTypes(),
      hasChildren: this.hasChildren(),
    }),
  );

  getChildBorderTypes(isLastChild: boolean): TreeviewBorderType[] {
    return getChildBorderTypes(this.resolvedBorderTypes(), isLastChild);
  }

  constructor() {
    effect(
      () => {
        this.isOpenSignal.set(this.isOpen());
      },
      { allowSignalWrites: true },
    );
  }

  toggleOpen(): void {
    if (!canToggleOpen(this.hasChildren(), this.disabled())) {
      return;
    }
    const newOpen = !this.isOpenSignal();
    this.isOpenSignal.set(newOpen);
    this.openChange.emit({ id: this.itemId(), open: newOpen });
  }

  handleContentClick(): void {
    if (this.disabled()) {
      return;
    }
    const service = this.selectionService;
    if (service) {
      const currentItemId = this.itemId();
      service.select(currentItemId);
    }
    this.itemClick.emit(this.itemId());
  }

  handleChevronKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      this.toggleOpen();
    }
  }

  handleContentKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      this.handleContentClick();
    }
  }

  handleCheckboxClick(event: Event): void {
    event.preventDefault();
    event.stopPropagation();
    if (this.disabled()) {
      return;
    }
    this.checkService?.toggleChecked(
      { id: this.itemId(), labelText: this.labelText(), items: this.items() },
      this.rootItems(),
    );
  }

  handleCheckboxKeydown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      this.handleCheckboxClick(event);
    }
  }

  handleActionIconClick(event: Event): void {
    event.stopPropagation();
    if (this.disabled()) {
      return;
    }
    this.actionIconClick.emit({ itemId: this.itemId(), event });
  }

  handleActionIconKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      event.stopPropagation();
      this.handleActionIconClick(event);
    }
  }

  handleActionMenuClick(menuEvent: DropdownItemEvent): void {
    if (this.disabled()) {
      return;
    }
    const menuItemId = menuEvent.id;
    const menuItemLabel = menuEvent.item?.label ?? menuItemId;
    this.actionMenuClick.emit({
      itemId: this.itemId(),
      menuItemId,
      menuItemLabel,
      event: menuEvent.event,
      item: menuEvent.item,
    });
  }

  trackChild(child: TreeviewItemProps): string {
    return getTreeviewItemKey(child);
  }
}

<div class="treeview-item-row">
  @if (hasCheckbox()) {
    <div
      class="treeview-item-checkbox"
      role="input"
      data-treeview-focusable="checkbox"
      tabindex="-1"
      [attr.aria-checked]="isChecked() ? 'true' : isIndeterminate() ? 'mixed' : 'false'"
      [attr.aria-label]="labelText()"
      (click)="handleCheckboxClick($event)"
      (keydown)="handleCheckboxKeydown($event)"
    >
      <rte-checkbox
        [id]="checkboxId()"
        [label]="labelText()"
        [showLabel]="false"
        [tabindex]="-1"
        [disabled]="disabled()"
        [checked]="isChecked()"
        [indeterminate]="isIndeterminate()"
      />
    </div>
  }
  <div class="treeview-item-borders-container">
    @for (borderType of connectorBorderTypes(); track $index) {
      <rte-treeview-item-border [borderType]="borderType" [dottedLine]="dottedLine()" [isCompact]="isCompact()" />
    }
    @if (hasChildren()) {
      <button
        type="button"
        class="treeview-item-chevron"
        data-treeview-focusable="chevron"
        tabindex="-1"
        [attr.aria-label]="isOpenSignal() ? 'Replier' : 'Déplier'"
        [disabled]="disabled()"
        (click)="toggleOpen(); $event.stopPropagation()"
        (keydown)="handleChevronKeyDown($event)"
      >
        <rte-icon [name]="isOpenSignal() ? 'arrow-chevron-down' : 'arrow-chevron-right'" [size]="16" />
      </button>
    }
  </div>
  <div class="treeview-item-content-wrapper">
    <div class="treeview-item-main-content" (keydown)="handleContentKeyDown($event)" (click)="handleContentClick()">
      @if (hasIcon() && icon() && !isCompact()) {
        <rte-icon class="treeview-item-icon" [name]="icon()!" [size]="16" />
      }
      <div
        class="treeview-item-content"
        data-treeview-focusable="content"
        tabindex="-1"
        [class.treeview-item-content-compact]="isCompact()"
      >
        <span class="treeview-item-label">{{ labelText() }}</span>
      </div>
      @if (hasBadge()) {
        <span class="treeview-item-badge">
          <rte-badge badgeType="indicator" badgeContent="empty" badgeSize="s" [simpleBadge]="true" />
        </span>
      }
      @if (actionIcon()) {
        @if (actionMenuItems() && actionMenuItems()!.length > 0) {
          <div
            class="treeview-item-action"
            rteDropdown
            (menuEvent)="handleActionMenuClick($event)"
            (click)="$event.stopPropagation()"
          >
            <button
              type="button"
              class="treeview-item-action-button"
              data-treeview-focusable="action"
              tabindex="-1"
              rteDropdownTrigger
              [attr.aria-label]="'Actions pour ' + labelText()"
              [disabled]="disabled()"
            >
              <rte-icon [name]="actionIcon()!" [size]="16" />
            </button>
            <rte-dropdown-menu [items]="actionMenuItems()!" />
          </div>
        } @else {
          <button
            type="button"
            class="treeview-item-action-button"
            data-treeview-focusable="action"
            tabindex="-1"
            [attr.aria-label]="'Actions pour ' + labelText()"
            [disabled]="disabled()"
            (click)="handleActionIconClick($event)"
            (keydown)="handleActionIconKeyDown($event)"
          >
            <rte-icon [name]="actionIcon()!" [size]="16" />
          </button>
        }
      }
    </div>
  </div>
</div>
@if (hasChildren()) {
  <ul class="treeview-item-children" role="group" [class.treeview-item-children-open]="isOpenSignal()">
    @for (child of items(); track trackChild(child); let childIndex = $index) {
      <li
        rteTreeviewItem
        [rootItems]="rootItems()"
        [treeId]="treeId()"
        [nodePath]="nodePath().concat(childIndex)"
        [id]="child.id"
        [labelText]="child.labelText"
        [icon]="child.icon"
        [disabled]="child.disabled ?? false"
        [isCompact]="child.isCompact ?? isCompact()"
        [hasCheckbox]="child.hasCheckbox ?? hasCheckbox()"
        [isOpen]="child.isOpen ?? false"
        [hasIcon]="child.hasIcon ?? hasIcon()"
        [hasBadge]="child.hasBadge ?? false"
        [dottedLine]="child.dottedLine ?? dottedLine()"
        [items]="child.items ?? []"
        [actionIcon]="child.actionIcon"
        [actionMenuItems]="child.actionMenuItems"
        [depth]="effectiveDepth() + 1"
        [isLastChild]="childIndex === items().length - 1"
        [borderTypes]="getChildBorderTypes(childIndex === items().length - 1)"
        (itemClick)="itemClick.emit($event)"
        (openChange)="openChange.emit($event)"
        (actionIconClick)="actionIconClick.emit($event)"
        (actionMenuClick)="actionMenuClick.emit($event)"
      ></li>
    }
  </ul>
}

// packages/react/src/components/treeview/treeviewItem/TreeviewItem.tsx
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core";
import { TreeviewItemProps as coreTreeviewItem } from "@design-system-rte/core/components/treeview/treeview-item.interface";
import {
  buildTreeviewNodeId,
  BuildTreeviewNodeIdParams,
  canToggleOpen,
  computeCheckboxId,
  computeConnectorBorderTypes,
  getChildBorderTypes,
  hasChildren,
  isNodeIndeterminate,
} from "@design-system-rte/core/components/treeview/treeview.utils";
import { useState } from "react";

import Badge from "../../badge/Badge";
import Checkbox from "../../checkbox/Checkbox";
import Dropdown from "../../dropdown/Dropdown";
import DropdownItem from "../../dropdown/dropdownItem/DropdownItem";
import Icon from "../../icon/Icon";
import { concatClassNames } from "../../utils";
import TreeviewItemBorder from "../treeviewItemBorder/TreeviewItemBorder";
import { computeIsChecked } from "../treeviewUtil";

import styles from "./TreeviewItem.module.scss";

interface TreeviewItemProps extends coreTreeviewItem, Omit<React.HTMLAttributes<HTMLLIElement>, "onClick"> {
  onOpenChange?: (id: string, isOpen: boolean) => void;
  onClickElement?: (id: string) => void;
  isSelected?: boolean;
  selectedId?: string;
  onActionIconClick?: (id: string) => void;
  itemIndex?: number;
  onCheckedIdsChange?: (node: TreeviewItemProps) => void;
  checkedIds?: string[];
  isChecked?: boolean;
  onClick?: (id: string) => void;
}

const TreeviewItem = ({
  id,
  treeId,
  itemIndex,
  labelText,
  icon,
  disabled,
  isCompact,
  hasCheckbox,
  isOpen,
  hasIcon,
  hasBadge,
  items,
  borderTypes,
  actionIcon,
  actionMenuItems,
  depth,
  onOpenChange,
  onClickElement,
  onActionIconClick,
  onCheckedIdsChange,
  selectedId,
  checkedIds,
}: TreeviewItemProps) => {
  const [internalDepth] = useState(depth || 0);
  const [isOpenInternal, setIsOpenInternal] = useState(isOpen || false);
  const [isActionMenuOpen, setIsActionMenuOpen] = useState(false);

  const itemId = id || labelText;

  const isChecked = computeIsChecked(itemId, labelText, items ?? [], checkedIds ?? []);
  const isIndeterminate = isNodeIndeterminate(
    { id: itemId, labelText: labelText, items: items ?? [] },
    new Set(checkedIds),
  );

  const handleActionIconClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    event.preventDefault();
    if (disabled) {
      return;
    }
    onActionIconClick?.(itemId);
  };

  const handleActionIconKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      event.stopPropagation();
      if (disabled) {
        return;
      }
      onActionIconClick?.(itemId);
    }
  };

  const handleItemClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (disabled) {
      return;
    }
    event.stopPropagation();
    onClickElement?.(itemId);
  };

  const resolvedBorderTypes = () => {
    return borderTypes ? borderTypes : [];
  };

  const connectorBorderType = computeConnectorBorderTypes({
    depth: internalDepth,
    isCompact: isCompact,
    resolvedBorderTypes: resolvedBorderTypes(),
    hasChildren: hasChildren(items),
  });

  const toggleOpen = () => {
    if (!canToggleOpen(hasChildren(items), !!disabled)) {
      return;
    }
    setIsOpenInternal((prev) => !prev);
    onOpenChange?.(itemId, !isOpenInternal);
  };

  const handleActionMenuClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    event.preventDefault();
    if (disabled) {
      return;
    }
    setIsActionMenuOpen(true);
  };

  const handleActionMenuKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.stopPropagation();
      event.preventDefault();
      if (disabled) {
        return;
      }
      setIsActionMenuOpen(true);
    }
  };

  const getNodeUid = () => {
    return buildTreeviewNodeId({
      treeId: treeId,
      path: [itemIndex],
      itemId: itemId,
    } as BuildTreeviewNodeIdParams);
  };

  const checkboxId = computeCheckboxId(getNodeUid());

  const handleOnKeyDownCheckbox = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      if (disabled) {
        return;
      }
      handleCheckedIdsChange();
    }
  };

  const handleCheckedIdsChange = () => {
    if (disabled) {
      return;
    }
    onCheckedIdsChange?.({ id: itemId, labelText: labelText, items: items });
  };

  const handleContentKeydown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      if (disabled) {
        return;
      }
      onClickElement?.(itemId);
    }
  };

  return (
    <li
      className={concatClassNames(styles["rte-treeview-item"], "treeview-item")}
      data-disabled={disabled}
      data-item-id={itemId}
      data-has-children={hasChildren(items)}
      data-is-expanded={isOpenInternal && hasChildren(items)}
      data-is-compact={isCompact}
      data-root-depth={internalDepth === 0}
      data-is-selected={selectedId === itemId}
      data-depth={internalDepth}
      role="treeitem"
      aria-disabled={disabled ? true : undefined}
      aria-expanded={hasChildren(items) ? isOpenInternal : undefined}
      aria-selected={selectedId === itemId}
      aria-level={internalDepth + 1}
      data-has-checked-items={checkedIds && checkedIds.length > 0}
    >
      <div className={styles["rte-treeview-item-row"]}>
        {hasCheckbox && (
          <div
            className={styles["rte-treeview-item-checkbox"]}
            role="input"
            data-treeview-focusable="checkbox"
            aria-checked={isIndeterminate ? "mixed" : isChecked ? "true" : "false"}
            aria-label={labelText}
            tabIndex={-1}
            onKeyDown={handleOnKeyDownCheckbox}
          >
            <Checkbox
              id={checkboxId}
              label={labelText}
              showLabel={false}
              tabIndex={-1}
              disabled={disabled}
              onChange={handleCheckedIdsChange}
              checked={isChecked}
              indeterminate={isIndeterminate}
            />
          </div>
        )}
        <div className={styles["rte-treeview-item-borders-container"]}>
          {connectorBorderType.map((type, index) => (
            <TreeviewItemBorder key={index} isCompact={!!isCompact} borderType={type} />
          ))}
          {hasChildren(items) && (
            <button
              type="button"
              className={concatClassNames(
                styles["rte-treeview-item-chevron"],
                isOpenInternal ? styles["rte-treeview-item-chevron-open"] : "",
              )}
              onClick={toggleOpen}
              aria-label={`${isOpenInternal ? "Fermer" : "Ouvrir"} les enfants de ${labelText}`}
              disabled={disabled}
              tabIndex={-1}
              data-treeview-focusable="chevron"
            >
              <Icon name={isOpenInternal ? "arrow-chevron-down" : "arrow-chevron-right"} size={16} />
            </button>
          )}
        </div>
        <div className={styles["rte-treeview-item-content-wrapper"]}>
          <div
            className={styles["rte-treeview-item-main-content"]}
            onClick={handleItemClick}
            onKeyDown={handleContentKeydown}
            data-testid={`treeview-item-main-content-${id}`}
          >
            {hasIcon && icon && !isCompact && (
              <Icon name={icon} className={styles["rte-treeview-item-icon"]} size={16} />
            )}
            <div
              className={concatClassNames(
                styles["rte-treeview-item-content"],
                isCompact ? styles["rte-treeview-item-content-compact"] : "",
              )}
              data-treeview-focusable="content"
              tabIndex={-1}
            >
              <span className={styles["rte-treeview-item-label"]}> {labelText} </span>
            </div>
            {hasBadge && <Badge badgeType="indicator" content="empty" size="s" />}
            {actionIcon && (
              <>
                {actionMenuItems ? (
                  <div className={styles["rte-treeview-item-action"]}>
                    <Dropdown
                      dropdownId={`${itemId}-action-menu`}
                      isOpen={isActionMenuOpen}
                      autoClose={true}
                      onClose={() => {
                        setIsActionMenuOpen(false);
                      }}
                      trigger={
                        <button
                          type="button"
                          className={styles["rte-treeview-item-action-button"]}
                          data-treeview-focusable="action"
                          tabIndex={-1}
                          aria-label={`Action pour ${labelText}`}
                          disabled={disabled}
                          onClick={handleActionMenuClick}
                          onKeyDown={handleActionMenuKeyDown}
                        >
                          <Icon name={actionIcon} size={16} />
                        </button>
                      }
                    >
                      {actionMenuItems.map(({ label, leftIcon, hasSeparator, onClick }, index) => (
                        <DropdownItem
                          key={index}
                          label={label}
                          leftIcon={leftIcon}
                          hasSeparator={hasSeparator}
                          onClick={onClick}
                          disabled={disabled}
                        />
                      ))}
                    </Dropdown>
                  </div>
                ) : (
                  <button
                    type="button"
                    className={styles["rte-treeview-item-action-button"]}
                    data-treeview-focusable="action"
                    tabIndex={-1}
                    aria-label={`Actions pour ${labelText}`}
                    disabled={disabled}
                    onClick={handleActionIconClick}
                    onKeyDown={handleActionIconKeyDown}
                  >
                    <Icon name={actionIcon} size={16}></Icon>
                  </button>
                )}
              </>
            )}
          </div>
        </div>
      </div>
      {hasChildren(items) && (
        <ul
          className={concatClassNames(
            styles["rte-treeview-item-children"],
            isOpenInternal ? styles["rte-treeview-item-children-open"] : "",
            "treeview-item-children",
            isOpenInternal ? "treeview-item-children-open" : "",
          )}
          role="group"
          data-open={isOpen}
        >
          {items!.map((child, index) => (
            <TreeviewItem
              key={child.id}
              {...child}
              depth={internalDepth + 1}
              borderTypes={getChildBorderTypes(resolvedBorderTypes(), index === items!.length - 1)}
              isCompact={isCompact}
              onClickElement={(id) => onClickElement?.(id)}
              selectedId={selectedId}
              hasCheckbox={child.hasCheckbox ?? hasCheckbox}
              onCheckedIdsChange={onCheckedIdsChange}
              checkedIds={checkedIds}
              onActionIconClick={child.onActionIconClick}
            />
          ))}
        </ul>
      )}
    </li>
  );
};

export default TreeviewItem;
