// packages/angular/projects/ds-rte-lib/src/lib/components/tab/tab-item/tab-item.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  input,
  signal,
  ElementRef,
  AfterViewInit,
  viewChild,
  output,
} from "@angular/core";
import { TabItemProps } from "@design-system-rte/core/components/tab/tab.interface";

import { BadgeComponent } from "../../badge/badge.component";
import { IconComponent } from "../../icon/icon.component";

@Component({
  selector: "rte-tab-item",
  imports: [CommonModule, IconComponent, BadgeComponent],
  standalone: true,
  templateUrl: "./tab-item.component.html",
  styleUrl: "./tab-item.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TabItemComponent implements AfterViewInit {
  readonly direction = input<"horizontal" | "vertical">("horizontal");
  readonly option = input<TabItemProps>();
  readonly compactSpacing = input<boolean>();
  readonly isSelected = input<boolean>(false);
  readonly click = output<string>();
  readonly handleKeydown = input<() => void>();

  readonly tabItemRef = viewChild<ElementRef<HTMLButtonElement>>("tabItem");

  readonly hoverIndicatorStyle = signal<{
    width?: number;
    left?: number;
    top?: number;
    height?: number;
    opacity?: number;
  } | null>(null);

  readonly displayBadge = (option: TabItemProps): boolean => {
    return !!(option.badgeAppearance || option.badgeType || option.badgeIcon || option.badgeCount);
  };

  ngAfterViewInit() {
    if (this.tabItemRef && this.tabItemRef()?.nativeElement) {
      if (this.option()?.disabled) return;
      if (this.direction() === "horizontal") {
        this.hoverIndicatorStyle.set({
          width: this.tabItemRef()?.nativeElement.offsetWidth,
          height: 2,
          left: this.tabItemRef()?.nativeElement.offsetLeft,
          top: this.tabItemRef()
            ? this.tabItemRef()!.nativeElement.offsetTop + this.tabItemRef()!.nativeElement.offsetHeight
            : undefined,
          opacity: 0,
        });
      } else {
        this.hoverIndicatorStyle.set({
          width: 2,
          height: this.tabItemRef()?.nativeElement.offsetHeight,
          left:
            this.tabItemRef()?.nativeElement.offsetLeft !== undefined
              ? this.tabItemRef()!.nativeElement.offsetLeft - 2
              : undefined,
          top: this.tabItemRef()!.nativeElement.offsetTop,
          opacity: 0,
        });
      }
    }
  }

  onClickTabItem(event: MouseEvent, id: string): void {
    this.hoverIndicatorStyle.set({
      ...this.hoverIndicatorStyle(),
      opacity: 0,
    });
    if (!this.option()?.disabled) {
      this.click.emit(id);
    } else {
      event.stopPropagation();
    }
  }

  handleMouseHover() {
    if (!this.isSelected()) {
      this.hoverIndicatorStyle.set({
        ...this.hoverIndicatorStyle(),
        opacity: 1,
      });
    }
  }

  handleMouseOut() {
    this.hoverIndicatorStyle.set({
      ...this.hoverIndicatorStyle(),
      opacity: 0,
    });
  }
}

<button
  #tabItem
  class="rte-tabitem"
  role="tab"
  [id]="option()?.id"
  [attr.aria-selected]="isSelected()"
  [attr.aria-controls]="option()?.panelId"
  [tabIndex]="isSelected() ? 0 : -1"
  [attr.data-selected]="isSelected()"
  [attr.data-inverted]="inverted()"
  [attr.data-compact-spacing]="compactSpacing()"
  [attr.data-disabled]="option()?.disabled"
  (click)="onClickTabItem($event, option()?.id || '')"
  (mouseover)="handleMouseHover()"
  (mouseout)="handleMouseOut()"
  (keydown)="handleKeydown()"
>
  <rte-icon
    *ngIf="option()?.icon"
    [name]="option()?.icon || ''"
    [appearance]="isSelected() ? 'filled' : 'outlined'"
  />
  <span *ngIf="option()?.label">{{ option()?.label }}</span>
  <rte-badge
    *ngIf="displayBadge(option()!)"
    [simpleBadge]="true"
    [badgeAppearance]="option()?.badgeAppearance || 'empty'"
    [badgeType]="option()?.badgeType || 'neutral'"
    [icon]="option()?.badgeIcon || ''"
    [count]="option()?.badgeCount"
  />
</button>
<span
  #hoverIndicator
  class="rte-tab-hover-indicator"
  [attr.data-disabled]="option()?.disabled"
  [id]="'tab-hover-indicator' + option()?.id"
  [ngStyle]="{
    width: hoverIndicatorStyle()?.width + 'px',
    left: hoverIndicatorStyle()?.left + 'px',
    top: hoverIndicatorStyle()?.top + 'px',
    height: hoverIndicatorStyle()?.height + 'px',
    opacity: hoverIndicatorStyle()?.opacity || '0',
  }"
></span>

// packages/react/src/components/tab/tabitem/TabItem.tsx
import { TabItemProps as CoreTabItemProps } from "@design-system-rte/core/components/tab/tab.interface";
import { ARROW_LEFT_KEY, ARROW_RIGHT_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { HTMLAttributes, useCallback, useEffect, useRef, useState, MouseEvent, KeyboardEvent } from "react";

import Badge from "../../badge/Badge";
import Icon from "../../icon/Icon";

import style from "./TabItem.module.scss";

interface TabItemProps extends CoreTabItemProps, Omit<HTMLAttributes<HTMLButtonElement>, "id" | "onClick"> {
  onClick: (event: MouseEvent<HTMLButtonElement> | KeyboardEvent<HTMLButtonElement>) => void;
}

const TabItem = ({
  id,
  panelId,
  label,
  isSelected,
  showBadge,
  badgeCount,
  badgeAppearance = "empty",
  badgeIcon,
  onClick,
  icon,
  badgeType = "indicator",
  compactSpacing,
  direction,
  ...props
}: TabItemProps) => {
  const badgeProps = {
    count: badgeCount,
    appearance: badgeAppearance,
    icon: badgeIcon,
    badgeType,
  };

  const displayBadge =
    showBadge ||
    (badgeCount !== undefined && badgeCount > 0 && badgeAppearance === "text") ||
    (badgeAppearance === "icon" && badgeIcon);
  const tabItemRef = useRef<HTMLButtonElement | null>(null);

  const [hoverIndicatorStyle, setHoverIndicatorStyle] = useState<{
    width?: number;
    left?: number;
    top?: number;
    height?: number;
    opacity?: number;
  } | null>(null);

  const handleHover = useCallback(
    (event: string) => {
      if (tabItemRef.current && !isSelected) {
        if (event === "mouseover") {
          setHoverIndicatorStyle((prev) => ({
            ...prev,
            opacity: 1,
          }));
        } else {
          setHoverIndicatorStyle((prev) => ({
            ...prev,
            opacity: 0,
          }));
        }
      }
    },
    [isSelected],
  );

  const handleKeyDown = (event: KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === "Tab") {
      console.log(event.key);
    }
    if ([ARROW_LEFT_KEY, ARROW_RIGHT_KEY].includes(event.key)) {
      event.preventDefault();
      if (event.key === ARROW_RIGHT_KEY) {
        focusItem("next");
      } else {
        focusItem("previous");
      }
    }
  };

  const focusItem = (direction: "next" | "previous") => {
    const parent = tabItemRef.current?.parentElement;
    if (!parent) return;
    const allTabItems = Array.from(parent.querySelectorAll(`.${style.tabitem}`)) as HTMLElement[];
    const currentIndex = allTabItems.findIndex((tab) => tab === document.activeElement);
    let newIndex;
    if (direction === "next") {
      newIndex = (currentIndex + 1) % allTabItems.length;
    } else {
      newIndex = (currentIndex - 1 + allTabItems.length) % allTabItems.length;
    }
    allTabItems[newIndex].focus();
    allTabItems[newIndex].click();
  };

  useEffect(() => {
    if (tabItemRef.current) {
      console.log(direction);
      if (direction === "horizontal") {
        setHoverIndicatorStyle({
          width: tabItemRef.current.offsetWidth,
          left: tabItemRef.current.offsetLeft,
          top: tabItemRef.current.offsetTop + tabItemRef.current.offsetHeight,
          opacity: 0,
        });
      } else {
        console.log("vertical");
        setHoverIndicatorStyle({
          left: tabItemRef.current.offsetLeft - 2,
          top: tabItemRef.current.offsetTop,
          height: tabItemRef.current.offsetHeight,
          opacity: 0,
        });
      }
    }
  }, [isSelected, direction]);

  return (
    <>
      <button
        id={id}
        className={style["tabitem"]}
        role="tab"
        aria-selected={isSelected}
        aria-controls={panelId}
        tabIndex={isSelected ? 0 : -1}
        data-selected={isSelected}
        onClick={onClick}
        data-compact-spacing={compactSpacing}
        ref={tabItemRef}
        onKeyDown={handleKeyDown}
        onMouseEnter={() => handleHover("mouseover")}
        onMouseLeave={() => handleHover("mouseleave")}
        {...(isSelected && { "data-testid": "tabitem-selected" })}
        {...props}
      >
        {icon && <Icon name={icon} appearance={isSelected ? "filled" : "outlined"} />}
        {label && <span>{label}</span>}
        {displayBadge && <Badge {...badgeProps} />}
      </button>
      <span
        className={style["segment-hover-indicator"]}
        style={{
          width: hoverIndicatorStyle?.width,
          height: hoverIndicatorStyle?.height,
          left: hoverIndicatorStyle?.left,
          top: hoverIndicatorStyle?.top,
          opacity: hoverIndicatorStyle?.opacity,
        }}
      />
    </>
  );
};

export default TabItem;
