// packages/angular/.storybook/template/ThemeSelector/theme-selector.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, signal } from "@angular/core";

import { ChipComponent } from "../../../projects/ds-rte-lib/src/lib/components/chip/chip.component";
import { IconButtonComponent } from "../../../projects/ds-rte-lib/src/lib/components/icon-button/icon-button.component";

type Theme = "bleu_iceberg" | "violet" | "vert_foret";
type Mode = "light" | "dark";

@Component({
  selector: "rte-theme-selector",
  imports: [ChipComponent, CommonModule, IconButtonComponent],
  standalone: true,
  templateUrl: "./theme-selector.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThemeSelectorComponent {
  readonly themes: Array<{ id: Theme; label: string }> = [
    { id: "bleu_iceberg", label: "Bleu Iceberg" },
    { id: "violet", label: "Violet" },
    { id: "vert_foret", label: "Vert Forêt" },
  ];

  readonly selectedTheme = signal<Theme>("bleu_iceberg");

  readonly selectedMode = signal<Mode>("light");

  readonly iconName = computed(() => (this.selectedMode() === "light" ? "mode-dark" : "mode-light"));
  readonly nextMode = computed<Mode>(() => (this.selectedMode() === "light" ? "dark" : "light"));

  selectTheme(theme: Theme): void {
    this.selectedTheme.set(theme);
    document.documentElement.setAttribute("data-theme", theme);
  }

  selectMode(mode: Mode): void {
    this.selectedMode.set(mode);
    document.documentElement.setAttribute("data-mode", mode);
  }
}

<div
  style="display: flex; gap: 24px; flex-direction: row; justify-content: end"
>
  <div style="display: flex; gap: 8px" role="radiogroup">
    <rte-chip
      *ngFor="let theme of themes"
      type="single"
      [id]="theme.id"
      [label]="theme.label"
      [selected]="selectedTheme() === theme.id"
      (click)="selectTheme(theme.id)"
    />
    <div style="display: flex">
      <rte-icon-button
        label="Réinitialiser le thème"
        [name]="iconName()"
        (click)="selectMode(nextMode())"
      />
    </div>
  </div>
</div>

// packages/react/.storybook/template/ThemeSelector/ThemeSelector.tsx
import { Chip, IconButton } from "@design-system-rte/react";
import { useEffect, useState } from "react";

const ThemeSelector = () => {
  const [currentMode, setCurrentMode] = useState<"light" | "dark">("light");
  const [currentTheme, setCurrentTheme] = useState<"bleu_iceberg" | "vert_foret" | "violet">("bleu_iceberg");

  const switchMode = (mode: "light" | "dark") => {
    document.querySelector("html")?.setAttribute("data-mode", mode);
  };

  const switchTheme = (theme: "bleu_iceberg" | "vert_foret" | "violet") => {
    document.querySelector("html")?.setAttribute("data-theme", theme);
  };

  useEffect(() => {
    if (currentMode) {
      switchMode(currentMode);
    }
  }, [currentMode]);

  useEffect(() => {
    if (currentTheme) {
      switchTheme(currentTheme);
    }
  }, [currentTheme]);

  const themes = [
    { id: "bleu_iceberg", label: "Bleu Iceberg" },
    { id: "violet", label: "Violet" },
    { id: "vert_foret", label: "Vert Forêt" },
  ];

  const handleClick = (event: React.MouseEvent<HTMLSpanElement> | React.KeyboardEvent<HTMLSpanElement>) => {
    const clickedChipId = event.currentTarget.id as "bleu_iceberg" | "vert_foret" | "violet";
    setCurrentTheme(clickedChipId);
  };

  return (
    <div style={{ display: "flex", flexDirection: "row", gap: "24px", justifyContent: "end" }}>
      <div style={{ display: "flex", gap: "8px" }} role="radiogroup">
        {themes.map(({ id, label }) => (
          <Chip
            id={id}
            key={id}
            label={label}
            selected={currentTheme === id}
            onClick={handleClick}
            type="single"
            className="chip"
          />
        ))}
      </div>
      <div style={{ display: "flex" }}>
        <IconButton
          name={currentMode === "light" ? "mode-dark" : "mode-light"}
          aria-label={"Mode " + currentMode}
          onClick={() => setCurrentMode(currentMode === "light" ? "dark" : "light")}
        />
      </div>
    </div>
  );
};

export default ThemeSelector;
