// packages/react/src/components/treeview/Treeview.tsx
import { computeCheckedIdsAfterToggle, resetMovingTabIndex } from "@design-system-rte/core";
import { TreeviewItemProps } from "@design-system-rte/core/components/treeview/treeview-item.interface";
import { Fragment, useEffect, useRef, useState } from "react";

import { useSelectItem } from "./hooks/useSelectItem";
import styles from "./Treeview.module.scss";
import TreeviewItem from "./treeviewItem/TreeviewItem";
import { onFocusIn, onFocusOut, onKeyDown } from "./treeviewService";

interface TreeviewProps extends Omit<React.HTMLAttributes<HTMLUListElement>, "onChange"> {
  items: TreeviewItemProps[];
  isCompact?: boolean;
  selectedId?: string;
  onChange?: (id: string) => void;
  onCheckedIdsChange?: (checkedIds: string[]) => void;
  selectedPath?: string;
  hasCheckbox?: boolean;
  id?: string;
}

const Treeview = ({
  items,
  isCompact,
  selectedId,
  onChange,
  selectedPath,
  hasCheckbox,
  id = "treeview",
}: TreeviewProps) => {
  const { internalSelectedId, setInternalSelectedId } = useSelectItem(selectedId!, selectedPath, items);
  const [checkedIds, setCheckedIds] = useState<string[]>([]);
  const treeRef = useRef<HTMLUListElement>(null);

  const handleCheckedIdsChange = (node: TreeviewItemProps) => {
    const res = Array.from(computeCheckedIdsAfterToggle(new Set(checkedIds), node, items));
    setCheckedIds(res);
  };

  useEffect(() => {
    if (treeRef.current) {
      const treeElement = treeRef.current;
      resetMovingTabIndex(treeElement);

      const handleKeyDown = (event: KeyboardEvent): void => {
        onKeyDown(event, treeElement);
      };

      const handleFocusIn = (event: FocusEvent): void => {
        onFocusIn(treeElement, event);
      };

      const handleFocusOut = (event: FocusEvent): void => {
        onFocusOut(treeElement, event);
      };

      treeElement.addEventListener("keydown", handleKeyDown, true);
      treeElement.addEventListener("focusin", handleFocusIn);
      treeElement.addEventListener("focusout", handleFocusOut);

      return () => {
        treeElement.removeEventListener("keydown", handleKeyDown, true);
        treeElement.removeEventListener("focusin", handleFocusIn);
        treeElement.removeEventListener("focusout", handleFocusOut);
      };
    }
  }, []);

  const hasCheckedItems = () => {
    return false;
  };

  const handleItemChange = (id: string) => {
    setInternalSelectedId(id);
    onChange?.(id);
  };

  return (
    <ul
      className={styles["rte-treeview"]}
      data-compact={isCompact}
      data-has-checked-items={hasCheckedItems()}
      role="tree"
      ref={treeRef}
    >
      {items.map((item, index) => (
        <Fragment key={(item.id || item.labelText) + index}>
          <TreeviewItem
            treeId={id}
            key={item.id}
            {...item}
            isCompact={isCompact}
            onChange={handleItemChange}
            selectedId={internalSelectedId!}
            hasCheckbox={item.hasCheckbox ?? hasCheckbox}
            onCheckedIdsChange={handleCheckedIdsChange}
            checkedIds={checkedIds}
          />
        </Fragment>
      ))}
    </ul>
  );
};

export default Treeview;

// packages/angular/projects/ds-rte-lib/src/lib/components/treeview/treeview.component.ts
import { CommonModule } from "@angular/common";
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
  viewChild,
} from "@angular/core";
import {
  type TreeviewItemProps,
  TreeviewOpenChangeEvent,
  TreeviewSelectionChangeEvent,
  hasNestedItemsInTree,
} from "@design-system-rte/core/components/treeview";

import { TreeviewCheckService } from "./treeview-check.service";
import { TreeviewItemComponent } from "./treeview-item/treeview-item.component";
import { TreeviewKeyboardService } from "./treeview-keyboard.service";
import { TreeviewSelectionService } from "./treeview-selection.service";

@Component({
  selector: "rte-treeview",
  imports: [CommonModule, TreeviewItemComponent],
  standalone: true,
  templateUrl: "./treeview.component.html",
  styleUrl: "./treeview.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [TreeviewSelectionService, TreeviewCheckService, TreeviewKeyboardService],
})
export class TreeviewComponent implements AfterViewInit {
  readonly treeRef = viewChild<ElementRef<HTMLElement>>("treeRef");

  readonly isCompact = input<boolean>(false);
  readonly dottedLine = input<boolean>(false);
  readonly hasCheckbox = input<boolean>(false);
  readonly items = input<TreeviewItemProps[]>([]);
  readonly selectedId = input<string | undefined>(undefined);
  readonly selectedPath = input<string | undefined>(undefined);
  readonly id = input<string>("treeview");
  readonly itemClick = output<string | undefined>();
  readonly openChange = output<TreeviewOpenChangeEvent>();
  readonly actionIconClick = output<{ itemId: string; event: Event }>();
  readonly selectionChange = output<TreeviewSelectionChangeEvent>();
  readonly checkedIdsChange = output<ReadonlySet<string>>();

  readonly selectionService = inject(TreeviewSelectionService);
  readonly checkService = inject(TreeviewCheckService);

  private cdr = inject(ChangeDetectorRef);
  private keyboardService = inject(TreeviewKeyboardService);
  private destroyRef = inject(DestroyRef);

  readonly hasCheckedItems = computed(() => this.hasCheckbox() && this.checkService.checkedIds().size > 0);

  readonly hasNestedItems = computed(() => hasNestedItemsInTree(this.items()));

  constructor() {
    effect(
      () => {
        const id = this.selectedId();
        this.selectionService.select(id);
        this.selectionChange.emit({ id, selected: true });
      },
      { allowSignalWrites: true },
    );
    effect(
      () => {
        const pathString = this.selectedPath();
        const currentItems = this.items();
        if (pathString != null && pathString !== "" && currentItems.length > 0) {
          this.selectionService.selectByNodePath(pathString, currentItems);
        }
      },
      { allowSignalWrites: true },
    );
    effect(
      () => {
        const ids = this.checkService.checkedIds();
        this.checkedIdsChange.emit(ids);
        this.cdr.markForCheck();
      },
      { allowSignalWrites: true },
    );
    effect(
      () => {
        this.checkService.setRootItems(this.items());
      },
      { allowSignalWrites: true },
    );
  }

  private setupKeyboardListeners(): void {
    const treeElement = this.treeRef()?.nativeElement;
    if (!treeElement) {
      return;
    }

    this.keyboardService.initialize(treeElement);

    const handleKeyDown = (event: KeyboardEvent): void => {
      this.keyboardService.handleKeyDown(event, treeElement);
    };

    const handleFocusIn = (event: FocusEvent): void => {
      this.keyboardService.onFocusIn(treeElement, event);
    };

    const handleFocusOut = (event: FocusEvent): void => {
      this.keyboardService.onFocusOut(treeElement, event);
    };

    treeElement.addEventListener("keydown", handleKeyDown, true);
    treeElement.addEventListener("focusin", handleFocusIn);
    treeElement.addEventListener("focusout", handleFocusOut);

    this.destroyRef.onDestroy(() => {
      treeElement.removeEventListener("keydown", handleKeyDown, true);
      treeElement.removeEventListener("focusin", handleFocusIn);
      treeElement.removeEventListener("focusout", handleFocusOut);
    });
  }

  ngAfterViewInit(): void {
    this.setupKeyboardListeners();
  }

  itemTrack(item: TreeviewItemProps): string {
    return item.id ?? item.labelText;
  }
}

<ul
  #treeRef
  class="treeview"
  role="tree"
  [class.compact]="isCompact()"
  [class.has-checked-items]="hasCheckedItems()"
  [class.has-nested-items]="hasNestedItems()"
>
  @for (item of items(); track itemTrack(item); let itemIndex = $index) {
    <li
      rteTreeviewItem
      [rootItems]="items()"
      [treeId]="id()"
      [nodePath]="[itemIndex]"
      [id]="item.id"
      [labelText]="item.labelText"
      [icon]="item.icon"
      [disabled]="item.disabled ?? false"
      [isCompact]="item.isCompact ?? isCompact()"
      [hasCheckbox]="item.hasCheckbox ?? hasCheckbox()"
      [isOpen]="item.isOpen ?? false"
      [hasIcon]="item.hasIcon ?? false"
      [hasBadge]="item.hasBadge ?? false"
      [dottedLine]="item.dottedLine ?? dottedLine()"
      [items]="item.items ?? []"
      [actionIcon]="item.actionIcon"
      [actionMenuItems]="item.actionMenuItems"
      [isLastChild]="itemIndex === items().length - 1"
      (itemClick)="itemClick.emit($event)"
      (openChange)="openChange.emit($event)"
      (actionIconClick)="actionIconClick.emit($event)"
    ></li>
  }
</ul>
