// packages/angular/src/components/button/button.component.ts
import { Component, input, output } from '@angular/core';
import { ButtonSize, ButtonType } from '@design-system-rte/core/components/button/button.interface';

@Component({
  selector: 'rte-button',
  standalone: true,
  imports: [],
  templateUrl: './button.component.html',
  styleUrl: './button.component.scss'
})
export class ButtonComponent {

  label = input('');
  type = input<ButtonType>('filled');
  size = input<ButtonSize>('m');
  disabled = input(false);

  click = output<void>();

}

<button
    class="rte-button {{ type() }} size-{{ size() }}"
    [disabled]="disabled()"
    (click)="click.emit()"
>
    {{ label() }}
</button>

// packages/react/src/components/Button/Button.tsx
import { forwardRef } from 'react';

import style from './Button.module.scss';
import { ButtonProps as CoreButtonProps } from '@design-system-rte/core/components';

type ButtonProps = CoreButtonProps & Omit<React.HTMLProps<HTMLButtonElement>, 'size' | 'type'>;

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ size = 'm', label, type = 'filled', disabled = false, className = '', ...props }, ref) => {
    return (
      <button
        ref={ref}
        type="button"
        // TODO: use clsx to generate className concatenation
        className={style.coreButton + ' ' + className}
        data-size={size}
        data-type={type}
        disabled={disabled}
        {...props}
      >
        {label}
      </button>
    );
  },
);

export default Button;
