// preview/add-text-area/angular/components/button/button.component.ts
import { ChangeDetectionStrategy, Component, input, output } from "@angular/core";
import { ButtonType } from "@design-system-rte/core/components/button/button.interface";
import { ButtonSize, ButtonVariant } from "@design-system-rte/core/components/button/common/common-button";

@Component({
  selector: "rte-button",
  imports: [],
  standalone: true,
  templateUrl: "./button.component.html",
  styleUrl: "./button.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent {
  readonly label = input("");
  readonly variant = input<ButtonVariant>("primary");
  readonly size = input<ButtonSize>("m");
  readonly disabled = input(false);
  readonly icon = input<string>("");
  readonly ariaLabel = input<string>("");
  readonly ariaLabelledBy = input<string>("");
  readonly buttonType = input<ButtonType>("button");

  readonly click = output<void>();

  onClick(event: MouseEvent | KeyboardEvent): void {
    event.stopPropagation();
    this.click.emit();
  }
}

// packages/react/src/components/button/Button.tsx
import { forwardRef } from "react";

import { ButtonProps as CoreButtonProps } from '@design-system-rte/core/components/button/button.interface';
import style from './Button.module.scss';
import { concatClassNames } from '../utils';

interface ButtonProps
  extends Omit<CoreButtonProps, "disabled">,
    Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> {
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ size = 'm', label, variant = 'primary', className = '', onClick, type = 'button', ...props }, ref) => {
    return (
        <button
          ref={ref}
          type={type}
          className={concatClassNames(style.button, className)}
          data-size={size}
          data-variant={variant}
          onClick={onClick}
          {...props}
        >
          <span data-size={size} className={style.label}>
            {label}
          </span>
        </button>
    );
  },
);

export default Button;
