// preview/dsr-500/angular/components/side-nav/side-nav.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, input, output, signal } from "@angular/core";
import { RouterLink } from "@angular/router";
import { DividerAppearance } from "@design-system-rte/core/components/divider/divider.interface";
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { setNavMenuOpenById } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.utils";
import { NavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { getDividerAppearanceBySideNavTheme } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import {
  SideNavAppearance,
  SideNavContrast,
  SideNavHeaderConfig,
  SideNavSize,
} from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";

import { DividerComponent } from "../divider/divider.component";
import { TooltipDirective } from "../tooltip/tooltip.directive";

import { BaseSideNavComponent } from "./base-side-nav/base-side-nav.component";
import { NavItemComponent } from "./nav-item/nav-item.component";
import { NavMenuComponent, NavMenuOpenChangeEvent } from "./nav-menu/nav-menu.component";

const TRANSITION_DURATION = 300;

@Component({
  selector: "rte-side-nav",
  imports: [
    CommonModule,
    BaseSideNavComponent,
    DividerComponent,
    NavItemComponent,
    NavMenuComponent,
    TooltipDirective,
    RouterLink,
  ],
  templateUrl: "./side-nav.component.html",
  styleUrl: "./side-nav.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SideNavComponent {
  readonly size = input<SideNavSize>("m" as SideNavSize);
  readonly collapsible = input<boolean>(false);
  readonly headerConfig = input<SideNavHeaderConfig | undefined>();
  readonly items = input<NavItemProps[]>([]);
  readonly footerItems = input<NavItemProps[] | undefined>();
  readonly isCollapsed = input<boolean>(false);
  readonly appearance = input<SideNavAppearance>("brand");
  readonly contrast = input<SideNavContrast>("high");

  readonly collapsedState = signal<boolean>(false);
  readonly shouldShowTitle = signal<boolean>(true);

  readonly itemClicked = output<string>();

  private titleTimeoutId: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    effect(() => {
      this.collapsedState.set(this.isCollapsed());
    });

    effect(() => {
      if (this.titleTimeoutId) {
        clearTimeout(this.titleTimeoutId);
        this.titleTimeoutId = null;
      }

      if (this.collapsedState()) {
        this.shouldShowTitle.set(false);
      } else {
        this.titleTimeoutId = setTimeout(() => {
          this.shouldShowTitle.set(true);
          this.titleTimeoutId = null;
        }, TRANSITION_DURATION);
      }
    });
  }

  readonly collapseIcon = computed<string>(() => {
    return this.collapsedState() ? "arrow-double-right" : "arrow-double-left";
  });

  readonly dividerAppearance = computed<DividerAppearance>(() => {
    return getDividerAppearanceBySideNavTheme(this.appearance(), this.contrast());
  });

  readonly headerTooltip = computed<string>(() => {
    const config = this.headerConfig();
    return config?.tooltip ?? config?.title ?? "";
  });

  handleHeaderKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      const config = this.headerConfig();
      if (config?.onClick) {
        config.onClick();
      }
    }
  }

  handleHeaderClick(): void {
    const config = this.headerConfig();
    if (config?.onClick) {
      config.onClick();
    }
  }

  hasNestedItems(item: NavItemProps): item is NavMenuProps {
    return !!item.items?.length;
  }

  handleItemClick(itemId: string): void {
    this.itemClicked.emit(itemId);
  }

  handleFooterItemClick(itemId: string): void {
    this.itemClicked.emit(itemId);
  }

  handleMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    setNavMenuOpenById(this.items(), event.id, event.open);
  }

  handleFooterMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const footerItems = this.footerItems();
    if (footerItems) {
      setNavMenuOpenById(footerItems, event.id, event.open);
    }
  }

  handleCollapseClick(): void {
    this.collapsedState.set(!this.collapsedState());
  }
}

<rte-base-side-nav [size]="size()" [isCollapsed]="collapsedState()" [appearance]="appearance()" [contrast]="contrast()">
  <div side-nav-header>
    <div
      class="side-nav-header-container"
      [ngClass]="{ collapsed: collapsedState(), compact: headerConfig()?.isCompact ?? false }"
    >
      <div
        class="side-nav-header {{ appearance() }}"
        [ngClass]="{ collapsed: collapsedState(), compact: headerConfig()?.isCompact ?? false }"
      >
        <ng-template #headerTitleInner>
          <div class="side-nav-header-title">
            <div class="side-nav-header-identifier">{{ headerConfig()?.identifier }}</div>
            @if (!collapsedState()) {
              <h1>{{ headerConfig()?.title }}</h1>
            }
          </div>
        </ng-template>
        @if (collapsedState() && headerTooltip()) {
          @if (headerConfig()?.link) {
            <a
              class="side-nav-header-title-container"
              rteTooltip
              rteTooltipPosition="right"
              rteTooltipAlignment="center"
              [rteTooltip]="headerTooltip()"
              [rteTooltipArrow]="false"
              [rteTooltipGap]="20"
              [rteTooltipShouldFocusTrigger]="true"
              [routerLink]="headerConfig()!.link!"
              [attr.aria-label]="headerConfig()?.ariaLabel"
              (click)="handleHeaderClick()"
            >
              <ng-container *ngTemplateOutlet="headerTitleInner" />
            </a>
          } @else if (headerConfig()?.onClick) {
            <div
              class="side-nav-header-title-container"
              rteTooltip
              rteTooltipPosition="right"
              rteTooltipAlignment="center"
              tabindex="0"
              role="button"
              [rteTooltip]="headerTooltip()"
              [rteTooltipArrow]="false"
              [rteTooltipGap]="20"
              [rteTooltipShouldFocusTrigger]="true"
              [attr.aria-label]="headerConfig()?.ariaLabel"
              (click)="handleHeaderClick()"
              (keydown)="handleHeaderKeyDown($event)"
            >
              <ng-container *ngTemplateOutlet="headerTitleInner" />
            </div>
          } @else {
            <div
              class="side-nav-header-title-container"
              rteTooltip
              rteTooltipPosition="right"
              rteTooltipAlignment="center"
              [rteTooltip]="headerTooltip()"
              [rteTooltipArrow]="false"
              [rteTooltipGap]="20"
              [rteTooltipShouldFocusTrigger]="false"
            >
              <ng-container *ngTemplateOutlet="headerTitleInner" />
            </div>
          }
        } @else {
          @if (headerConfig()?.link) {
            <a
              class="side-nav-header-title-container"
              [routerLink]="headerConfig()!.link!"
              [attr.aria-label]="headerConfig()?.ariaLabel"
              (click)="handleHeaderClick()"
            >
              <ng-container *ngTemplateOutlet="headerTitleInner" />
            </a>
          } @else if (headerConfig()?.onClick) {
            <div
              class="side-nav-header-title-container"
              tabindex="0"
              role="button"
              [attr.aria-label]="headerConfig()?.ariaLabel"
              (click)="handleHeaderClick()"
              (keydown)="handleHeaderKeyDown($event)"
            >
              <ng-container *ngTemplateOutlet="headerTitleInner" />
            </div>
          } @else {
            <div class="side-nav-header-title-container">
              <ng-container *ngTemplateOutlet="headerTitleInner" />
            </div>
          }
        }
        @if (!headerConfig()?.isCompact) {
          <div class="side-nav-header-version" [ngClass]="{ hidden: !shouldShowTitle() }">
            <span>{{ headerConfig()?.version }}</span>
          </div>
        }
      </div>
      <rte-divider [appearance]="dividerAppearance()" />
    </div>
  </div>
  <div side-nav-body>
    <div class="side-nav-body">
      <ul>
        @for (item of items(); track item.label) {
          @if (hasNestedItems(item)) {
            <rte-nav-menu
              [id]="item.id"
              [label]="item.label"
              [icon]="item.icon"
              [hasLeadingIcon]="item.hasLeadingIcon ?? true"
              [isCollapsed]="collapsedState()"
              [routerLink]="item.link"
              [link]="item.link"
              [open]="item.open"
              [active]="item.active ?? false"
              [items]="item.items || []"
              [appearance]="appearance()"
              [contrast]="contrast()"
              [badge]="item.badge"
              [hasDivider]="item.hasDivider!"
              (itemClick)="handleItemClick($event)"
              (openChange)="handleMenuOpenChange($event)"
            />
          } @else {
            <li>
              <rte-nav-item
                [id]="item.id"
                [label]="item.label"
                [icon]="item.icon"
                [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                [isCollapsed]="collapsedState()"
                [routerLink]="item.link"
                [link]="item.link"
                [appearance]="appearance()"
                [active]="item.active ?? false"
                [badge]="item.badge"
                (itemClick)="handleItemClick(item.id || item.label)"
              ></rte-nav-item>
            </li>
            @if (item.hasDivider) {
              <rte-divider [appearance]="dividerAppearance()" />
            }
          }
        }
      </ul>
    </div>
  </div>
  @if (footerItems()?.length || collapsible()) {
    <div side-nav-footer>
      <div class="side-nav-footer-container">
        @if (footerItems()?.length) {
          <div class="side-nav-footer-items">
            <ul>
              @for (item of footerItems()!; track item.id || item.label) {
                @if (hasNestedItems(item)) {
                  <rte-nav-menu
                    [id]="item.id"
                    [label]="item.label"
                    [icon]="item.icon"
                    [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                    [isCollapsed]="collapsedState()"
                    [routerLink]="item.link"
                    [link]="item.link"
                    [open]="item.open"
                    [active]="item.active ?? false"
                    [items]="item.items || []"
                    [appearance]="appearance()"
                    [contrast]="contrast()"
                    [badge]="item.badge"
                    [hasDivider]="item.hasDivider!"
                    (itemClick)="handleFooterItemClick($event)"
                    (openChange)="handleFooterMenuOpenChange($event)"
                  />
                } @else {
                  <li>
                    <rte-nav-item
                      [id]="item.id"
                      [label]="item.label"
                      [icon]="item.icon"
                      [hasLeadingIcon]="item.hasLeadingIcon ?? true"
                      [isCollapsed]="collapsedState()"
                      [routerLink]="item.link"
                      [link]="item.link"
                      [appearance]="appearance()"
                      [active]="item.active ?? false"
                      [badge]="item.badge"
                      (itemClick)="handleFooterItemClick(item.id || item.label)"
                    ></rte-nav-item>
                  </li>
                  @if (item.hasDivider) {
                    <rte-divider [appearance]="dividerAppearance()" />
                  }
                }
              }
            </ul>
          </div>
        }
        <rte-divider [appearance]="dividerAppearance()" />
        @if (collapsible()) {
          <div class="side-nav-footer">
            <div class="collapsible-section">
              <ul>
                <li>
                  <rte-nav-item
                    [label]="collapsedState() ? 'Ouvrir le menu' : 'Réduire le menu'"
                    [icon]="collapseIcon()"
                    [isCollapsed]="collapsedState()"
                    [appearance]="appearance()"
                    (itemClick)="handleCollapseClick()"
                  />
                </li>
              </ul>
            </div>
          </div>
        }
      </div>
    </div>
  }
  <div side-nav-content>
    <ng-content select="[content]"></ng-content>
  </div>
</rte-base-side-nav>

// packages/react/src/components/sideNav/SideNav.tsx
import { NavItemProps } from "@design-system-rte/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps } from "@design-system-rte/core/components/side-nav/nav-menu/nav-menu.interface";
import { getDividerAppearanceBySideNavTheme } from "@design-system-rte/core/components/side-nav/side-nav.constants";
import { SideNavProps as CoreSideNavProps } from "@design-system-rte/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, SPACE_KEY } from "@design-system-rte/core/constants/keyboard/keyboard.constants";
import { forwardRef, Fragment, ReactNode, useEffect, useState } from "react";

import { useActiveKeyboard } from "../../hooks/useActiveKeyboard";
import Divider from "../divider/Divider";

import BaseSideNav from "./baseSideNav/BaseSideNav";
import NavItem from "./navItem/NavItem";
import NavMenu from "./navMenu/NavMenu";
import style from "./SideNav.module.scss";

interface SideNavProps extends Partial<CoreSideNavProps>, Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  children?: ReactNode;
  defaultCollapsed?: boolean;
  onCollapsedChange?: (collapsed: boolean) => void;
}

const TRANSITION_DURATION = 300;

const SideNav = forwardRef<HTMLElement | HTMLDivElement, SideNavProps>(
  (
    {
      size = "m",
      collapsible,
      children,
      headerConfig,
      items,
      footerItems,
      isCollapsed: controlledIsCollapsed,
      defaultCollapsed = false,
      onCollapsedChange,
      appearance = "brand",
      contrast = "high",
      activeItem,
    }: SideNavProps,
    ref,
  ) => {
    const [isCollapsed, setIsCollapsed] = useState(controlledIsCollapsed ?? defaultCollapsed);
    const [shouldShowTitle, setShouldShowTitle] = useState(true);

    useEffect(() => {
      if (controlledIsCollapsed !== undefined) {
        setIsCollapsed(controlledIsCollapsed);
      }
    }, [controlledIsCollapsed]);

    useEffect(() => {
      if (isCollapsed) {
        setShouldShowTitle(false);
      } else {
        const timer = setTimeout(() => {
          setShouldShowTitle(true);
        }, TRANSITION_DURATION);
        return () => clearTimeout(timer);
      }
    }, [isCollapsed]);

    const collapseSideNav = () => {
      const newCollapsed = !isCollapsed;
      if (controlledIsCollapsed === undefined) {
        setIsCollapsed(newCollapsed);
      }
      onCollapsedChange?.(newCollapsed);
    };

    const collapseIcon = isCollapsed ? "arrow-double-right" : "arrow-double-left";

    const dividerAppearance = getDividerAppearanceBySideNavTheme(appearance, contrast);

    const handleHeaderKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      if ([SPACE_KEY, ENTER_KEY].includes(e.key)) {
        e.preventDefault();
        if (headerConfig?.onClick) {
          headerConfig.onClick();
        }
      }
    };

    const { onKeyDown: headerOnKeyDown } = useActiveKeyboard<HTMLDivElement>(
      { onKeyDown: handleHeaderKeyDown },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY],
      },
    );

    const headerTitleContent = (
      <div className={style.sideNavHeaderTitle}>
        <div className={style.sideNavHeaderIdentifier}>{headerConfig?.identifier}</div>
        {isCollapsed ? "" : <h1 data-hidden={!shouldShowTitle}>{headerConfig?.title}</h1>}
      </div>
    );

    const ariaLabel = headerConfig?.ariaLabel;

    const headerTitleLink = (
      <a
        href={headerConfig?.link ?? ""}
        className={style.sideNavHeaderTitleContainer}
        onClick={headerConfig?.onClick}
        aria-label={ariaLabel}
      >
        {headerTitleContent}
      </a>
    );

    const clickableHeaderTitle = (
      <div
        className={style.sideNavHeaderTitleContainer}
        tabIndex={0}
        onClick={headerConfig?.onClick}
        onKeyDown={headerOnKeyDown}
        role="button"
        aria-label={ariaLabel}
      >
        {headerTitleContent}
      </div>
    );

    const headerTitle = headerConfig?.link ? (
      headerTitleLink
    ) : headerConfig?.onClick ? (
      clickableHeaderTitle
    ) : (
      <div className={style.sideNavHeaderTitleContainer}>{headerTitleContent}</div>
    );

    function renderNavItems(itemsToRender: NavItemProps[] | undefined) {
      if (!itemsToRender?.length) {
        return null;
      }

      return (
        <ul>
          {itemsToRender.map((item: NavItemProps) => {
            const hasNestedItems = item.items?.length;
            if (hasNestedItems) {
              return (
                <NavMenu
                  key={item.id}
                  id={item.id}
                  badge={item.badge}
                  label={item.label}
                  icon={item.icon}
                  hasLeadingIcon={item.hasLeadingIcon}
                  isCollapsed={isCollapsed}
                  link={item.link}
                  onClick={item.onClick}
                  items={item.items || []}
                  open={(item as NavMenuProps).open}
                  active={item.active}
                  appearance={appearance}
                  contrast={contrast}
                  hasDivider={item.hasDivider}
                />
              );
            }
            return (
              <Fragment key={item.id}>
                <li>
                  <NavItem
                    id={item.id}
                    badge={item.badge}
                    label={item.label}
                    icon={item.icon}
                    hasLeadingIcon={item.hasLeadingIcon}
                    isCollapsed={isCollapsed}
                    link={item.link}
                    onClick={item.onClick}
                    appearance={appearance}
                    active={item.id === activeItem && !!activeItem}
                  />
                </li>
                {item.hasDivider && <Divider appearance={dividerAppearance} />}
              </Fragment>
            );
          })}
        </ul>
      );
    }

    return (
      <BaseSideNav
        ref={ref}
        size={size}
        isCollapsed={isCollapsed}
        appearance={appearance}
        contrast={contrast}
        className={style.sideNavContainer}
        header={
          <div className={style.sideNavHeaderContainer}>
            <div className={style.sideNavHeader} data-collapsed={isCollapsed} data-appearance={appearance}>
              {headerTitle}
              <div className={style.sideNavHeaderVersion} data-hidden={!shouldShowTitle}>
                <span>{headerConfig?.version}</span>
              </div>
            </div>
            <Divider appearance={dividerAppearance} />
          </div>
        }
        body={<div className={style.sideNavBody}>{renderNavItems(items)}</div>}
        footer={
          (footerItems?.length || collapsible) && (
            <div className={style.sideNavFooterContainer}>
              {footerItems?.length && <div className={style.sideNavFooterItems}>{renderNavItems(footerItems)}</div>}
              <Divider appearance={dividerAppearance} />
              <div className={style.sideNavFooter}>
                {collapsible && (
                  <div className={style.collapsibleSection}>
                    <NavItem
                      id="collapse-button"
                      icon={collapseIcon}
                      hasLeadingIcon={true}
                      isCollapsed={isCollapsed}
                      onClick={collapseSideNav}
                      label={isCollapsed ? "Ouvrir le menu" : "Réduire le menu"}
                      appearance={appearance}
                      role="button"
                    />
                  </div>
                )}
              </div>
            </div>
          )
        }
      >
        {children}
      </BaseSideNav>
    );
  },
);

export default SideNav;
